# $FreeBSD: stable/11/sys/modules/xl/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/xl

KMOD=	if_xl
SRCS=	bus_if.h device_if.h if_xl.c miibus_if.h miidevs.h pci_if.h xlphy.c

.include <bsd.kmod.mk>
