# $FreeBSD: release/10.0.0/sys/modules/xl/Makefile 226154 2011-10-08 12:33:10Z marius $

.PATH: ${.CURDIR}/../../dev/xl

KMOD=	if_xl
SRCS=	bus_if.h device_if.h if_xl.c miibus_if.h miidevs.h pci_if.h xlphy.c

.include <bsd.kmod.mk>
