# $MidnightBSD$
# $FreeBSD: stable/10/usr.bin/comm/tests/Makefile 313488 2017-02-09 22:49:48Z ngie $

TAP_TESTS_SH=	legacy_test

FILESDIR=	${TESTSDIR}
FILES=		regress.00.out
FILES+=		regress.00a.in
FILES+=		regress.00b.in
FILES+=		regress.01.out
FILES+=		regress.01a.in
FILES+=		regress.01b.in
FILES+=		regress.02.out
FILES+=		regress.02a.in
FILES+=		regress.02b.in
FILES+=		regress.sh

.include <bsd.test.mk>
