# $FreeBSD: release/10.0.0/share/i18n/csmapper/KS/Makefile 219019 2011-02-25 00:04:39Z gabor $
# $NetBSD: Makefile.inc,v 1.4 2006/10/18 17:54:55 tnozaki Exp $

CODE=	KS

MAPS=	JOHAB%UCS.mps KSC5601HANGUL%UCS.mps KSC5601HANJA%UCS.mps \
	UCS%JOHAB.mps UCS%KSC5601HANGUL.mps UCS%KSC5601HANJA.mps

.include "../Makefile.part"
