#	from: @(#)Makefile	5.8 (Berkeley) 7/28/90
# $FreeBSD: release/7.0.0/usr.sbin/rarpd/Makefile 117452 2003-07-11 17:15:19Z mux $

PROG=	rarpd
MAN=	rarpd.8

WARNS?=	3
# This breaks with format strings returned by expand_syslog_m().. argh!
#FORMAT_AUDIT?=	1

.include <bsd.prog.mk>
