# $FreeBSD: stable/9/lib/clang/libllvmx86info/Makefile 246637 2013-02-10 21:24:47Z dim $

.include <bsd.own.mk>

LIB=	llvmx86info

SRCDIR=	lib/Target/X86/TargetInfo
INCDIR=	lib/Target/X86
SRCS=	X86TargetInfo.cpp

TGHDRS=	X86GenInstrInfo \
	X86GenRegisterInfo \
	X86GenSubtargetInfo

.include "../clang.lib.mk"
