# $FreeBSD: release/10.0.0/lib/clang/libllvmx86info/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvmx86info

SRCDIR=	lib/Target/X86/TargetInfo
INCDIR=	lib/Target/X86
SRCS=	X86TargetInfo.cpp

TGHDRS=	X86GenInstrInfo \
	X86GenRegisterInfo \
	X86GenSubtargetInfo

.include "../clang.lib.mk"
