# $FreeBSD: release/10.0.0/lib/clang/liblldbPluginDisassemblerLLVM/Makefile 255722 2013-09-20 01:52:02Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginDisassemblerLLVM

SRCDIR=	tools/lldb/source/Plugins/Disassembler/llvm
SRCS=	DisassemblerLLVMC.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
