# $FreeBSD: stable/11/sys/modules/rtwn/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:  ${SRCTOP}/sys/dev/rtwn

KMOD    = if_rtwn
SRCS    = if_rtwn.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
