# $FreeBSD: release/10.0.0/sys/modules/netgraph/ppp/Makefile 89260 2002-01-11 15:49:02Z ru $
# $Whistle: Makefile,v 1.1 1999/01/24 02:52:12 archie Exp $

KMOD=	ng_ppp
SRCS= 	ng_ppp.c

.include <bsd.kmod.mk>
