# $FreeBSD: stable/11/sys/modules/ipfw_pmod/Makefile 316435 2017-04-03 03:07:48Z ae $

.PATH: ${SRCTOP}/sys/netpfil/ipfw/pmod

KMOD=   ipfw_pmod
SRCS=   ip_fw_pmod.c tcpmod.c opt_inet.h opt_inet6.h

.include <bsd.kmod.mk>
