# ex:ts=8
#
# Makefile for amd
# 	This file is under a "BSD" copyright (c) by David O'Brien 1998
#
# $FreeBSD: release/10.0.0/usr.sbin/amd/wire-test/Makefile 80029 2001-07-20 06:20:32Z obrien $

.PATH: ${.CURDIR}/../../../contrib/amd/wire-test

PROG=	wire-test
MAN=	wire-test.8

DPADD=	${LIBAMU}
LDADD=	${LIBAMU}

.include <bsd.prog.mk>
