# $MidnightBSD$
# $FreeBSD: stable/10/sys/modules/geom/geom_map/Makefile 284152 2015-06-08 13:23:56Z ae $

.PATH: ${.CURDIR}/../../../geom

KMOD=	geom_map
SRCS=	geom_map.c bus_if.h device_if.h

.include <bsd.kmod.mk>
