# $FreeBSD: stable/9/usr.bin/mkesdb/Makefile 219019 2011-02-25 00:04:39Z gabor $

.PATH: ${.CURDIR}/../../lib/libc/iconv

PROG=	mkesdb
LDFLAGS+= -L${.OBJDIR}/../../lib/libc

.include "${.CURDIR}/Makefile.inc"
.include <bsd.prog.mk>
