# $FreeBSD: stable/11/usr.sbin/zonectl/Makefile 319191 2017-05-30 05:15:09Z ngie $

PROG=	zonectl
SRCS=	zonectl.c
SDIR=	${SRCTOP}/sys
LIBADD= cam sbuf util
MAN=	zonectl.8
CFLAGS+=-g -O0

.include <bsd.prog.mk>
