# $FreeBSD: stable/11/lib/libiconv_modules/mapper_std/Makefile 260334 2014-01-05 21:03:49Z dim $

SHLIB=	mapper_std
SRCS+=	citrus_mapper_std.c
CFLAGS.gcc+= --param max-inline-insns-single=8

.include <bsd.lib.mk>
