# $MidnightBSD$
# $FreeBSD: stable/10/lib/libiconv_modules/mapper_std/Makefile 260497 2014-01-09 23:08:56Z dim $

SHLIB=	mapper_std
SRCS+=	citrus_mapper_std.c
CFLAGS.gcc+= --param max-inline-insns-single=8

.include <bsd.lib.mk>
