# $FreeBSD: release/10.0.0/lib/libiconv_modules/mapper_std/Makefile 219019 2011-02-25 00:04:39Z gabor $

SHLIB=	mapper_std
SRCS+=	citrus_mapper_std.c
CFLAGS+= --param max-inline-insns-single=8

.include <bsd.lib.mk>
