# $FreeBSD: release/7.0.0/sbin/fsck_ffs/SMM.doc/Makefile 66861 2000-10-09 08:26:35Z adrian $
#	@(#)Makefile	8.1 (Berkeley) 6/8/93

DIR=	smm/03.fsck_ffs
SRCS=	0.t 1.t 2.t 3.t 4.t
MACROS=	-ms

.include <bsd.doc.mk>
