# $FreeBSD: release/10.0.0/sys/modules/cc/cc_vegas/Makefile 218152 2011-02-01 06:17:00Z lstewart $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/../../../netinet/cc
KMOD=	cc_vegas
SRCS=	cc_vegas.c

.include <bsd.kmod.mk>
