# $FreeBSD: stable/10/usr.bin/bmake/tests/execution/Makefile 266074 2014-05-14 18:43:13Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/execution

TESTS_SUBDIRS=	ellipsis empty joberr plus

.include <bsd.test.mk>
