# $FreeBSD: stable/11/usr.bin/bmake/tests/execution/Makefile 299094 2016-05-04 23:20:53Z ngie $

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/execution

TESTS_SUBDIRS=	ellipsis empty joberr plus

.include <bsd.test.mk>
