# $FreeBSD: release/10.0.0/sys/modules/hyperv/stordisengage/Makefile 255923 2013-09-28 07:04:03Z uqs $

.PATH:  ${.CURDIR}/../../../dev/hyperv/stordisengage

KMOD=	hv_ata_pci_disengage
SRCS=	hv_ata_pci_disengage.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
