# $FreeBSD: release/10.0.0/sys/modules/aha/Makefile 217070 2011-01-06 21:04:00Z imp $

.PATH: ${.CURDIR}/../../dev/aha

KMOD=	aha
SRCS=	aha.c aha_isa.c ahareg.h opt_cam.h device_if.h bus_if.h \
	isa_if.h

.include <bsd.kmod.mk>
