# $FreeBSD: stable/11/sys/modules/ntb/ntb_hw_plx/Makefile 323032 2017-08-30 21:16:32Z mav $

.PATH:  ${SRCTOP}/sys/dev/ntb/ntb_hw

KMOD    = ntb_hw_plx
SRCS    = ntb_hw_plx.c
SRCS += device_if.h bus_if.h pci_if.h ntb_if.h

.include <bsd.kmod.mk>
