#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/11/usr.bin/fstat/Makefile 275042 2014-11-25 14:29:10Z bapt $

PROG=	fstat
SRCS=	fstat.c fuser.c main.c
LINKS=	${BINDIR}/fstat ${BINDIR}/fuser
LIBADD=	procstat

MAN1=	fuser.1 fstat.1

.include <bsd.prog.mk>
