# $FreeBSD: release/10.0.0/usr.bin/chat/Makefile 121784 2003-10-31 06:22:03Z kientzle $

# I once used this extensively, but no longer have a modem.  Feel free
# to ask me questions about it, but I disclaim ownership now.  -Peter

PROG=	chat
MAN=	chat.8

.include <bsd.prog.mk>
