# $FreeBSD: release/10.0.0/sys/boot/ia64/Makefile 239377 2012-08-18 23:17:42Z marcel $

SUBDIR= common efi

# In the ski sub-directory, one can build a loader for use under Ski.
# Ski is an Itanium simulator, originally developed by HP. It's not
# supported anymore in FreeBSD, but left for reference and education.
# SUBDIR += ski

.include <bsd.subdir.mk>
