# $FreeBSD: stable/11/usr.bin/clang/llvm-dwarfdump/Makefile 331838 2018-03-31 11:38:16Z dim $

PROG_CXX=	llvm-dwarfdump

SRCDIR=		tools/llvm-dwarfdump
SRCS+=		Statistics.cpp
SRCS+=		llvm-dwarfdump.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
