# $FreeBSD: release/10.0.0/sys/modules/age/Makefile 179101 2008-05-19 01:53:47Z yongari $

.PATH: ${.CURDIR}/../../dev/age

KMOD=	if_age
SRCS=	if_age.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
