# $FreeBSD: stable/11/sys/modules/age/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/age

KMOD=	if_age
SRCS=	if_age.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
