# $FreeBSD: stable/11/usr.bin/clang/clang-format/Makefile 310618 2016-12-26 20:36:37Z dim $

PROG_CXX=	clang-format
MAN=

SRCDIR=		tools/clang/tools/clang-format
SRCS+=		ClangFormat.cpp

.include "../clang.prog.mk"
