# $FreeBSD: release/7.0.0/sys/modules/hfa/sbus/Makefile 94898 2002-04-17 00:26:09Z mdodd $

.PATH:	${.CURDIR}/../../../dev/hfa

KMOD=	hfa_sbus
SRCS=	hfa_sbus.c device_if.h bus_if.h

.include <bsd.kmod.mk>
