#       $NetBSD: Makefile,v 1.3 2009/04/14 22:15:26 lukem Exp $
# $FreeBSD: release/10.0.0/usr.bin/seq/Makefile 204103 2010-02-19 23:54:12Z delphij $

PROG=	seq
DPADD=	${LIBM}
LDADD=	-lm

.include <bsd.prog.mk>
