#       $NetBSD: Makefile,v 1.3 2009/04/14 22:15:26 lukem Exp $
# $FreeBSD: stable/11/usr.bin/seq/Makefile 335739 2018-06-27 21:03:05Z kevans $

.include <src.opts.mk>

PROG=	seq

LIBADD=	m

HAS_TESTS=
SUBDIR.${MK_TESTS}+=	tests

.include <bsd.prog.mk>
