# $FreeBSD: release/10.0.0/usr.bin/svn/lib/Makefile 251886 2013-06-18 02:53:45Z peter $

SUBDIR=	libapr libapr_util libserf libsqlite3 \
	libsvn_client libsvn_delta libsvn_diff libsvn_fs libsvn_fs_fs \
	libsvn_fs_util libsvn_ra libsvn_ra_local libsvn_ra_serf \
	libsvn_ra_svn libsvn_repos libsvn_subr libsvn_wc

.include <bsd.subdir.mk>
