# $FreeBSD: stable/11/sys/modules/sysvipc/sysvshm/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/kern

KMOD=	sysvshm
SRCS=	sysv_shm.c opt_sysvipc.h opt_compat.h

.include <bsd.kmod.mk>
