# $FreeBSD: release/7.0.0/sys/modules/sysvipc/sysvshm/Makefile 141562 2005-02-09 08:35:24Z obrien $

.PATH: ${.CURDIR}/../../../kern

KMOD=	sysvshm
SRCS=	sysv_shm.c opt_mac.h opt_sysvipc.h opt_compat.h

.include <bsd.kmod.mk>
