# $FreeBSD: release/10.0.0/sys/modules/sysvipc/sysvshm/Makefile 193588 2009-06-06 17:01:44Z rwatson $

.PATH: ${.CURDIR}/../../../kern

KMOD=	sysvshm
SRCS=	sysv_shm.c opt_sysvipc.h opt_compat.h

.include <bsd.kmod.mk>
