# $MidnightBSD$
# $FreeBSD: stable/10/usr.sbin/unbound/Makefile 289252 2015-10-13 18:56:50Z bdrewery $

SUBDIR=	daemon anchor checkconf control
SUBDIR+= setup
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
