# $FreeBSD: release/10.0.0/tools/tools/ath/ath_ee_v14_print/Makefile 217682 2011-01-21 03:14:08Z adrian $

.PATH:  ${.CURDIR}/../../../../sys/dev/ath/ath_hal

PROG=	ath_ee_v14_print
NOMAN=	yes
NO_MAN=	yes

.include <../Makefile.inc>

.include <bsd.prog.mk>
