# $FreeBSD: release/10.0.0/sys/modules/geom/geom_virstor/Makefile 172302 2007-09-23 07:34:23Z pjd $

.PATH: ${.CURDIR}/../../../geom/virstor

KMOD=	geom_virstor
SRCS=	g_virstor.c g_virstor_md.c binstream.c

.include <bsd.kmod.mk>
