# $FreeBSD: stable/11/sys/modules/geom/geom_virstor/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/geom/virstor

KMOD=	geom_virstor
SRCS=	g_virstor.c g_virstor_md.c binstream.c

.include <bsd.kmod.mk>
