# $FreeBSD: release/10.0.0/sys/modules/geom/geom_uzip/Makefile 150706 2005-09-29 11:56:16Z fjoe $

.PATH: ${.CURDIR}/../../../geom/uzip ${.CURDIR}/../../../net

KMOD=	geom_uzip
SRCS=	g_uzip.c
#CFLAGS=	-g -DINVARIANT_SUPPORT -DINVARIANTS

.include <bsd.kmod.mk>
