# $MidnightBSD$
# $FreeBSD: stable/10/usr.sbin/bsdinstall/scripts/Makefile 291819 2015-12-04 19:16:56Z bdrewery $

SCRIPTS= auto adduser checksum config entropy hostname jail \
	 keymap mirrorselect mount netconfig netconfig_ipv4 netconfig_ipv6 \
	 rootpass script services time umount wlanconfig zfsboot
BINDIR= ${LIBEXECDIR}/bsdinstall

MAN=

.include <bsd.prog.mk>
