
SCRIPTS= auto adduser bootconfig checksum config entropy \
         fetchmissingdists hardening hostname jail keymap mirrorselect mount \
         netconfig netconfig_ipv4 netconfig_ipv6 packages rootpass script services time \
         umount wlanconfig zfsboot
BINDIR= ${LIBEXECDIR}/bsdinstall

MAN=

.include <bsd.prog.mk>
