#!/bin/sh
#-
# Copyright (c) 2011 Nathan Whitehorn
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $MidnightBSD$
# $FreeBSD: src/usr.sbin/bsdinstall/scripts/mirrorselect,v 1.4 2011/09/10 09:40:00 brueffer Exp $

: ${DIALOG_OK=0}
: ${DIALOG_CANCEL=1}
: ${DIALOG_HELP=2}
: ${DIALOG_EXTRA=3}
: ${DIALOG_ITEM_HELP=4}
: ${DIALOG_ESC=255}

exec 3>&1
MIRROR=`dialog --backtitle "MidnightBSD Installer" \
    --title "Mirror Selection" --extra-button --extra-label "Other" \
    --menu "Please select the site closest to you or \"other\" if you'd like to specify a different choice.  Also note that not every site listed here carries more than the base distribution kits. Only Primary sites are guaranteed to carry the full range of possible distributions." \
    0 0 0 \
	ftp://ftp1.midnightbsd.org 	"Primary (MI, USA)"\
	ftp://ftp3.midnightbsd.org 	"Primary #2 (Japan)"\
    2>&1 1>&3`
MIRROR_BUTTON=$?
exec 3>&-

_UNAME_R=`uname -r`
RELDIR="releases"

BSDINSTALL_DISTSITE="$MIRROR/pub/MidnightBSD/${RELDIR}/`uname -p`/${_UNAME_R}"

case $MIRROR_BUTTON in
$DIALOG_CANCEL)
	exit 1
	;;
$DIALOG_OK)
	;;
$DIALOG_EXTRA)
	exec 3>&1
	BSDINSTALL_DISTSITE=`dialog --backtitle "MidnightBSD Installer" \
	    --title "Mirror Selection" \
	    --inputbox "Please enter the URL to an alternate mirror:" \
	    0 0 "$BSDINSTALL_DISTSITE" 2>&1 1>&3`
	MIRROR_BUTTON=$?
	exec 3>&-
	test $MIRROR_BUTTON -eq 0 || exec $0 $@
	;;
esac

export BSDINSTALL_DISTSITE
echo $BSDINSTALL_DISTSITE >&2
