# $FreeBSD: release/10.0.0/sys/modules/ntb/if_ntb/Makefile 250079 2013-04-29 22:48:53Z carl $

.PATH:  ${.CURDIR}/../../../dev/ntb/if_ntb

KMOD    = if_ntb
SRCS    = if_ntb.c
SRCS += device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
