# $FreeBSD: stable/11/sys/modules/ntb/if_ntb/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:  ${SRCTOP}/sys/dev/ntb/if_ntb

KMOD    = if_ntb
SRCS    = if_ntb.c
SRCS += device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
