# $FreeBSD: release/7.0.0/share/doc/psd/25.xdrrfc/Makefile 136910 2004-10-24 15:33:08Z ru $

VOLUME=		psd/25.xdrrfc
SRCS=		stubs xdr.rfc.ms
MACROS=		-ms
USE_TBL=
SRCDIR=		${.CURDIR}/../../../../lib/libc/rpc/PSD.doc

.include <bsd.doc.mk>
