# $FreeBSD: release/10.0.0/gnu/usr.bin/texinfo/libtxi/Makefile 136910 2004-10-24 15:33:08Z ru $

LIB=	txi
INTERNALLIB=

SRCS=   substring.c xexit.c xmalloc.c xstrdup.c

.include <bsd.lib.mk>

.PATH: ${TXIDIR}/lib
