#	@(#)Makefile	5.4 (Berkeley) 6/5/91
# $FreeBSD: stable/11/sbin/etherswitchcfg/Makefile 319185 2017-05-30 04:17:22Z ngie $

PACKAGE=runtime
PROG=	etherswitchcfg
MAN=	etherswitchcfg.8
SRCS=	etherswitchcfg.c ifmedia.c
CFLAGS+= -I${SRCTOP}/sys

.include <bsd.prog.mk>
