#	@(#)Makefile	5.4 (Berkeley) 6/5/91
# $FreeBSD: release/10.0.0/sbin/etherswitchcfg/Makefile 235289 2012-05-11 20:56:04Z adrian $

PROG=	etherswitchcfg
MAN=	etherswitchcfg.8
SRCS=	etherswitchcfg.c ifmedia.c
CFLAGS+= -I${.CURDIR}/../../sys

.include <bsd.prog.mk>
