# $FreeBSD: release/7.0.0/sys/modules/libalias/libalias/Makefile 168541 2007-04-09 17:08:27Z piso $

.PATH: ${.CURDIR}/../../../netinet/libalias

KMOD=	libalias
SRCS=	alias.c alias_db.c alias_proxy.c alias_util.c alias_mod.c

.include <bsd.kmod.mk>
