# $FreeBSD: release/10.0.0/sys/modules/libalias/libalias/Makefile 188294 2009-02-07 18:49:42Z piso $

.PATH: ${.CURDIR}/../../../netinet/libalias

KMOD=	libalias
SRCS=	alias.c alias_db.c alias_proxy.c alias_util.c alias_mod.c alias_sctp.c

.include <bsd.kmod.mk>
