#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: release/7.0.0/share/doc/smm/02.config/Makefile 136910 2004-10-24 15:33:08Z ru $

VOLUME=		smm/02.config
SRCS=		0.t 1.t 2.t 3.t 4.t 5.t 6.t a.t b.t c.t d.t e.t
MACROS=		-ms
USE_TBL=
SRCDIR=		${.CURDIR}/../../../../usr.sbin/config/SMM.doc

.include <bsd.doc.mk>
