# $FreeBSD: stable/11/stand/libsa32/Makefile 329140 2018-02-11 20:58:00Z kevans $

DO32=1

.include <bsd.init.mk>

LIB=sa32
LIBSA_CPUARCH=${MACHINE_CPUARCH:C/amd64/i386/}

.PATH:	${SASRC}
.include "${SASRC}/Makefile"
