# $FreeBSD: release/7.0.0/sys/modules/mac_bsdextended/Makefile 101172 2002-08-01 17:41:27Z rwatson $

.PATH: ${.CURDIR}/../../security/mac_bsdextended

KMOD=	mac_bsdextended
SRCS=	vnode_if.h \
	mac_bsdextended.c

.include <bsd.kmod.mk>
