# $FreeBSD: stable/11/usr.bin/bmake/tests/sysmk/t1/mk/Makefile 299094 2016-05-04 23:20:53Z ngie $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/sysmk/t1/mk

${PACKAGE}FILES+=		sys.mk.test

${PACKAGE}FILESNAME_sys.mk.test=	sys.mk

.include <bsd.test.mk>
