# $FreeBSD: release/7.0.0/sys/modules/hfa/eisa/Makefile 94898 2002-04-17 00:26:09Z mdodd $

.PATH:	${.CURDIR}/../../../dev/hfa

KMOD=	hfa_eisa
SRCS=	hfa_eisa.c eisa_if.h device_if.h bus_if.h

.include <bsd.kmod.mk>
