#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/share/man/man7/Makefile,v 1.29.8.1 2006/01/25 13:22:58 harti Exp $
# $MidnightBSD: src/share/man/man7/Makefile,v 1.4 2010/06/19 14:46:43 laffer1 Exp $

#MISSING: eqnchar.7 ms.7 term.7
MAN=	adding_user.7 \
	ascii.7 \
	bsd.snmpmod.mk.7 \
	build.7 \
	c99.7 \
	clocks.7 \
	development.7 \
	environ.7 \
	ffs.7 \
	firewall.7 \
	hier.7 \
	hostname.7 \
	intro.7 \
	maclabel.7 \
	mailaddr.7 \
	mports.7 \
	operator.7 \
	release.7 \
	sdoc.7 \
	security.7 \
	sprog.7 \
	stdint.7 \
	sticky.7 \
	tuning.7

MLINKS=	intro.7 miscellaneous.7
MLINKS+= mports.7 ports.7
MLINKS+= security.7 securelevel.7
MLINKS+= c99.7 c.7
MLINKS+= c99.7 c78.7
MLINKS+= c99.7 c89.7
MLINKS+= c99.7 c90.7

.include <bsd.prog.mk>
