# $FreeBSD: release/10.0.0/sys/modules/sem/Makefile 211339 2010-08-15 15:33:01Z kib $

.PATH: ${.CURDIR}/../../kern

KMOD=	sem
SRCS=	uipc_sem.c opt_compat.h opt_posix.h vnode_if.h

.include <bsd.kmod.mk>
