# $FreeBSD: stable/11/share/examples/smbfs/print/Makefile 299293 2016-05-10 00:51:50Z gjb $

PACKAGE=examples
FILESDIR= ${SHAREDIR}/examples/smbfs/print
FILES=	lj6l ljspool printcap.sample tolj

.PATH: ${.CURDIR}/../../../../contrib/smbfs/examples/print

.include <bsd.prog.mk>
