# $FreeBSD: release/10.0.0/share/examples/smbfs/print/Makefile 139103 2004-12-21 08:47:35Z ru $

NO_OBJ=
BINDIR=	/usr/share/examples/smbfs/print
FILES=	lj6l ljspool printcap.sample tolj

.PATH: ${.CURDIR}/../../../../contrib/smbfs/examples/print

.include <bsd.prog.mk>
