#!/bin/sh 
# $Id: slapd-stop,v 1.1.1.1 2012-07-21 15:09:06 laffer1 Exp $

echo stoping slapd

# kill of old slapd
if [ -f slapd.pid ]; then
    kill `cat slapd.pid`
    sleep 5
fi
if [ -f slapd.pid ]; then
    kill -9 `cat slapd.pid`
    rm -f slapd.pid
    sleep 5
fi

exit 0

