# $FreeBSD: release/10.0.0/lib/clang/liblldbPluginUnwindAssemblyInstEmulation/Makefile 255722 2013-09-20 01:52:02Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginUnwindAssemblyInstEmulation

SRCDIR=	tools/lldb/source/Plugins/UnwindAssembly/InstEmulation
SRCS=	UnwindAssemblyInstEmulation.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
