# $MidnightBSD$
# $FreeBSD: stable/10/usr.sbin/fifolog/Makefile 289252 2015-10-13 18:56:50Z bdrewery $

SUBDIR=	lib .WAIT \
	fifolog_create fifolog_writer fifolog_reader
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
