# $Id: Makefile,v 1.5 2003/08/14 20:06:21 max Exp $
# $FreeBSD: release/10.0.0/usr.sbin/bluetooth/hcseriald/Makefile 140941 2005-01-28 16:08:11Z ru $

PROG=		hcseriald
MAN=		hcseriald.8
WARNS?=		2

DPADD=		${LIBNETGRAPH}
LDADD=		-lnetgraph

.include <bsd.prog.mk>
