# $Id: Makefile,v 1.1.1.1 2006-02-25 02:29:36 laffer1 Exp $
# $FreeBSD: src/usr.sbin/bluetooth/hcseriald/Makefile,v 1.4 2005/01/28 16:08:09 ru Exp $

PROG=		hcseriald
MAN=		hcseriald.8
WARNS?=		2

DPADD=		${LIBNETGRAPH}
LDADD=		-lnetgraph

.include <bsd.prog.mk>
