# $FreeBSD: stable/11/gnu/usr.bin/groff/src/utils/Makefile 275866 2014-12-17 19:46:12Z ngie $

SUBDIR=		addftinfo afmtodit hpftodit indxbib lkbib lookbib pfbtops tfmtodit

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
