# $FreeBSD: release/7.0.0/sys/modules/netgraph/atm/Makefile 171453 2007-07-14 21:49:24Z rwatson $

SUBDIR=			\
	atm 		\
	atmbase		\
	ccatm		\
	sscfu		\
	sscop		\
	uni

# atmpif disabled due to non-MPSAFEty in 7.0
#	atmpif		\

.include <bsd.subdir.mk>
