# $FreeBSD: stable/11/share/doc/legal/intel_iwn/Makefile 289399 2015-10-16 00:38:05Z bdrewery $

FILES=		${.CURDIR}/../../../../sys/contrib/dev/iwn/LICENSE
FILESDIR=	${SHAREDIR}/doc/legal
FILESNAME=	intel_iwn.LICENSE

.include <bsd.prog.mk>
