# $FreeBSD: stable/11/sys/modules/s3/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/fb

KMOD=	s3
SRCS=	device_if.h bus_if.h isa_if.h pci_if.h \
	s3_pci.c

.include <bsd.kmod.mk>
