# $FreeBSD: stable/11/lib/libiconv_modules/ISO2022/Makefile 260334 2014-01-05 21:03:49Z dim $

SHLIB=	ISO2022
SRCS+=	citrus_iso2022.c
CFLAGS.gcc+= --param max-inline-insns-single=128

.include <bsd.lib.mk>
