# $FreeBSD: stable/9/sys/boot/sparc64/zfsboot/Makefile 236076 2012-05-26 08:54:26Z marius $

.PATH: ${.CURDIR}/../boot1

PROGNAME=	zfsboot
CFLAGS+=	-DZFSBOOT
FILES=		zfsboot

.include "${.CURDIR}/../boot1/Makefile"
