# $FreeBSD: stable/11/usr.bin/clang/llvm-diff/Makefile 331838 2018-03-31 11:38:16Z dim $

PROG_CXX=	llvm-diff

SRCDIR=		tools/llvm-diff
SRCS+=		DiffConsumer.cpp
SRCS+=		DiffLog.cpp
SRCS+=		DifferenceEngine.cpp
SRCS+=		llvm-diff.cpp

.include "../llvm.prog.mk"
