# $Id: Makefile,v 1.2 2003/04/27 00:22:11 max Exp $
# $FreeBSD: release/7.0.0/sys/modules/netgraph/bluetooth/Makefile 171818 2007-08-13 17:19:28Z emax $

SUBDIR=	\
	bluetooth \
	hci	\
	l2cap	\
	socket	\
	bt3c	\
	h4	\
	ubt	\
	ubtbcmfw

.include <bsd.subdir.mk>
