# $Id: Makefile,v 1.1.1.3 2008-11-27 13:51:53 laffer1 Exp $
# $FreeBSD: src/sys/modules/netgraph/bluetooth/Makefile,v 1.5 2007/08/13 17:19:28 emax Exp $

SUBDIR=	\
	bluetooth \
	hci	\
	l2cap	\
	socket	\
	bt3c	\
	h4	\
	ubt	\
	ubtbcmfw

.include <bsd.subdir.mk>
