# $FreeBSD: stable/11/sys/modules/ipw/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/ipw

KMOD    = if_ipw
SRCS    = if_ipw.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
