# $FreeBSD: release/10.0.0/sys/modules/ipw/Makefile 150636 2005-09-27 18:10:43Z mlaier $

.PATH: ${.CURDIR}/../../dev/ipw

KMOD    = if_ipw
SRCS    = if_ipw.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
