# $FreeBSD: release/7.0.0/usr.sbin/moused/Makefile 167461 2007-03-11 20:02:26Z philip $

PROG=	moused
MAN=	moused.8

DPADD=	${LIBUTIL}  ${LIBM}
LDADD=	-lutil -lm

#BINMODE=4555
#PRECIOUSPROG=

.include <bsd.prog.mk>
