# $FreeBSD: release/10.0.0/usr.sbin/moused/Makefile 201390 2010-01-02 11:07:44Z ed $

PROG=	moused
MAN=	moused.8

DPADD=	${LIBUTIL}  ${LIBM}
LDADD=	-lutil -lm

#BINMODE=4555
#PRECIOUSPROG=

.include <bsd.prog.mk>
