# $FreeBSD: stable/11/sys/modules/aic7xxx/aicasm/Makefile 319182 2017-05-30 04:11:12Z ngie $

MAKESRCPATH=	${SRCTOP}/sys/dev/aic7xxx/aicasm

install:

.include "${SRCTOP}/sys/dev/aic7xxx/aicasm/Makefile"

build-tools: ${PROG}
