# $FreeBSD: stable/11/stand/pc98/Makefile 330311 2018-03-03 06:37:53Z kevans $

NO_OBJ=t

.include <bsd.init.mk>

SUBDIR=		boot0 boot0.5 pc98boot btx boot2 cdboot kgzldr libpc98 loader

.include <bsd.subdir.mk>
