# $FreeBSD: release/10.0.0/lib/clang/libllvmmipsinfo/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvmmipsinfo

SRCDIR=	lib/Target/Mips/TargetInfo
INCDIR=	lib/Target/Mips
SRCS=	MipsTargetInfo.cpp

TGHDRS=	MipsGenInstrInfo \
	MipsGenRegisterInfo \
	MipsGenSubtargetInfo

.include "../clang.lib.mk"
