# $FreeBSD: release/10.0.0/usr.sbin/wpa/Makefile 164363 2006-11-17 19:38:51Z sam $

SUBDIR= wpa_supplicant wpa_cli wpa_passphrase
SUBDIR+= hostapd hostapd_cli
SUBDIR+= ndis_events

.include <bsd.subdir.mk>
