#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/11/usr.bin/col/Makefile 282339 2015-05-02 12:08:28Z bapt $

.include <src.opts.mk>

PROG=	col

.if ${MK_TESTS} != "no"
SUBDIR+=	tests
.endif

.include <bsd.prog.mk>
