# $FreeBSD: release/10.0.0/usr.sbin/bsdconfig/networking/include/Makefile 247280 2013-02-25 19:55:32Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/120.networking/include
FILES=		messages.subr

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
