# $FreeBSD: stable/11/sys/modules/amd_ecc_inject/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/amd_ecc_inject

KMOD=	amd_ecc_inject
SRCS=	ecc_inject.c bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
