# $FreeBSD: stable/11/tests/sys/geom/class/part/Makefile 329275 2018-02-14 20:26:09Z asomers $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/sys/geom/class/${.CURDIR:T}

# TODO: port the perl tests in tools/regression/geom_gpt
ATF_TESTS_SH+=	misc

.include <bsd.test.mk>
