.\" Copyright (c) 1980, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)time.1	8.1 (Berkeley) 6/6/93
.\"
.Dd September 8, 2026
.Dt TIME 1
.Os
.Sh NAME
.Nm time
.Nd time command execution
.Sh SYNOPSIS
.Nm
.Op Fl al
.Op Fl f Ar format | Fl h | Fl p
.Op Fl o Ar file
.Ar utility Op Ar argument ...
.Sh DESCRIPTION
The
.Nm
utility
executes and
times the specified
.Ar utility .
After the
.Ar utility
finishes,
.Nm
writes to the standard error stream,
(in seconds):
the total time elapsed,
the time used to execute the
.Ar utility
process and the time consumed by system overhead.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl a
If the
.Fl o
flag is used, append to the specified file rather than overwriting
it.
Otherwise, this option has no effect.
.It Fl f Ar format
Print the resource usage using
.Ar format
instead of the default output.
The format string is copied to the output verbatim, with the following
exceptions:
a newline is appended,
the sequences
.Ql \et ,
.Ql \en
and
.Ql \e\e
produce a tab, a newline and a backslash respectively,
and each
.Ql %
introduces a conversion described below.
An unknown conversion is printed as a
.Ql \&?
followed by the offending character.
The conversions are compatible with those of GNU
.Nm ,
so scripts written for it can be used unchanged.
.Pp
Time:
.Bl -tag -width indent -compact
.It Cm \&%E
Elapsed real time, as
.Ar minutes:seconds.hundredths ,
or
.Ar hours:minutes:seconds
if the command ran for an hour or more.
.It Cm \&%e
Elapsed real time in seconds.
.It Cm \&%S
Total CPU seconds spent in kernel mode.
.It Cm \&%U
Total CPU seconds spent in user mode.
.It Cm \&%P
Percentage of the CPU this job got, computed as
.Cm ( \&%U No + Cm \&%S ) No / Cm \&%e .
.El
.Pp
Memory (all sizes are in kilobytes):
.Bl -tag -width indent -compact
.It Cm \&%M
Maximum resident set size.
.It Cm \&%t
Average resident set size (unshared data).
.It Cm \&%K
Average total memory use (data, stack and text).
.It Cm \&%D
Average size of the unshared data and stack areas.
.It Cm \&%p
Average size of the unshared stack area.
.It Cm \&%X
Average size of the shared text area.
.It Cm \&%Z
The system page size, in bytes.
.It Cm \&%F
Number of major page faults.
.It Cm \&%R
Number of minor page faults (page reclaims).
.It Cm \&%W
Number of times the process was swapped out.
.It Cm \&%c
Number of involuntary context switches.
.It Cm \&%w
Number of voluntary context switches.
.El
.Pp
I/O and miscellaneous:
.Bl -tag -width indent -compact
.It Cm \&%I
Number of block input operations.
.It Cm \&%O
Number of block output operations.
.It Cm \&%r
Number of socket messages received.
.It Cm \&%s
Number of socket messages sent.
.It Cm \&%k
Number of signals delivered to the process.
.It Cm \&%C
The name and arguments of the command being timed.
.It Cm \&%x
The exit status of the command, or the number of the signal that
terminated it.
.It Cm \&%%
A literal
.Ql % .
.El
.Pp
The
.Fl f
option takes precedence over
.Fl h
and
.Fl p .
The
.Fl l
output, if requested, follows the formatted line.
.It Fl h
Print times in a human friendly format.
Times are printed in minutes, hours,
etc.\& as appropriate.
.It Fl l
The contents of the
.Em rusage
structure are printed as well.
.It Fl o Ar file
Write the output to
.Ar file
instead of stderr.
If
.Ar file
exists and the
.Fl a
flag is not specified, the file will be overwritten.
.It Fl p
Makes
.Nm
output POSIX.2 compliant (each time is printed on its own line).
.El
.Pp
Some shells may provide a builtin
.Nm
command which is similar or identical to this utility.
Consult the
.Xr builtin 1
manual page.
.Pp
If
.Nm
receives a
.Dv SIGINFO
(see the status argument for
.Xr stty 1 )
signal, the current time the given command is running will be written to the
standard output in the default format.
.Sh ENVIRONMENT
The
.Ev PATH
environment variable is used to locate the requested
.Ar utility
if the name contains no
.Ql /
characters.
.Sh EXIT STATUS
If
.Ar utility
could be timed successfully, its exit status is returned.
If
.Ar utility
terminated abnormally, a warning message is output to stderr.
If the
.Ar utility
was found but could not be run, the exit status is 126.
If no
.Ar utility
could be found at all, the exit status is 127.
If
.Nm
encounters any other error, the exit status is between 1 and 125
included.
.Sh EXAMPLES
Time the execution of
.Xr ls 1
on an empty directory:
.Bd -literal -offset indent
$ /usr/bin/time ls
        0.00 real         0.00 user         0.00 sys
.Ed
.Pp
Time the execution of the
.Xr cp 1
command and store the result in the
.Pa times.txt
file.
Then execute the command again to make a new copy and add the result to the same
file:
.Bd -literal -offset indent
$ /usr/bin/time -o times.txt cp FreeBSD-12.1-RELEASE-amd64-bootonly.iso copy1.iso
$ /usr/bin/time -a -o times.txt cp FreeBSD-12.1-RELEASE-amd64-bootonly.iso copy2.iso
.Ed
.Pp
The
.Pa times.txt
file will contain the times of both commands:
.Bd -literal -offset indent
$ cat times.txt
        0.68 real         0.00 user         0.22 sys
        0.67 real         0.00 user         0.21 sys
.Ed
.Pp
Time the
.Xr sleep 1
command and show the results in a human friendly format.
Show the contents of the
.Em rusage
structure too:
.Bd -literal -offset indent
$ /usr/bin/time -l -h -p sleep 5
real 5.01
user 0.00
sys 0.00
         0  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
        80  page reclaims
         0  page faults
         0  swaps
         1  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         0  signals received
         3  voluntary context switches
         0  involuntary context switches
.Ed
.Pp
Print only the elapsed time and the peak memory use of a
.Xr sort 1
run, using a custom format:
.Bd -literal -offset indent
$ /usr/bin/time -f "%e seconds, %M KB max RSS, exit %x" sort -o /dev/null words
0.12 seconds, 6740 KB max RSS, exit 0
.Ed
.Sh SEE ALSO
.Xr builtin 1 ,
.Xr csh 1 ,
.Xr getrusage 2 ,
.Xr wait 2
.Sh STANDARDS
The
.Nm
utility is expected to conform to ISO/IEC 9945-2:1993 (``POSIX'').
.Sh HISTORY
A
.Nm
utility appeared in
.At v3 .
