#	$FreeBSD: release/10.0.0/sbin/ipf/ipresend/Makefile 145630 2005-04-28 16:26:35Z darrenr $

PROG=		ipresend
SRCS=		ipresend.c ip.c resend.c sbpf.c sock.c 44arp.c
MAN=		ipresend.1

.PATH:		${.CURDIR}/../../../contrib/ipfilter/ipsend

.include <bsd.prog.mk>
