#	$FreeBSD: stable/11/sbin/ipf/ipresend/Makefile 319185 2017-05-30 04:17:22Z ngie $

PACKAGE=	ipf
PROG=		ipresend
SRCS=		ipresend.c ip.c resend.c sbpf.c sock.c 44arp.c
MAN=		ipresend.1

.PATH:		${SRCTOP}/contrib/ipfilter/ipsend

.include <bsd.prog.mk>
