# $FreeBSD: release/10.0.0/sys/modules/amr/amr_cam/Makefile 184577 2008-11-03 04:13:27Z scottl $

.PATH: ${.CURDIR}/../../../dev/amr

KMOD=	amr_cam
SRCS=	amr_cam.c device_if.h bus_if.h
SRCS+=	opt_cam.h opt_scsi.h

.include <bsd.kmod.mk>
