# $FreeBSD: stable/11/sys/modules/amr/amr_cam/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/amr

KMOD=	amr_cam
SRCS=	amr_cam.c device_if.h bus_if.h
SRCS+=	opt_cam.h opt_scsi.h

.include <bsd.kmod.mk>
