# $FreeBSD: stable/11/sys/modules/dtb/am335x/Makefile 340341 2018-11-10 23:43:03Z manu $
# All the dts files for am335x systems we support.
DTS=	\
	beaglebone.dts \
	beaglebone-black.dts \
	ufw.dts

LINKS= \
	${DTBDIR}/beaglebone.dtb ${DTBDIR}/am335x-bone.dtb \
	${DTBDIR}/beaglebone-black.dtb ${DTBDIR}/am335x-boneblack.dtb

.include <bsd.dtb.mk>
