# $MidnightBSD$
# $FreeBSD: stable/10/sys/modules/dtb/am335x/Makefile 279824 2015-03-09 21:50:10Z ian $
# All the dts files for am335x systems we support.
DTS=	\
	beaglebone.dts \
        beaglebone-black.dts

.include <bsd.dtb.mk>
