# $Id: Makefile,v 1.6 2003/08/14 20:06:24 max Exp $
# $FreeBSD: release/10.0.0/usr.sbin/bluetooth/l2ping/Makefile 140941 2005-01-28 16:08:11Z ru $

PROG=		l2ping
MAN=		l2ping.8
WARNS?=		2

DPADD=		${LIBBLUETOOTH}
LDADD=		-lbluetooth

.include <bsd.prog.mk>
