# $Id: Makefile,v 1.6 2003/08/14 20:06:24 max Exp $
# $FreeBSD: stable/11/usr.sbin/bluetooth/l2ping/Makefile 275054 2014-11-25 16:57:27Z bapt $

PROG=		l2ping
MAN=		l2ping.8
WARNS?=		2

LIBADD=		bluetooth

.include <bsd.prog.mk>
