# $Id: Makefile,v 1.1.1.2 2006-02-25 02:38:25 laffer1 Exp $
# $FreeBSD: src/usr.sbin/bluetooth/l2ping/Makefile,v 1.4 2005/01/28 16:08:09 ru Exp $

PROG=		l2ping
MAN=		l2ping.8
WARNS?=		2

DPADD=		${LIBBLUETOOTH}
LDADD=		-lbluetooth

.include <bsd.prog.mk>
