# $FreeBSD: stable/11/lib/libcasper/services/Makefile 322715 2017-08-20 06:07:40Z ngie $

SUBDIR=		cap_dns
SUBDIR+=	cap_grp
SUBDIR+=	cap_pwd
SUBDIR+=	cap_random
SUBDIR+=	cap_sysctl

SUBDIR.${MK_TESTS}+=	tests

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
