# $FreeBSD: stable/11/cddl/usr.bin/zlook/Makefile 321268 2017-07-20 00:53:50Z ngie $

.PATH: ${SRCTOP}/cddl/contrib/opensolaris/cmd/zlook

PROG=	zlook
MAN=

WARNS?=	0
CFLAGS+= -I${SRCTOP}/sys/cddl/compat/opensolaris
CFLAGS+= -I${SRCTOP}/sys/cddl/contrib/opensolaris/uts/common

.include <bsd.prog.mk>
