# $Id: Makefile,v 1.5 2003/08/14 20:06:00 max Exp $
# $FreeBSD: stable/11/usr.sbin/bluetooth/bt3cfw/Makefile 275054 2014-11-25 16:57:27Z bapt $

PROG=		bt3cfw
MAN=		bt3cfw.8
WARNS?=		2

LIBADD+=	netgraph

.include <bsd.prog.mk>
