# $Id: Makefile,v 1.5 2003/08/14 20:06:00 max Exp $
# $FreeBSD: release/10.0.0/usr.sbin/bluetooth/bt3cfw/Makefile 140941 2005-01-28 16:08:11Z ru $

PROG=		bt3cfw
MAN=		bt3cfw.8
WARNS?=		2

DPADD=		${LIBNETGRAPH}
LDADD=		-lnetgraph

.include <bsd.prog.mk>
