# $Id: Makefile,v 1.1.1.1 2006-02-25 02:29:35 laffer1 Exp $
# $FreeBSD: src/usr.sbin/bluetooth/bt3cfw/Makefile,v 1.4 2005/01/28 16:08:09 ru Exp $

PROG=		bt3cfw
MAN=		bt3cfw.8
WARNS?=		2

DPADD=		${LIBNETGRAPH}
LDADD=		-lnetgraph

.include <bsd.prog.mk>
