# $MidnightBSD$
# $FreeBSD: stable/10/sys/boot/i386/zfsloader/Makefile 276486 2014-12-31 23:25:37Z ngie $

.PATH:	${.CURDIR}/../loader

LOADER=		zfsloader
NEWVERSWHAT=	"ZFS enabled bootstrap loader" x86
LOADER_ZFS_SUPPORT=yes
LOADER_ONLY=	yes
MAN=

.include "${.CURDIR}/../loader/Makefile"

