#	$FreeBSD: release/10.0.0/libexec/tftp-proxy/Makefile 201380 2010-01-02 09:50:19Z ed $

.PATH:	${.CURDIR}/../../contrib/pf/tftp-proxy

PROG=	tftp-proxy
SRCS=	tftp-proxy.c filter.c
MAN=	tftp-proxy.8

WARNS?=	3

.include <bsd.prog.mk>
