# $MidnightBSD: src/libexec/tftp-proxy/Makefile,v 1.1 2008/11/11 20:36:12 laffer1 Exp $
# $FreeBSD: src/libexec/tftp-proxy/Makefile,v 1.1 2007/07/03 12:46:05 mlaier Exp $

.PATH:	${.CURDIR}/../../contrib/pf/tftp-proxy

PROG=	tftp-proxy
SRCS=	tftp-proxy.c filter.c
MAN=	tftp-proxy.8

WARNS?=	3

.include <bsd.prog.mk>
