# $FreeBSD: stable/11/sys/dev/patm/genrtab/Makefile 291738 2015-12-04 03:17:47Z bdrewery $
#
# This program is used to generate the if_patm_rtables.c file
# for the idt77252 driver. It is not installed.
#
PROG=	genrtab
INTERNALPROG=
WARNS?=	5
MAN=
LIBADD=	m

.include <bsd.prog.mk>
