# $FreeBSD: release/10.0.0/sys/dev/patm/genrtab/Makefile 139103 2004-12-21 08:47:35Z ru $
#
# This program is used to generate the if_patm_rtables.c file
# for the idt77252 driver. It is not installed.
#
PROG=	genrtab
INTERNALPROG=
WARNS?=	5
NO_MAN=
DPADD=	${LIBM}
LDADD=	-lm

.include <bsd.prog.mk>
