# $MidnightBSD$
# $FreeBSD: stable/10/sys/dev/patm/genrtab/Makefile 276486 2014-12-31 23:25:37Z ngie $
#
# This program is used to generate the if_patm_rtables.c file
# for the idt77252 driver. It is not installed.
#
PROG=	genrtab
INTERNALPROG=
WARNS?=	5
MAN=
DPADD=	${LIBM}
LDADD=	-lm

.include <bsd.prog.mk>
