# $FreeBSD: release/7.0.0/usr.sbin/i4b/isdntrace/Makefile 80029 2001-07-20 06:20:32Z obrien $

PROG=	isdntrace
MAN=	isdntrace.8
SRCS=	q921.c q931.c q931_util.c q932_fac.c 1tr6.c trace.c \
	pcause_1tr6.c pcause_q850.c unknownl3.c

.include <bsd.prog.mk>

