# $MidnightBSD$
# $FreeBSD: stable/10/sys/modules/splash/bmp/Makefile 133226 2004-08-06 20:37:08Z des $

.PATH:	${.CURDIR}/../../../dev/fb

KMOD=	splash_bmp
SRCS= 	splash_bmp.c

.include <bsd.kmod.mk>
