#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/7.0.0/usr.bin/xinstall/Makefile 140817 2005-01-25 14:34:57Z ssouhlal $

PROG=		xinstall
PROGNAME=	install
MAN=		install.1
WARNS?=		6

.include <bsd.prog.mk>
