# $MidnightBSD: src/usr.sbin/pnpinfo/Makefile,v 1.2 2009/03/25 16:51:02 laffer1 Exp $
# $FreeBSD: src/usr.sbin/pnpinfo/Makefile,v 1.11 2005/01/27 14:52:47 delphij Exp $

.PATH: ${.CURDIR}/../../contrib/pnpinfo

PROG=	pnpinfo
MAN=	pnpinfo.8

CFLAGS+= -I${.CURDIR}/../../sys

WARNS?=	2

.include <bsd.prog.mk>
