# $MidnightBSD: src/usr.bin/less/Makefile.common,v 1.2 2007/04/10 22:05:46 laffer1 Exp $

LSDIR=	${.CURDIR}/../../contrib/less
.PATH:	${LSDIR}

CFLAGS+=-I${.CURDIR}/../less -I${LSDIR}

WARNS?=	1

.SUFFIXES: .nro .1

.nro.1:
	cat ${.IMPSRC} > ${.TARGET}
