# $FreeBSD: release/10.0.0/usr.bin/less/Makefile.common 201386 2010-01-02 10:27:05Z ed $

LSDIR=	${.CURDIR}/../../contrib/less
.PATH:	${LSDIR}

CFLAGS+=-I${.CURDIR}/../less -I${LSDIR}
WARNS?=	1

.SUFFIXES: .nro .1

.nro.1:
	cat ${.IMPSRC} > ${.TARGET}
