# $FreeBSD: release/7.0.0/usr.bin/less/Makefile.common 115898 2003-06-06 13:46:55Z kuriyama $

LSDIR=	${.CURDIR}/../../contrib/less
.PATH:	${LSDIR}

CFLAGS+=-I${.CURDIR}/../less -I${LSDIR}

.SUFFIXES: .nro .1

.nro.1:
	cat ${.IMPSRC} > ${.TARGET}
