#	$FreeBSD: stable/11/usr.bin/usbhidaction/Makefile 275042 2014-11-25 14:29:10Z bapt $
#	$NetBSD: Makefile,v 1.4 2002/02/02 16:54:26 veego Exp $

PROG=	usbhidaction

LIBADD=	usbhid

.include <bsd.prog.mk>
