# $FreeBSD: stable/11/usr.sbin/jail/tests/Makefile 352263 2019-09-12 18:53:29Z mizhka $

PACKAGE=        tests

ATF_TESTS_SH+=  jail_basic_test

${PACKAGE}FILES+=	commands.jail.conf

.include <bsd.test.mk>
