# $FreeBSD: stable/11/sys/modules/ata/atapci/chipsets/Makefile 280451 2015-03-24 18:09:07Z mav $

SUBDIR += ataacard ataacerlabs ataamd ataati atacenatek atacypress atacyrix atahighpoint ataintel ataite atajmicron atamarvell atamicron atanational atanetcell atanvidia atapromise ataserverworks atasiliconimage atasis atavia

.include <bsd.subdir.mk>
