# $FreeBSD: release/10.0.0/sys/modules/ata/atapci/chipsets/Makefile 183724 2008-10-09 12:56:57Z sos $

SUBDIR += ataacard ataacerlabs ataadaptec ataahci ataamd ataati atacenatek atacypress atacyrix atahighpoint ataintel ataite atajmicron atamarvell atamicron atanational atanetcell atanvidia atapromise ataserverworks atasiliconimage atasis atavia

.include <bsd.subdir.mk>
