# $FreeBSD: stable/11/usr.sbin/pc-sysinstall/conf/Makefile 284255 2015-06-11 04:22:17Z sjg $

FILESGROUPS=	CONF LICENSE
CONF=		exclude-from-upgrade pc-sysinstall.conf avail-langs
CONFDIR=	${SHAREDIR}/pc-sysinstall/conf
LICENSE=	licenses/bsd-en.txt licenses/intel-en.txt licenses/nvidia-en.txt
LICENSEDIR=	${SHAREDIR}/pc-sysinstall/conf/license

.include <bsd.prog.mk>
