# $FreeBSD: stable/11/gnu/usr.bin/groff/src/utils/lookbib/Makefile 291738 2015-12-04 03:17:47Z bdrewery $

PROG_CXX=	lookbib
SRCS=		lookbib.cpp
DPADD=		${LIBBIB} ${LIBGROFF}
LDADD=		${LIBBIB} ${LIBGROFF}
LIBADD=		m
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
