# $MidnightBSD$
# $FreeBSD: stable/10/lib/libiconv_modules/EUC/Makefile 260497 2014-01-09 23:08:56Z dim $

SHLIB=	EUC
SRCS+=	citrus_euc.c
CFLAGS.gcc+= --param max-inline-insns-single=32

.include <bsd.lib.mk>
