# $MidnightBSD: src/gnu/usr.bin/cc/Makefile.tgt,v 1.3 2009/05/22 00:51:15 laffer1 Exp $
# $FreeBSD: src/gnu/usr.bin/cc/Makefile.tgt,v 1.11 2007/05/19 04:25:56 kan Exp $

TARGET_CPUARCH=${MACHINE_CPUARCH}
TARGET_ARCH?=	${MACHINE_ARCH}
GCC_CPU=${TARGET_CPUARCH:C/amd64/i386/:C/sparc64/sparc/}

.if ${TARGET_ARCH} == "sparc64"
TARGET_CPU_DEFAULT= TARGET_CPU_ultrasparc
.endif
