# $MidnightBSD$
# $FreeBSD: src/gnu/usr.bin/cc/Makefile.tgt,v 1.11 2007/05/19 04:25:56 kan Exp $

TARGET_ARCH?=	${MACHINE_ARCH}

.if ${TARGET_ARCH} == "i386" || ${TARGET_ARCH} == "amd64"
GCC_CPU=	i386
.elif ${TARGET_ARCH} == "sparc64"
GCC_CPU=	sparc
TARGET_CPU_DEFAULT= TARGET_CPU_ultrasparc
.endif
