# $FreeBSD: release/10.0.0/sys/modules/i2c/iic/Makefile 93023 2002-03-23 15:49:15Z nsouch $

.PATH:		${.CURDIR}/../../../dev/iicbus
KMOD		= iic
SRCS		= device_if.h bus_if.h iicbus_if.h \
		  iic.c

.include <bsd.kmod.mk>
