# $MidnightBSD$
# $FreeBSD: stable/10/release/picobsd/tinyware/simple_httpd/Makefile 276486 2014-12-31 23:25:37Z ngie $
#
PROG=simple_httpd
SRCS= 	simple_httpd.c
MAN=
WARNS?=6

.include <bsd.prog.mk>
