#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/10.0.0/usr.sbin/lpr/lptest/Makefile 117622 2003-07-15 08:45:06Z gad $

PROG=	lptest

CFLAGS+= -I${.CURDIR}/../common_source

.include <bsd.prog.mk>
