# $FreeBSD: release/10.0.0/sys/modules/geom/geom_bsd/Makefile 150373 2005-09-20 11:16:05Z imura $

.PATH: ${.CURDIR}/../../../geom

KMOD=	geom_bsd
SRCS=	geom_bsd.c geom_bsd_enc.c

.include <bsd.kmod.mk>
