# $FreeBSD: release/10.0.0/sys/modules/bios/vpd/Makefile 204309 2010-02-25 14:13:39Z attilio $
#

.PATH:  ${.CURDIR}/../../../x86/bios

KMOD=	vpd
SRCS=	vpd.c \
	bus_if.h device_if.h

.include <bsd.kmod.mk>
