# $MidnightBSD$
#
# $FreeBSD: stable/10/sys/modules/cxgbe/if_ccv/Makefile 305852 2016-09-16 00:08:37Z np $
#

CXGBE=	${.CURDIR}/../../../dev/cxgbe
.PATH: ${CXGBE}

KMOD=	if_ccv
SRCS=	if_ccv.c

.include <bsd.kmod.mk>
