# $FreeBSD: stable/11/lib/libmt/Makefile 298107 2016-04-16 07:45:30Z gjb $

PACKAGE=lib${LIB}
LIB=		mt
SHLIBDIR?=	/lib
SRCS=		mtlib.c
INCS=		mtlib.h

LIBADD=		sbuf bsdxml

MAN=		mt.3

.include <bsd.lib.mk>
