# $FreeBSD: release/7.0.0/share/doc/psd/23.rpc/Makefile 136910 2004-10-24 15:33:08Z ru $

VOLUME=		psd/23.rpc
SRCS=		stubs rpc.prog.ms
MACROS=		-ms
USE_TBL=
USE_PIC=
SRCDIR=		${.CURDIR}/../../../../lib/libc/rpc/PSD.doc

.include <bsd.doc.mk>
