# $FreeBSD: release/10.0.0/usr.sbin/bsdconfig/usermgmt/include/Makefile 242123 2012-10-26 03:20:04Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/070.usermgmt/include
FILES=		messages.subr usermgmt.hlp

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
