#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: release/10.0.0/usr.sbin/IPXrouted/Makefile 125430 2004-02-04 10:18:05Z ru $

PROG=	IPXrouted
MAN=	IPXrouted.8
SRCS=	af.c if.c input.c main.c output.c startup.c tables.c timer.c trace.c
SRCS+=  sap_input.c sap_tables.c sap_output.c

WARNS?= 2

.include <bsd.prog.mk>
