# $FreeBSD: stable/11/sys/modules/asmc/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/asmc

KMOD=	asmc
SRCS=	asmc.c opt_acpi.h opt_intr_filter.h acpi_if.h bus_if.h device_if.h

.include <bsd.kmod.mk>
