# $FreeBSD: release/10.0.0/sys/modules/asmc/Makefile 177973 2008-04-07 11:26:13Z rpaulo $

.PATH: ${.CURDIR}/../../dev/asmc

KMOD=	asmc
SRCS=	asmc.c opt_acpi.h opt_intr_filter.h acpi_if.h bus_if.h device_if.h

.include <bsd.kmod.mk>
