# $FreeBSD: release/10.0.0/sys/modules/cc/cc_htcp/Makefile 216115 2010-12-02 06:40:21Z lstewart $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/../../../netinet/cc
KMOD=	cc_htcp
SRCS=	cc_htcp.c

.include <bsd.kmod.mk>
