# $MidnightBSD$
#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/10/usr.bin/locate/bigram/Makefile 276486 2014-12-31 23:25:37Z ngie $

PROG=	locate.bigram
MAN=
BINDIR=	${LIBEXECDIR}
CFLAGS+= -I${.CURDIR}/../locate

.include <bsd.prog.mk>
