/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * $FreeBSD: stable/11/sys/i386/ibcs2/ibcs2_isc_syscall.h 357109 2020-01-25 05:52:31Z kevans $
 */

#define	IBCS2_ISC_ibcs2_rename	2
#define	IBCS2_ISC_ibcs2_sigaction	3
#define	IBCS2_ISC_ibcs2_sigprocmask	4
#define	IBCS2_ISC_ibcs2_sigpending	5
#define	IBCS2_ISC_getgroups	6
#define	IBCS2_ISC_setgroups	7
#define	IBCS2_ISC_ibcs2_pathconf	8
#define	IBCS2_ISC_ibcs2_fpathconf	9
#define	IBCS2_ISC_ibcs2_wait	11
#define	IBCS2_ISC_setsid	12
#define	IBCS2_ISC_getpid	13
#define	IBCS2_ISC_ibcs2_sysconf	16
#define	IBCS2_ISC_ibcs2_sigsuspend	17
#define	IBCS2_ISC_ibcs2_symlink	18
#define	IBCS2_ISC_ibcs2_readlink	19
#define	IBCS2_ISC_MAXSYSCALL	21
