# $FreeBSD: release/10.0.0/gnu/usr.bin/groff/src/libs/libbib/Makefile 136910 2004-10-24 15:33:08Z ru $

LIB=		bib
INTERNALLIB=
SRCS=		common.cpp index.cpp linear.cpp search.cpp map.c

.include <bsd.lib.mk>
