# $FreeBSD: release/10.0.0/usr.sbin/pkg_install/lib/Makefile 241830 2012-10-22 02:12:20Z eadler $

LIB=	install
INTERNALLIB=
SRCS=	file.c msg.c plist.c str.c exec.c global.c pen.c match.c \
	deps.c version.c pkgwrap.c url.c pkgng.c

WARNS?=	3
WFORMAT?=	1

.include <bsd.lib.mk>
