# $FreeBSD: stable/9/usr.sbin/pkg_install/lib/Makefile 136910 2004-10-24 15:33:08Z ru $

LIB=	install
INTERNALLIB=
SRCS=	file.c msg.c plist.c str.c exec.c global.c pen.c match.c \
	deps.c version.c pkgwrap.c url.c

WARNS?=	3
WFORMAT?=	1

.include <bsd.lib.mk>
