# $FreeBSD: stable/11/usr.bin/patch/tests/Makefile 351836 2019-09-05 03:16:14Z kevans $

PACKAGE=	tests

ATF_TESTS_SH+=	unified_patch_test

${PACKAGE}FILES+=		PR74127-cline.diff
${PACKAGE}FILES+=		PR74127-good.diff
${PACKAGE}FILES+=		PR74127-repro.diff
${PACKAGE}FILES+=		PR74127.in

.include <bsd.test.mk>
