# $FreeBSD: stable/10/kerberos5/usr.bin/Makefile 233294 2012-03-22 08:48:42Z stas $

SUBDIR=	hxtool kadmin kcc kdestroy kgetcred kf kinit kpasswd krb5-config ksu \
	string2key verify_krb5_conf

.include <bsd.subdir.mk>
