# $FreeBSD: stable/11/kerberos5/usr.bin/Makefile 288266 2015-09-26 14:13:51Z bdrewery $

SUBDIR=	hxtool kadmin kcc kdestroy kgetcred kf kinit kpasswd krb5-config ksu \
	string2key verify_krb5_conf
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
