#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/11/usr.bin/du/Makefile 321132 2017-07-18 16:48:36Z ngie $

.include <src.opts.mk>

PROG=	du
LIBADD=	util

SUBDIR.${MK_TESTS}+=	tests

.include <bsd.prog.mk>
