#	@(#)Makefile.inc	8.1 (Berkeley) 5/31/93
# $FreeBSD: src/games/Makefile.inc,v 1.16 2002/10/21 10:05:14 markm Exp $
# $MidnightBSD: src/games/Makefile.inc,v 1.2 2007/07/17 10:36:10 laffer1 Exp $

BINDIR?=	/usr/games
FILESDIR?=	${SHAREDIR}/games
DISTRIBUTION?=	games
