#	@(#)Makefile	8.2 (Berkeley) 3/31/94
# $FreeBSD: src/games/Makefile,v 1.20 2002/10/20 11:18:56 markm Exp $
# $MidnightBSD: src/games/Makefile,v 1.3 2009/04/11 16:32:15 laffer1 Exp $

SUBDIR= \
	arithmetic \
	battlestar \
	bcd \
	caesar \
	factor \
	fortune \
	grdc \
	morse \
	number \
	pom \
	ppt \
	primes \
	random

.include <bsd.subdir.mk>
