#	@(#)Makefile	8.2 (Berkeley) 3/31/94
# $FreeBSD: src/games/Makefile,v 1.20 2002/10/20 11:18:56 markm Exp $
# $MidnightBSD: src/games/Makefile,v 1.14 2009/04/12 01:32:13 laffer1 Exp $

SUBDIR= \
	arithmetic \
	atc \
	backgammon \
	battlestar \
	bcd \
	bs \
	caesar \
	dm \
	factor \
	fish \
	fortune \
	grdc \
	hangman \
	morse \
	number \
	pig \
	pom \
	ppt \
	primes \
	random \
	snake \
	trek \
	wargames \
	worm \
	worms \
	wump

.include <bsd.subdir.mk>
