# $FreeBSD: release/10.0.0/sys/modules/nvd/Makefile 240619 2012-09-17 19:58:02Z jimharris $

.PATH: ${.CURDIR}/../../dev/nvd

KMOD=	nvd
SRCS=	nvd.c opt_geom.h device_if.h bus_if.h

.include <bsd.kmod.mk>
