# $OpenBSD: Makefile,v 1.3 2014/07/02 20:18:42 schwarze Exp $

REGRESS_TARGETS = link noarg font
LINT_TARGETS	= noarg

# it's unclear what font changes in link destinations should do

SKIP_MARKDOWN  ?= font

.include <bsd.regress.mk>
