# $FreeBSD: stable/9/gnu/usr.bin/binutils/Makefile 131090 2004-06-25 07:34:56Z obrien $

SUBDIR=		libiberty libbfd libopcodes libbinutils \
		addr2line ar as ld nm objcopy objdump ranlib readelf \
		size strings strip doc

.include <bsd.subdir.mk>
