# $FreeBSD: release/10.0.0/gnu/usr.bin/binutils/Makefile 255974 2013-10-01 17:40:56Z emaste $

SUBDIR=		libiberty libbfd libopcodes libbinutils \
		addr2line as ld nm objcopy objdump readelf \
		size strings strip doc

.include <bsd.subdir.mk>
