# $FreeBSD: release/10.0.0/usr.bin/lesskey/Makefile 74848 2001-03-27 10:52:19Z ru $

PROG=	lesskey
SRCS=	lesskey.c version.c
CLEANFILES= lesskey.1

.include "${.CURDIR}/../less/Makefile.common"
.include <bsd.prog.mk>
