# $FreeBSD: stable/11/usr.bin/lesskey/Makefile 319186 2017-05-30 04:27:05Z ngie $

PROG=	lesskey
SRCS=	lesskey.c version.c
CLEANFILES= lesskey.1

.include "${SRCTOP}/usr.bin/less/Makefile.common"
.include <bsd.prog.mk>
