#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/7.0.0/usr.sbin/chown/Makefile 114007 2003-04-25 09:02:59Z johan $

PROG=	chown
LINKS=	${BINDIR}/chown /usr/bin/chgrp
MAN=	chgrp.1 chown.8

WARNS?=	5

.include <bsd.prog.mk>
