# $FreeBSD: release/10.0.0/usr.sbin/bsdconfig/startup/share/Makefile 240684 2012-09-18 22:28:42Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/bsdconfig/startup
FILES=		rcconf.subr rcedit.subr rcvar.subr

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
