# $FreeBSD: stable/11/share/doc/legal/intel_iwi/Makefile 289399 2015-10-16 00:38:05Z bdrewery $

FILES=		${.CURDIR}/../../../../sys/contrib/dev/iwi/LICENSE
FILESDIR=	${SHAREDIR}/doc/legal
FILESNAME=	intel_iwi.LICENSE

.include <bsd.prog.mk>
