#
# $FreeBSD: release/7.0.0/usr.sbin/flowctl/Makefile 135408 2004-09-17 22:37:45Z glebius $
#

PROG=	flowctl
MAN=	flowctl.8

WARNS?= 2
DPADD=  ${LIBNETGRAPH}
LDADD=  -lnetgraph

.include <bsd.prog.mk>
