# $FreeBSD: stable/11/usr.sbin/bsnmpd/modules/snmp_lm75/Makefile 266936 2014-06-01 03:14:03Z loos $

.include <bsd.own.mk>

MOD=    lm75
SRCS=   snmp_lm75.c
XSYM=   begemotLm75
MAN=    snmp_lm75.3

BMIBS=  BEGEMOT-LM75-MIB.txt
DEFS=   ${MOD}_tree.def

.include <bsd.snmpmod.mk>
