#
# $FreeBSD: release/10.0.0/tools/regression/sockets/unix_seqpacket_exercise/Makefile 197781 2009-10-05 15:27:01Z rwatson $
#

PROG=unix_seqpacket_exercise
CFLAGS+=-Wall -Werror
NO_MAN=

.include <bsd.prog.mk>
