# $MidnightBSD$
#
# $FreeBSD: stable/10/sys/modules/cxgbe/if_cxlv/Makefile 305549 2016-09-07 18:13:57Z jhb $
#

CXGBE=	${.CURDIR}/../../../dev/cxgbe
.PATH: ${CXGBE}

KMOD=	if_cxlv
SRCS=	if_cxlv.c

.include <bsd.kmod.mk>
