# $FreeBSD: stable/11/usr.bin/bmake/tests/suffixes/basic/Makefile.test 263346 2014-03-19 12:29:20Z jmmv $
#
# Check that a simple suffix rule is correctly processed.

test1:	TEST1.b
	diff -u TEST1.a TEST1.b

.SUFFIXES:

.SUFFIXES: .a .b

.a.b:
	cat ${.IMPSRC} >${.TARGET}
