# $FreeBSD: release/7.0.0/usr.sbin/i4b/Makefile 88736 2001-12-31 09:31:51Z joerg $

SUBDIR=	dtmfdecode g711conv isdnd isdndebug isdndecode isdnmonitor isdnphone \
	isdntel isdntelctl isdntest isdntrace man

.include <bsd.subdir.mk>

