# $FreeBSD: release/7.0.0/sys/modules/wpi/Makefile 174446 2007-12-08 12:44:59Z benjsc $

.PATH:  ${.CURDIR}/../../dev/wpi

KMOD    = if_wpi
SRCS    = if_wpi.c opt_bdg.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
