# $FreeBSD: stable/11/sys/modules/wpi/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:  ${SRCTOP}/sys/dev/wpi

KMOD    = if_wpi
SRCS    = if_wpi.c device_if.h bus_if.h pci_if.h opt_wpi.h opt_wlan.h

.include <bsd.kmod.mk>
