# $FreeBSD: stable/11/sys/modules/mac_ifoff/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/security/mac_ifoff

KMOD=	mac_ifoff
SRCS=	vnode_if.h \
	mac_ifoff.c

.include <bsd.kmod.mk>
