# $FreeBSD: stable/11/sys/modules/sound/driver/neomagic/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/sound/pci

KMOD=	snd_neomagic
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	neomagic.c

.include <bsd.kmod.mk>
