# $FreeBSD: stable/9/tools/tools/net80211/wlanstats/Makefile 161200 2006-08-10 19:01:16Z sam $

PROG=	wlanstats
BINDIR=	/usr/local/bin
NO_MAN=

SRCS=	statfoo.c wlanstats.c main.c

.include <bsd.prog.mk>
