# $FreeBSD: release/10.0.0/lib/clang/liblldbPluginPlatformGDB/Makefile 255722 2013-09-20 01:52:02Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginPlatformGDB

SRCDIR=	tools/lldb/source/Plugins/Platform/gdb-server
SRCS=	PlatformRemoteGDBServer.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
