# $FreeBSD: release/10.0.0/sys/modules/viawd/Makefile 228431 2011-12-12 09:50:33Z fabient $

.PATH: ${.CURDIR}/../../dev/viawd

KMOD=	viawd
SRCS=	viawd.c device_if.h bus_if.h pci_if.h isa_if.h

.include <bsd.kmod.mk>
