# $OpenBSD: Makefile,v 1.4 2015/02/06 01:07:07 schwarze Exp $

REGRESS_TARGETS	 = args

# OpenBSD only: .Xr target tests cause too much trouble elsewhere

LINT_TARGETS	 = args

.include <bsd.regress.mk>
