# $FreeBSD: release/10.0.0/sys/modules/bm/Makefile 179645 2008-06-07 22:58:32Z marcel $

.PATH: ${.CURDIR}/../../dev/bm

KMOD=	if_bm
SRCS=	if_bm.c
SRCS+=	bus_if.h device_if.h miibus_if.h ofw_bus_if.h

.include <bsd.kmod.mk>
