# $FreeBSD: release/7.0.0/usr.sbin/pppctl/Makefile 125270 2004-01-31 17:28:09Z marcel $

PROG=	pppctl
MAN=	pppctl.8

DPADD=	${LIBPTHREAD} ${LIBEDIT} ${LIBTERMCAP}
LDADD=	-lpthread -ledit -ltermcap

.include <bsd.prog.mk>
