# $FreeBSD: release/10.0.0/usr.bin/man/Makefile 213317 2010-10-01 03:59:18Z gordon $

SCRIPTS= man.sh
LINKS=	${BINDIR}/man ${BINDIR}/apropos \
	${BINDIR}/man ${BINDIR}/manpath \
	${BINDIR}/man ${BINDIR}/whatis

MAN=	man.1 manpath.1 apropos.1 man.conf.5
MLINKS=	apropos.1 whatis.1

.include <bsd.prog.mk>
