# $FreeBSD: stable/9/release/doc/ja_JP.eucJP/relnotes/Makefile 116993 2003-06-28 17:38:02Z hrs $
# Original revision: 1.6

RELN_ROOT?= ${.CURDIR}/../..

SUBDIR = alpha
SUBDIR+= amd64
SUBDIR+= ia64
SUBDIR+= i386
SUBDIR+= pc98
SUBDIR+= sparc64

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
