# $FreeBSD: release/10.0.0/sys/modules/rndtest/Makefile 112103 2003-03-11 19:26:16Z sam $

.PATH:	${.CURDIR}/../../dev/rndtest
KMOD	= rndtest
SRCS	= rndtest.c
SRCS   += device_if.h bus_if.h

.include <bsd.kmod.mk>
