# $FreeBSD: stable/11/sys/modules/rndtest/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:	${SRCTOP}/sys/dev/rndtest
KMOD	= rndtest
SRCS	= rndtest.c
SRCS   += device_if.h bus_if.h

.include <bsd.kmod.mk>
