# $FreeBSD: stable/9/lib/clang/libllvmlinker/Makefile 246637 2013-02-10 21:24:47Z dim $

.include <bsd.own.mk>

LIB=	llvmlinker

SRCDIR=	lib/Linker
SRCS=	LinkArchives.cpp \
	LinkItems.cpp \
	LinkModules.cpp \
	Linker.cpp

.include "../clang.lib.mk"
