# $FreeBSD: release/10.0.0/lib/clang/libllvmlinker/Makefile 251662 2013-06-12 18:48:53Z dim $

.include <bsd.own.mk>

LIB=	llvmlinker

SRCDIR=	lib/Linker
SRCS=	LinkModules.cpp

.include "../clang.lib.mk"
