# $FreeBSD: release/9.2.0/lib/clang/libllvmlinker/Makefile 252723 2013-07-04 20:17:04Z dim $

.include <bsd.own.mk>

LIB=	llvmlinker

SRCDIR=	lib/Linker
SRCS=	LinkModules.cpp

.include "../clang.lib.mk"
