# $FreeBSD: release/10.0.0/sys/modules/cc/cc_hd/Makefile 218153 2011-02-01 06:42:46Z lstewart $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/../../../netinet/cc
KMOD=	cc_hd
SRCS=	cc_hd.c

.include <bsd.kmod.mk>
