#
# $FreeBSD: release/7.0.0/tools/regression/netipx/ipxdgramloopback/Makefile 160202 2006-07-09 11:51:14Z maxim $
#

PROG=	ipxdgramloopback
NO_MAN=

DPADD=	${LIBIPX};
LDADD=	-lipx
WARNS?=	3

.include <bsd.prog.mk>
