# $FreeBSD: stable/11/libexec/hyperv/Makefile 322134 2017-08-07 02:49:26Z sephe $

.PATH:		${SRCTOP}/contrib/hyperv/tools/scripts

BINDIR=		${LIBEXECDIR}/hyperv

SCRIPTS=	hv_set_ifconfig hv_get_dns_info hv_get_dhcp_info
SCRIPTS+=	hyperv_vfattach hyperv_vfup

.include <bsd.prog.mk>
