# $FreeBSD: release/7.0.0/sys/modules/fxp/Makefile 150636 2005-09-27 18:10:43Z mlaier $

.PATH: ${.CURDIR}/../../dev/fxp

KMOD=	if_fxp
SRCS=	if_fxp.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
