#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/11/usr.sbin/pstat/Makefile 275054 2014-11-25 16:57:27Z bapt $

PROG=	pstat
LINKS=	${BINDIR}/pstat ${BINDIR}/swapinfo
MAN=	pstat.8
MLINKS=	pstat.8 swapinfo.8

LIBADD=	kvm util

.include <bsd.prog.mk>
