# $FreeBSD: release/10.0.0/sys/modules/geom/geom_multipath/Makefile 167050 2007-02-27 04:01:58Z mjacob $

.PATH: ${.CURDIR}/../../../geom/multipath

KMOD=	geom_multipath
SRCS=	g_multipath.c

.include <bsd.kmod.mk>
