# $FreeBSD: stable/11/sys/modules/geom/geom_multipath/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/geom/multipath

KMOD=	geom_multipath
SRCS=	g_multipath.c

.include <bsd.kmod.mk>
