# $FreeBSD: release/10.0.0/sys/modules/sound/driver/ds1/Makefile 110498 2003-02-07 13:56:33Z nyan $

.PATH: ${.CURDIR}/../../../../dev/sound/pci

KMOD=	snd_ds1
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	ds1.c

.include <bsd.kmod.mk>
