# $FreeBSD: stable/11/sys/modules/sound/driver/ds1/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/sound/pci

KMOD=	snd_ds1
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	ds1.c

.include <bsd.kmod.mk>
