# $FreeBSD: release/10.0.0/lib/clang/liblldbPluginCXXItaniumABI/Makefile 255722 2013-09-20 01:52:02Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginCXXItaniumABI

SRCDIR=	tools/lldb/source/Plugins/LanguageRuntime/CPlusPlus/ItaniumABI
SRCS=	ItaniumABILanguageRuntime.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
