# $MidnightBSD: src/libexec/mknetid/Makefile,v 1.2 2012/04/11 00:46:54 laffer1 Exp $
# $FreeBSD: src/libexec/mknetid/Makefile,v 1.7 2001/08/21 15:39:15 ru Exp $

PROG=	mknetid
SRCS=	mknetid.c hash.c parse_group.c

MAN=	netid.5 mknetid.8

WARNS?=	2

.include <bsd.prog.mk>
