# $MidnightBSD$
# $FreeBSD: stable/10/libexec/mknetid/Makefile 201380 2010-01-02 09:50:19Z ed $

PROG=	mknetid
SRCS=	mknetid.c hash.c parse_group.c

MAN=	netid.5 mknetid.8

WARNS?=	2

.include <bsd.prog.mk>
