# $FreeBSD: release/7.0.0/usr.bin/tail/Makefile 139995 2005-01-10 20:22:37Z dwmalone $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

PROG=	tail
SRCS=	forward.c misc.c read.c reverse.c tail.c
WARNS?=	4

.include <bsd.prog.mk>
