# $FreeBSD: release/10.0.0/usr.bin/tail/Makefile 201386 2010-01-02 10:27:05Z ed $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

PROG=	tail
SRCS=	forward.c misc.c read.c reverse.c tail.c

.include <bsd.prog.mk>
