# $FreeBSD: release/10.0.0/usr.sbin/pc-sysinstall/Makefile 209513 2010-06-24 22:21:47Z imp $
SUBDIR=backend backend-partmanager backend-query conf doc examples
SUBDIR+=pc-sysinstall

.include <bsd.subdir.mk>
