# $FreeBSD: stable/11/usr.sbin/pc-sysinstall/Makefile 288266 2015-09-26 14:13:51Z bdrewery $
SUBDIR=backend backend-partmanager backend-query conf doc examples
SUBDIR+=pc-sysinstall
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
