# $FreeBSD: release/10.0.0/sys/modules/cc/cc_cubic/Makefile 216114 2010-12-02 06:05:44Z lstewart $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/../../../netinet/cc
KMOD=	cc_cubic
SRCS=	cc_cubic.c

.include <bsd.kmod.mk>
