# $FreeBSD: release/10.0.0/sys/modules/aacraid/aacraid_linux/Makefile 250963 2013-05-24 09:22:43Z achim $

.PATH: ${.CURDIR}/../../../dev/aacraid

KMOD=	aacraid_linux
SRCS=	aacraid_linux.c

.include <bsd.kmod.mk>
