# $FreeBSD: stable/11/sys/modules/aacraid/aacraid_linux/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/aacraid

KMOD=	aacraid_linux
SRCS=	aacraid_linux.c

.include <bsd.kmod.mk>
