#
# This builds network tools.
#
# $FreeBSD: stable/11/tools/bsdbox/Makefile.net 291479 2015-11-30 09:02:28Z adrian $
#

CRUNCH_PROGS_sbin+=	route ping
CRUNCH_PROGS_usr.sbin+=	arp

# inetd
CRUNCH_PROGS_usr.sbin+=	inetd
CRUNCH_LIBS+=	-lwrap

#.if ${MK_INET6_SUPPORT} != "no"
#CRUNCH_PROGS_sbin+= ping6
#.endif

# netstat
CRUNCH_PROGS_usr.bin+=	netstat
CRUNCH_LIBS+=	-lmemstat -lnetgraph

# ifconfig
CRUNCH_PROGS_sbin+=	ifconfig
CRUNCH_SHLIBS+=	-l80211

# wlan stuff
CRUNCH_PROGS_usr.sbin+=	wlandebug

# tcpdump
CRUNCH_PROGS_usr.sbin+=	tcpdump
# CRUNCH_LIBS+=	-lpcap -lcrypto
