# $FreeBSD: release/7.0.0/share/examples/pf/Makefile 173538 2007-11-11 02:16:00Z mlaier $

NO_OBJ=

FILES=	faq-example1 faq-example2 faq-example3 \
	ackpri queue1 queue2 queue3 queue4 \
	pf.conf \
	spamd

FILESDIR=	${SHAREDIR}/examples/pf

.include <bsd.prog.mk>
