# $FreeBSD: stable/11/share/examples/pf/Makefile 299293 2016-05-10 00:51:50Z gjb $

PACKAGE=examples
FILES=	faq-example1 faq-example2 faq-example3 \
	ackpri queue1 queue2 queue3 queue4 \
	pf.conf \
	spamd

FILESDIR=	${SHAREDIR}/examples/pf

.include <bsd.prog.mk>
