# $MidnightBSD$
#
# $FreeBSD: stable/10/sys/modules/cxgbe/if_cxl/Makefile 278303 2015-02-06 01:10:04Z np $
#

CXGBE=	${.CURDIR}/../../../dev/cxgbe
.PATH: ${CXGBE}

KMOD=	if_cxl
SRCS=	if_cxl.c

.include <bsd.kmod.mk>
