# $FreeBSD: stable/11/sys/modules/sound/driver/driver/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/sound

KMOD=	snd_driver
SRCS=	device_if.h bus_if.h
SRCS+=	driver.c

.include <bsd.kmod.mk>
