#! /bin/sh
# $FreeBSD: release/10.0.0/usr.sbin/ctm/mkCTM/dequeue 50479 1999-08-28 01:35:59Z peter $

L=/home/ctm/log.dequeue
/usr/sbin/ctm_dequeue -n 1 -l $L /home/ctm/queue/ctm-cvs-cur
/usr/sbin/ctm_dequeue -n 1 -l $L /home/ctm/queue/ctm-src-cur
