# $MidnightBSD$
#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: stable/10/games/fortune/unstr/Makefile 276486 2014-12-31 23:25:37Z ngie $

PROG=	unstr
MAN=
CFLAGS+= -I${.CURDIR}/../strfile

.include <bsd.prog.mk>
