#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: release/7.0.0/games/fortune/unstr/Makefile 142328 2005-02-23 20:59:03Z ru $

PROG=	unstr
NO_MAN=
WARNS?=	6
CFLAGS+= -I${.CURDIR}/../strfile

.include <bsd.prog.mk>
