# $MidnightBSD$
# $FreeBSD: stable/10/lib/libiconv_modules/iconv_std/Makefile 260497 2014-01-09 23:08:56Z dim $

SHLIB=	iconv_std
SRCS+=	citrus_iconv_std.c
CFLAGS.gcc+= --param max-inline-insns-single=32

.include <bsd.lib.mk>
