# $FreeBSD: stable/11/lib/libiconv_modules/iconv_std/Makefile 285884 2015-07-26 00:11:04Z pfg $

SHLIB=	iconv_std
SRCS+=	citrus_iconv_std.c
CFLAGS.gcc+= --param max-inline-insns-single=64

.include <bsd.lib.mk>
