# $FreeBSD: release/10.0.0/lib/libiconv_modules/iconv_std/Makefile 219019 2011-02-25 00:04:39Z gabor $

SHLIB=	iconv_std
SRCS+=	citrus_iconv_std.c
CFLAGS+= --param max-inline-insns-single=32

.include <bsd.lib.mk>
