# $FreeBSD: release/10.0.0/sys/modules/mcd/Makefile 112806 2003-03-29 16:13:11Z mdodd $

.PATH: ${.CURDIR}/../../dev/mcd

KMOD=	mcd
SRCS=	mcd.c mcd_isa.c \
	bus_if.h device_if.h isa_if.h

.include <bsd.kmod.mk>
