#	From: @(#)Makefile	8.1 (Berkeley) 8/14/93
# $FreeBSD: release/10.0.0/share/doc/psd/20.ipctut/Makefile 136910 2004-10-24 15:33:08Z ru $

VOLUME=		psd/20.ipctut
SRCS=		tutor.me
MACROS=		-me
EXTRA=		dgramread.c dgramsend.c fig2.pic fig3.pic fig8.pic pipe.c \
		socketpair.c strchkread.c streamread.c streamwrite.c \
		udgramread.c udgramsend.c ustreamread.c ustreamwrite.c
USE_SOELIM=
USE_PIC=
USE_TBL=

.include <bsd.doc.mk>
