# $FreeBSD: release/10.0.0/tools/tools/cxgbetool/Makefile 222900 2011-06-09 20:21:45Z np $

PROG=	cxgbetool
SRCS=	cxgbetool.c
NO_MAN=
CFLAGS+= -I${.CURDIR}/../../../sys/dev/cxgbe -I.
BINDIR?= /usr/sbin

.include <bsd.prog.mk>
