#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/10.0.0/usr.bin/unvis/Makefile 248303 2013-03-15 00:05:50Z brooks $

PROG=	unvis

.PATH: ${.CURDIR}/../../contrib/unvis

.include <bsd.prog.mk>
