# $MidnightBSD$
# $FreeBSD: stable/10/sbin/mdconfig/tests/Makefile 313488 2017-02-09 22:49:48Z ngie $

ATF_TESTS_SH=	mdconfig_test

TEST_METADATA.mdconfig_test+=	required_user="root"

.include <bsd.test.mk>
