# $FreeBSD: release/10.0.0/tools/tools/net80211/wesside/dics/Makefile 161030 2006-08-07 00:05:04Z sam $

PROG=	dics
BINDIR=	/usr/local/bin
DPADD=	${LIBZ}
LDADD=	-lz
CFLAGS=-g
NO_MAN=

.include <bsd.prog.mk>
