# $MidnightBSD$
# $FreeBSD: stable/10/lib/libalias/libalias/Makefile 313581 2017-02-11 05:45:00Z ngie $

.PATH: ${SRCTOP}/sys/netinet/libalias

LIB=	alias
SHLIBDIR?= /lib
SHLIB_MAJOR= 7
MAN=	libalias.3
SRCS=	alias.c alias_db.c alias_proxy.c alias_util.c alias_mod.c
INCS=	alias.h
NO_WERROR=

.include <bsd.lib.mk>
