# $FreeBSD: stable/11/lib/libc/amd64/string/Makefile.inc 315044 2017-03-11 02:51:29Z brooks $

MDSRCS+= \
	bcmp.S \
	bcopy.S \
	bzero.S \
	memcmp.S \
	memcpy.S \
	memmove.S \
	memset.S \
	strcat.S \
	strcmp.S \
	stpcpy.S
