# $FreeBSD: release/10.0.0/lib/libc/amd64/string/Makefile.inc 224246 2011-07-21 16:32:13Z gnn $

MDSRCS+= bcmp.S bcopy.S bzero.S memcmp.S memcpy.S memmove.S memset.S \
	strcat.S strcmp.S stpcpy.S strcpy.c
