# $FreeBSD: stable/11/sbin/nandfs/Makefile 298107 2016-04-16 07:45:30Z gjb $

PACKAGE=nandfs
PROG=	nandfs
SRCS=	nandfs.c lssnap.c mksnap.c rmsnap.c
MAN=	nandfs.8

LIBADD=	nandfs

.include <bsd.prog.mk>
