# $FreeBSD: stable/11/sys/modules/ipdivert/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/netinet

KMOD=   ipdivert
SRCS=   ip_divert.c opt_inet.h opt_inet6.h opt_sctp.h

.include <bsd.kmod.mk>
