# $FreeBSD: stable/11/lib/msun/riscv/Makefile.inc 292124 2015-12-11 22:55:23Z br $

# RISCVTODO: should be 113
# compilation problems: gcc generates bltuz instruction, which is not exists

LDBL_PREC = 53
