# $FreeBSD: release/10.0.0/sys/modules/canbepm/Makefile 110285 2003-02-03 14:46:26Z nyan $

.PATH:	${.CURDIR}/../../pc98/pc98
KMOD	= canbepm
SRCS	= canbepm.c
SRCS	+= device_if.h bus_if.h canbus_if.h

.include <bsd.kmod.mk>
