#!/bin/sh
#
# Add additional swap files
#
# $FreeBSD: release/10.0.0/etc/rc.d/addswap 252310 2013-06-27 18:28:45Z hrs $
#

# PROVIDE: addswap
# REQUIRE: FILESYSTEMS kld
# BEFORE:  netif
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="addswap"
start_cmd=":"
stop_cmd=":"
rcvar=

set_rcvar_obsolete swapfile
set_rcvar_obsolete geli_swap_flags

load_rc_config $name
run_rc_command "$1"
