#!/bin/sh
#
# $FreeBSD: stable/11/etc/rc.d/adjkerntz 273957 2014-11-02 01:47:27Z des $
#

# PROVIDE: adjkerntz
# REQUIRE: FILESYSTEMS
# BEFORE: netif
# KEYWORD: nojail

. /etc/rc.subr

name="adjkerntz"
start_cmd="adjkerntz -i"
stop_cmd=":"

load_rc_config $name
run_rc_command "$1"
