#!/bin/sh
#
# $MidnightBSD: src/etc/rc.d/adjkerntz,v 1.2 2006/08/28 02:13:44 laffer1 Exp $
# $FreeBSD: src/etc/rc.d/adjkerntz,v 1.5 2004/10/07 13:55:25 mtm Exp $
#

# PROVIDE: adjkerntz
# REQUIRE: FILESYSTEMS random
# BEFORE: netif
# KEYWORD: nojail

. /etc/rc.subr

name="adjkerntz"
start_cmd="adjkerntz -i"
stop_cmd=":"

load_rc_config $name
run_rc_command "$1"
