#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/archdep 193119 2009-05-30 21:51:38Z dougb $
#

# PROVIDE: archdep
# REQUIRE: mountcritremote
# KEYWORD: nojail

. /etc/rc.subr

name="archdep"
start_cmd="archdep_start"
stop_cmd=":"

archdep_start()
{
	local _arch

	_arch=`${SYSCTL_N} hw.machine_arch`
	case $_arch in
	i386)
		# SCO binary emulation
		#
		if checkyesno ibcs2_enable; then
			echo -n 'Initial i386 initialization:'
			echo -n ' ibcs2'
			load_kld ibcs2
			case ${ibcs2_loaders} in
			[Nn][Oo])
				;;
			*)
				for i in ${ibcs2_loaders}; do
					load_kld ibcs2_$i
				done
				;;
			esac
			echo '.'
		fi
		;;
	esac
}

load_rc_config $name
run_rc_command "$1"
