#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/auditdistd 244181 2012-12-13 09:41:32Z pjd $
#

# PROVIDE: auditdistd
# REQUIRE: auditd
# BEFORE:  DAEMON
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="auditdistd"
rcvar="${name}_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"
required_files="/etc/security/${name}.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
