#!/bin/sh
#
# $FreeBSD: stable/11/etc/rc.d/bootparams 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: bootparams
# REQUIRE: rpcbind DAEMON
# BEFORE:  LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="bootparamd"
desc="Boot parameter daemon"
rcvar="bootparamd_enable"
required_files="/etc/bootparams"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
