#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/bootparams 175737 2008-01-28 07:58:32Z dougb $
#

# PROVIDE: bootparams
# REQUIRE: rpcbind DAEMON
# BEFORE:  LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="bootparamd"
rcvar=`set_rcvar`
required_files="/etc/bootparams"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
