#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/bsnmpd 145184 2005-04-17 10:47:58Z glebius $
#

# PROVIDE: bsnmpd
# REQUIRE: NETWORKING syslogd
# KEYWORD: nojail

. /etc/rc.subr

name="bsnmpd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/snmpd.pid"

load_rc_config $name
run_rc_command "$1"
