#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/bsnmpd 254511 2013-08-19 05:37:49Z peter $
#

# PROVIDE: bsnmpd
# REQUIRE: NETWORKING syslogd
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="bsnmpd"
rcvar="bsnmpd_enable"
command="/usr/sbin/${name}"

load_rc_config $name
pidfile="${bsnmpd_pidfile:-/var/run/snmpd.pid}"
command_args="-p ${pidfile}"
run_rc_command "$1"
