#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/bsnmpd 231653 2012-02-14 10:16:56Z dougb $
#

# PROVIDE: bsnmpd
# REQUIRE: NETWORKING syslogd
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="bsnmpd"
rcvar="bsnmpd_enable"
command="/usr/sbin/${name}"
pidfile="/var/run/snmpd.pid"

load_rc_config $name
run_rc_command "$1"
