#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/ccd 174438 2007-12-08 07:20:23Z dougb $
#

# PROVIDE: disks
# KEYWORD: nojail

. /etc/rc.subr

name="ccd"
start_cmd="ccd_start"
stop_cmd=":"

ccd_start()
{
	if [ -f /etc/ccd.conf ]; then
		echo "Configuring CCD devices."
		ccdconfig -C
	fi
}

load_rc_config $name
run_rc_command "$1"
