#!/bin/sh
#
# $FreeBSD: stable/11/etc/rc.d/cron 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: cron
# REQUIRE: LOGIN FILESYSTEMS
# BEFORE: securelevel
# KEYWORD: shutdown

. /etc/rc.subr

name="cron"
desc="Daemon to execute scheduled commands"
rcvar="cron_enable"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config $name
if checkyesno cron_dst
then
	cron_flags="$cron_flags -s"
fi
run_rc_command "$1"
