#!/bin/sh
#
# $FreeBSD: stable/11/etc/rc.d/ctld 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: ctld
# REQUIRE: FILESYSTEMS
# BEFORE:  DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="ctld"
desc="CAM Target Layer / iSCSI target daemon"
rcvar="ctld_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"
required_files="/etc/ctl.conf"
required_modules="ctl"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
