#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/ctld 255570 2013-09-14 15:29:06Z trasz $
#

# PROVIDE: ctld
# REQUIRE: FILESYSTEMS
# BEFORE:  DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="ctld"
rcvar="ctld_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"
required_files="/etc/ctl.conf"
required_modules="ctl"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
