#!/bin/sh
#
# $MidnightBSD: src/etc/rc.d/DAEMON,v 1.3 2009/01/17 17:42:14 laffer1 Exp $

# PROVIDE: DAEMON
# REQUIRE: NETWORKING SERVERS

#	This is a dummy dependency, to ensure that general purpose daemons
#	are run _after_ the above are.
