#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/DAEMON 174438 2007-12-08 07:20:23Z dougb $
#

# PROVIDE: DAEMON
# REQUIRE: NETWORKING SERVERS

#	This is a dummy dependency, to ensure that general purpose daemons
#	are run _after_ the above are.
