#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/DAEMON 175737 2008-01-28 07:58:32Z dougb $
#

# PROVIDE: DAEMON
# REQUIRE: NETWORKING SERVERS

#	This is a dummy dependency, to ensure that general purpose daemons
#	are run _after_ the above are.
