#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/ddb 230099 2012-01-14 02:18:41Z dougb $
#

# PROVIDE: ddb
# REQUIRE: dumpon
# BEFORE: disks
# KEYWORD: nojail

. /etc/rc.subr

name="ddb"
rcvar="ddb_enable"
command="/sbin/${name}"
start_precmd="ddb_prestart"
stop_cmd=":"

ddb_prestart()
{
	# Silently exit if ddb is not enabled
	if [ -z "`sysctl -Nq debug.ddb.scripting.scripts`" ]; then
		return 1
	fi
}

load_rc_config $name

required_files="${ddb_config}"
command_args="${ddb_config}"

run_rc_command "$1"
