#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/FILESYSTEMS,v 1.1 2007/04/02 22:53:07 des Exp $
# $MidnightBSD: src/etc/rc.d/FILESYSTEMS,v 1.1 2007/10/26 13:51:41 laffer1 Exp $

# PROVIDE: FILESYSTEMS
# REQUIRE: root mountcritlocal zfs

#	This is a dummy dependency, for services which require file systems
#	to be mounted before starting.  It also serves as the default early /
#	late divider; after this point, rc.d directories are rescanned to
#	catch scripts from other file systems than /.
