#!/bin/sh
#
# $MidnightBSD: src/etc/rc.d/firstboot,v 1.1 2007/08/06 00:23:51 laffer1 Exp $

# PROVIDE: firstboot
# REQUIRE: NETWORKING cleanvar
# KEYWORD: nojail

. /etc/rc.subr

name="firstboot"
rcvar=
start_cmd="firstboot_start"

firstboot_start()
{
	local lsuffix
	local red
	local yellow
	local receipt

	lsuffix="\e[0m"
	red="\e[1;31;40m"
	yellow="\e[1;33;40m"
	receipt="/etc/fbreceipt"

	if [ ! -f ${receipt} ]; then
		echo -e "\r${red}MidnightBSD FirstBoot Configuration${lsuffix}"

		echo "This utility requires an active Internet connection."
		echo -e "\r${yellow}Do you wish to install a graphical environment? (yes or no)${lsuffix}"
		read installgui

		if [ ${installgui} = "yes" ]; then
			echo -e "\r${red}Installing Graphical User Interface${lsuffix}"
			/usr/sbin/pkg_add -r gnustep
			/usr/sbin/pkg_add -r slim
			/usr/sbin/pkg_add -r windowmaker
			echo -e "\r${yellow}Done.${lsuffix}"
		else
			echo "To run this utility again, rm ${receipt} and restart."
		fi
		touch ${receipt}
	fi
}

load_rc_config $name
run_rc_command "$1"
