#!/bin/sh
#
# $MidnightBSD$

# PROVIDE: firstboot
# REQUIRE: NETWORKING cleanvar
# KEYWORD: nojail

. /etc/rc.subr

name="firstboot"
rcvar=
start_cmd="firstboot_start"
required_files="/etc/reconfig"

firstboot_start()
{
	local lsuffix
	local red
	local yellow

	lsuffix="\e[0m"
	red="\e[1;31;40m"
	yellow="\e[1;33;40m"

	if [ -f /etc/reconfig ]; then
		echo -e "\r${red}MidnightBSD FirstBoot Configuration${lsuffix}"

		echo "This utility requires an active Internet connection."
		echo -e "\r${yellow}Do you wish to install a graphical environment? (yes or no)${lsuffix}"
		read installgui

		if [ ${installgui} = "yes" ]; then
			echo -e "\r${red}Installing Graphical User Interface${lsuffix}"
			/usr/sbin/pkg_add -r gnustep
			/usr/sbin/pkg_add -r slim
			/usr/sbin/pkg_add -r windowmaker
			echo -e "\r${yellow}Done.${lsuffix}"
		else
			echo "To run this utility again, touch /etc/reconfig and restart."
		fi
		rm -f /etc/reconfig
	fi
}

load_rc_config $name
run_rc_command "$1"
