#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/ftp-proxy 231653 2012-02-14 10:16:56Z dougb $
#

# PROVIDE: ftp-proxy
# REQUIRE: DAEMON pf
# KEYWORD: shutdown

. /etc/rc.subr

name="ftpproxy"
rcvar="ftpproxy_enable"
command="/usr/sbin/ftp-proxy"

load_rc_config $name
run_rc_command "$1"
