#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/ftpd 154645 2006-01-21 18:08:16Z yar $
#

# PROVIDE: ftpd
# REQUIRE: LOGIN cleanvar

. /etc/rc.subr

name="ftpd"
rcvar=`set_rcvar`
command="/usr/libexec/${name}"
pidfile="/var/run/${name}.pid"
start_precmd=ftpd_prestart

ftpd_prestart()
{
	rc_flags="-D ${rc_flags}"
	return 0
}

load_rc_config $name
run_rc_command "$1"
