#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/ftpd 240336 2012-09-11 05:04:59Z obrien $
#

# PROVIDE: ftpd
# REQUIRE: LOGIN FILESYSTEMS
# KEYWORD: shutdown

. /etc/rc.subr

name="ftpd"
rcvar="ftpd_enable"
command="/usr/libexec/${name}"
pidfile="/var/run/${name}.pid"
start_precmd=ftpd_prestart

ftpd_prestart()
{
	rc_flags="-D ${rc_flags}"
	return 0
}

load_rc_config $name
run_rc_command "$1"
