#!/bin/sh
#
# $FreeBSD: stable/11/etc/rc.d/gssd 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: gssd
# REQUIRE: root
# KEYWORD: nojail shutdown

. /etc/rc.subr

name=gssd
desc="Generic Security Services Daemon"
rcvar=gssd_enable

load_rc_config $name
run_rc_command "$1"
