#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/hastd 230099 2012-01-14 02:18:41Z dougb $
#

# PROVIDE: hastd
# REQUIRE: NETWORKING syslogd
# BEFORE:  DAEMON
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="hastd"
rcvar="hastd_enable"
pidfile="/var/run/${name}.pid"
command="/sbin/${name}"
hastctl="/sbin/hastctl"
required_files="/etc/hast.conf"
stop_precmd="hastd_stop_precmd"
required_modules="geom_gate:g_gate"
extra_commands="reload"

hastd_stop_precmd()
{
	${hastctl} role init all
}

load_rc_config $name
run_rc_command "$1"
