#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/hcsecd 165683 2006-12-31 10:37:18Z yar $
#

# PROVIDE: hcsecd
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="hcsecd"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
rcvar=`set_rcvar`
required_modules="ng_btsocket"

load_rc_config $name
config="${hcsecd_config:-/etc/bluetooth/${name}.conf}"
command_args="-f ${config}"
required_files="${config}"

run_rc_command "$1"
