#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/hostid_save 208307 2010-05-19 19:03:19Z dougb $
#

# PROVIDE: hostid_save
# REQUIRE: root
# KEYWORD: nojail

. /etc/rc.subr

name="hostid_save"
start_cmd="hostid_save"
stop_cmd=":"
rcvar="hostid_enable"

hostid_save()
{
	if [ ! -r ${hostid_file} ]; then
		$SYSCTL_N kern.hostuuid > ${hostid_file}
		if [ $? -ne 0 ]; then
			warn "could not store hostuuid in ${hostid_file}."
		fi
	fi
}

load_rc_config $name
run_rc_command "$1"
