#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/hostapd 175142 2008-01-07 21:15:45Z brix $
#

# PROVIDE: hostapd
# REQUIRE: mountcritremote
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="hostapd"
command="/usr/sbin/${name}"
rcvar=`set_rcvar`

conf_file="/etc/${name}.conf"
pidfile="/var/run/${name}.pid"

command_args="-P ${pidfile} -B ${conf_file}"
required_files="${conf_file}"
extra_commands="reload"

load_rc_config ${name}
run_rc_command "$1"
