#!/bin/sh
#
# $FreeBSD: stable/11/etc/rc.d/inetd 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: inetd
# REQUIRE: DAEMON LOGIN FILESYSTEMS
# KEYWORD: shutdown

. /etc/rc.subr

name="inetd"
desc="Internet \"super-server\""
rcvar="inetd_enable"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/${name}.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
