#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/inetd 175737 2008-01-28 07:58:32Z dougb $
#

# PROVIDE: inetd
# REQUIRE: DAEMON LOGIN cleanvar
# KEYWORD: shutdown

. /etc/rc.subr

name="inetd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/${name}.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
