#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/ipmon 242153 2012-10-26 18:06:49Z obrien $
#

# PROVIDE: ipmon
# REQUIRE: FILESYSTEMS hostname sysctl FILESYSTEMS ipfilter
# BEFORE:  SERVERS
# KEYWORD: nojail

. /etc/rc.subr

name="ipmon"
rcvar="ipmon_enable"
command="/sbin/${name}"
start_precmd="ipmon_precmd"

ipmon_precmd()
{
	# Continue only if ipfilter or ipnat is enabled and the
	# ipfilter module is loaded.
	#
	if ! checkyesno ipfilter_enable && ! checkyesno ipnat_enable ; then
		err 1  "${name} requires either ipfilter or ipnat enabled"
	fi
	if ! sysctl net.inet.ipf.fr_pass >/dev/null 2>&1; then
		err 1 "ipfilter module is not loaded"
	fi
	return 0
}

load_rc_config $name
run_rc_command "$1"
