#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/ipxrouted 231653 2012-02-14 10:16:56Z dougb $
#

# PROVIDE: ipxrouted
# REQUIRE: SERVERS
# BEFORE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="ipxrouted"
rcvar="ipxrouted_enable"
command="/usr/sbin/IPXrouted"
command_args="> /dev/null 2>&1"

load_rc_config $name
run_rc_command "$1"
