#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/ipxrouted 136224 2004-10-07 13:55:26Z mtm $
#

# PROVIDE: ipxrouted
# REQUIRE: SERVERS
# BEFORE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="ipxrouted"
rcvar=`set_rcvar`
command="/usr/sbin/IPXrouted"
command_args="> /dev/null 2>&1"

load_rc_config $name
run_rc_command "$1"
