#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/ipxrouted 230099 2012-01-14 02:18:41Z dougb $
#

# PROVIDE: ipxrouted
# REQUIRE: SERVERS
# BEFORE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="ipxrouted"
rcvar="ipxrouted_enable"
command="/usr/sbin/IPXrouted"
command_args="> /dev/null 2>&1"

load_rc_config $name
run_rc_command "$1"
