#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/iscsictl 255570 2013-09-14 15:29:06Z trasz $
#

# PROVIDE: iscsictl
# REQUIRE: NETWORK iscsid
# BEFORE:  DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="iscsictl"
rcvar="iscsictl_enable"
command="/usr/bin/${name}"
command_args="${iscsictl_flags}"
required_modules="iscsi"

load_rc_config $name
run_rc_command "$1"
