#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/kadmind 180563 2008-07-16 19:22:48Z dougb $
#

# PROVIDE: kadmin
# REQUIRE: kerberos
# BEFORE: DAEMON

. /etc/rc.subr

name="kadmind5"
load_rc_config $name
rcvar="kadmind5_server_enable"
unset start_cmd
command="${kadmind5_server}"
command_args="&"
required_vars="kerberos5_server_enable"

run_rc_command "$1"
