#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/kadmind 136224 2004-10-07 13:55:26Z mtm $
#

# PROVIDE: kadmin
# REQUIRE: kerberos
# BEFORE: DAEMON

. /etc/rc.subr

name="kadmind5"
load_rc_config $name
rcvar="kadmind5_server_enable"
unset start_cmd
command="${kadmind5_server}"
command_args="&"
required_vars="kerberos5_server_enable"

run_rc_command "$1"
