#!/bin/sh
#
# $FreeBSD: stable/11/etc/rc.d/kdc 298844 2016-04-30 09:50:08Z ngie $
#

# PROVIDE: kdc
# REQUIRE: NETWORKING
# BEFORE: SERVERS
# KEYWORD: shutdown

. /etc/rc.subr

name=kdc
desc="Kerberos 5 server"
rcvar=${name}_enable
start_precmd=${name}_start_precmd

set_rcvar_obsolete kerberos5_server_enable kdc_enable
set_rcvar_obsolete kerberos5_server kdc_program
set_rcvar_obsolete kerberos5_server_flags kdc_flags

kdc_start_precmd()
{

	command_args="$command_args --detach"
}

load_rc_config $name
run_rc_command "$1"
