#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/kerberos 175788 2008-01-29 07:15:46Z mtm $
#

# PROVIDE: kerberos
# REQUIRE: NETWORKING

. /etc/rc.subr

name="kerberos5"
rcvar="kerberos5_server_enable"

load_rc_config $name
command="${kerberos5_server}"
kerberos5_flags="${kerberos5_server_flags}"
run_rc_command "$1"
