#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/kerberos 180563 2008-07-16 19:22:48Z dougb $
#

# PROVIDE: kerberos
# REQUIRE: NETWORKING

. /etc/rc.subr

name="kerberos5"
rcvar="kerberos5_server_enable"

load_rc_config $name
command="${kerberos5_server}"
kerberos5_flags="${kerberos5_server_flags}"
run_rc_command "$1"
