#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/kernel 160835 2006-07-30 12:54:37Z mckay $
#

# PROVIDE: kernel
# REQUIRE: mountcritremote
# KEYWORD: nojail

. /etc/rc.subr

name="kernel"
start_cmd="kernel_start"
stop_cmd=":"

kernel_start()
{
	bootdir=$(dirname $(sysctl -n kern.bootfile))
	if [ "$bootdir" != /boot/kernel ] ; then
		if [ ! -e /boot/kernel -o -h /boot/kernel ] ; then
			ln -hfs ${bootdir} /boot/kernel
		fi
	fi
}

load_rc_config $name
run_rc_command "$1"
