#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/keyserv 231792 2012-02-15 22:59:15Z dougb $
#

# Start keyserv if we are running Secure RPC

# PROVIDE: keyserv
# REQUIRE: ypset
# BEFORE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="keyserv"
rcvar="keyserv_enable"
command="/usr/sbin/${name}"
start_precmd="keyserv_prestart"

keyserv_prestart()
{
	force_depend rpcbind || return 1
}

load_rc_config $name
run_rc_command "$1"
