#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/local 175737 2008-01-28 07:58:32Z dougb $
#

# PROVIDE: local
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="local"
start_cmd="local_start"
stop_cmd="local_stop"

local_start()
{
	echo -n 'Starting local daemons:'
	if [ -f /etc/rc.local ]; then
		. /etc/rc.local
	fi
	echo '.'
}

local_stop()
{
	echo -n 'Shutting down local daemons:'
	if [ -f /etc/rc.shutdown.local ]; then
		. /etc/rc.shutdown.local
	fi
	echo '.'
}

load_rc_config $name
run_rc_command "$1"
