#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/local 179931 2008-06-22 16:23:39Z mtm $
#

# PROVIDE: local
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="local"
start_cmd="local_start"
stop_cmd="local_stop"

local_start()
{
	if [ -f /etc/rc.local ]; then
		echo -n 'Starting local daemons:'
		. /etc/rc.local
		echo '.'
	fi
}

local_stop()
{
	if [ -f /etc/rc.shutdown.local ]; then
		echo -n 'Shutting down local daemons:'
		. /etc/rc.shutdown.local
		echo '.'
	fi
}

load_rc_config $name
run_rc_command "$1"
