#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/LOGIN 175737 2008-01-28 07:58:32Z dougb $
#

# PROVIDE: LOGIN
# REQUIRE: DAEMON

#	This is a dummy dependency to ensure user services such as xdm,
#	inetd, cron and kerberos are started after everything else, in case
#	the administrator has increased the system security level and
#	wants to delay user logins until the system is (almost) fully
#	operational.
