#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/lpd,v 1.8.4.1 2008/01/28 07:58:31 dougb Exp $
# $MidnightBSD: src/etc/rc.d/lpd,v 1.2 2006/08/28 02:47:45 laffer1 Exp $

# PROVIDE: lpd
# REQUIRE: DAEMON
# BEFORE:  LOGIN

. /etc/rc.subr

name="lpd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
required_files="/etc/printcap"
start_precmd="chkprintcap"

chkprintcap()
{
	if checkyesno chkprintcap_enable ; then
		/usr/sbin/chkprintcap ${chkprintcap_flags}
	fi
}

load_rc_config $name
run_rc_command "$1"
