#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/lpd 230099 2012-01-14 02:18:41Z dougb $
#

# PROVIDE: lpd
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="lpd"
rcvar="lpd_enable"
command="/usr/sbin/${name}"
required_files="/etc/printcap"
start_precmd="chkprintcap"

chkprintcap()
{
	if checkyesno chkprintcap_enable ; then
		/usr/sbin/chkprintcap ${chkprintcap_flags}
	fi
}

load_rc_config $name
run_rc_command "$1"
