#!/bin/sh
#
# $MidnightBSD: src/etc/rc.d/inetd,v 1.2 2006/08/28 02:47:45 laffer1 Exp $

# PROVIDE: mdnsd
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="mdnsd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/mDNSResponder.pid"

load_rc_config $name
run_rc_command $*
