#!/bin/sh
#
# $MidnightBSD$

# PROVIDE: mdnsd
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="mdnsd"
rcvar=mdnsd_enable
command="/usr/sbin/${name}"
pidfile="/var/run/mDNSResponder.pid"

load_rc_config $name
run_rc_command $*
