#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/mountlate 169668 2007-05-18 12:04:41Z mtm $
#

# PROVIDE: mountlate
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="mountlate"
start_cmd="mountlate_start"
stop_cmd=":"

mountlate_start()
{
	# Mount "late" filesystems.
	echo -n 'Mounting late file systems:'
	mount -a -l
	echo '.'

	case $? in
	0)
		;;
	*)
		echo 'Mounting /etc/fstab filesystems failed,' \
		    ' startup aborted'
		stop_boot true
		;;
	esac
}

load_rc_config $name
run_rc_command "$1"
