#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/mrouted 242153 2012-10-26 18:06:49Z obrien $
#

# PROVIDE: mrouted
# REQUIRE: netif routing FILESYSTEMS
# KEYWORD: nojail

. /etc/rc.subr

name="mrouted"
rcvar="mrouted_enable"
command="/usr/local/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/${name}.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
