#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/mroute6d 136224 2004-10-07 13:55:26Z mtm $
#

# PROVIDE: mroute6d
# REQUIRE: network_ipv6
# KEYWORD: nojail

. /etc/rc.subr

name="mroute6d"
rcvar=`set_rcvar`
command="/usr/local/sbin/pim6dd"

load_rc_config $name
run_rc_command "$1"
