#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/mrouted 240336 2012-09-11 05:04:59Z obrien $
#

# PROVIDE: mrouted
# REQUIRE: netif routing FILESYSTEMS
# KEYWORD: nojail

. /etc/rc.subr

name="mrouted"
rcvar="mrouted_enable"
command="/usr/local/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/${name}.conf"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
