#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/mroute6d 231653 2012-02-14 10:16:56Z dougb $
#

# PROVIDE: mroute6d
# REQUIRE: netif routing
# BEFORE: NETWORKING
# KEYWORD: nojail

. /etc/rc.subr

name="mroute6d"
rcvar="mroute6d_enable"
command="/usr/local/sbin/pim6dd"

load_rc_config $name
run_rc_command "$1"
