#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/msgs 136224 2004-10-07 13:55:26Z mtm $
#

# PROVIDE: msgs
# REQUIRE: LOGIN

# Make a bounds file for msgs(1) if there isn't one already
#
if [ -d /var/msgs -a ! -f /var/msgs/bounds -a ! -L /var/msgs/bounds ]; then
	echo 0 > /var/msgs/bounds
fi
