#!/bin/sh
#
# $FreeBSD: stable/11/etc/rc.d/msgs 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: msgs
# REQUIRE: LOGIN

. /etc/rc.subr

name="msgs"
desc="Make a bounds file for msgs(1)"
start_cmd="msgs_start"
stop_cmd=":"

msgs_start()
{
	# Make a bounds file for msgs(1) if there isn't one already
	#
	if [ -d /var/msgs -a ! -f /var/msgs/bounds -a ! -L /var/msgs/bounds ]; then
		echo 0 > /var/msgs/bounds
	fi
}

load_rc_config $name
run_rc_command "$1"
