#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/NETWORKING 255843 2013-09-24 11:49:04Z des $
#

# PROVIDE: NETWORKING NETWORK
# REQUIRE: netif netoptions routing ppp ipfw stf faith
# REQUIRE: defaultroute routed mrouted route6d mroute6d resolv bridge
# REQUIRE: static_arp static_ndp local_unbound

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
