#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/NETWORKING 226786 2011-10-26 08:34:00Z mm $
#

# PROVIDE: NETWORKING NETWORK
# REQUIRE: netif netoptions routing ppp ipfw stf faith
# REQUIRE: defaultroute routed mrouted route6d mroute6d resolv bridge
# REQUIRE: static_arp static_ndp

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
