#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/newsyslog 175737 2008-01-28 07:58:32Z dougb $
#

# PROVIDE: newsyslog
# REQUIRE: cleanvar mountcritremote

. /etc/rc.subr

name="newsyslog"
rcvar=`set_rcvar`
required_files="/etc/newsyslog.conf"
command="/usr/sbin/${name}"
start_cmd="newsyslog_start"
stop_cmd=":"

newsyslog_start()
{
	echo -n "Creating and/or trimming log files:"
	${command} ${rc_flags}
	echo "."
}

load_rc_config $name
run_rc_command "$1"
