#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/nfscbd 231653 2012-02-14 10:16:56Z dougb $
#

# PROVIDE: nfscbd
# REQUIRE: NETWORKING nfsuserd
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="nfscbd"
rcvar="nfscbd_enable"
command="/usr/sbin/${name}"
sig_stop="USR1"

load_rc_config $name

run_rc_command "$1"
