#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/nfslocking,v 1.11 2004/10/07 13:55:26 mtm Exp $
# $MidnightBSD: src/etc/rc.d/nfslocking,v 1.2 2006/08/28 02:47:46 laffer1 Exp $

# PROVIDE: nfslocking
# REQUIRE: nfsserver nfsclient nfsd
# BEFORE:  DAEMON
# KEYWORD: nojail

. /etc/rc.subr

# Save the (one) commandline argument in case it gets clobbered.
arg=$1

# Either NFS client or server must be enabled or this must be a 'forcestart'
# for either of the daemons to start.
#
start_precmd='checkyesno nfs_server_enable || checkyesno nfs_client_enable ||
    [ -n "$rc_force" ]'
stop_precmd=$start_precmd
status_precmd=$start_precmd

# rpc.statd
#
name="statd"
rcvar=rpc_statd_enable
command="/usr/sbin/rpc.${name}"
load_rc_config $name
run_rc_command "$arg"

# rpc.lockd
#
name="lockd"
rcvar=rpc_lockd_enable
command="/usr/sbin/rpc.${name}"
load_rc_config $name
run_rc_command "$arg"
