#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/nfsserver 165683 2006-12-31 10:37:18Z yar $
#

# PROVIDE: nfsserver
# REQUIRE: NETWORKING mountcritremote
# KEYWORD: nojail

. /etc/rc.subr

name="nfsserver"
rcvar="nfs_server_enable"
start_cmd=":"
stop_cmd=":"
required_modules="nfsserver"

load_rc_config $name
run_rc_command "$1"
