#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/nfsuserd 231653 2012-02-14 10:16:56Z dougb $
#

# PROVIDE: nfsuserd
# REQUIRE: NETWORKING
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="nfsuserd"
rcvar="nfsuserd_enable"
command="/usr/sbin/${name}"
sig_stop="USR1"

load_rc_config $name

run_rc_command "$1"
