#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/nfsuserd 230099 2012-01-14 02:18:41Z dougb $
#

# PROVIDE: nfsuserd
# REQUIRE: NETWORKING
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="nfsuserd"
rcvar="nfsuserd_enable"
command="/usr/sbin/${name}"
sig_stop="USR1"

load_rc_config $name

run_rc_command "$1"
