#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/ntpdate 160524 2006-07-20 10:07:34Z flz $
#

# PROVIDE: ntpdate
# REQUIRE: NETWORKING syslogd named
# KEYWORD: nojail

. /etc/rc.subr

name="ntpdate"
rcvar=`set_rcvar`
stop_cmd=":"
start_cmd="ntpdate_start"

ntpdate_start()
{
	if [ -z "$ntpdate_hosts" -a -f ${ntpdate_config} ]; then
		ntpdate_hosts=`awk '
			/^server[ \t]*127.127/      {next}
			/^(server|peer)/            {print $2}
		' < ${ntpdate_config}`
	fi
	if [ -n "$ntpdate_hosts" -o -n "$rc_flags" ]; then
		echo "Setting date via ntp."
		${ntpdate_program:-ntpdate} $rc_flags $ntpdate_hosts
	fi
}

load_rc_config $name
run_rc_command "$1"
