#!/bin/sh
#
# $MidnightBSD: src/etc/rc.d/ntpd,v 1.5 2007/09/28 22:17:23 laffer1 Exp $
#

# PROVIDE: ntpd
# REQUIRE: DAEMON rdate cleanvar devfs
# BEFORE:  LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name=ntpd
rcvar="ntpd_enable"
command="/usr/sbin/${name}"
start_precmd="ntpd_precmd"
required_files="/etc/ntpd.conf"

ntpd_precmd()
{
	if checkyesno ntpd_sync_on_start; then
		rc_flags="-s ${ntpd_flags}"
	fi
}

load_rc_config $name
run_rc_command "$1"
