#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/ntpd,v 1.11.2.1 2006/01/17 06:45:05 dougb Exp $
#

# PROVIDE: ntpd
# REQUIRE: DAEMON ntpdate cleanvar devfs
# BEFORE:  LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name=ntpd
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
start_precmd="ntpd_precmd"
required_files="/etc/ntpd.conf"

ntpd_precmd()
{
	if checkyesno ntpd_sync_on_start; then
		rc_flags="-s ${ntpd_flags}"
	fi
}

load_rc_config $name
run_rc_command "$1"
