#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/opensm 221006 2011-04-25 05:57:01Z dougb $
#

# PROVIDE: opensm
# BEFORE: netif
# REQUIRE: FILESYSTEMS

. /etc/rc.subr

name="opensm"
start_cmd="opensm_start"
rcvar="opensm_enable"

command=/usr/bin/opensm
command_args="-B"

opensm_start()
{
	for guid in `ibstat | grep "Port GUID" | cut -d ':' -f2`; do
		[ -z "${rc_quiet}" ] && echo "Starting ${guid} opensm."
		${command} ${command_args} -g ${guid} >> /dev/null
	done
}

load_rc_config $name
run_rc_command $*
