#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/othermta 136224 2004-10-07 13:55:26Z mtm $
#

# PROVIDE: mail
# REQUIRE: LOGIN

# XXX - TEMPORARY SCRIPT UNTIL YOU WRITE YOUR OWN REPLACEMENT.
#
. /etc/rc.subr

load_rc_config 'XXX'

if [ -n "${mta_start_script}" ]; then
	[ "${mta_start_script}" != "/etc/rc.sendmail" ] && \
	    sh ${mta_start_script} "$1"
fi
