#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/othermta 180563 2008-07-16 19:22:48Z dougb $
#

# PROVIDE: mail
# REQUIRE: LOGIN

# XXX - TEMPORARY SCRIPT UNTIL YOU WRITE YOUR OWN REPLACEMENT.
#
. /etc/rc.subr

load_rc_config 'XXX'

if [ -n "${mta_start_script}" ]; then
	[ "${mta_start_script}" != "/etc/rc.sendmail" ] && \
	    sh ${mta_start_script} "$1"
fi
