#!/bin/sh
#
# $MidnightBSD: src/etc/rc.d/othermta,v 1.2 2006/08/28 02:47:46 laffer1 Exp $
#

# PROVIDE: mail
# REQUIRE: LOGIN

# XXX - TEMPORARY SCRIPT UNTIL YOU WRITE YOUR OWN REPLACEMENT.
#
. /etc/rc.subr

load_rc_config 'XXX'

if [ -n "${mta_start_script}" ]; then
	[ "${mta_start_script}" != "/etc/rc.sendmail" ] && \
	    sh ${mta_start_script} "$1"
fi
