#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/pfsync 253357 2013-07-15 08:48:45Z des $
#

# PROVIDE: pfsync
# REQUIRE: FILESYSTEMS netif
# KEYWORD: nojail

. /etc/rc.subr

name="pfsync"
rcvar="pfsync_enable"
start_precmd="pfsync_prestart"
start_cmd="pfsync_start"
stop_cmd="pfsync_stop"
required_modules="pf"

pfsync_prestart()
{
	case "$pfsync_syncdev" in
	'')
		warn "pfsync_syncdev is not set."
		return 1
		;;
	esac
	return 0
}

pfsync_start()
{
	local _syncpeer

	echo "Enabling pfsync."
	if [ -n "${pfsync_syncpeer}" ]; then
		_syncpeer="syncpeer ${pfsync_syncpeer}"
	fi
	load_kld pfsync
	ifconfig pfsync0 $_syncpeer syncdev $pfsync_syncdev $pfsync_ifconfig up
}

pfsync_stop()
{
	echo "Disabling pfsync."
	ifconfig pfsync0 -syncdev -syncpeer down
}

load_rc_config $name
run_rc_command "$1"
