#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/powerd,v 1.2.2.1 2005/12/16 01:42:54 dougb Exp $
# $MidnightBSD: src/etc/rc.d/powerd,v 1.2 2006/08/28 02:47:46 laffer1 Exp $

# PROVIDE: powerd
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="powerd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
