#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/pppoed,v 1.3 2004/10/07 13:55:26 mtm Exp $
# $MidnightBSD: src/etc/rc.d/pppoed,v 1.2 2006/08/28 02:47:46 laffer1 Exp $

# PROVIDE: pppoed
# REQUIRE: NETWORKING
# BEFORE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="pppoed"
rcvar="`set_rcvar`"
start_cmd="pppoed_start"
# XXX stop_cmd will not be straightforward
stop_cmd=":"

pppoed_start()
{
	local _opts
	if [ -n "${pppoed_provider}" ]; then
			pppoed_flags="${pppoed_flags} -p ${pppoed_provider}"
	fi
	echo 'Starting pppoed'
	_opts=$-; set -f
	/usr/libexec/pppoed ${pppoed_flags} ${pppoed_interface}
	set +f; set -${_opts}
}

load_rc_config $name
run_rc_command "$1"
