#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/pwcheck 175737 2008-01-28 07:58:32Z dougb $
#

# PROVIDE: pwcheck
# REQUIRE: mountcritremote syslogd
# BEFORE:  DAEMON

. /etc/rc.subr

name="pwcheck"
start_cmd="pwcheck_start"
stop_cmd=":"

pwcheck_start()
{
	#	check the password temp/lock file
	#
	if [ -f /etc/ptmp ]; then
		logger -s -p auth.err \
		    "password file may be incorrect -- /etc/ptmp exists"
	fi
}

load_rc_config $name
run_rc_command "$1"
