#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/pwcheck,v 1.4 2004/10/07 13:55:26 mtm Exp $
# $MidnightBSD: src/etc/rc.d/pwcheck,v 1.2 2006/08/28 02:47:46 laffer1 Exp $

# PROVIDE: pwcheck
# REQUIRE: mountcritremote syslogd
# BEFORE:  DAEMON

. /etc/rc.subr

name="pwcheck"
start_cmd="pwcheck_start"
stop_cmd=":"

pwcheck_start()
{
	#	check the password temp/lock file
	#
	if [ -f /etc/ptmp ]; then
		logger -s -p auth.err \
		    "password file may be incorrect -- /etc/ptmp exists"
	fi
}

load_rc_config $name
run_rc_command "$1"
