#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/quota 231653 2012-02-14 10:16:56Z dougb $
#

# Enable/Check the quotas (must be after ypbind if using NIS)

# PROVIDE: quota
# REQUIRE: mountcritremote ypset
# BEFORE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="quota"
rcvar="quota_enable"
load_rc_config $name
start_cmd="quota_start"
stop_cmd="/usr/sbin/quotaoff ${quotaoff_flags}"

quota_start()
{
	if checkyesno check_quotas; then
		echo -n 'Checking quotas:'
		quotacheck ${quotacheck_flags}
		echo ' done.'
	fi

	echo -n 'Enabling quotas:'
	quotaon ${quotaon_flags}
	echo ' done.'
}

run_rc_command "$1"
