#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/rctl 220167 2011-03-30 18:32:45Z trasz $
#

# PROVIDE: rctl
# BEFORE: LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="rctl"
start_cmd="rctl_start"
stop_cmd="rctl_stop"

rctl_start()
{
	if [ -f /etc/rctl.conf ]; then
		while read var comments
		do
			case ${var} in
			\#*|'')
				;;
			*)
				rctl -a "${var}"
				;;
			esac
		done < /etc/rctl.conf
	fi
}

rctl_stop()
{

	rctl -r :
}

load_rc_config $name
run_rc_command "$1"
