#!/bin/sh
#
# $MidnightBSD$
#

# BEFORE: ntpd
# PROVIDE: rdate
# REQUIRE: NETWORKING syslogd
# BEFORE:  LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="rdate"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
