#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/root,v 1.10.2.2 2006/01/21 17:25:00 wes Exp $
# $MidnightBSD: src/etc/rc.d/root,v 1.3 2007/09/28 22:17:23 laffer1 Exp $

# PROVIDE: root
# REQUIRE: fsck
# KEYWORD: nojail

. /etc/rc.subr

name="root"
start_cmd="root_start"
stop_cmd=":"

root_start()
{
	# root normally must be read/write, but if this is a BOOTP NFS
	# diskless boot it does not have to be.
	#
	case ${root_rw_mount} in
	[Nn][Oo] | '')
		;;
	*)
		if ! mount -uw /; then
			echo 'Mounting root filesystem rw failed, startup aborted'
			/bin/kill -QUIT $$
		fi
		;;
	esac

	umount -a >/dev/null 2>&1

	# If we booted a special kernel remove the record
	# so we will boot the default kernel next time.
	if [ -x /sbin/nextboot ]; then
		/sbin/nextboot -D
	fi
}

load_rc_config $name
run_rc_command "$1"
