#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/route6d 231653 2012-02-14 10:16:56Z dougb $
#

# PROVIDE: route6d
# REQUIRE: netif routing
# KEYWORD: nojail

. /etc/rc.subr

name="route6d"
rcvar="route6d_enable"

set_rcvar_obsolete ipv6_router_enable route6d_enable
set_rcvar_obsolete ipv6_router route6d_program
set_rcvar_obsolete ipv6_router_flags route6d_flags

load_rc_config $name
run_rc_command "$1"
