#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/route6d 230099 2012-01-14 02:18:41Z dougb $
#

# PROVIDE: route6d
# REQUIRE: netif routing
# KEYWORD: nojail

. /etc/rc.subr

name="route6d"
rcvar="route6d_enable"

set_rcvar_obsolete ipv6_router_enable route6d_enable
set_rcvar_obsolete ipv6_router route6d_program
set_rcvar_obsolete ipv6_router_flags route6d_flags

load_rc_config $name
run_rc_command "$1"
