#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/routed 175737 2008-01-28 07:58:32Z dougb $
#

# PROVIDE: routed
# REQUIRE: netif routing
# KEYWORD: nojail

. /etc/rc.subr

name="routed"

# XXX - Executable may be in a different location. The $name variable
#       is different from the variable in rc.conf(5) so the
#       subroutines in rc.subr won't catch it.
#
load_rc_config $name
rcvar="router_enable"
command="${router:-/sbin/${name}}"
eval ${name}_flags=\"${router_flags}\"
run_rc_command "$1"
