#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/routed,v 1.12 2004/10/07 13:55:26 mtm Exp $
# $MidnightBSD: src/etc/rc.d/routed,v 1.2 2006/08/28 02:47:46 laffer1 Exp $

# PROVIDE: routed
# REQUIRE: netif routing
# KEYWORD: nojail

. /etc/rc.subr

name="routed"

# XXX - Executable may be in a different location. The $name variable
#       is different from the variable in rc.conf(5) so the
#       subroutines in rc.subr won't catch it.
#
load_rc_config $name
rcvar="router_enable"
command="${router:-/sbin/${name}}"
eval ${name}_flags=\"${router_flags}\"
run_rc_command "$1"
