#!/bin/sh
#
# $FreeBSD: stable/11/etc/rc.d/route6d 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: route6d
# REQUIRE: netif routing
# KEYWORD: nojail

. /etc/rc.subr

name="route6d"
desc="RIP6 routing daemon"
rcvar="route6d_enable"

set_rcvar_obsolete ipv6_router_enable route6d_enable
set_rcvar_obsolete ipv6_router route6d_program
set_rcvar_obsolete ipv6_router_flags route6d_flags

load_rc_config $name
run_rc_command "$1"
