#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/routed 230099 2012-01-14 02:18:41Z dougb $
#

# PROVIDE: routed
# REQUIRE: netif routing
# KEYWORD: nojail

. /etc/rc.subr

name="routed"
rcvar="routed_enable"
desc="network RIP and router discovery routing daemon"

set_rcvar_obsolete router_enable routed_enable
set_rcvar_obsolete router routed_program
set_rcvar_obsolete router_flags	routed_flags

load_rc_config $name
run_rc_command "$1"
