#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/rpcbind 258121 2013-11-14 09:14:33Z glebius $
#

# PROVIDE: rpcbind
# REQUIRE: NETWORKING ntpdate syslogd
# KEYWORD: shutdown

. /etc/rc.subr

name="rpcbind"
rcvar="rpcbind_enable"
command="/usr/sbin/${name}"

stop_postcmd='/bin/rm -f /var/run/rpcbind.*'

load_rc_config $name
run_rc_command "$1"
