#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/rpcbind 175737 2008-01-28 07:58:32Z dougb $
#

# PROVIDE: rpcbind
# REQUIRE: NETWORKING ntpdate syslogd named

. /etc/rc.subr

name="rpcbind"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
