#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/rpcbind,v 1.12 2004/10/07 13:55:26 mtm Exp $
# $MidnightBSD: src/etc/rc.d/rpcbind,v 1.3 2006/12/27 17:18:07 laffer1 Exp $

# PROVIDE: rpcbind
# REQUIRE: NETWORKING rdate syslogd named
# KEYWORD: shutdown

. /etc/rc.subr

name="rpcbind"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
