#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/rtsold 230099 2012-01-14 02:18:41Z dougb $
#

# PROVIDE: rtsold
# REQUIRE: netif
# BEFORE: NETWORKING
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="rtsold"
rcvar="rtsold_enable"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
start_postcmd="rtsold_poststart"

rtsold_poststart()
{
	# wait for DAD
	sleep $(($(${SYSCTL_N} net.inet6.ip6.dad_count) + 1))
}

load_rc_config $name
run_rc_command "$1"
