#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/rtsold 231653 2012-02-14 10:16:56Z dougb $
#

# PROVIDE: rtsold
# REQUIRE: netif
# BEFORE: NETWORKING
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="rtsold"
rcvar="rtsold_enable"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
start_postcmd="rtsold_poststart"

rtsold_poststart()
{
	# wait for DAD
	sleep $(($(${SYSCTL_N} net.inet6.ip6.dad_count) + 1))
}

load_rc_config $name
run_rc_command "$1"
