#!/bin/sh
#
# $FreeBSD: stable/11/etc/rc.d/rwho 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: rwho
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="rwhod"
desc="System status server"
rcvar="rwhod_enable"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
