#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/rwho,v 1.4 2004/10/07 13:55:26 mtm Exp $
# $MidnightBSD: src/etc/rc.d/rwho,v 1.2 2006/08/28 02:28:59 laffer1 Exp $

# PROVIDE: rwho
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="rwhod"
rcvar="`set_rcvar`"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
