#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/sdpd 165683 2006-12-31 10:37:18Z yar $
#

# PROVIDE: sdpd
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="sdpd"
command="/usr/sbin/${name}"
rcvar=`set_rcvar`
required_modules="ng_btsocket"

load_rc_config $name
control="${sdpd_control:-/var/run/sdp}"
group="${sdpd_groupname:-nobody}"
user="${sdpd_username:-nobody}"
command_args="-c ${control} -g ${group} -u ${user}"

run_rc_command "$1"
