#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/securelevel,v 1.10 2004/10/07 13:55:26 mtm Exp $
# $MidnightBSD: src/etc/rc.d/securelevel,v 1.2 2006/08/28 02:28:59 laffer1 Exp $

# PROVIDE: securelevel

. /etc/rc.subr

name="securelevel"
rcvar='kern_securelevel_enable'
start_cmd="securelevel_start"
stop_cmd=":"

# Last chance to set sysctl variables that failed the first time.
#
/etc/rc.d/sysctl lastload

securelevel_start()
{
	if [ ${kern_securelevel} -ge 0 ]; then
		echo 'Raising kernel security level: '
		${SYSCTL_W} kern.securelevel=${kern_securelevel}
	fi
}

load_rc_config $name
run_rc_command "$1"
