#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/sensorsd,v 1.1 2007/10/14 10:45:29 netchild Exp $
#

# PROVIDE: sensorsd
# REQUIRE: syslogd
#

. /etc/rc.subr

name="sensorsd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
