#!/bin/sh
#
# $MidnightBSD: src/etc/rc.d/SERVERS,v 1.4 2009/01/17 17:42:14 laffer1 Exp $

# PROVIDE: SERVERS
# REQUIRE: mountcritremote abi ldconfig savecore watchdogd

#	This is a dummy dependency, for early-start servers relying on
#	some basic configuration.
