#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/SERVERS,v 1.5 2004/10/07 13:55:25 mtm Exp $
# $MidnightBSD: src/etc/rc.d/SERVERS,v 1.3 2006/12/30 00:03:30 laffer1 Exp $

# PROVIDE: SERVERS
# REQUIRE: mountcritremote abi ldconfig

#	This is a dummy dependency, for early-start servers relying on
#	some basic configuration.
