#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/SERVERS 175737 2008-01-28 07:58:32Z dougb $
#

# PROVIDE: SERVERS
# REQUIRE: mountcritremote abi ldconfig

#	This is a dummy dependency, for early-start servers relying on
#	some basic configuration.
