#!/bin/sh
#
# Copyright 2002-2005 G.U.F.I. All rights reserved.
# Copyright 2006 Timothy Redaelli
#
# Copyright 2007 Lucas Holt
# Copyright (c) 2005-2007 FreeSBIE Project
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $MidnightBSD: src/etc/rc.d/sound,v 1.1 2007/06/30 01:04:41 laffer1 Exp $
# $Id: sound,v 1.2 2007-07-25 14:25:36 laffer1 Exp $
#
# Detect the audio card and load the appropriate driver
#
# PROVIDE: sound
# KEYWORD: nojail
 	
. /etc/rc.subr

name="sound_detect"
start_cmd="do_sound_detect"
stop_cmd=":"

do_sound_detect()
{
	CARD_FILE=/usr/share/sound/snd_card_ids.txt
	if [ -f $CARD_FILE ]; then
		pciconf -lv | awk -F '[ =]' '/^none/{print $6}' | while read i
		do
			SND_DRIVER=`fgrep $i $CARD_FILE | cut -d: -f 1`
			if [ "$SND_DRIVER" ]; then
         			echo -n "Loading $SND_DRIVER.ko... "
         			/sbin/kldload /boot/kernel/$SND_DRIVER.ko
      			fi
		done
	fi	
}

load_rc_config $name
run_rc_command "$1"
