#!/bin/sh
#
# $FreeBSD: release/7.0.0/etc/rc.d/sppp 136224 2004-10-07 13:55:26Z mtm $
#

# PROVIDE: sppp
# REQUIRE: root
# BEFORE: netif
# KEYWORD: nojail

. /etc/rc.subr

name="sppp"
start_cmd="sppp_start"
stop_cmd=":"

sppp_start()
{
	# Special options for sppp(4) interfaces go here.  These need
	# to go _before_ the general ifconfig since in the case
	# of hardwired (no link1 flag) but required authentication, you
	# cannot pass auth parameters down to the already running interface.
	#
	for ifn in ${sppp_interfaces}; do
		eval spppcontrol_args=\$spppconfig_${ifn}
		if [ -n "${spppcontrol_args}" ]; then
			# The auth secrets might contain spaces; in order
			# to retain the quotation, we need to eval them
			# here.
			eval spppcontrol ${ifn} ${spppcontrol_args}
		fi
	done
}

load_rc_config $name
run_rc_command "$1"
