#!/bin/sh
#
# $FreeBSD: stable/11/etc/rc.d/swaplate 308865 2016-11-19 20:02:49Z jilles $
#

# PROVIDE: swaplate
# REQUIRE: mountlate
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="swaplate"
desc="Setup late swap space"
start_cmd='/sbin/swapon -aLq'
stop_cmd='/sbin/swapoff -aLq'

load_rc_config swap
run_rc_command "$1"
