#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/swap1 189694 2009-03-11 12:55:12Z guido $
#

# PROVIDE: localswap
# REQUIRE: disks
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="swap1"
start_cmd='swapon -aq'
stop_cmd=':'

load_rc_config swap
run_rc_command "$1"
