#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/swap1,v 1.9 2004/11/05 12:38:27 pjd Exp $
# $MidnightBSD: src/etc/rc.d/swap1,v 1.2 2006/08/28 02:28:59 laffer1 Exp $

# PROVIDE: localswap
# REQUIRE: disks
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="swap1"
start_cmd='swapon -a'
stop_cmd=':'

load_rc_config swap
run_rc_command "$1"
