#!/bin/sh
#
# $MidnightBSD: src/etc/rc.d/swap1,v 1.3 2007/09/28 22:17:23 laffer1 Exp $

# PROVIDE: localswap
# REQUIRE: disks
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="swap1"
start_cmd='swapon -aq'
stop_cmd=':'

load_rc_config swap
run_rc_command "$1"
