#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/sysctl,v 1.16 2004/10/07 13:55:26 mtm Exp $
# $MidnightBSD: src/etc/rc.d/sysctl,v 1.2 2006/08/28 02:28:59 laffer1 Exp $

# PROVIDE: sysctl
# REQUIRE: root
# BEFORE:  DAEMON

. /etc/rc.subr

name="sysctl"
stop_cmd=":"
start_cmd="sysctl_start"
reload_cmd="sysctl_start"
lastload_cmd="sysctl_start last"
extra_commands="reload lastload"

sysctl_start()
{
	#
	# Read in /etc/sysctl.conf and set things accordingly
	#
	if [ -f /etc/sysctl.conf ]; then
		while read var comments
		do
			case ${var} in
			\#*|'')
				;;
			*)
				mib=${var%=*}
				val=${var#*=}

				if current_value=`${SYSCTL} -n ${mib} 2>/dev/null`; then
					case ${current_value} in
					${val})
						;;
					*)
						sysctl ${var}
						;;
					esac
				elif [ "$1" = "last" ]; then
					warn "sysctl ${mib} does not exist."
				fi
				;;
			esac
		done < /etc/sysctl.conf
	fi
}

load_rc_config $name
run_rc_command "$1"
