#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/timed 231653 2012-02-14 10:16:56Z dougb $
#

# PROVIDE: timed
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="timed"
rcvar="timed_enable"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
