#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/timed,v 1.5 2004/10/07 13:55:26 mtm Exp $
# $MidnightBSD$

# PROVIDE: timed
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="timed"
rcvar="timed_enable"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
