#!/bin/sh
#
# $FreeBSD: stable/11/etc/rc.d/utx 298514 2016-04-23 16:10:54Z lme $
#

# PROVIDE: utx
# REQUIRE: DAEMON FILESYSTEMS
# BEFORE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="utx"
desc="Manage the user accounting database"
start_cmd="utx boot"
stop_cmd="utx shutdown"

load_rc_config $name
run_rc_command "$1"
