#!/bin/sh
# 
# $MidnightBSD: src/etc/rc.d/wpa_supplicant,v 1.2 2006/08/28 02:28:59 laffer1 Exp $
# $FreeBSD: src/etc/rc.d/wpa_supplicant,v 1.1.2.1 2005/10/27 17:06:45 wpaul Exp $
#

# PROVIDE: wpa_supplicant
# REQUIRE: mountcritremote
# KEYWORD: nojail nostart

. /etc/rc.subr
. /etc/network.subr

name="wpa_supplicant"
rcvar=
command="/usr/sbin/${name}"
conf_file="/etc/wpa_supplicant.conf"

ifn="$2"
if [ -z "$ifn" ]; then
	return 1
fi

case ${ifn} in
ndis*)
	driver="ndis"
	;;
*)
	driver="bsd"
	;;
esac

load_rc_config $name

pidfile="/var/run/${name}/${ifn}.pid"
command_args="-B -q -i $ifn -c $conf_file -D $driver -P $pidfile"
required_files=$conf_file

run_rc_command "$1"
