#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/yppasswdd,v 1.10 2004/10/07 13:55:26 mtm Exp $
# $MidnightBSD: src/etc/rc.d/yppasswdd,v 1.2 2006/08/28 02:28:59 laffer1 Exp $

# PROVIDE: yppasswdd
# REQUIRE: ypserv ypbind
# BEFORE:  LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="yppasswdd"
command="/usr/sbin/rpc.${name}"
start_precmd="yppasswdd_precmd"

load_rc_config $name
rcvar="nis_yppasswdd_enable"
command_args="${nis_yppasswdd_flags}"

yppasswdd_precmd()
{
	if ! checkyesno rpcbind_enable  && \
	    ! /etc/rc.d/rpcbind forcestatus 1>/dev/null 2>&1
	then
		force_depend rpcbind || return 1
	fi
	if ! checkyesno nis_server_enable && \
	    ! /etc/rc.d/ypserv forcestatus 1>/dev/null 2>&1
	then
		force_depend ypserv || return 1
	fi
	_domain=`domainname`
	if [ -z "$_domain" ]; then
		warn "NIS domainname(1) is not set."
		return 1
	fi
}

run_rc_command "$1"
