#!/bin/sh
#
# $FreeBSD: release/10.0.0/etc/rc.d/ypupdated 231667 2012-02-14 10:51:24Z dougb $
#

# PROVIDE: ypupdated
# REQUIRE: rpcbind ypserv
# KEYWORD: shutdown

. /etc/rc.subr

name="ypupdated"
rcvar="rpc_ypupdated_enable"

load_rc_config $name

command="/usr/sbin/rpc.${name}"
start_precmd="rpc_ypupdated_precmd"

rpc_ypupdated_precmd()
{
	local _domain

	force_depend rpcbind || return 1
	force_depend ypserv nis_server || return 1

	_domain=`domainname`
	if [ -z "$_domain" ]; then
		warn "NIS domainname(1) is not set."
		return 1
	fi
}

run_rc_command "$1"
