# $FreeBSD: release/7.0.0/sys/modules/digi/Makefile 76195 2001-05-02 01:08:09Z brian $

SUBDIR=	digi
SUBDIR+=digi_CX
SUBDIR+=digi_CX_PCI
SUBDIR+=digi_EPCX
SUBDIR+=digi_EPCX_PCI
SUBDIR+=digi_Xe
SUBDIR+=digi_Xem
SUBDIR+=digi_Xr

.include <bsd.subdir.mk>
