# $FreeBSD: release/10.0.0/sys/modules/digi/Makefile 245952 2013-01-26 22:08:21Z pfg $

SUBDIR=	digi
SUBDIR+=digi_CX
SUBDIR+=digi_CX_PCI
SUBDIR+=digi_EPCX
SUBDIR+=digi_EPCX_PCI
SUBDIR+=digi_Xe
SUBDIR+=digi_Xem
SUBDIR+=digi_Xr

.include <bsd.subdir.mk>
