# $FreeBSD: stable/9/sys/modules/digi/Makefile 246069 2013-01-29 13:49:08Z pfg $

SUBDIR=	digi
SUBDIR+=digi_CX
SUBDIR+=digi_CX_PCI
SUBDIR+=digi_EPCX
SUBDIR+=digi_EPCX_PCI
SUBDIR+=digi_Xe
SUBDIR+=digi_Xem
SUBDIR+=digi_Xr

.include <bsd.subdir.mk>
