#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/11/usr.bin/vis/Makefile 319186 2017-05-30 04:27:05Z ngie $

PROG=	vis
SRCS=	vis.c foldit.c

.PATH: ${SRCTOP}/contrib/vis
CFLAGS+=	-I${SRCTOP}/contrib/vis

.include <bsd.prog.mk>
