# Note that this files is under a "BSD" copyright (c) by David O'Brien 1997, 
# even though it may live in src/gnu/...

# $FreeBSD: release/7.0.0/gnu/usr.bin/cpio/doc/Makefile 150770 2005-10-01 04:57:01Z tjr $

.PATH:	${.CURDIR}/../../../../contrib/cpio/doc

INFO = cpio

INFOSECTION= "Cpio Documentation"
INFOENTRY_cpio="* CPIO: (cpio).                 Making tape (or disk) archives."

SRCDIR= ${.CURDIR}/../../../../contrib/cpio/doc

.include <bsd.info.mk>
