# $FreeBSD: stable/11/sys/modules/lge/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/lge

KMOD=	if_lge
SRCS=	if_lge.c miibus_if.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
