# $FreeBSD: release/10.0.0/sys/modules/lge/Makefile 150636 2005-09-27 18:10:43Z mlaier $

.PATH: ${.CURDIR}/../../dev/lge

KMOD=	if_lge
SRCS=	if_lge.c miibus_if.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
