#$FreeBSD: stable/11/sys/modules/i2c/controllers/ismt/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:		${SRCTOP}/sys/dev/ismt
KMOD		= ismt
SRCS		= device_if.h bus_if.h iicbb_if.h pci_if.h smbus_if.h \
		  ismt.c

.include <bsd.kmod.mk>
