# $FreeBSD: release/10.0.0/sys/modules/digi/digi_Xe/Makefile 76195 2001-05-02 01:08:09Z brian $

.PATH:	${.CURDIR}/../../../dev/digi
KMOD=	digi_Xe
SRCS=	Xe.c Xe.bios.h Xe.fepos.h digi_mod.h

.include <bsd.kmod.mk>
