#
# $FreeBSD: release/7.0.0/usr.sbin/pmccontrol/Makefile 145280 2005-04-19 14:43:59Z jkoshy $
#

PROG=	pmccontrol
MAN=	pmccontrol.8

DPADD=	${LIBPMC}
LDADD=	-lpmc

WARNS?=	6

SRCS=	pmccontrol.c

.include <bsd.prog.mk>
