# $FreeBSD: stable/11/usr.bin/clang/llvm-cxxdump/Makefile 331838 2018-03-31 11:38:16Z dim $

PROG_CXX=	llvm-cxxdump
MAN=

SRCDIR=		tools/llvm-cxxdump
SRCS+=		Error.cpp
SRCS+=		llvm-cxxdump.cpp

.include "../llvm.prog.mk"
