# $FreeBSD: release/10.0.0/sys/modules/ksyms/Makefile 192859 2009-05-26 21:39:09Z sson $

.PATH: ${.CURDIR}/../../dev/ksyms

KMOD=  ksyms   
SRCS=  ksyms.c linker_if.h

MFILES= kern/linker_if.m

.include <bsd.kmod.mk>
