.\"-
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.\" Copyright (c) 2026 Lucas Holt
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd July 10, 2026
.Dt TAC 1
.Os
.Sh NAME
.Nm tac
.Nd concatenate and print files in reverse line order
.Sh SYNOPSIS
.Nm
.Op Fl br
.Op Fl s Ar separator
.Op Ar file ...
.Sh DESCRIPTION
The
.Nm
utility reads each
.Ar file
operand and writes its records to the standard output in reverse order.
If no
.Ar file
operands are specified, or if a
.Ar file
operand is a single dash
.Pq Sq Fl ,
.Nm
reads from the standard input.
.Pp
Records are separated by newline characters by default.
The options are as follows:
.Bl -tag -width indent
.It Fl b , Fl -before
Attach the separator to the beginning of the record that it precedes
instead of to the end of the record that it follows.
.It Fl r , Fl -regex
Treat the separator as a basic regular expression.
.It Fl s Ar separator , Fl -separator Ns = Ns Ar separator
Use
.Ar separator
as the record separator instead of newline.
An empty separator is treated as a NUL byte.
.El
.Pp
When multiple files are specified, each file is reversed independently
and files are processed in command-line order.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr cat 1 ,
.Xr tail 1
.Sh HISTORY
The
.Nm
utility was written for
.Mx .
