# $FreeBSD: release/10.0.0/sys/modules/syscons/logo/Makefile 89260 2002-01-11 15:49:02Z ru $

.PATH:	${.CURDIR}/../../../dev/syscons/logo

KMOD=	logo_saver
SRCS=	logo_saver.c logo.c

.include <bsd.kmod.mk>
