# $FreeBSD: release/9.2.0/lib/clang/libllvmobject/Makefile 252723 2013-07-04 20:17:04Z dim $

.include <bsd.own.mk>

LIB=	llvmobject

SRCDIR=	lib/Object
SRCS=	Archive.cpp \
	Binary.cpp \
	COFFObjectFile.cpp \
	ELFObjectFile.cpp \
	Error.cpp \
	MachOObjectFile.cpp \
	Object.cpp \
	ObjectFile.cpp

.include "../clang.lib.mk"
