# $FreeBSD: stable/9/lib/clang/libllvmobject/Makefile 246637 2013-02-10 21:24:47Z dim $

.include <bsd.own.mk>

LIB=	llvmobject

SRCDIR=	lib/Object
SRCS=	Archive.cpp \
	Binary.cpp \
	COFFObjectFile.cpp \
	ELFObjectFile.cpp \
	Error.cpp \
	MachOObject.cpp \
	MachOObjectFile.cpp \
	Object.cpp \
	ObjectFile.cpp

.include "../clang.lib.mk"
