# $FreeBSD: stable/11/usr.bin/clang/llvm-cxxfilt/Makefile 331838 2018-03-31 11:38:16Z dim $

PROG_CXX=	llvm-cxxfilt
MAN=

SRCDIR=		tools/llvm-cxxfilt
SRCS+=		llvm-cxxfilt.cpp

.include "../llvm.prog.mk"
