# $FreeBSD: stable/9/lib/clang/libllvmarchive/Makefile 246637 2013-02-10 21:24:47Z dim $

.include <bsd.own.mk>

LIB=	llvmarchive

SRCDIR=	lib/Archive
SRCS=	Archive.cpp \
	ArchiveReader.cpp \
	ArchiveWriter.cpp

.include "../clang.lib.mk"
