# $FreeBSD: release/10.0.0/lib/clang/libllvmarchive/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvmarchive

SRCDIR=	lib/Archive
SRCS=	Archive.cpp \
	ArchiveReader.cpp \
	ArchiveWriter.cpp

.include "../clang.lib.mk"
