# $FreeBSD: stable/11/sys/modules/geom/geom_sunlabel/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/geom

KMOD=	geom_sunlabel
SRCS=	geom_sunlabel.c geom_sunlabel_enc.c

.include <bsd.kmod.mk>
