# $FreeBSD: release/10.0.0/sys/modules/netgraph/rfc1490/Makefile 89260 2002-01-11 15:49:02Z ru $
# $Whistle: Makefile,v 1.2 1999/01/19 19:39:22 archie Exp $

KMOD=	ng_rfc1490
SRCS= 	ng_rfc1490.c

.include <bsd.kmod.mk>
