# $Id: Makefile,v 1.1.1.1 2006-02-25 02:29:35 laffer1 Exp $
# $FreeBSD: src/usr.sbin/bluetooth/bcmfw/Makefile,v 1.4 2005/01/28 16:08:09 ru Exp $

PROG=		bcmfw
MAN=		bcmfw.8
WARNS?=		2

.include <bsd.prog.mk>
