#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/10.0.0/usr.sbin/repquota/Makefile 207736 2010-05-07 00:41:12Z mckusick $

PROG=	repquota
MAN=	repquota.8
DPADD=  ${LIBUTIL}
LDADD=  -lutil

.include <bsd.prog.mk>
