# $MidnightBSD$
# $FreeBSD: stable/10/usr.bin/timeout/Makefile 287392 2015-09-02 05:45:47Z bapt $

.include <bsd.own.mk>

PROG=	timeout

.if ${MK_TESTS} != "no"
SUBDIR+= tests
.endif

.include <bsd.prog.mk>
