#	from @(#)Makefile.inc	8.1 (Berkeley) 6/4/93
# $FreeBSD: release/10.0.0/lib/libc/db/mpool/Makefile.inc 190498 2009-03-28 07:31:02Z delphij $

.PATH: ${.CURDIR}/db/mpool

SRCS+=	mpool.c mpool-compat.c
