# $FreeBSD: stable/11/share/examples/hwpmc/Makefile 299293 2016-05-10 00:51:50Z gjb $

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/hwpmc
PROG=	overhead
LDFLAGS+= -lpmc
MAN=

install:

.include <bsd.prog.mk>
