# $FreeBSD: stable/11/libexec/rtld-elf/tests/libpythagoras/Makefile 316388 2017-04-02 02:16:01Z asomers $

.include <bsd.own.mk>

LIB=		pythagoras
SHLIB_MAJOR=	0

LIBDIR=		${TESTSBASE}/libexec/rtld-elf
SHLIBDIR=	${TESTSBASE}/libexec/rtld-elf

SRCS=		pythagoras.c

WARNS?=		6
LIBADD=		m

.include <bsd.lib.mk>
