#	@(#)Makefile	5.4 (Berkeley) 5/11/90
#
# $FreeBSD: release/7.0.0/sbin/slattach/Makefile 126178 2004-02-23 20:25:27Z johan $

PROG=	slattach
WARNS?=	0
MAN=	slattach.8
MLINKS=	slattach.8 slip.8
LDADD=	-lutil
DPADD=	${LIBUTIL}

.include <bsd.prog.mk>
