# $FreeBSD: release/7.0.0/sys/modules/if_vlan/Makefile 167709 2007-03-19 17:34:31Z yar $

.PATH: ${.CURDIR}/../../net

KMOD=	if_vlan
SRCS=	if_vlan.c
SRCS+=	opt_inet.h opt_vlan.h

.include <bsd.kmod.mk>
