# $FreeBSD: release/10.0.0/sys/modules/if_vlan/Makefile 193744 2009-06-08 19:57:35Z bz $

.PATH: ${.CURDIR}/../../net

KMOD=	if_vlan
SRCS=	if_vlan.c
SRCS+=	opt_inet.h opt_vlan.h

.include <bsd.kmod.mk>
