# $MidnightBSD$
# $FreeBSD: stable/10/tests/etc/Makefile 313488 2017-02-09 22:49:48Z ngie $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/etc

.PATH:		${SRCTOP}/tests
KYUAFILE=	yes

SUBDIR+=	rc.d

.include <bsd.test.mk>
