# $FreeBSD: stable/11/tests/etc/Makefile 299094 2016-05-04 23:20:53Z ngie $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/etc

.PATH:		${SRCTOP}/tests
KYUAFILE=	yes

SUBDIR+=	rc.d

.include <bsd.test.mk>
