# $FreeBSD: release/10.0.0/sys/modules/i2c/controllers/amdpm/Makefile 93023 2002-03-23 15:49:15Z nsouch $

.PATH:		${.CURDIR}/../../../../pci
KMOD		= amdpm
SRCS		= device_if.h bus_if.h pci_if.h smbus_if.h \
		  amdpm.c

.include <bsd.kmod.mk>
