# $FreeBSD: stable/11/sys/compat/cloudabi64/Makefile 357108 2020-01-25 05:47:56Z kevans $

SYSENT_FILE=	${SYSDIR}/contrib/cloudabi/syscalls64.master
GENERATED_PREFIX=	cloudabi64_

.include "../../conf/sysent.mk"
