# $FreeBSD: release/7.0.0/sys/modules/sbsh/Makefile 113429 2003-04-13 06:27:13Z fjoe $

.PATH: ${.CURDIR}/../../dev/sbsh

KMOD=	if_sbsh
SRCS=	if_sbsh.c bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
