#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/11/usr.bin/dirname/Makefile 272781 2014-10-09 00:55:04Z ngie $

.include <src.opts.mk>

PROG=	dirname
MAN=

.if ${MK_TESTS} != "no"
SUBDIR+=	tests
.endif

.include <bsd.prog.mk>
