# $FreeBSD: release/10.0.0/sys/modules/fdescfs/Makefile 89260 2002-01-11 15:49:02Z ru $

.PATH: ${.CURDIR}/../../fs/fdescfs

KMOD=	fdescfs
SRCS=	vnode_if.h \
	fdesc_vfsops.c fdesc_vnops.c

.include <bsd.kmod.mk>
