# $FreeBSD: stable/11/sys/modules/fdescfs/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/fs/fdescfs

KMOD=	fdescfs
SRCS=	vnode_if.h \
	fdesc_vfsops.c fdesc_vnops.c

.include <bsd.kmod.mk>
