# $FreeBSD: stable/9/lib/clang/libllvminterpreter/Makefile 246637 2013-02-10 21:24:47Z dim $

.include <bsd.own.mk>

LIB=	llvminterpreter

SRCDIR=	lib/ExecutionEngine/Interpreter
SRCS=	Execution.cpp \
	ExternalFunctions.cpp \
	Interpreter.cpp \

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
