# $FreeBSD: stable/9/lib/clang/libllvmvectorize/Makefile 246637 2013-02-10 21:24:47Z dim $

.include <bsd.own.mk>

LIB=	llvmvectorize

SRCDIR=	lib/Transforms/Vectorize
SRCS=	BBVectorize.cpp \
	LoopVectorize.cpp \
	Vectorize.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
