# $FreeBSD: release/10.0.0/sys/modules/netgraph/netgraph/Makefile 89260 2002-01-11 15:49:02Z ru $
# $Whistle: Makefile,v 1.2 1999/01/19 19:39:22 archie Exp $

KMOD=	netgraph
SRCS= 	ng_base.c ng_parse.c

.include <bsd.kmod.mk>
