# $FreeBSD: stable/11/usr.bin/clang/llvm-modextract/Makefile 331838 2018-03-31 11:38:16Z dim $

PROG_CXX=	llvm-modextract
MAN=

SRCDIR=		tools/llvm-modextract
SRCS=		llvm-modextract.cpp

.include "../llvm.prog.mk"
