#	@(#)Makefile.inc	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/7.0.0/usr.bin/Makefile.inc 90313 2002-02-06 18:13:12Z markm $

BINDIR?=	/usr/bin

# Commented out for the time being.
# I intend to make this default at some stage.
#WARNS?=		2
