#	@(#)Makefile	1.1 (Berkeley) 6/6/93
# $FreeBSD: release/10.0.0/usr.bin/ktrace/Makefile 226504 2011-10-18 08:26:12Z des $

PROG=	ktrace
SRCS=	ktrace.c subr.c
MLINKS= ktrace.1 trace.1 

.include <bsd.prog.mk>
