#	@(#)Makefile	1.1 (Berkeley) 6/6/93
# $FreeBSD: stable/9/usr.bin/ktrace/Makefile 231263 2012-02-09 09:24:33Z bapt $

PROG=	ktrace
SRCS=	ktrace.c subr.c
MLINKS= ktrace.1 trace.1 

.include <bsd.prog.mk>
