#	@(#)Makefile	1.1 (Berkeley) 6/6/93
# $FreeBSD: release/7.0.0/usr.bin/ktrace/Makefile 50477 1999-08-28 01:08:13Z peter $

PROG=	ktrace
SRCS=	ktrace.c subr.c
MLINKS= ktrace.1 trace.1 

.include <bsd.prog.mk>
