# $FreeBSD: stable/11/usr.bin/uuencode/tests/Makefile 299094 2016-05-04 23:20:53Z ngie $

PACKAGE=	tests

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		regress.base64.out
${PACKAGE}FILES+=		regress.in
${PACKAGE}FILES+=		regress.sh
${PACKAGE}FILES+=		regress.traditional.out

.include <bsd.test.mk>
