# $FreeBSD: stable/11/sys/modules/syscons/dragon/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:	${SRCTOP}/sys/dev/syscons/dragon

KMOD=	dragon_saver
SRCS= 	dragon_saver.c

.include <bsd.kmod.mk>
