# $FreeBSD: release/10.0.0/sys/modules/syscons/dragon/Makefile 106762 2002-11-11 10:11:59Z mux $

.PATH:	${.CURDIR}/../../../dev/syscons/dragon

KMOD=	dragon_saver
SRCS= 	dragon_saver.c

.include <bsd.kmod.mk>
