# $FreeBSD: release/10.0.0/sys/modules/digi/digi_Xr/Makefile 76195 2001-05-02 01:08:09Z brian $

.PATH:	${.CURDIR}/../../../dev/digi
KMOD=	digi_Xr
SRCS=	Xr.c Xr.bios.h Xr.fepos.h digi_mod.h

.include <bsd.kmod.mk>
