# $FreeBSD: stable/11/usr.bin/clang/llvm-symbolizer/Makefile 310618 2016-12-26 20:36:37Z dim $

PROG_CXX=	llvm-symbolizer

SRCDIR=		tools/llvm-symbolizer
SRCS+=		llvm-symbolizer.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
