# $MidnightBSD$
# $FreeBSD: stable/10/sys/modules/toecore/Makefile 237560 2012-06-25 09:46:06Z uqs $

.PATH: ${.CURDIR}/../../netinet

KMOD=	toecore
SRCS=	toecore.c
SRCS+=	opt_ofed.h opt_inet.h opt_inet6.h

.include <bsd.kmod.mk>
