# $MidnightBSD$
# $FreeBSD: release/9.2.0/sys/modules/toecore/Makefile 237263 2012-06-19 07:34:13Z np $

.PATH: ${.CURDIR}/../../netinet

KMOD=	toecore
SRCS=	toecore.c
SRCS+=	opt_ofed.h

.include <bsd.kmod.mk>
# $FreeBSD$

.PATH: ${.CURDIR}/../../netinet

KMOD=	toecore
SRCS=	toecore.c
SRCS+=	opt_ofed.h

.include <bsd.kmod.mk>
# $MidnightBSD$
# $FreeBSD: release/9.2.0/sys/modules/toecore/Makefile 237263 2012-06-19 07:34:13Z np $

.PATH: ${.CURDIR}/../../netinet

KMOD=	toecore
SRCS=	toecore.c
SRCS+=	opt_ofed.h

.include <bsd.kmod.mk>
