# $FreeBSD: stable/11/sys/modules/toecore/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/netinet

KMOD=	toecore
SRCS=	toecore.c
SRCS+=	opt_ofed.h opt_inet.h opt_inet6.h

.include <bsd.kmod.mk>
