#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/10.0.0/usr.sbin/vipw/Makefile 201390 2010-01-02 11:07:44Z ed $

PROG=	vipw
MAN=	vipw.8

DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
