#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/7.0.0/usr.sbin/vipw/Makefile 113091 2003-04-04 17:49:21Z obrien $

PROG=	vipw
MAN=	vipw.8

WARNS?=	4

DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
