#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.sbin/vipw/Makefile,v 1.8 2003/04/04 17:49:20 obrien Exp $
# $MidnightBSD$

PROG=	vipw
MAN=	vipw.8

DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
