#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: release/10.0.0/share/dict/Makefile 139103 2004-12-21 08:47:35Z ru $

NO_OBJ=

# XXX MISSING:	connectives words
FILES=		README propernames web2 web2a freebsd
FILESDIR=	${BINDIR}/dict
SYMLINKS=	web2 ${FILESDIR}/words

.include <bsd.prog.mk>
