# $FreeBSD: stable/11/gnu/usr.bin/groff/src/devices/grohtml/Makefile 291738 2015-12-04 03:17:47Z bdrewery $

PROG_CXX=	post-grohtml
SRCS=		post-html.cpp html-table.cpp html-text.cpp output.cpp
DPADD=		${LIBDRIVER} ${LIBGROFF}
LDADD=		${LIBDRIVER} ${LIBGROFF}
LIBADD=		m
MAN=

.include <bsd.prog.mk>
