#	@(#)Makefile	8.1 (Berkeley) 6/9/93
# $FreeBSD: stable/11/usr.sbin/pmcstudy/Makefile 352023 2019-09-07 20:01:26Z imp $

PROG=	pmcstudy
MAN=	pmcstudy.8
SRCS= pmcstudy.c eval_expr.c
CFLAGS+= -Wall ${WERROR}

BINDIR= /usr/bin

.include <bsd.prog.mk>

