# $FreeBSD: stable/11/lib/libclang_rt/ubsan_minimal/Makefile 327119 2017-12-23 21:41:32Z dim $

.include <bsd.init.mk>

LIB=		clang_rt.ubsan_minimal-${CRTARCH}

SRCS+=		ubsan_minimal/ubsan_minimal_handlers.cc

.include <bsd.lib.mk>
