# $FreeBSD: release/10.0.0/share/examples/kld/khelp/Makefile 218545 2011-02-11 07:26:17Z lstewart $

.include <bsd.own.mk>

# Change if the src tree you are compiling for is not in /usr/src
#SYSDIR=/usr/src/sys

KMOD=	h_example
SRCS=	h_example.c

.include <bsd.kmod.mk>
