# $FreeBSD: stable/11/share/examples/kld/khelp/Makefile 299293 2016-05-10 00:51:50Z gjb $

.include <bsd.own.mk>

# Change if the src tree you are compiling for is not in /usr/src
#SYSDIR=/usr/src/sys

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/kld/khelp
KMOD=	h_example
SRCS=	h_example.c

.include <bsd.kmod.mk>
