# $FreeBSD: release/10.0.0/usr.sbin/bsdinstall/Makefile 222998 2011-06-11 21:44:07Z nwhitehorn $

SUBDIR= distextract distfetch partedit scripts
SCRIPTS= bsdinstall
MAN= bsdinstall.8

.include <bsd.prog.mk>
