# $Id: Makefile,v 1.5 2003/09/08 02:28:35 max Exp $
# $FreeBSD: release/10.0.0/usr.sbin/bluetooth/Makefile 215195 2010-11-12 19:43:12Z emax $

SUBDIR= \
	ath3kfw \
	bcmfw \
	bt3cfw \
	bthidcontrol \
	bthidd \
	btpand \
	hccontrol \
	hcsecd \
	hcseriald \
	l2control \
	l2ping \
	rfcomm_pppd \
	sdpcontrol \
	sdpd

.include <bsd.subdir.mk>

