# $MidnightBSD$
# $FreeBSD: stable/10/libexec/ulog-helper/Makefile 276486 2014-12-31 23:25:37Z ngie $

PROG=	ulog-helper
BINOWN=	root
BINMODE=4555
MAN=

DPADD=	${LIBULOG}
LDADD=	-lulog

.include <bsd.prog.mk>
