#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/7.0.0/usr.bin/uudecode/Makefile 139103 2004-12-21 08:47:35Z ru $

PROG=	uudecode
WARNS?=	4
LINKS=	${BINDIR}/uudecode ${BINDIR}/b64decode
NO_MAN=

.include <bsd.prog.mk>
