# $FreeBSD: release/10.0.0/sys/modules/mac_stub/Makefile 122512 2003-11-11 21:23:54Z rwatson $

.PATH: ${.CURDIR}/../../security/mac_stub

KMOD=	mac_stub
SRCS=	vnode_if.h \
	mac_stub.c

.include <bsd.kmod.mk>
