# $FreeBSD: release/10.0.0/lib/libc_nonshared/Makefile.iconv 258750 2013-11-29 19:44:30Z gjb $

.if ${MK_ICONV} == "yes"
LIBC_NONSHARED_SRCS+=	\
	__iconv.c __iconv_free_list.c __iconv_get_list.c \
	iconv.c iconv_canonicalize.c iconv_close.c \
	iconv_open.c iconv_open_into.c \
	iconv_set_relocation_prefix.c iconvctl.c iconvlist.c
.endif
