# $MidnightBSD: src/tools/tools/tinderbox/Makefile,v 1.1.1.1.2.1 2008/03/04 03:06:59 laffer1 Exp $
# $FreeBSD: src/tools/tools/tinderbox/Makefile,v 1.9 2003/08/01 07:24:30 des Exp $

BINDIR		?= ${HOME}/bin
BINOWN		?= ${USER}
BINGRP		?= ${USER}
SCRIPTS		 = tbmaster.pl tinderbox.pl

MANDIR		?= ${HOME}/man/man
MANOWN		?= ${USER}
MANGRP		?= ${USER}
MAN		 = tbmaster.1 tinderbox.1

SUBDIR		 = etc www

.include <bsd.prog.mk>
