# $MidnightBSD: src/tools/tools/tinderbox/Makefile,v 1.2 2008/03/06 20:23:45 laffer1 Exp $

BINDIR		?= ${HOME}/bin
BINOWN		?= ${USER}
BINGRP		?= ${USER}
SCRIPTS		 = tbmaster.pl tinderbox.pl

MANDIR		?= ${HOME}/man/man
MANOWN		?= ${USER}
MANGRP		?= ${USER}
MAN		 = tbmaster.1 tinderbox.1

SUBDIR		 = etc www

.include <bsd.prog.mk>
