#	@(#)Makefile	8.1 (Berkeley) 6/4/93
# $FreeBSD: release/10.0.0/libexec/fingerd/Makefile 201380 2010-01-02 09:50:19Z ed $

PROG=	fingerd
DPADD=	${LIBUTIL}
LDADD=	-lutil
MAN=	fingerd.8

WARNS?=	2
WFORMAT=0

.include <bsd.prog.mk>
