# $FreeBSD: stable/9/share/doc/psd/28.cvs/Makefile 136910 2004-10-24 15:33:08Z ru $

VOLUME=		psd/28.cvs
SRCS=		cvs-paper.ms
MACROS=		-ms
USE_PIC=
USE_TBL=
SRCDIR=		${.CURDIR}/../../../../contrib/cvs/doc

.include <bsd.doc.mk>
