# $FreeBSD: release/10.0.0/lib/clang/libllvmasmparser/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvmasmparser

SRCDIR=	lib/AsmParser
SRCS=	LLLexer.cpp \
	LLParser.cpp \
	Parser.cpp

.include "../clang.lib.mk"
