# $FreeBSD: stable/11/lib/libdevinfo/Makefile 298107 2016-04-16 07:45:30Z gjb $

PACKAGE=lib${LIB}
LIB=	devinfo
SRCS=	devinfo.c
INCS=	devinfo.h
MAN=	devinfo.3

SHLIB_MAJOR=	6

WARNS?=	3

.include <bsd.lib.mk>
