# $FreeBSD: stable/11/usr.bin/clang/llvm-pdbutil/Makefile 346296 2019-04-16 20:05:24Z dim $

PROG_CXX=	llvm-pdbutil

SRCDIR=		tools/llvm-pdbutil
SRCS+=		BytesOutputStyle.cpp
SRCS+=		DumpOutputStyle.cpp
SRCS+=		ExplainOutputStyle.cpp
SRCS+=		FormatUtil.cpp
SRCS+=		InputFile.cpp
SRCS+=		LinePrinter.cpp
SRCS+=		MinimalSymbolDumper.cpp
SRCS+=		MinimalTypeDumper.cpp
SRCS+=		PdbYaml.cpp
SRCS+=		PrettyBuiltinDumper.cpp
SRCS+=		PrettyClassDefinitionDumper.cpp
SRCS+=		PrettyClassLayoutGraphicalDumper.cpp
SRCS+=		PrettyCompilandDumper.cpp
SRCS+=		PrettyEnumDumper.cpp
SRCS+=		PrettyExternalSymbolDumper.cpp
SRCS+=		PrettyFunctionDumper.cpp
SRCS+=		PrettyTypeDumper.cpp
SRCS+=		PrettyTypedefDumper.cpp
SRCS+=		PrettyVariableDumper.cpp
SRCS+=		StreamUtil.cpp
SRCS+=		YAMLOutputStyle.cpp
SRCS+=		llvm-pdbutil.cpp

.include "../llvm.prog.mk"
