# $MidnightBSD$
# $FreeBSD: stable/10/usr.sbin/extattr/tests/Makefile 301145 2016-06-01 17:22:15Z asomers $

TESTSDIR=	${TESTSBASE}/usr.sbin/extattr

ATF_TESTS_SH=	extattr_test

.include <bsd.test.mk>
