# $FreeBSD: stable/11/stand/defaults/Makefile 332115 2018-04-06 16:59:58Z kevans $

.include <bsd.init.mk>

FILES+=	loader.conf
MAN+=	loader.conf.5

FILESDIR_loader.conf=  /boot/defaults

.include <bsd.prog.mk>
