# $FreeBSD: stable/11/stand/userboot/Makefile 344413 2019-02-21 03:18:12Z kevans $

.include <bsd.init.mk>

SUBDIR.yes=		test
SUBDIR.${MK_FORTH}+= userboot_4th
SUBDIR.${MK_LOADER_LUA}+= userboot_lua

.include <bsd.subdir.mk>

