# $FreeBSD: release/10.0.0/sys/modules/ahb/Makefile 217070 2011-01-06 21:04:00Z imp $

.PATH: ${.CURDIR}/../../dev/ahb

KMOD=	ahb
SRCS=	ahb.c opt_cam.h device_if.h bus_if.h eisa_if.h

.include <bsd.kmod.mk>
