# $FreeBSD: stable/11/lib/libiconv_modules/mapper_serial/Makefile 260334 2014-01-05 21:03:49Z dim $

SHLIB=	mapper_serial
SRCS+=	citrus_mapper_serial.c
CFLAGS.gcc+= --param max-inline-insns-single=32

.include <bsd.lib.mk>
