# $FreeBSD: release/10.0.0/lib/libiconv_modules/mapper_serial/Makefile 219019 2011-02-25 00:04:39Z gabor $

SHLIB=	mapper_serial
SRCS+=	citrus_mapper_serial.c
CFLAGS+= --param max-inline-insns-single=32

.include <bsd.lib.mk>
