# $FreeBSD: stable/11/sys/modules/utopia/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/utopia

KMOD=	utopia
SRCS=	utopia.c suni.c idtphy.c bus_if.h device_if.h

.include <bsd.kmod.mk>
