# $FreeBSD: release/10.0.0/sys/modules/utopia/Makefile 142445 2005-02-25 09:49:29Z harti $

.PATH: ${.CURDIR}/../../dev/utopia

KMOD=	utopia
SRCS=	utopia.c suni.c idtphy.c bus_if.h device_if.h

.include <bsd.kmod.mk>
