#	$FreeBSD: stable/11/share/examples/kld/dyn_sysctl/Makefile 299293 2016-05-10 00:51:50Z gjb $

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/kld/${KMOD}
SRCS	= dyn_sysctl.c
KMOD	= dyn_sysctl

.include <bsd.kmod.mk>
