# $MidnightBSD$
# $FreeBSD: stable/10/sbin/geom/class/raid3/Makefile 216468 2010-12-15 23:24:34Z obrien $

.PATH:	${.CURDIR}/../../misc

GEOM_CLASS=	raid3

DPADD=	${LIBMD}
LDADD=	-lmd

.include <bsd.lib.mk>
