# $FreeBSD: release/10.0.0/share/man/man4/man4.arm/Makefile 249999 2013-04-27 23:07:49Z wkoszek $

MAN=	mge.4 npe.4 devcfg.4

MLINKS= mge.4 if_mge.4
MLINKS+=npe.4 if_npe.4

MANSUBDIR=/arm

.include <bsd.prog.mk>
