# $FreeBSD: release/10.0.0/usr.bin/lessecho/Makefile 161480 2006-08-20 15:52:17Z delphij $

PROG=	lessecho
SRCS=	lessecho.c version.c
CLEANFILES= lessecho.1

.include "${.CURDIR}/../less/Makefile.common"
.include <bsd.prog.mk>
