# $FreeBSD: release/10.0.0/usr.sbin/bsdconfig/security/include/Makefile 241899 2012-10-22 18:01:38Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/130.security/include
FILES=		messages.subr securelevel.hlp

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
