# $FreeBSD: stable/11/sys/modules/md/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/md

KMOD=	geom_md
SRCS=	md.c opt_md.h opt_geom.h opt_rootdevname.h vnode_if.h

.include <bsd.kmod.mk>
