# $FreeBSD: release/10.0.0/usr.sbin/ctm/ctm_dequeue/Makefile 201390 2010-01-02 11:07:44Z ed $

.PATH: ${.CURDIR}/../ctm_rmail

PROG=	ctm_dequeue
NO_MAN=
SRCS=	ctm_dequeue.c error.c

CFLAGS+= -I${.CURDIR}/../ctm_rmail

WARNS?=	1

.include <bsd.prog.mk>
