# $FreeBSD: release/10.0.0/gnu/usr.bin/groff/font/Makefile 75592 2001-04-17 12:37:18Z ru $

SUBDIR=		devX100 devX100-12 devX75 devX75-12 \
		devascii devcp1047 devdvi devhtml devkoi8-r \
		devlatin1 devlbp devlj4 devps devutf8

.include <bsd.subdir.mk>
