# $FreeBSD: release/10.0.0/gnu/usr.bin/groff/font/Makefile.dev 114412 2003-05-01 13:22:21Z ru $

FILES=		${DEVFILES}
FILESDIR?=	${fontdir}/dev${DEV}
SCRIPTS=	${DEVSCRIPTS}
SCRIPTSDIR?=	${fontdir}/dev${DEV}
.for script in ${SCRIPTS}
SCRIPTSNAME_${script:T}= ${script:T}
.endfor

.include <bsd.prog.mk>
