# $FreeBSD: release/7.0.0/usr.sbin/ctm/ctm_rmail/Makefile 113091 2003-04-04 17:49:21Z obrien $

PROG=	ctm_rmail
MLINKS=	ctm_rmail.1 ctm_smail.1 \
	ctm_rmail.1 ctm_dequeue.1
SRCS=	ctm_rmail.c error.c

.include <bsd.prog.mk>
