# $MidnightBSD: src/sys/modules/ata/Makefile,v 1.2 2010/02/06 23:08:34 laffer1 Exp $
# $FreeBSD: src/sys/modules/ata/Makefile,v 1.2 2005/04/05 02:05:01 scottl Exp $

SUBDIR = atacore
SUBDIR += atacard
SUBDIR += ataisa
SUBDIR += atapci 
SUBDIR += atadisk atapicd atapifd atapist ataraid atapicam #atacam

.include <bsd.subdir.mk>
