# $FreeBSD: release/10.0.0/sys/modules/jme/Makefile 179338 2008-05-27 01:54:45Z yongari $

.PATH: ${.CURDIR}/../../dev/jme

KMOD=	if_jme
SRCS=	if_jme.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
