# Make `routed` tools for BSD/OS
# $Revision: 1.6 $
# $FreeBSD: release/7.0.0/sbin/routed/rtquery/Makefile 133650 2004-08-13 14:18:24Z ru $

PROG=	rtquery
MAN=	rtquery.8
LDADD=	-lmd
DPADD=	${LIBMD}
WARNS?=	0

.include <bsd.prog.mk>
