# $FreeBSD: stable/11/sys/modules/geom/geom_linux_lvm/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/geom/linux_lvm

KMOD=	geom_linux_lvm
SRCS=	g_linux_lvm.c

.include <bsd.kmod.mk>
