# $FreeBSD: release/10.0.0/sys/modules/geom/geom_linux_lvm/Makefile 176418 2008-02-20 07:50:13Z thompsa $

.PATH: ${.CURDIR}/../../../geom/linux_lvm

KMOD=	geom_linux_lvm
SRCS=	g_linux_lvm.c

.include <bsd.kmod.mk>
