# $FreeBSD: stable/11/usr.bin/indent/tests/Makefile 334542 2018-06-02 21:50:00Z eadler $

PACKAGE=	tests

${PACKAGE}FILES+=	binary.0
${PACKAGE}FILES+=	binary.0.stdout
${PACKAGE}FILES+=	comments.0
${PACKAGE}FILES+=	comments.0.stdout
${PACKAGE}FILES+=	declarations.0
${PACKAGE}FILES+=	declarations.0.stdout
${PACKAGE}FILES+=	float.0
${PACKAGE}FILES+=	float.0.stdout
${PACKAGE}FILES+=	nsac.0
${PACKAGE}FILES+=	nsac.0.stdout
${PACKAGE}FILES+=	nsac.0.pro
${PACKAGE}FILES+=	offsetof.0
${PACKAGE}FILES+=	offsetof.0.stdout
${PACKAGE}FILES+=	struct.0
${PACKAGE}FILES+=	struct.0.stdout
${PACKAGE}FILES+=	surplusbad.0
${PACKAGE}FILES+=	surplusbad.0.stdout
${PACKAGE}FILES+=	surplusbad.0.pro
${PACKAGE}FILES+=	wchar.0
${PACKAGE}FILES+=	wchar.0.stdout

ATF_TESTS_SH+=		functional_test

BINDIR=	${TESTSDIR}

.include <bsd.test.mk>
