# $FreeBSD: release/10.0.0/sys/modules/mac_none/Makefile 105725 2002-10-22 17:10:15Z rwatson $

.PATH: ${.CURDIR}/../../security/mac_none

KMOD=	mac_none
SRCS=	vnode_if.h \
	mac_none.c

.include <bsd.kmod.mk>
