# $FreeBSD: release/10.0.0/sys/modules/syscons/daemon/Makefile 106497 2002-11-06 13:47:00Z nyan $

.PATH:	${.CURDIR}/../../../dev/syscons/daemon

KMOD=	daemon_saver
SRCS=	daemon_saver.c

.include <bsd.kmod.mk>
