# $FreeBSD: release/10.0.0/tools/tools/shlib-compat/Makefile.sysfake 248693 2013-03-25 00:31:14Z gleb $

SRCS+= sysfake.c
CLEANFILES+= sysfake.c

sysfake.c: ${.CURDIR}/../../sys/kern/syscalls.master
	sh ${.CURDIR}/../../tools/tools/shlib-compat/makesyscalls-fake.sh \
		${.CURDIR}/../../sys/kern/syscalls.master > ${.TARGET}

