# $FreeBSD: release/10.0.0/tools/regression/file/newfileops_on_fork/Makefile 188483 2009-02-11 13:44:27Z rwatson $

PROG=	newfileops_on_fork
NO_MAN=
WARNS?=	6
LDFLAGS=	-lpthread

.include <bsd.prog.mk>
