# $FreeBSD: stable/9/gnu/usr.bin/patch/Makefile 125910 2004-02-17 01:34:53Z ache $

PROG= 	patch
SRCS=   backupfile.c inp.c patch.c pch.c util.c version.c
CFLAGS+=-DHAVE_CONFIG_H

.include <bsd.prog.mk>
