# $FreeBSD: stable/11/sys/modules/imx/Makefile 346526 2019-04-22 05:00:29Z ian $
# Build modules specific to freescale/nxp imx-family SoCs.

SUBDIR = \
	../ffec \
	imx6_ahci \
	imx6_snvs \
	imx_i2c \
	imx_spi \
	imx_wdog \
	
.include <bsd.subdir.mk>
