# $FreeBSD: release/10.0.0/sys/modules/ata/atapci/chipsets/atanetcell/Makefile 249213 2013-04-06 19:12:49Z marius $

.PATH: ${.CURDIR}/../../../../../dev/ata/chipsets

KMOD=	atanetcell
SRCS=	ata-netcell.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
