# $FreeBSD: release/9.2.0/lib/clang/libllvmmcdisassembler/Makefile 252723 2013-07-04 20:17:04Z dim $

.include <bsd.own.mk>

LIB=	llvmmcdisassembler

SRCDIR=	lib/MC/MCDisassembler
SRCS=	Disassembler.cpp

.include "../clang.lib.mk"
