# $FreeBSD: stable/9/lib/clang/libllvmmcdisassembler/Makefile 246637 2013-02-10 21:24:47Z dim $

.include <bsd.own.mk>

LIB=	llvmmcdisassembler

SRCDIR=	lib/MC/MCDisassembler
SRCS=	Disassembler.cpp \
	EDDisassembler.cpp \
	EDInst.cpp \
	EDOperand.cpp \
	EDToken.cpp

.include "../clang.lib.mk"
