# $FreeBSD: release/10.0.0/lib/clang/libllvmmcdisassembler/Makefile 249423 2013-04-12 17:57:40Z dim $

.include <bsd.own.mk>

LIB=	llvmmcdisassembler

SRCDIR=	lib/MC/MCDisassembler
SRCS=	Disassembler.cpp

.include "../clang.lib.mk"
