#	$NetBSD: Makefile,v 1.2 1995/07/03 21:23:45 cgd Exp $
# $FreeBSD: release/10.0.0/usr.bin/xlint/Makefile 116402 2003-06-15 13:03:37Z markm $

.if ${LINT} == "lint"
_llib=	llib
.else
_llib=
.endif

SUBDIR=	lint1 lint2 xlint ${_llib}

.include <bsd.subdir.mk>
