#$FreeBSD: stable/10/share/dtrace/toolkit/Makefile 235613 2012-05-18 16:40:15Z gnn $
#
# Install scripts from the DTraceToolkit
#
DTRACETOOLKIT= ../../../cddl/contrib/dtracetoolkit

SCRIPTS=	${DTRACETOOLKIT}/execsnoop \
		${DTRACETOOLKIT}/hotuser   \
		${DTRACETOOLKIT}/hotkernel \
		${DTRACETOOLKIT}/opensnoop \
		${DTRACETOOLKIT}/procsystime \

SCRIPTSDIR= ${SHAREDIR}/dtrace/toolkit

NO_OBJ=

.include <bsd.prog.mk>
