# $FreeBSD: stable/11/lib/libclang_rt/asan-preinit/Makefile 310618 2016-12-26 20:36:37Z dim $

.include <bsd.init.mk>

LIB=		clang_rt.asan-preinit-${CRTARCH}

SRCS+=		asan/asan_preinit.cc

.include <bsd.lib.mk>
