# $FreeBSD: release/10.0.0/gnu/usr.bin/groff/src/utils/addftinfo/Makefile 114412 2003-05-01 13:22:21Z ru $

PROG_CXX=	addftinfo
SRCS=		addftinfo.cpp guess.cpp
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
