# $FreeBSD: stable/11/gnu/usr.bin/groff/src/utils/addftinfo/Makefile 270168 2014-08-19 15:04:32Z bdrewery $

PROG_CXX=	addftinfo
SRCS=		addftinfo.cpp guess.cpp
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
