# $FreeBSD: stable/9/lib/clang/libllvmexecutionengine/Makefile 246637 2013-02-10 21:24:47Z dim $

.include <bsd.own.mk>

LIB=	llvmexecutionengine

SRCDIR=	lib/ExecutionEngine
SRCS=	ExecutionEngine.cpp \
	ExecutionEngineBindings.cpp \
	TargetSelect.cpp

.include "../clang.lib.mk"
