# $FreeBSD: release/10.0.0/lib/clang/libllvmexecutionengine/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvmexecutionengine

SRCDIR=	lib/ExecutionEngine
SRCS=	ExecutionEngine.cpp \
	ExecutionEngineBindings.cpp \
	TargetSelect.cpp

.include "../clang.lib.mk"
