#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/7.0.0/usr.bin/lastcomm/Makefile 169857 2007-05-22 06:51:38Z dds $

PROG=	lastcomm
SRCS=	lastcomm.c readrec.c
WARNS?= 6

.include <bsd.prog.mk>
