# $FreeBSD: release/10.0.0/usr.sbin/Makefile.ia64 252356 2013-06-28 21:00:08Z davide $

.if ${MK_ACPI} != "no"
SUBDIR+=	acpi
.endif
SUBDIR+=	kgmon
SUBDIR+=	mount_smbfs
SUBDIR:=	${SUBDIR:Nuathload}
SUBDIR+=	zzz
