# $FreeBSD: release/10.0.0/usr.sbin/Makefile.mips 233644 2012-03-29 02:54:35Z jmallett $

# uathload broken for n32 and n64 due to toolchain issues, only build for o32
.if ${MACHINE_ARCH} != "mips" && ${MACHINE_ARCH} != "mipsel"
SUBDIR:=	${SUBDIR:Nuathload}
.endif
