#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: release/7.0.0/sbin/startslip/Makefile 133002 2004-08-02 08:10:28Z stefanf $

PROG=	startslip
WARNS?=	3
DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
