#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/11/usr.sbin/lpr/filters/Makefile 321276 2017-07-20 01:07:15Z ngie $

BINDIR=	${LIBEXECDIR}/lpr

PROG=	lpf
MAN=

CFLAGS+= -I${.CURDIR:H}/common_source

.include <bsd.prog.mk>
