#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/10.0.0/usr.sbin/lpr/filters/Makefile 156512 2006-03-09 19:52:44Z gad $

BINDIR=	/usr/libexec/lpr

PROG=	lpf
NO_MAN=

CFLAGS+= -I${.CURDIR}/../common_source

.include <bsd.prog.mk>
