# Makefile for building the sample syscall module
# $FreeBSD: stable/9/share/examples/kld/syscall/module/Makefile 83608 2001-09-18 12:03:42Z ru $

KMOD=	syscall
SRCS=	syscall.c

.include <bsd.kmod.mk>
