# The FreeBSD Simplified Chinese Project
#
# Original Revision: 1.8
# $FreeBSD: release/7.0.0/release/doc/zh_CN.GB2312/Makefile 174504 2007-12-09 23:37:43Z delphij $

RELN_ROOT?= ${.CURDIR}/..

SUBDIR = relnotes
SUBDIR+= hardware
SUBDIR+= readme
SUBDIR+= errata

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
