# The FreeBSD Simplified Chinese Project
#
# Original Revision: 171847
# $FreeBSD: stable/9/release/doc/zh_CN.GB2312/Makefile 183116 2008-09-17 18:13:37Z delphij $

RELN_ROOT?= ${.CURDIR}/..

SUBDIR = relnotes
SUBDIR+= hardware
SUBDIR+= readme
SUBDIR+= errata

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
