#
# $FreeBSD: release/10.0.0/usr.sbin/bsnmpd/tools/libbsnmptools/Makefile 216377 2010-12-11 13:24:01Z syrinx $
#

.PATH: ${.CURDIR}

LIB=	bsnmptools
#INTERNALLIB=
SRCS=	bsnmpimport.c bsnmpmap.c bsnmptools.c bsnmptc.c

SHLIB_MAJOR=	0

.include <bsd.lib.mk>
