#
# $FreeBSD: stable/11/usr.sbin/bsnmpd/tools/libbsnmptools/Makefile 313242 2017-02-04 17:21:17Z ngie $
#

.PATH: ${.CURDIR}

LIB=	bsnmptools

SRCS=	bsnmpimport.c bsnmpmap.c bsnmptools.c bsnmptc.c

INTERNALLIB=

.include <bsd.lib.mk>
