# $MidnightBSD$
# $FreeBSD: stable/10/share/examples/tests/Makefile 313488 2017-02-09 22:49:48Z ngie $

.include <bsd.own.mk>

SUBDIR=		tests

.PATH:		${SRCTOP}/tests
KYUAFILE=	yes

.include <bsd.test.mk>
