# $FreeBSD: release/10.0.0/sbin/mdmfs/Makefile 198236 2009-10-19 16:00:24Z ru $

PROG=		mdmfs
LINKS=		${BINDIR}/${PROG} ${BINDIR}/mount_mfs
MAN=		mdmfs.8
MLINKS+=	mdmfs.8 mount_mfs.8

.include <bsd.prog.mk>
