# $FreeBSD: release/7.0.0/sbin/mdmfs/Makefile 140815 2005-01-25 14:28:31Z ssouhlal $

PROG=		mdmfs
LINKS=		${BINDIR}/${PROG} ${BINDIR}/mount_mfs
MAN=		mdmfs.8
MLINKS+=	mdmfs.8 mount_mfs.8
WARNS?=		6

.include <bsd.prog.mk>
