# $FreeBSD: release/10.0.0/share/i18n/esdb/ISO646/Makefile 219019 2011-02-25 00:04:39Z gabor $
# $NetBSD: Makefile.inc,v 1.4 2008/10/25 22:27:36 apb Exp $

CODE=	ISO646
SED_EXP= 's/ISO646-x/ISO646-%%PART%%/'

.include "../Makefile.part"
