# $FreeBSD: stable/11/share/doc/legal/intel_ipw/Makefile 289399 2015-10-16 00:38:05Z bdrewery $

FILES=		${.CURDIR}/../../../../sys/contrib/dev/ipw/LICENSE
FILESDIR=	${SHAREDIR}/doc/legal
FILESNAME=	intel_ipw.LICENSE

.include <bsd.prog.mk>
