# $FreeBSD: stable/11/sys/modules/geom/geom_part/geom_part_apm/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/geom/part

KMOD=	geom_part_apm
SRCS=	g_part_apm.c

SRCS+=	bus_if.h device_if.h g_part_if.h

.include <bsd.kmod.mk>
