# $MidnightBSD$
# Makefile for simple caller of syscall
# $FreeBSD: stable/10/share/examples/kld/syscall/test/Makefile 276486 2014-12-31 23:25:37Z ngie $

PROG=	call
MAN=
WARNS?=	5

.include <bsd.prog.mk>
