# $FreeBSD: release/7.0.0/sys/modules/vesa/Makefile 89260 2002-01-11 15:49:02Z ru $

.PATH: ${.CURDIR}/../../dev/syscons ${.CURDIR}/../../i386/isa

KMOD=	vesa
SRCS=	vesa.c scvesactl.c opt_vga.h opt_vesa.h

.include <bsd.kmod.mk>
