# $FreeBSD: stable/11/tests/sys/netinet/Makefile 308701 2016-11-15 22:18:52Z hiren $

TESTSDIR=	${TESTSBASE}/sys/netinet
BINDIR=		${TESTSDIR}

ATF_TESTS_SH=	fibs_test

PROGS=	udp_dontroute tcp_user_cookie

MAN=

WARNS?=	6

.include <bsd.test.mk>
