# $FreeBSD: stable/9/lib/clang/libllvmdebuginfo/Makefile 246637 2013-02-10 21:24:47Z dim $

.include <bsd.own.mk>

LIB=	llvmdebuginfo

SRCDIR=	lib/DebugInfo
SRCS=	DIContext.cpp \
	DWARFAbbreviationDeclaration.cpp \
	DWARFCompileUnit.cpp \
	DWARFContext.cpp \
	DWARFDebugAbbrev.cpp \
	DWARFDebugArangeSet.cpp \
	DWARFDebugAranges.cpp \
	DWARFDebugInfoEntry.cpp \
	DWARFDebugLine.cpp \
	DWARFDebugRangeList.cpp \
	DWARFFormValue.cpp

.include "../clang.lib.mk"
