# $FreeBSD: release/9.2.0/lib/clang/libllvmdebuginfo/Makefile 252723 2013-07-04 20:17:04Z dim $

.include <bsd.own.mk>

LIB=	llvmdebuginfo

SRCDIR=	lib/DebugInfo
SRCS=	DIContext.cpp \
	DWARFAbbreviationDeclaration.cpp \
	DWARFCompileUnit.cpp \
	DWARFContext.cpp \
	DWARFDebugAbbrev.cpp \
	DWARFDebugArangeSet.cpp \
	DWARFDebugAranges.cpp \
	DWARFDebugFrame.cpp \
	DWARFDebugInfoEntry.cpp \
	DWARFDebugLine.cpp \
	DWARFDebugRangeList.cpp \
	DWARFFormValue.cpp

.include "../clang.lib.mk"
