# $FreeBSD: release/10.0.0/tools/regression/usr.bin/make/sysmk/t0/2/1/Makefile 201526 2010-01-04 18:57:22Z obrien $
#
# Can we traverse up to / and find a 'mk/sys.mk'?
#
all:
	@echo ${DASH_M_DOTDOTDOT}
