# $MidnightBSD: src/usr.bin/spell/spellprog/Makefile,v 1.1 2006/12/31 07:08:37 laffer1 Exp $
#	$NetBSD: Makefile,v 1.3 2006/08/26 18:17:43 christos Exp $

PROG=	spellprog
WARNS?=	6
NO_MAN=	1
SRCS=	spellprog.c look.c
BINDIR=	/usr/libexec

#LDADD+=-lutil
#DPADD+=${LIBUTIL}

.include <bsd.prog.mk>
