# $FreeBSD: release/10.0.0/sys/modules/iwi/Makefile 156600 2006-03-12 19:06:06Z damien $

.PATH: ${.CURDIR}/../../dev/iwi

KMOD    = if_iwi
SRCS    = if_iwi.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
