# $FreeBSD: stable/11/sys/modules/iwi/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/iwi

KMOD    = if_iwi
SRCS    = if_iwi.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
