# $FreeBSD: release/10.0.0/sys/modules/nfslock/Makefile 210455 2010-07-24 22:11:11Z rmacklem $

.PATH: ${.CURDIR}/../../nfs
KMOD=	nfslock
SRCS=	vnode_if.h \
	nfs_lock.c \
	opt_nfs.h

.include <bsd.kmod.mk>
