# $FreeBSD: stable/11/usr.bin/ofed/libibverbs/Makefile 335253 2018-06-16 15:05:05Z kib $

SUBDIR= \
asyncwatch \
devinfo \
devices \
rc_pingpong \
srq_pingpong \
uc_pingpong \
ud_pingpong

.include <bsd.subdir.mk>
