# $FreeBSD: stable/11/usr.bin/ofed/libibverbs/uc_pingpong/Makefile 335253 2018-06-16 15:05:05Z kib $

PROG=	ibv_uc_pingpong
MAN=	ibv_uc_pingpong.1
SRCS=	uc_pingpong.c pingpong.c

.include <bsd.prog.mk>
