# $FreeBSD: release/10.0.0/sys/modules/speaker/Makefile 152306 2005-11-11 09:57:32Z ru $

.PATH: ${.CURDIR}/../../dev/speaker

KMOD=	speaker
SRCS=	spkr.c
SRCS+=	bus_if.h device_if.h isa_if.h

.include <bsd.kmod.mk>
