# $FreeBSD: stable/11/sys/modules/dtb/zynq/Makefile 298666 2016-04-26 21:11:01Z gonzo $
# All the dts files for Zynq systems we support.
DTS=	\
	zedboard.dts \
        zybo.dts

.include <bsd.dtb.mk>
