# $MidnightBSD$
# $FreeBSD: stable/10/usr.bin/tests/Makefile 313488 2017-02-09 22:49:48Z ngie $

.include <bsd.own.mk>

.PATH:		${SRCTOP}/tests
KYUAFILE=	yes

FILESDIR=	${TESTSDIR}
FILES=		regress.m4

.include <bsd.test.mk>
