# Copyright (c) 2011 David E O'Brien
# $FreeBSD: stable/11/lib/libedit/edit/readline/Makefile 234690 2012-04-26 00:51:43Z obrien $

INCS=	readline.h history.h tilde.h

INCSDIR= ${INCLUDEDIR}/edit/readline

.include <bsd.lib.mk>
