# $MidnightBSD: src/sys/i386/conf/Makefile,v 1.2 2006/10/01 22:12:20 laffer1 Exp $
# $FreeBSD: src/sys/i386/conf/Makefile,v 1.9 2003/02/26 23:36:58 ru Exp $

TARGET=i386

.include "${.CURDIR}/../../conf/makeLINT.mk"
