# $MidnightBSD$
# $FreeBSD: stable/10/share/examples/smbfs/Makefile 291794 2015-12-04 18:21:05Z bdrewery $

NO_OBJ=
FILESDIR= ${SHAREDIR}/examples/smbfs
FILES=	dot.nsmbrc

.PATH: ${.CURDIR}/../../../contrib/smbfs/examples

SUBDIR=	print

.include <bsd.prog.mk>
