# $FreeBSD: stable/11/share/examples/smbfs/Makefile 299293 2016-05-10 00:51:50Z gjb $

PACKAGE=examples
FILESDIR= ${SHAREDIR}/examples/smbfs
FILES=	dot.nsmbrc

.PATH: ${.CURDIR}/../../../contrib/smbfs/examples

SUBDIR=	print

.include <bsd.prog.mk>
