# $FreeBSD: stable/11/sys/modules/sound/driver/es137x/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/sound/pci

KMOD=	snd_es137x
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	es137x.c

.include <bsd.kmod.mk>
