# $FreeBSD: stable/11/sys/modules/elink/Makefile 319182 2017-05-30 04:11:12Z ngie $
#

.PATH:	${SRCTOP}/sys/i386/isa

KMOD=		elink
SRCS=		elink.c
EXPORT_SYMS=	elink_reset elink_idseq

.include <bsd.kmod.mk>
