# $MidnightBSD$
# $FreeBSD: stable/10/lib/libalias/modules/Makefile 313581 2017-02-11 05:45:00Z ngie $

.include "${SRCTOP}/sys/modules/libalias/modules/modules.inc"

SUBDIR=	${MODULES}

.include <bsd.subdir.mk>
