# $FreeBSD: stable/11/sys/modules/ow/ow_temp/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/ow

KMOD=	ow_temp
SRCS=	ow_temp.c
SRCS+=	own_if.h bus_if.h device_if.h

.include <bsd.kmod.mk>
