# $FreeBSD: release/7.0.0/libexec/rpc.sprayd/Makefile 74814 2001-03-26 14:22:12Z ru $

PROG =	rpc.sprayd
SRCS =	sprayd.c
MAN =	rpc.sprayd.8

DPADD=	${LIBRPCSVC}
LDADD=	-lrpcsvc

.include <bsd.prog.mk>

