#
#      The FreeBSD Documentation Project
#      The FreeBSD French Documentation Project
#
#      $Id: Makefile,v 1.1.1.1 2006-02-25 02:27:00 laffer1 Exp $
#      $FreeBSD: src/release/doc/fr_FR.ISO8859-1/hardware/Makefile,v 1.1 2002/09/09 22:09:46 gioria Exp $
#      Original revision: 1.4

RELN_ROOT?= ${.CURDIR}/../..

SUBDIR = alpha
SUBDIR+= i386
SUBDIR+= pc98
SUBDIR+= sparc64

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
