#
#      The FreeBSD Documentation Project
#      The FreeBSD French Documentation Project
#
#      $Id: Makefile,v 1.2 2009-10-24 04:45:18 laffer1 Exp $
#      $FreeBSD: src/release/doc/fr_FR.ISO8859-1/hardware/Makefile,v 1.1 2002/09/09 22:09:46 gioria Exp $
#      Original revision: 1.4

RELN_ROOT?= ${.CURDIR}/../..

SUBDIR+= i386
SUBDIR+= sparc64

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
