# $FreeBSD: release/10.0.0/sys/modules/geom/geom_vol_ffs/Makefile 115783 2003-06-03 20:32:13Z gordon $

.PATH: ${.CURDIR}/../../../geom

KMOD=	geom_vol_ffs
SRCS=	geom_vol_ffs.c

.include <bsd.kmod.mk>
