# The FreeBSD Russian Documentation Project
#
# $FreeBSDru: frdp/release/doc/ru_RU.KOI8-R/installation/Makefile,v 1.1 2004/06/24 07:21:47 den Exp $
# $FreeBSD: stable/9/release/doc/ru_RU.KOI8-R/installation/Makefile 131040 2004-06-24 08:39:20Z den $
#
# Original revision: 1.6
#

RELN_ROOT?= ${.CURDIR}/../..

SUBDIR = alpha
SUBDIR+= amd64
SUBDIR+= ia64
SUBDIR+= i386
SUBDIR+= pc98
SUBDIR+= sparc64

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
