#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/7.0.0/usr.bin/lock/Makefile 90415 2002-02-08 22:31:43Z markm $

PROG=	lock
BINOWN=	root
BINMODE=4555
DPADD=	${LIBCRYPT}
LDADD=	-lcrypt

.include <bsd.prog.mk>
