#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/10.0.0/usr.bin/lock/Makefile 209567 2010-06-28 08:30:10Z gavin $

PROG=	lock
BINOWN=	root
BINMODE=4555
DPADD=	${LIBCRYPT}
LDADD=	-lcrypt

.include <bsd.prog.mk>
