# $FreeBSD: stable/11/usr.bin/bmake/tests/variables/modifier_t/Makefile.test 263346 2014-03-19 12:29:20Z jmmv $
#
# Test the t modifier.
#
# below is missing '
ASCII=	!"\#$$%&()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~

test1:
	@echo '${ASCII}'

test2:
	@echo '${ASCII:tl}'

test3:
	@echo '${ASCII:tu}'
