# $FreeBSD: stable/11/lib/libnetbsd/Makefile 332979 2018-04-25 01:30:29Z benno $

.include <bsd.own.mk>

PACKAGE=lib${LIB}
LIB=	netbsd

CFLAGS+=	-I${.CURDIR}

SRCS+=	efun.c sockaddr_snprintf.c strsuftoll.c util.c util.h

INTERNALLIB=

.include <bsd.lib.mk>
