# $FreeBSD: release/7.0.0/sbin/gpt/Makefile 149688 2005-09-01 02:49:20Z marcel $

PROG=	gpt
SRCS=	add.c create.c destroy.c gpt.c label.c map.c migrate.c recover.c \
	remove.c show.c
WARNS?=	4
MAN=	gpt.8

.include <bsd.prog.mk>
