# $FreeBSD: release/10.0.0/sys/modules/vte/Makefile 216829 2010-12-31 00:21:41Z yongari $

.PATH: ${.CURDIR}/../../dev/vte

KMOD=	if_vte
SRCS=	if_vte.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
