# $FreeBSD: stable/11/sys/modules/ip_mroute_mod/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/netinet ${SRCTOP}/sys/netinet6

KMOD=	ip_mroute

SRCS=	ip_mroute.c
SRCS+=	opt_inet.h opt_mrouting.h

.include <bsd.kmod.mk>
