#	from: @(#)Makefile	5.2 (Berkeley) 5/11/90
# $FreeBSD: release/7.0.0/usr.bin/rpcinfo/Makefile 160748 2006-07-27 13:47:02Z yar $

PROG=	rpcinfo
SRCS=	rpcinfo.c
MAN=	rpcinfo.8

CFLAGS+= -DPORTMAP

.include <bsd.prog.mk>
