# $FreeBSD: stable/11/usr.bin/ofed/libibverbs/srq_pingpong/Makefile 335253 2018-06-16 15:05:05Z kib $

PROG=	ibv_srq_pingpong
MAN=	ibv_srq_pingpong.1
SRCS=	srq_pingpong.c pingpong.c

.include <bsd.prog.mk>
