# Cronyx Id: sbin.sconfig.Makefile,v 1.1.4.1 2003/02/17 12:51:24 rik Exp $
# $FreeBSD: release/10.0.0/sbin/sconfig/Makefile 198236 2009-10-19 16:00:24Z ru $

PROG=	sconfig
MAN=	sconfig.8
MANSUBDIR= /i386
WARNS?=	2

.include <bsd.prog.mk>
