# Cronyx Id: sbin.sconfig.Makefile,v 1.1.4.1 2003/02/17 12:51:24 rik Exp $
# $FreeBSD: release/7.0.0/sbin/sconfig/Makefile 124784 2004-01-21 13:24:38Z ru $

PROG=	sconfig
MAN=	sconfig.8
MANSUBDIR= /i386

.include <bsd.prog.mk>
