# Cronyx Id: sbin.sconfig.Makefile,v 1.1.4.1 2003/02/17 12:51:24 rik Exp $
# $FreeBSD: stable/11/sbin/sconfig/Makefile 298107 2016-04-16 07:45:30Z gjb $

PACKAGE=runtime
PROG=	sconfig
MAN=	sconfig.8
MANSUBDIR= /i386
WARNS?=	2

.include <bsd.prog.mk>
