#	$NetBSD: Makefile,v 1.14 1996/09/27 22:38:37 christos Exp $
# $FreeBSD: stable/11/sbin/fsck/Makefile 298107 2016-04-16 07:45:30Z gjb $

PACKAGE=runtime
PROG=	fsck
SRCS=	fsck.c fsutil.c preen.c
MAN=	fsck.8

.include <bsd.prog.mk>
