# $FreeBSD: stable/11/usr.bin/ofed/infiniband-diags/ibqueryerrors/Makefile 335253 2018-06-16 15:05:05Z kib $

PROG=	ibqueryerrors
SRCS=	ibqueryerrors.c
LIBADD=	ibnetdisc
MAN=	ibqueryerrors.8

.include <bsd.prog.mk>
