#	From: @(#)Makefile	8.1 (Berkeley) 8/14/93
# $FreeBSD: release/7.0.0/share/doc/psd/18.gprof/Makefile 136910 2004-10-24 15:33:08Z ru $

VOLUME=		psd/18.gprof
SRCS=		header.me abstract.me intro.me profiling.me gathering.me \
		postp.me present.me refs.me
EXTRA=		postp1.pic postp2.pic postp3.pic pres1.pic pres2.pic
MACROS=		-me
USE_SOELIM=
USE_PIC=
USE_TBL=
USE_EQN=
SRCDIR=		${.CURDIR}/../../../../usr.bin/gprof/PSD.doc

.include <bsd.doc.mk>
