# $MidnightBSD: src/lib/bind/Makefile,v 1.2 2008/04/28 00:03:14 laffer1 Exp $
# $FreeBSD: src/lib/bind/Makefile,v 1.1 2004/09/21 19:01:42 des Exp $

SUBDIR=		bind9 dns isc isccc isccfg lwres

.include <bsd.subdir.mk>
