# $FreeBSD: release/7.0.0/usr.sbin/ofwdump/Makefile 129589 2004-05-22 16:51:11Z marius $

PROG=	ofwdump
MAN=	ofwdump.8
MANSUBDIR= /sparc64
SRCS=	ofwdump.c ofw_util.c

WARNS?=	6

.include <bsd.prog.mk>
