# $FreeBSD: stable/11/gnu/usr.bin/groff/src/devices/grodvi/Makefile 291738 2015-12-04 03:17:47Z bdrewery $

PROG_CXX=	grodvi
SRCS=		dvi.cpp
DPADD=		${LIBDRIVER} ${LIBGROFF}
LDADD=		${LIBDRIVER} ${LIBGROFF}
LIBADD=		m
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
