# $FreeBSD: stable/9/lib/clang/libclangfrontendtool/Makefile 246637 2013-02-10 21:24:47Z dim $

.include <bsd.own.mk>

LIB=	clangfrontendtool

SRCDIR=	tools/clang/lib/FrontendTool
SRCS=	ExecuteCompilerInvocation.cpp

TGHDRS=	DiagnosticCommonKinds \
	DiagnosticFrontendKinds \
	Options

.include "../clang.lib.mk"
