# $FreeBSD: release/10.0.0/lib/clang/libclangfrontendtool/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	clangfrontendtool

SRCDIR=	tools/clang/lib/FrontendTool
SRCS=	ExecuteCompilerInvocation.cpp

TGHDRS=	DiagnosticCommonKinds \
	DiagnosticFrontendKinds \
	Options

.include "../clang.lib.mk"
