# $Id: Makefile,v 1.7 2003/08/14 20:06:22 max Exp $
# $FreeBSD: stable/11/usr.sbin/bluetooth/l2control/Makefile 275054 2014-11-25 16:57:27Z bapt $

PROG=		l2control
MAN=		l2control.8
SRCS=		l2cap.c l2control.c
WARNS?=		2

LIBADD=		bluetooth

.include <bsd.prog.mk>
