# $FreeBSD: stable/11/usr.bin/bmake/tests/suffixes/src_wild2/Makefile.test 263346 2014-03-19 12:29:20Z jmmv $
#
# Source expansion with the source in a macro
#

SRC=*.a

test1:	TEST1.b
	cat TEST1.a TEST2.a | diff -u - TEST1.b

TEST1.b: ${SRC}
	cat ${.ALLSRC} >${.TARGET}
