# $FreeBSD: stable/11/usr.bin/clang/clang-tblgen/Makefile 331838 2018-03-31 11:38:16Z dim $

PROG_CXX=	clang-tblgen
MAN=

SRCDIR=		tools/clang/utils/TableGen
SRCS+=		ClangASTNodesEmitter.cpp
SRCS+=		ClangAttrEmitter.cpp
SRCS+=		ClangCommentCommandInfoEmitter.cpp
SRCS+=		ClangCommentHTMLNamedCharacterReferenceEmitter.cpp
SRCS+=		ClangCommentHTMLTagsEmitter.cpp
SRCS+=		ClangDataCollectorsEmitter.cpp
SRCS+=		ClangDiagnosticsEmitter.cpp
SRCS+=		ClangOptionDocEmitter.cpp
SRCS+=		ClangSACheckersEmitter.cpp
SRCS+=		NeonEmitter.cpp
SRCS+=		TableGen.cpp

.include "../llvm.prog.mk"
