# $FreeBSD: release/7.0.0/sys/modules/ichwd/Makefile 129124 2004-05-11 18:21:38Z des $

.PATH: ${.CURDIR}/../../dev/ichwd

KMOD=	ichwd
SRCS=	ichwd.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
