# $FreeBSD: stable/11/sys/modules/ichwd/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/ichwd

KMOD=	ichwd
SRCS=	ichwd.c device_if.h bus_if.h pci_if.h isa_if.h

.include <bsd.kmod.mk>
