# $FreeBSD: stable/9/lib/clang/libllvmpowerpcinfo/Makefile 246637 2013-02-10 21:24:47Z dim $

.include <bsd.own.mk>

LIB=	llvmpowerpcinfo

SRCDIR=	lib/Target/PowerPC/TargetInfo
INCDIR=	lib/Target/PowerPC
SRCS=	PowerPCTargetInfo.cpp

TGHDRS=	PPCGenInstrInfo \
	PPCGenRegisterInfo \
	PPCGenSubtargetInfo

.include "../clang.lib.mk"
