# $FreeBSD: release/10.0.0/lib/clang/libllvmpowerpcinfo/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvmpowerpcinfo

SRCDIR=	lib/Target/PowerPC/TargetInfo
INCDIR=	lib/Target/PowerPC
SRCS=	PowerPCTargetInfo.cpp

TGHDRS=	PPCGenInstrInfo \
	PPCGenRegisterInfo \
	PPCGenSubtargetInfo

.include "../clang.lib.mk"
