#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/11/usr.bin/cut/Makefile 272783 2014-10-09 01:46:31Z ngie $

.include <src.opts.mk>

PROG=	cut

.if ${MK_TESTS} != "no"
SUBDIR+=	tests
.endif

.include <bsd.prog.mk>
