# $FreeBSD: stable/9/lib/libiconv_modules/Makefile 219019 2011-02-25 00:04:39Z gabor $

.include <bsd.own.mk>

SUBDIR=	BIG5 DECHanyu EUC EUCTW GBK2K HZ ISO2022 JOHAB MSKanji UES UTF1632 \
	UTF7 UTF8 VIQR ZW iconv_none iconv_std mapper_646 mapper_none \
	mapper_parallel mapper_serial mapper_std mapper_zone

.include <bsd.subdir.mk>
