# $FreeBSD: stable/11/lib/libiconv_modules/Makefile 289393 2015-10-15 22:55:08Z bdrewery $

.include <bsd.own.mk>

SUBDIR=	BIG5 DECHanyu EUC EUCTW GBK2K HZ ISO2022 JOHAB MSKanji UES UTF1632 \
	UTF7 UTF8 VIQR ZW iconv_none iconv_std mapper_646 mapper_none \
	mapper_parallel mapper_serial mapper_std mapper_zone
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
