# $MidnightBSD$
# $FreeBSD: stable/10/lib/libiconv_modules/Makefile 291792 2015-12-04 18:14:31Z bdrewery $

.include <bsd.own.mk>

SUBDIR=	BIG5 DECHanyu EUC EUCTW GBK2K HZ ISO2022 JOHAB MSKanji UES UTF1632 \
	UTF7 UTF8 VIQR ZW iconv_none iconv_std mapper_646 mapper_none \
	mapper_parallel mapper_serial mapper_std mapper_zone
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
