# $FreeBSD: release/10.0.0/sys/modules/digi/digi_CX_PCI/Makefile 76195 2001-05-02 01:08:09Z brian $

.PATH:	${.CURDIR}/../../../dev/digi
KMOD=	digi_CX_PCI
SRCS=	CX_PCI.c CX_PCI.bios.h CX_PCI.fepos.h digi_mod.h

.include <bsd.kmod.mk>
