# $FreeBSD: stable/11/usr.bin/clang/llvm-mc/Makefile 310618 2016-12-26 20:36:37Z dim $

PROG_CXX=	llvm-mc
MAN=

SRCDIR=		tools/llvm-mc
SRCS+=		Disassembler.cpp
SRCS+=		llvm-mc.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
