# $FreeBSD: stable/11/sys/modules/sound/driver/als4000/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/sound/pci

KMOD=	snd_als4000
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	als4000.c

.include <bsd.kmod.mk>
