# $FreeBSD: stable/9/release/doc/en_US.ISO8859-1/Makefile 229979 2012-01-11 20:04:52Z hrs $

RELN_ROOT?= ${.CURDIR}/..

SUBDIR = relnotes
SUBDIR+= hardware
SUBDIR+= readme
SUBDIR+= errata
SUBDIR+= installation

COMPAT_SYMLINK = en

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
