# $FreeBSD: release/7.0.0/release/doc/en_US.ISO8859-1/Makefile 171847 2007-08-15 03:02:22Z bmah $

RELN_ROOT?= ${.CURDIR}/..

SUBDIR = relnotes
SUBDIR+= hardware
SUBDIR+= readme
SUBDIR+= errata

COMPAT_SYMLINK = en

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
