# $Id: Makefile,v 1.1.1.2 2006-02-25 02:35:24 laffer1 Exp $
# $FreeBSD: src/sbin/mount_autofs/Makefile,v 1.2 2004/09/08 08:44:14 alfred Exp $

PROG=mount_autofs
MAN=mount_autofs.8
BINDIR?=/sbin

.include <bsd.prog.mk>
