# $Id: Makefile,v 1.6 2004/09/08 08:27:12 bright Exp $
# $FreeBSD: release/7.0.0/sbin/mount_autofs/Makefile 134940 2004-09-08 08:44:14Z alfred $

PROG=mount_autofs
MAN=mount_autofs.8
BINDIR?=/sbin

.include <bsd.prog.mk>
