# Makefile for acpi tools
# $Id: Makefile,v 1.1.1.1 2006-02-25 02:29:33 laffer1 Exp $
# $FreeBSD: src/usr.sbin/acpi/Makefile,v 1.3 2003/08/08 03:20:59 njl Exp $

SUBDIR= acpiconf acpidb acpidump iasl

.include <bsd.subdir.mk>
