# Makefile for acpi tools
# $Id: Makefile,v 1.1 2000/07/14 18:16:22 iwasaki Exp $
# $FreeBSD: release/10.0.0/usr.sbin/acpi/Makefile 118643 2003-08-08 03:20:59Z njl $

SUBDIR= acpiconf acpidb acpidump iasl

.include <bsd.subdir.mk>
