# $MidnightBSD$
# $FreeBSD: stable/10/sys/boot/userboot/libstand/Makefile 312403 2017-01-19 07:29:52Z delphij $

.include <bsd.own.mk>

LIBSTAND_SRC=	${.CURDIR}/../../../../lib/libstand

INTERNALLIB=
INCS=
MAN=
.PATH:	${LIBSTAND_SRC}

.include "${LIBSTAND_SRC}/Makefile"
