# $FreeBSD: release/10.0.0/tools/regression/usr.bin/Makefile 205147 2010-03-14 10:24:03Z edwin $

SUBDIR=	apply calendar comm file2c join jot m4 ncal printf sed tr	\
	uudecode uuencode xargs
.if !defined(AUTOMATED)
SUBDIR+= lastcomm
.endif

.include <bsd.subdir.mk>
