# $FreeBSD: release/7.0.0/tools/regression/usr.bin/Makefile 170231 2007-06-03 03:29:32Z grog $

SUBDIR=	calendar file2c join jot m4 printf sed uudecode uuencode xargs lastcomm

.include <bsd.subdir.mk>
