language: c

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo apt-get -qq update;
      sudo apt-get -qq install byacc flex;
    elif [ $TRAVIS_OS_NAME == "osx" ]; then
      brew update;
      brew install byacc flex;
    fi
