#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: release/7.0.0/share/doc/smm/11.timedop/Makefile 50476 1999-08-28 00:22:10Z peter $

VOLUME=	smm/11.timedop
SRCS=	timed.ms
MACROS=	-ms
SRCDIR=	${.CURDIR}/../../../../usr.sbin/timed/SMM.doc/timedop

.include <bsd.doc.mk>
