# $MidnightBSD$
#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: stable/10/games/primes/Makefile 276486 2014-12-31 23:25:37Z ngie $

PROG=	primes
SRCS=	pattern.c pr_tbl.c primes.c
MAN=
DPADD=	${LIBM}
LDADD=	-lm

.include <bsd.prog.mk>
