# $FreeBSD: stable/10/usr.bin/bmake/tests/syntax/Makefile 266074 2014-05-14 18:43:13Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/syntax

TESTS_SUBDIRS=	directive-t0 enl funny-targets semi

.include <bsd.test.mk>
