# $FreeBSD: stable/11/usr.bin/bmake/tests/syntax/Makefile 299094 2016-05-04 23:20:53Z ngie $

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/syntax

TESTS_SUBDIRS=	directive-t0 enl funny-targets semi

.include <bsd.test.mk>
