# $FreeBSD: stable/11/sys/modules/acpi/acpi_toshiba/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:	${SRCTOP}/sys/dev/acpi_support

KMOD=	acpi_toshiba
SRCS=	acpi_toshiba.c opt_acpi.h acpi_if.h bus_if.h device_if.h

.include <bsd.kmod.mk>
