#	From: @(#)Makefile	8.1 (Berkeley) 8/14/93
# $FreeBSD: release/7.0.0/share/doc/psd/12.make/Makefile 106143 2002-10-29 14:56:09Z ru $

VOLUME=	psd/12.make
SRCS=	stubs tutorial.ms
MACROS=	-ms
SRCDIR=	${.CURDIR}/../../../../usr.bin/make/PSD.doc

.include <bsd.doc.mk>
