#	$FreeBSD: stable/11/share/examples/kld/firmware/fwconsumer/Makefile 299293 2016-05-10 00:51:50Z gjb $

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/kld/fwconsumer
KMOD=	fw_consumer
SRCS=	fw_consumer.c

.include <bsd.kmod.mk>
