# $FreeBSD: release/10.0.0/share/i18n/esdb/Makefile.inc 219019 2011-02-25 00:04:39Z gabor $

.PATH: ${.CURDIR}

ESDBDIR?= /usr/share/i18n/esdb
MKESDB?= ${.OBJDIR}/../../../usr.bin/mkesdb_static/mkesdb_static
