#	@(#)Makefile	8.4 (Berkeley) 6/22/95
# $FreeBSD: release/7.0.0/usr.sbin/rpc.umntall/Makefile 121560 2003-10-26 06:14:10Z peter $

PROG=	rpc.umntall
MAN=	rpc.umntall.8
SRCS=	rpc.umntall.c mounttab.c

#WARNS?= 2

.include <bsd.prog.mk>
