#	@(#)Makefile	8.4 (Berkeley) 6/22/95
# $FreeBSD: release/10.0.0/usr.sbin/rpc.umntall/Makefile 201390 2010-01-02 11:07:44Z ed $

PROG=	rpc.umntall
MAN=	rpc.umntall.8
SRCS=	rpc.umntall.c mounttab.c

WARNS?= 3

.include <bsd.prog.mk>
