#	@(#)Makefile	8.1 (Berkeley) 6/5/93
#	$FreeBSD: stable/9/usr.sbin/rip6query/Makefile 201390 2010-01-02 11:07:44Z ed $

PROG=	rip6query
MAN=	rip6query.8

CFLAGS+= -I${.CURDIR}/../route6d

.include <bsd.prog.mk>
