#	@(#)Makefile	8.1 (Berkeley) 6/5/93
#	$FreeBSD: stable/11/usr.sbin/rip6query/Makefile 319119 2017-05-29 10:15:41Z ngie $

PROG=	rip6query
MAN=	rip6query.8

CFLAGS+= -I${.CURDIR:H}/route6d

.include <bsd.prog.mk>
