#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: release/7.0.0/share/doc/smm/12.timed/Makefile 136910 2004-10-24 15:33:08Z ru $

VOLUME=		smm/12.timed
SRCS=		timed.ms
EXTRA=		date loop time unused
MACROS=		-ms
USE_SOELIM=
USE_TBL=
SRCDIR=		${.CURDIR}/../../../../usr.sbin/timed/SMM.doc/timed

.include <bsd.doc.mk>
