# $FreeBSD: release/7.0.0/sys/modules/ufoma/Makefile 154141 2006-01-09 17:46:36Z takawata $

.PATH: ${.CURDIR}/../../dev/usb

KMOD=	ufoma
SRCS=	bus_if.h device_if.h opt_usb.h ufoma.c usbdevs.h

.include <bsd.kmod.mk>
