# $FreeBSD: release/10.0.0/sys/modules/nfs_common/Makefile 203968 2010-02-16 20:00:21Z marius $

.PATH: ${.CURDIR}/../../nfs

KMOD=	nfs_common
SRCS=	nfs_common.c opt_nfs.h vnode_if.h

.include <bsd.kmod.mk>
