# $FreeBSD: stable/9/lib/clang/libclangdriver/Makefile 246637 2013-02-10 21:24:47Z dim $

.include <bsd.own.mk>

LIB=	clangdriver

SRCDIR=	tools/clang/lib/Driver
SRCS=	Action.cpp \
	Arg.cpp \
	ArgList.cpp \
	CC1AsOptions.cpp \
	Compilation.cpp \
	Driver.cpp \
	DriverOptions.cpp \
	Job.cpp \
	OptTable.cpp \
	Option.cpp \
	Phases.cpp \
	Tool.cpp \
	ToolChain.cpp \
	ToolChains.cpp \
	Tools.cpp \
	Types.cpp \
	WindowsToolChain.cpp

TGHDRS=	CC1AsOptions \
	DiagnosticCommonKinds \
	DiagnosticDriverKinds \
	Options

.include "../clang.lib.mk"
