# $MidngithBSD$
# $FreeBSD: src/usr.sbin/bsdinstall/distextract/Makefile,v 1.1 2011/02/18 14:54:34 nwhitehorn Exp $

BINDIR= /usr/libexec/bsdinstall
PROG=	distextract
LDADD=	-larchive -lncursesw -ldialog -lm

WARNS?=	6
NO_MAN=	true

.include <bsd.prog.mk>
