# $FreeBSD: stable/9/usr.sbin/bsdinstall/distextract/Makefile 218799 2011-02-18 14:54:34Z nwhitehorn $

BINDIR= /usr/libexec/bsdinstall
PROG=	distextract
LDADD=	-larchive -lncursesw -ldialog -lm

WARNS?=	6
NO_MAN=	true

.include <bsd.prog.mk>
