# $FreeBSD: release/10.0.0/sys/modules/mmc/Makefile 163519 2006-10-20 06:52:59Z imp $

.PATH: ${.CURDIR}/../../dev/mmc

KMOD=	mmc
SRCS=	mmc.c mmcbr_if.h mmcbus_if.h device_if.h bus_if.h

.include <bsd.kmod.mk>
