# $FreeBSD: stable/11/sys/modules/mmc/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/mmc

KMOD=	mmc
SRCS=	bus_if.h device_if.h mmc_subr.c mmc.c mmcbr_if.h mmcbus_if.h

.include <bsd.kmod.mk>
