# $MidnightBSD$
# $FreeBSD: stable/10/sys/modules/mmc/Makefile 318198 2017-05-11 21:01:02Z marius $

.PATH: ${.CURDIR}/../../dev/mmc

KMOD=	mmc
SRCS=	bus_if.h device_if.h mmc_subr.c mmc.c mmcbr_if.h mmcbus_if.h

.include <bsd.kmod.mk>
