# $FreeBSD: release/10.0.0/lib/clang/liblldbPluginObjectFileELF/Makefile 255722 2013-09-20 01:52:02Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginObjectFileELF

SRCDIR=	tools/lldb/source/Plugins/ObjectFile/ELF
SRCS=	ELFHeader.cpp \
	ObjectFileELF.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
