#	From: @(#)Makefile	1.8 (Berkeley) 6/8/93
# $FreeBSD: release/10.0.0/share/doc/papers/kernmalloc/Makefile 217893 2011-01-26 19:39:31Z uqs $

VOLUME=		papers
DOC=		kernmalloc
SRCS=		kernmalloc.t appendix.ms
EXTRA=		alloc.fig usage.tbl
MACROS=		-ms
USE_EQN=
USE_PIC=
USE_SOELIM=
USE_TBL=

.include <bsd.doc.mk>
