# $FreeBSD: release/7.0.0/share/doc/psd/24.xdr/Makefile 136910 2004-10-24 15:33:08Z ru $

VOLUME=		psd/24.xdr
SRCS=		stubs xdr.nts.ms
MACROS=		-ms
USE_EQN=
SRCDIR=		${.CURDIR}/../../../../lib/libc/rpc/PSD.doc

.include <bsd.doc.mk>
