# $FreeBSD: stable/11/sys/modules/netgraph/vjc/Makefile 319182 2017-05-30 04:11:12Z ngie $
# $Whistle: Makefile,v 1.1 1999/01/24 06:48:07 archie Exp $

.PATH: ${SRCTOP}/sys/net

KMOD=	ng_vjc
SRCS= 	ng_vjc.c slcompress.c

.include <bsd.kmod.mk>
