# $FreeBSD: release/10.0.0/lib/clang/libllvmjit/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvmjit

SRCDIR=	lib/ExecutionEngine/JIT
SRCS=	JIT.cpp \
	JITDwarfEmitter.cpp \
	JITEmitter.cpp \
	JITMemoryManager.cpp

.include "../clang.lib.mk"
