# $MidnightBSD$
# $FreeBSD: stable/10/lib/clang/libllvmjit/Makefile 263508 2014-03-21 17:53:59Z dim $

.include <bsd.own.mk>

LIB=	llvmjit

SRCDIR=	lib/ExecutionEngine/JIT
SRCS=	JIT.cpp \
	JITEmitter.cpp \
	JITMemoryManager.cpp

.include "../clang.lib.mk"
