# $FreeBSD: stable/11/sys/modules/ata/atapci/chipsets/ataintel/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/ata/chipsets

KMOD=	ataintel
SRCS=	ata-intel.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
