# $FreeBSD: stable/11/sys/modules/geom/geom_raid3/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/geom/raid3

KMOD=	geom_raid3
SRCS=	g_raid3.c
SRCS+=	g_raid3_ctl.c

.include <bsd.kmod.mk>
