# $FreeBSD: release/10.0.0/sys/modules/geom/geom_raid3/Makefile 133808 2004-08-16 06:23:14Z pjd $

.PATH: ${.CURDIR}/../../../geom/raid3

KMOD=	geom_raid3
SRCS=	g_raid3.c
SRCS+=	g_raid3_ctl.c

.include <bsd.kmod.mk>
