# $MidnightBSD$
# $FreeBSD: stable/10/tools/tools/npe/npestats/Makefile 276486 2014-12-31 23:25:37Z ngie $

PROG=	npestats
SRCS=	main.c statfoo.c npestats.c
BINDIR=	/usr/local/bin
MAN=

.include <bsd.prog.mk>
