# $FreeBSD: release/10.0.0/tools/tools/npe/npestats/Makefile 192661 2009-05-23 19:16:34Z sam $

PROG=	npestats
SRCS=	main.c statfoo.c npestats.c
BINDIR=	/usr/local/bin
NO_MAN=	true

.include <bsd.prog.mk>
