# $FreeBSD: stable/11/usr.bin/ofed/infiniband-diags/ibnetdiscover/Makefile 335253 2018-06-16 15:05:05Z kib $

PROG=	ibnetdiscover
SRCS=	ibnetdiscover.c
LIBADD=	ibnetdisc
MAN=	ibnetdiscover.8

.include <bsd.prog.mk>
