# $FreeBSD: release/10.0.0/sys/modules/geom/geom_mountver/Makefile 202437 2010-01-16 09:52:49Z trasz $

.PATH: ${.CURDIR}/../../../geom/mountver

KMOD=	geom_mountver
SRCS=	g_mountver.c

.include <bsd.kmod.mk>
