# $FreeBSD: stable/11/usr.bin/bmake/tests/syntax/semi/Makefile.test 263346 2014-03-19 12:29:20Z jmmv $
#
# Test handling of escaped newlines.
#

.ifmake test1

FOO=
BAR=bar
FOO != echo ${FOO} ; echo ${BAR}

test1:
	echo ${FOO}

.endif

.ifmake test2

FOO=foo
BAR=bar
FOO != echo ${FOO} ; echo ${BAR}

test2:
	echo ${FOO}

.endif
