# $FreeBSD: release/10.0.0/tools/tools/ath/ath_ee_9287_print/Makefile 222322 2011-05-26 19:49:32Z adrian $

.PATH:  ${.CURDIR}/../../../../sys/dev/ath/ath_hal

PROG=	ath_ee_9287_print
SRCS=	main.c eeprom.c 9287.c
NOMAN=	yes
NO_MAN=	yes

.include <../Makefile.inc>

.include <bsd.prog.mk>
