# $FreeBSD: release/10.0.0/usr.sbin/sysrc/Makefile 246546 2013-02-08 11:14:01Z dteske $

SCRIPTS= sysrc

MAN= sysrc.8

beforeinstall:
	mkdir -p ${DESTDIR}${SCRIPTSDIR}
	mkdir -p ${DESTDIR}${MANDIR}8

.include <bsd.prog.mk>
