# $MidnightBSD: src/usr.sbin/sensorsd/Makefile,v 1.1 2009/11/28 22:44:36 laffer1 Exp $
#	$OpenBSD: Makefile,v 1.1 2003/09/24 20:32:49 henning Exp $

PROG=	sensorsd
MAN=	sensorsd.8 sensorsd.conf.5

WARNS?=	0

.include <bsd.prog.mk>
