# $FreeBSD: stable/11/lib/libcapsicum/Makefile 331434 2018-03-23 16:15:07Z ian $

PACKAGE=lib${LIB}

INCS=	capsicum_helpers.h

MAN+=	capsicum_helpers.3

MLINKS+=capsicum_helpers.3 caph_limit_stream.3
MLINKS+=capsicum_helpers.3 caph_limit_stdin.3
MLINKS+=capsicum_helpers.3 caph_limit_stderr.3
MLINKS+=capsicum_helpers.3 caph_limit_stdout.3
MLINKS+=capsicum_helpers.3 caph_limit_stdio.3
MLINKS+=capsicum_helpers.3 caph_cache_tzdata.3
MLINKS+=capsicum_helpers.3 caph_cache_catpages.3

.include <bsd.lib.mk>
