# $FreeBSD: stable/11/usr.bin/soelim/tests/Makefile 316256 2017-03-30 06:20:24Z ngie $

PACKAGE=	tests

ATF_TESTS_SH=	soelim_test

${PACKAGE}FILES+=		nonexisting.in \
		basic.in \
		basic \
		basic.out \
		basic-with-space.in \
		basic-with-space.out

.include <bsd.test.mk>
