# $FreeBSD: stable/11/sys/modules/dtb/rpi/Makefile 326951 2017-12-18 20:17:54Z manu $
# DTS files for the Raspberry Pi-B
DTS=rpi.dts rpi2.dts

LINKS= \
	${DTBDIR}/rpi.dtb ${DTBDIR}/bcm2835-rpi-b.dtb \
	${DTBDIR}/rpi.dtb ${DTBDIR}/bcm2835-rpi-b-rev2.dtb \
	${DTBDIR}/rpi.dtb ${DTBDIR}/bcm2835-rpi-b-plus.dtb \
	${DTBDIR}/rpi.dtb ${DTBDIR}/bcm2835-rpi-zero.dtb \
	${DTBDIR}/rpi2.dtb ${DTBDIR}/bcm2836-rpi-2-b.dtb

.include <bsd.dtb.mk>
