#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: release/7.0.0/share/doc/psd/05.sysman/Makefile 172506 2007-10-10 16:59:15Z cvs2svn $

VOLUME=		psd/05.sysman
SRCS=		0.t 1.0.t 1.1.t 1.2.t 1.3.t 1.4.t 1.5.t 1.6.t 1.7.t \
		2.0.t 2.1.t 2.2.t 2.3.t 2.4.t 2.5.t a.t
MACROS=		-ms
USE_TBL=

.include <bsd.doc.mk>
