# $Id: Makefile,v 1.1.1.1 2006-02-25 02:29:04 laffer1 Exp $
# $FreeBSD: src/usr.bin/bluetooth/bthost/Makefile,v 1.2 2005/01/28 16:08:06 ru Exp $

PROG=		bthost
WARNS?=		2

DPADD=		${LIBBLUETOOTH}
LDADD=		-lbluetooth 

.include <bsd.prog.mk>
