# $Id: Makefile,v 1.4 2003/08/14 20:07:13 max Exp $
# $FreeBSD: release/7.0.0/usr.bin/bluetooth/bthost/Makefile 140941 2005-01-28 16:08:11Z ru $

PROG=		bthost
WARNS?=		2

DPADD=		${LIBBLUETOOTH}
LDADD=		-lbluetooth 

.include <bsd.prog.mk>
