#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/9/usr.bin/gcore/Makefile 204329 2010-02-25 20:24:19Z ru $

PROG=	gcore
SRCS=	elfcore.c gcore.c
DPADD=	${LIBUTIL}
LDADD=	-lutil

WARNS?=	1

.include <bsd.prog.mk>
