# $FreeBSD: stable/11/sys/compat/cloudabi32/Makefile 357108 2020-01-25 05:47:56Z kevans $

SYSENT_FILE=	${SYSDIR}/contrib/cloudabi/syscalls32.master
GENERATED_PREFIX=	cloudabi32_

.include "../../conf/sysent.mk"
