# $FreeBSD: stable/11/usr.bin/ofed/infiniband-diags/ibcacheedit/Makefile 335253 2018-06-16 15:05:05Z kib $

PROG=	ibcacheedit
SRCS=	ibcacheedit.c
LIBADD=	ibnetdisc
MAN=	ibcacheedit.8

.include <bsd.prog.mk>
