# $FreeBSD: release/7.0.0/sys/modules/netgraph/netflow/Makefile 135335 2004-09-16 20:35:28Z glebius $
#
# Author: Gleb Smirnoff <glebius@freebsd.org>
#

.PATH: ${.CURDIR}/../../../netgraph/netflow

KMOD=   ng_netflow
SRCS=   ng_netflow.c netflow.c

.include <bsd.kmod.mk>
