#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: release/7.0.0/share/doc/usd/07.mail/Makefile 136910 2004-10-24 15:33:08Z ru $

VOLUME=		usd/07.mail
SRCS=		mail0.nr mail1.nr mail2.nr mail3.nr mail4.nr mail5.nr mail6.nr \
		mail7.nr mail8.nr mail9.nr maila.nr
MACROS=		-me
USE_TBL=
SRCDIR=		${.CURDIR}/../../../../usr.bin/mail/USD.doc

.include <bsd.doc.mk>
