# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# <phk@FreeBSD.org> wrote this file.  As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return.   Poul-Henning Kamp
# ----------------------------------------------------------------------------
#
# $FreeBSD: release/7.0.0/usr.sbin/fdwrite/Makefile 139905 2005-01-08 15:46:06Z delphij $

PROG=	fdwrite
WARNS?=	6

.include <bsd.prog.mk>
