# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# <phk@FreeBSD.org> wrote this file.  As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return.   Poul-Henning Kamp
# ----------------------------------------------------------------------------
#
# $FreeBSD: release/10.0.0/usr.sbin/fdwrite/Makefile 201390 2010-01-02 11:07:44Z ed $

PROG=	fdwrite

.include <bsd.prog.mk>
