# $FreeBSD: stable/11/sys/modules/dtb/nvidia/Makefile 306460 2016-09-29 22:01:09Z gonzo $
# All the dts files for Nvidia ARM systems we support.
DTS=	\
	tegra124-jetson-tk1-fbsd.dts

.include <bsd.dtb.mk>
