# $FreeBSD: release/10.0.0/sys/modules/mac_partition/Makefile 105841 2002-10-24 02:04:03Z rwatson $

.PATH: ${.CURDIR}/../../security/mac_partition

KMOD=	mac_partition
SRCS=	vnode_if.h \
	mac_partition.c

.include <bsd.kmod.mk>
