# $FreeBSD: stable/11/sys/modules/digi/digi_EPCX_PCI/Makefile 76195 2001-05-02 01:08:09Z brian $

.PATH:	${.CURDIR}/../../../dev/digi
KMOD=	digi_EPCX_PCI
SRCS=	EPCX_PCI.c EPCX_PCI.bios.h EPCX_PCI.fepos.h digi_mod.h

.include <bsd.kmod.mk>
