# $FreeBSD: stable/11/gnu/usr.bin/binutils/doc/Makefile 279529 2015-03-02 17:24:04Z bapt $

.include "../Makefile.inc0"

.PATH: ${SRCDIR}/gas/doc \
	${SRCDIR}/ld \
	${SRCDIR}/binutils/doc

MAN=	ld.7 ldint.7 as.7 binutils.7

.include <bsd.prog.mk>
