#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: release/10.0.0/sbin/shutdown/Makefile 216823 2010-12-30 18:06:31Z pjd $

PROG=	shutdown
MAN=	shutdown.8
LINKS=	${BINDIR}/shutdown ${BINDIR}/poweroff
MLINKS=	shutdown.8 poweroff.8

BINOWN=	root
BINGRP=	operator
BINMODE=4550

.include <bsd.prog.mk>
