#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: stable/11/sbin/shutdown/Makefile 298107 2016-04-16 07:45:30Z gjb $

PACKAGE=runtime
PROG=	shutdown
MAN=	shutdown.8
LINKS=	${BINDIR}/shutdown ${BINDIR}/poweroff
MLINKS=	shutdown.8 poweroff.8

BINOWN=	root
BINGRP=	operator
BINMODE=4554

.include <bsd.prog.mk>
