#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: release/7.0.0/sbin/shutdown/Makefile 140796 2005-01-25 08:37:04Z delphij $

PROG=	shutdown
MAN=	shutdown.8

WARNS?=	6

BINOWN=	root
BINGRP=	operator
BINMODE=4550

.include <bsd.prog.mk>
