# $FreeBSD: stable/11/usr.sbin/bluetooth/ath3kfw/Makefile 301537 2016-06-07 04:22:18Z adrian $

PROG=		ath3kfw
MAN=		ath3kfw.8
LIBADD+=	usb
SRCS=		main.c ath3k_fw.c ath3k_hw.c

.include <bsd.prog.mk>
