# $FreeBSD: stable/10/usr.bin/bmake/tests/suffixes/Makefile 266074 2014-05-14 18:43:13Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/suffixes

TESTS_SUBDIRS=	basic src_wild1 src_wild2

.include <bsd.test.mk>
