# $FreeBSD: stable/11/usr.bin/bmake/tests/suffixes/Makefile 299094 2016-05-04 23:20:53Z ngie $

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/suffixes

TESTS_SUBDIRS=	basic src_wild1 src_wild2

.include <bsd.test.mk>
