# $FreeBSD: stable/9/release/doc/ja_JP.eucJP/Makefile 147696 2005-06-30 12:54:30Z rushani $
# Original revision: 1.7

RELN_ROOT?= ${.CURDIR}/..

SUBDIR = relnotes
SUBDIR+= hardware
#SUBDIR+= readme
SUBDIR+= errata
#SUBDIR+= installation

COMPAT_SYMLINK = ja

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
