# $FreeBSD: stable/11/usr.bin/bmake/tests/syntax/enl/Makefile 299094 2016-05-04 23:20:53Z ngie $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/syntax/enl

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		Makefile.test
${PACKAGE}FILES+=		expected.status.1
${PACKAGE}FILES+=		expected.status.2
${PACKAGE}FILES+=		expected.status.3
${PACKAGE}FILES+=		expected.status.4
${PACKAGE}FILES+=		expected.status.5
${PACKAGE}FILES+=		expected.stderr.1
${PACKAGE}FILES+=		expected.stderr.2
${PACKAGE}FILES+=		expected.stderr.3
${PACKAGE}FILES+=		expected.stderr.4
${PACKAGE}FILES+=		expected.stderr.5
${PACKAGE}FILES+=		expected.stdout.1
${PACKAGE}FILES+=		expected.stdout.2
${PACKAGE}FILES+=		expected.stdout.3
${PACKAGE}FILES+=		expected.stdout.4
${PACKAGE}FILES+=		expected.stdout.5

.include <bsd.test.mk>
