# $FreeBSD: release/10.0.0/lib/libiconv_modules/mapper_zone/Makefile 219019 2011-02-25 00:04:39Z gabor $

SHLIB=	mapper_zone
SRCS+=	citrus_mapper_zone.c
CFLAGS+= --param max-inline-insns-single=8

.include <bsd.lib.mk>
