# $MidnightBSD$
# $FreeBSD: stable/10/lib/libiconv_modules/mapper_zone/Makefile 260497 2014-01-09 23:08:56Z dim $

SHLIB=	mapper_zone
SRCS+=	citrus_mapper_zone.c
CFLAGS.gcc+= --param max-inline-insns-single=8

.include <bsd.lib.mk>
