# $FreeBSD: stable/11/usr.bin/ofed/libibverbs/rc_pingpong/Makefile 335253 2018-06-16 15:05:05Z kib $

PROG=	ibv_rc_pingpong
MAN=	ibv_rc_pingpong.1
SRCS=	rc_pingpong.c pingpong.c

.include <bsd.prog.mk>
