# $FreeBSD: stable/11/sys/modules/ata/atapci/chipsets/atamicron/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/ata/chipsets

KMOD=	atamicron
SRCS=	ata-micron.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
