SUBDIR=	mport.check-fake \
	mport.check-for-older \
	mport.delete \
	mport.info \
	mport.install \
	mport.merge \
	mport.update \
	mport.version_cmp \
	mport.check-fake \
	mport.create \
	mport.fetch \
	mport.init \
	mport.list \
	mport.query \
	mport.updepends

.include <bsd.subdir.mk>
