# $MidnightBSD: src/sbin/adjkerntz/Makefile,v 1.2 2007/01/02 06:59:59 laffer1 Exp $
# $FreeBSD: src/sbin/adjkerntz/Makefile,v 1.6 2001/12/04 02:19:43 obrien Exp $

PROG=   adjkerntz
MAN=	adjkerntz.8

.include <bsd.prog.mk>
