# $FreeBSD: release/10.0.0/tools/tools/net80211/wesside/wesside/Makefile 168502 2007-04-08 21:18:15Z sam $

PROG=	wesside
BINDIR=	/usr/local/bin
DPADD=	${LIBZ}
LDADD=	-lz
CFLAGS=-g
NO_MAN=
SRCS=wesside.c aircrack-ptw-lib.c

.include <bsd.prog.mk>
