# $FreeBSD: stable/11/sys/modules/geom/geom_sched/gs_sched/Makefile 275947 2014-12-20 00:04:01Z imp $
KMOD=   geom_sched
SRCS=   g_sched.c

# ../Makefile.inc automatically included
.include <bsd.kmod.mk>
