# $FreeBSD: release/10.0.0/sys/modules/geom/geom_sched/gs_sched/Makefile 206497 2010-04-12 16:37:45Z luigi $
KMOD=   geom_sched
SRCS=   g_sched.c subr_disk.c

# ../Makefile.inc automatically included
.include <bsd.kmod.mk>
