# $OpenBSD: Makefile,v 1.1 2004/04/26 19:51:20 markus Exp $
# $FreeBSD: release/7.0.0/usr.sbin/tcpdrop/Makefile 141381 2005-02-06 10:47:12Z maxim $

PROG=	tcpdrop
MAN=	tcpdrop.8
WARNS?=	6

.include <bsd.prog.mk>
