# $OpenBSD: Makefile,v 1.1 2004/04/26 19:51:20 markus Exp $
# $FreeBSD: release/10.0.0/usr.sbin/tcpdrop/Makefile 201390 2010-01-02 11:07:44Z ed $

PROG=	tcpdrop
MAN=	tcpdrop.8

.include <bsd.prog.mk>
