
# $FreeBSD: release/10.0.0/sys/modules/ppi/Makefile 122894 2003-11-19 05:08:27Z imp $

.PATH:	${.CURDIR}/../../dev/ppbus
KMOD=	ppi
SRCS=	bus_if.h device_if.h ppbus_if.h \
	opt_ppb_1284.h \
	ppi.c ppb_1284.c

.include <bsd.kmod.mk>
