# $MidnightBSD$
# $FreeBSD: stable/10/tests/sys/pjdfstest/tests/granular/Makefile 274016 2014-11-03 07:18:42Z ngie $

TAP_TESTS_SH=	00
TAP_TESTS_SH+=	01
TAP_TESTS_SH+=	02
TAP_TESTS_SH+=	03
TAP_TESTS_SH+=	04
TAP_TESTS_SH+=	05

.include "../pjdfstest.test.mk"
