# $FreeBSD: stable/11/tests/sys/pjdfstest/tests/granular/Makefile 299094 2016-05-04 23:20:53Z ngie $

TAP_TESTS_SH=	00
TAP_TESTS_SH+=	01
TAP_TESTS_SH+=	02
TAP_TESTS_SH+=	03
TAP_TESTS_SH+=	04
TAP_TESTS_SH+=	05

.include "../pjdfstest.test.mk"
