# 	This file is under a "BSD" copyright (c) by David O'Brien 1998.

# $FreeBSD: release/10.0.0/usr.sbin/amd/doc/Makefile 80029 2001-07-20 06:20:32Z obrien $

.PATH: ${.CURDIR}/../../../contrib/amd/doc

INFO=	am-utils

INFOSECTION=	"AMD Documentation"
INFOENTRY= 	"* Am-utils: (am-utils).	The Amd automounter suite of utilities"

MAKEINFOFLAGS+=	-I ${.CURDIR}/../../../contrib/amd/doc

.include <bsd.info.mk>
