# $FreeBSD: stable/11/sbin/geom/class/multipath/Makefile 319185 2017-05-30 04:17:22Z ngie $

PACKAGE=runtime
.PATH: ${.CURDIR:H:H}/misc

GEOM_CLASS=	multipath

CFLAGS+=  -I${SRCTOP}/sys

.include <bsd.lib.mk>
