# $FreeBSD: release/7.0.0/sbin/geom/class/multipath/Makefile 167056 2007-02-27 07:29:15Z mjacob $

.PATH: ${.CURDIR}/../../misc
CLASS=	multipath

.include <bsd.lib.mk>

CFLAGS+=  -I${.CURDIR}/../../../../sys
