# $FreeBSD: stable/11/gnu/usr.bin/groff/src/utils/hpftodit/Makefile 291738 2015-12-04 03:17:47Z bdrewery $

PROG_CXX=	hpftodit
SRCS=		hpftodit.cpp hpuni.cpp
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
LIBADD=		m
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
