# $MidnightBSD$
# $FreeBSD: stable/10/usr.bin/join/Makefile 264996 2014-04-27 01:15:10Z jmmv $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

.include <bsd.own.mk>

PROG=	join

.if ${MK_TESTS} != "no"
SUBDIR+= tests
.endif

.include <bsd.prog.mk>
