# $MidnightBSD$
# $FreeBSD: stable/10/sys/modules/geom/geom_part/Makefile 268091 2014-07-01 13:29:17Z ae $

SUBDIR=	geom_part_apm \
	geom_part_bsd \
	geom_part_bsd64 \
	geom_part_ebr \
	geom_part_gpt \
	geom_part_ldm \
	geom_part_mbr \
	geom_part_pc98 \
	geom_part_vtoc8

.include <bsd.subdir.mk>
