# $MidnightBSD: src/sys/modules/geom/geom_part/Makefile,v 1.1 2011/07/13 01:09:48 laffer1 Exp $
# $FreeBSD: src/sys/modules/geom/geom_part/Makefile,v 1.3.2.1.2.1 2008/11/25 02:59:29 kensmith Exp $

SUBDIR=	geom_part_apm \
	geom_part_bsd \
	geom_part_gpt \
	geom_part_mbr \
	geom_part_vtoc8

.include <bsd.subdir.mk>
