# $FreeBSD: stable/9/sys/modules/geom/geom_part/Makefile 234406 2012-04-18 04:59:47Z ae $

SUBDIR=	geom_part_apm \
	geom_part_bsd \
	geom_part_ebr \
	geom_part_gpt \
	geom_part_ldm \
	geom_part_mbr \
	geom_part_pc98 \
	geom_part_vtoc8

.include <bsd.subdir.mk>
