# $FreeBSD: stable/11/sbin/geom/class/virstor/Makefile 319185 2017-05-30 04:17:22Z ngie $

PACKAGE=runtime
.PATH: ${.CURDIR:H:H}/misc ${SRCTOP}/sys/geom/virstor

GEOM_CLASS=	virstor

SRCS+=	binstream.c
SRCS+=	g_virstor_md.c

.include <bsd.lib.mk>
