# $FreeBSD: release/10.0.0/lib/clang/liblldbPluginUnwindAssemblyX86/Makefile 255722 2013-09-20 01:52:02Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginUnwindAssemblyX86

SRCDIR=	tools/lldb/source/Plugins/UnwindAssembly/x86
SRCS=	UnwindAssembly-x86.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
