# $FreeBSD: release/10.0.0/kerberos5/libexec/Makefile 233294 2012-03-22 08:48:42Z stas $

SUBDIR=	digest-service ipropd-master ipropd-slave hprop hpropd kadmind kdc \
	kdigest kfd kimpersonate kpasswdd kcm

.include <bsd.subdir.mk>
