# $Id: Makefile,v 1.1 2003/09/08 02:27:27 max Exp $
# $FreeBSD: stable/11/usr.sbin/bluetooth/sdpcontrol/Makefile 275054 2014-11-25 16:57:27Z bapt $

PROG=		sdpcontrol
MAN=		sdpcontrol.8
SRCS=		sdpcontrol.c search.c
WARNS?=		2

LIBADD=		bluetooth sdp

.include <bsd.prog.mk>
