#$FreeBSD: stable/11/sys/modules/mxge/mxge/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/mxge

KMOD=	if_mxge
SRCS=	if_mxge.c device_if.h bus_if.h pci_if.h opt_inet.h opt_inet6.h

.include <bsd.kmod.mk>
