#$FreeBSD: release/10.0.0/sys/modules/mxge/mxge/Makefile 247133 2013-02-21 21:28:33Z gallatin $

.PATH: ${.CURDIR}/../../../dev/mxge

KMOD=	if_mxge
SRCS=	if_mxge.c device_if.h bus_if.h pci_if.h opt_inet.h opt_inet6.h

.include <bsd.kmod.mk>
