#$FreeBSD: stable/9/sys/modules/mxge/mxge/Makefile 247472 2013-02-28 16:38:28Z gallatin $

.PATH: ${.CURDIR}/../../../dev/mxge

KMOD=	if_mxge
SRCS=	if_mxge.c device_if.h bus_if.h pci_if.h opt_inet.h opt_inet6.h

.include <bsd.kmod.mk>
