/*
 * MD header for contrib/gdtoa
 *
 * This file can be generated by compiling and running contrib/gdtoa/qnan.c
 * on the target architecture after arith.h has been generated.
 *
 * $FreeBSD: release/10.0.0/lib/libc/sparc64/gd_qnan.h 174680 2007-12-16 21:15:09Z das $
 */

#define f_QNAN 0x7fc00000
#define d_QNAN0 0x7ff80000
#define d_QNAN1 0x00000000
#define ld_QNAN0 0x7fff8000
#define ld_QNAN1 0x00000000
#define ld_QNAN2 0x00000000
#define ld_QNAN3 0x00000000
#define ldus_QNAN0 0x7fff
#define ldus_QNAN1 0x8000
#define ldus_QNAN2 0x0000
#define ldus_QNAN3 0x0000
#define ldus_QNAN4 0x0000
