/*
 * MD header for contrib/gdtoa
 *
 * This file can be generated by compiling and running contrib/gdtoa/qnan.c
 * on the target architecture after arith.h has been generated.
 *
 * $FreeBSD: release/7.0.0/lib/libc/sparc64/gd_qnan.h 165747 2007-01-03 05:00:03Z das $
 */

#define f_QNAN 0x7fffffff
#define d_QNAN0 0x7fffffff
#define d_QNAN1 0xffffffff
#define ld_QNAN0 0x7fffffff
#define ld_QNAN1 0xffffffff
#define ld_QNAN2 0xffffffff
#define ld_QNAN3 0xffffffff
#define ldus_QNAN0 0x7fff
#define ldus_QNAN1 0xffff
#define ldus_QNAN2 0xffff
#define ldus_QNAN3 0xffff
#define ldus_QNAN4 0xffff
