# $FreeBSD: stable/11/sys/modules/coretemp/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/coretemp

KMOD=	coretemp
SRCS=	coretemp.c bus_if.h device_if.h

.include <bsd.kmod.mk>
