# $FreeBSD: stable/9/sys/modules/coretemp/Makefile 171854 2007-08-15 19:26:03Z des $

.PATH: ${.CURDIR}/../../dev/coretemp

KMOD=	coretemp
SRCS=	coretemp.c bus_if.h device_if.h

.include <bsd.kmod.mk>
