# $FreeBSD: release/10.0.0/sys/modules/ale/Makefile 184870 2008-11-12 09:52:06Z yongari $

.PATH: ${.CURDIR}/../../dev/ale

KMOD=	if_ale
SRCS=	if_ale.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
