# $FreeBSD: stable/11/usr.sbin/nghook/Makefile 275054 2014-11-25 16:57:27Z bapt $
# $Whistle: Makefile,v 1.4 1999/01/16 04:44:33 archie Exp $

PROG=	nghook
MAN=	nghook.8
SRCS=	main.c

LIBADD=	netgraph

.include <bsd.prog.mk>
