# $FreeBSD: release/10.0.0/usr.sbin/nghook/Makefile 201390 2010-01-02 11:07:44Z ed $
# $Whistle: Makefile,v 1.4 1999/01/16 04:44:33 archie Exp $

PROG=	nghook
MAN=	nghook.8
SRCS=	main.c

DPADD=	${LIBNETGRAPH}
LDADD=	-lnetgraph

.include <bsd.prog.mk>
