# $FreeBSD: stable/10/lib/libkse/test/sigsuspend_d.exp 172491 2007-10-09 13:42:34Z obrien $
  -> Suspender thread signal handler caught signal 16
Sigsuspend woke up by signal 16
  -> Suspender thread signal handler caught signal 16
Sigsuspend woke up by signal 16
  -> Suspender thread signal handler caught signal 31
Sigsuspend woke up by signal 31
  -> Suspender thread signal handler caught signal 31
Sigsuspend woke up by signal 31
