# $MidnightBSD$
# $FreeBSD: stable/10/sys/modules/syscons/plasma/Makefile 293034 2016-01-01 04:04:40Z des $

.PATH:	${.CURDIR}/../../../dev/syscons/plasma

KMOD=	plasma_saver
SRCS=	fp16.c plasma_saver.c

.include <bsd.kmod.mk>
