# $FreeBSD: stable/11/sys/modules/syscons/plasma/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:	${SRCTOP}/sys/dev/syscons/plasma

KMOD=	plasma_saver
SRCS=	fp16.c plasma_saver.c

.include <bsd.kmod.mk>
