#	@(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: release/10.0.0/share/doc/smm/06.nfs/Makefile 50476 1999-08-28 00:22:10Z peter $

VOLUME=	smm/06.nfs
SRCS=	0.t 1.t 2.t ref.t
MACROS=	-me

.include <bsd.doc.mk>
