#
# $FreeBSD: release/10.0.0/tools/regression/netinet/tcpsockclosebeforeaccept/Makefile 160202 2006-07-09 11:51:14Z maxim $
#

PROG=	tcpsockclosebeforeaccept
NO_MAN=
WARNS?=	3

.include <bsd.prog.mk>
