# $MidnightBSD$
# $FreeBSD: stable/10/usr.sbin/acpi/acpidump/Makefile 281075 2015-04-04 10:17:51Z dim $

PROG=	acpidump
MAN=	acpidump.8
SRCS=	acpi.c acpi_user.c acpidump.c
WARNS?=	3

.include <bsd.prog.mk>
