# $FreeBSD: stable/11/usr.bin/uudecode/tests/Makefile 299094 2016-05-04 23:20:53Z ngie $

PACKAGE=	tests

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		regress.base64.in
${PACKAGE}FILES+=		regress.out
${PACKAGE}FILES+=		regress.sh
${PACKAGE}FILES+=		regress.traditional.in

.include <bsd.test.mk>
