# $MidnightBSD$
# $FreeBSD: stable/10/usr.bin/uudecode/tests/Makefile 313488 2017-02-09 22:49:48Z ngie $

TAP_TESTS_SH=	legacy_test

FILESDIR=	${TESTSDIR}
FILES=		regress.base64.in
FILES+=		regress.out
FILES+=		regress.sh
FILES+=		regress.traditional.in

.include <bsd.test.mk>
