# $FreeBSD: stable/11/share/examples/libvgl/Makefile 299293 2016-05-10 00:51:50Z gjb $

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/libvgl
PROG=	demo
MAN=
DPADD=	${LIBVGL}
LDADD=	-lvgl

.include <bsd.prog.mk>
