# $FreeBSD: release/10.0.0/usr.bin/bzip2recover/Makefile 249657 2013-04-19 19:45:00Z ed $

BZ2DIR=	${.CURDIR}/../../contrib/bzip2
.PATH: ${BZ2DIR}

PROG=	bzip2recover
NO_MAN=

NO_WMISSING_VARIABLE_DECLARATIONS=

.include <bsd.prog.mk>
