# $FreeBSD: stable/11/usr.bin/bzip2recover/Makefile 319186 2017-05-30 04:27:05Z ngie $

BZ2DIR=	${SRCTOP}/contrib/bzip2
.PATH: ${BZ2DIR}

PROG=	bzip2recover
MAN=

NO_WMISSING_VARIABLE_DECLARATIONS=

.include <bsd.prog.mk>
