# $FreeBSD: src/usr.bin/bzip2recover/Makefile,v 1.3 2004/12/21 08:47:29 ru Exp $
# $MidnightBSD$

BZ2DIR=	${.CURDIR}/../../contrib/bzip2
.PATH: ${BZ2DIR}

PROG=	bzip2recover
NO_MAN=

.include <bsd.prog.mk>
