# $FreeBSD: release/7.0.0/usr.sbin/lpr/common_source/Makefile 136910 2004-10-24 15:33:08Z ru $

#
# Library of internal routines for the print spooler suite.
# Originally these were compiled separately into each program,
# but the library makes it much easier to modularize them.
#
LIB=		lpr
INTERNALLIB=
SRCS=		common.c ctlinfo.c displayq.c matchjobs.c net.c \
		printcap.c request.c rmjob.c startdaemon.c

.include <bsd.lib.mk>
