# $FreeBSD: stable/11/sys/modules/bfe/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/bfe

KMOD=	if_bfe
SRCS=	if_bfe.c miibus_if.h miidevs.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
