# $FreeBSD: release/10.0.0/sys/modules/bfe/Makefile 150636 2005-09-27 18:10:43Z mlaier $

.PATH: ${.CURDIR}/../../dev/bfe

KMOD=	if_bfe
SRCS=	if_bfe.c miibus_if.h miidevs.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
