# $FreeBSD: release/7.0.0/sys/modules/portalfs/Makefile 89260 2002-01-11 15:49:02Z ru $

.PATH: ${.CURDIR}/../../fs/portalfs

KMOD=	portalfs
SRCS=	vnode_if.h \
	portal_vfsops.c portal_vnops.c

.include <bsd.kmod.mk>
