# $MidnightBSD$
# $FreeBSD: stable/10/tests/sys/mac/Makefile 292570 2015-12-21 21:24:03Z ngie $

TESTSDIR=	${TESTSBASE}/sys/mac

TESTS_SUBDIRS+=	bsdextended
TESTS_SUBDIRS+=	portacl

.include <bsd.test.mk>
