# $FreeBSD: release/10.0.0/lib/clang/libllvmmcjit/Makefile 249423 2013-04-12 17:57:40Z dim $

.include <bsd.own.mk>

LIB=	llvmmcjit

SRCDIR=	lib/ExecutionEngine/MCJIT
SRCS=	MCJIT.cpp \
	SectionMemoryManager.cpp

.include "../clang.lib.mk"
