# $FreeBSD: release/9.2.0/lib/clang/libllvmmcjit/Makefile 252723 2013-07-04 20:17:04Z dim $

.include <bsd.own.mk>

LIB=	llvmmcjit

SRCDIR=	lib/ExecutionEngine/MCJIT
SRCS=	MCJIT.cpp \
	SectionMemoryManager.cpp

.include "../clang.lib.mk"
