# $FreeBSD: stable/9/lib/clang/libllvmmcjit/Makefile 245431 2013-01-14 19:51:26Z dim $

.include <bsd.own.mk>

LIB=	llvmmcjit

SRCDIR=	lib/ExecutionEngine/MCJIT
SRCS=	MCJIT.cpp

.include "../clang.lib.mk"
