#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/10.0.0/usr.bin/find/Makefile 249657 2013-04-19 19:45:00Z ed $

PROG=	find
SRCS=	find.c function.c ls.c main.c misc.c operator.c option.c \
	getdate.y
YFLAGS=

NO_WMISSING_VARIABLE_DECLARATIONS=

.include <bsd.prog.mk>
