# $MidnightBSD$
# $FreeBSD: stable/10/lib/libiconv_modules/JOHAB/Makefile 260497 2014-01-09 23:08:56Z dim $

SHLIB=	JOHAB
SRCS+=	citrus_johab.c
CFLAGS.gcc+= --param max-inline-insns-single=16

.include <bsd.lib.mk>
