# $FreeBSD: release/10.0.0/usr.sbin/bsdconfig/mouse/include/Makefile 238438 2012-07-14 03:16:57Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/110.mouse/include
FILES=		messages.subr

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
