# $MidnightBSD$
# $FreeBSD: stable/10/share/tests/Makefile 313488 2017-02-09 22:49:48Z ngie $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/share

.PATH:		${SRCTOP}/tests
KYUAFILE=	yes

.include <bsd.test.mk>
