# $FreeBSD: release/10.0.0/gnu/usr.bin/groff/font/devX75-12/Makefile 139103 2004-12-21 08:47:35Z ru $

NO_OBJ=

.include "../Makefile.inc"
.include "${DIST_DIR}/Makefile.sub"
.include "../Makefile.dev"
