# $FreeBSD: stable/11/tests/sys/auditpipe/Makefile 336728 2018-07-26 00:16:41Z asomers $

TESTSDIR=	${TESTSBASE}/sys/auditpipe

ATF_TESTS_C=	auditpipe_test

TEST_METADATA+= required_user="root"
WARNS?=	6

.include <bsd.test.mk>
