#	@(#)Makefile	8.2 (Berkeley) 4/28/95
# $FreeBSD: release/7.0.0/usr.bin/cksum/Makefile 90415 2002-02-08 22:31:43Z markm $

PROG=	cksum
SRCS=	cksum.c crc.c print.c sum1.c sum2.c crc32.c
LINKS=	${BINDIR}/cksum ${BINDIR}/sum
MLINKS=	cksum.1 sum.1

.include <bsd.prog.mk>
