# $FreeBSD: release/10.0.0/sys/modules/netgraph/bpf/Makefile 153213 2005-12-07 21:30:47Z jkim $
# $Whistle: Makefile,v 1.1 1999/12/03 01:44:28 archie Exp $

.PATH: ${.CURDIR}/../../../net

KMOD=	ng_bpf
SRCS=	opt_bpf.h ng_bpf.c bpf_filter.c

.include <bsd.kmod.mk>
