# $FreeBSD: stable/11/usr.bin/ofed/libibverbs/ud_pingpong/Makefile 335253 2018-06-16 15:05:05Z kib $

PROG=	ibv_ud_pingpong
MAN=	ibv_ud_pingpong.1
SRCS=	ud_pingpong.c pingpong.c

.include <bsd.prog.mk>
