# $FreeBSD: stable/11/cddl/usr.sbin/zfsd/Makefile 305909 2016-09-18 02:41:50Z ngie $

.include "Makefile.common"

PROG_CXX=	zfsd
MAN=		zfsd.8

.include <bsd.prog.mk>

# The unittests require devel/googletest and devel/googlemock from ports.
# Don't automatically build them.
SUBDIR=
