# $FreeBSD: stable/11/sys/modules/ow/ow/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/ow

KMOD=	ow
SRCS=	ow.c
SRCS+=	own_if.c own_if.h owll_if.c owll_if.h bus_if.h device_if.h

.include <bsd.kmod.mk>
