# $FreeBSD: release/10.0.0/sys/modules/netgraph/pptpgre/Makefile 89260 2002-01-11 15:49:02Z ru $
# $Whistle: Makefile,v 1.1 1999/11/29 23:14:33 archie Exp $

KMOD=	ng_pptpgre
SRCS= 	ng_pptpgre.c

.include <bsd.kmod.mk>
