# $FreeBSD: release/10.0.0/sys/modules/udf_iconv/Makefile 122221 2003-11-07 09:38:05Z scottl $

.PATH:	${.CURDIR}/../../fs/udf
KMOD=	udf_iconv
SRCS=	udf_iconv.c

CFLAGS+= -I${.CURDIR}/../../

.include <bsd.kmod.mk>
