# $FreeBSD: stable/11/sys/modules/udf_iconv/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:	${SRCTOP}/sys/fs/udf
KMOD=	udf_iconv
SRCS=	udf_iconv.c

CFLAGS+= -I${SRCTOP}/sys/

.include <bsd.kmod.mk>
