# $FreeBSD: release/7.0.0/usr.sbin/sa/Makefile 169863 2007-05-22 10:49:42Z dds $

.PATH: ${.CURDIR}/../../usr.bin/lastcomm

PROG=	sa
MAN=	sa.8
SRCS=	main.c db.c pdb.c usrdb.c readrec.c

WARNS?=	6

.include <bsd.prog.mk>
