# $Id: Makefile,v 1.1.1.1 2006-02-25 02:26:41 laffer1 Exp $
# $FreeBSD: src/etc/bluetooth/Makefile,v 1.1.10.1 2005/11/16 07:39:24 ru Exp $

FILESDIR=		/etc/bluetooth
FILES=			hcsecd.conf hosts protocols
FILESMODE_hcsecd.conf=	600
FILESMODE_hosts=	644

.include <bsd.prog.mk>
