# $FreeBSD: release/10.0.0/sys/modules/mac_seeotheruids/Makefile 101172 2002-08-01 17:41:27Z rwatson $

.PATH: ${.CURDIR}/../../security/mac_seeotheruids

KMOD=	mac_seeotheruids
SRCS=	vnode_if.h \
	mac_seeotheruids.c

.include <bsd.kmod.mk>
