# $FreeBSD: stable/11/sys/modules/mac_seeotheruids/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/security/mac_seeotheruids

KMOD=	mac_seeotheruids
SRCS=	vnode_if.h \
	mac_seeotheruids.c

.include <bsd.kmod.mk>
