# $FreeBSD: release/7.0.0/sys/modules/mac_lomac/Makefile 107278 2002-11-26 17:35:44Z rwatson $

.PATH: ${.CURDIR}/../../security/mac_lomac

KMOD=	mac_lomac
SRCS=	vnode_if.h \
	opt_mac.h \
	mac_lomac.c

.include <bsd.kmod.mk>
