# $FreeBSD: release/10.0.0/sys/modules/mac_lomac/Makefile 193588 2009-06-06 17:01:44Z rwatson $

.PATH: ${.CURDIR}/../../security/mac_lomac

KMOD=	mac_lomac
SRCS=	vnode_if.h \
	mac_lomac.c

.include <bsd.kmod.mk>
