# $FreeBSD: stable/11/sys/modules/mac_lomac/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/security/mac_lomac

KMOD=	mac_lomac
SRCS=	vnode_if.h \
	mac_lomac.c

.include <bsd.kmod.mk>
