# $FreeBSD: release/10.0.0/sys/modules/netgraph/ether_echo/Makefile 186481 2008-12-25 00:01:29Z julian $
# $Whistle: Makefile,v 1.2 1999/01/19 19:39:20 archie Exp $

KMOD=	ng_ether_echo
SRCS= 	ng_ether_echo.c

.include <bsd.kmod.mk>
