# $FreeBSD: stable/11/usr.bin/cmp/tests/Makefile 314427 2017-02-28 22:49:41Z asomers $

.include <bsd.own.mk>

ATF_TESTS_SH+=		cmp_test2
NETBSD_ATF_TESTS_SH=	cmp_test

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
