# $MidnightBSD$
# $FreeBSD: stable/10/usr.bin/cmp/tests/Makefile 314425 2017-02-28 22:18:05Z asomers $

.include <bsd.own.mk>

ATF_TESTS_SH+=		cmp_test2
NETBSD_ATF_TESTS_SH=	cmp_test

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
