# $FreeBSD: release/10.0.0/share/i18n/csmapper/KAZAKH/Makefile 219019 2011-02-25 00:04:39Z gabor $
# $NetBSD: Makefile.inc,v 1.1 2007/03/13 16:34:37 tnozaki Exp $

CODE=	KAZAKH

MAPS=	KZ1048%UCS.mps PTCP154%UCS.mps UCS%KZ1048.mps UCS%PTCP154.mps

.include "../Makefile.part"
