# $MidnightBSD$
# $FreeBSD: stable/10/sys/modules/if_vxlan/Makefile 273331 2014-10-20 14:42:42Z bryanv $

.PATH: ${.CURDIR}/../../net

KMOD=	if_vxlan
SRCS=	if_vxlan.c
SRCS+=	opt_inet.h opt_inet6.h

.include <bsd.kmod.mk>
