# $FreeBSD: stable/11/sys/modules/if_vxlan/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/net

KMOD=	if_vxlan
SRCS=	if_vxlan.c
SRCS+=	opt_inet.h opt_inet6.h

.include <bsd.kmod.mk>
