# $FreeBSD: release/10.0.0/sys/modules/ae/Makefile 185571 2008-12-02 21:37:28Z bz $

.PATH: ${.CURDIR}/../../dev/ae

KMOD=	if_ae
SRCS=	if_ae.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
