# $FreeBSD: stable/11/sys/modules/ae/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/ae

KMOD=	if_ae
SRCS=	if_ae.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
