# $FreeBSD: release/7.0.0/share/doc/legal/intel_wpi/Makefile 174446 2007-12-08 12:44:59Z benjsc $

NO_OBJ=
FILES=          ${.CURDIR}/../../../../sys/contrib/dev/wpi/LICENSE
FILESDIR=       ${SHAREDIR}/doc/legal/intel_wpi

.include <bsd.prog.mk>

