# $FreeBSD: release/10.0.0/share/doc/legal/intel_wpi/Makefile 173362 2007-11-05 11:47:19Z benjsc $

NO_OBJ=
FILES=          ${.CURDIR}/../../../../sys/contrib/dev/wpi/LICENSE
FILESDIR=       ${SHAREDIR}/doc/legal/intel_wpi

.include <bsd.prog.mk>

