# $FreeBSD: stable/11/share/doc/legal/intel_wpi/Makefile 289399 2015-10-16 00:38:05Z bdrewery $

FILES=          ${.CURDIR}/../../../../sys/contrib/dev/wpi/LICENSE
FILESDIR=       ${SHAREDIR}/doc/legal
FILESNAME=	intel_wpi.LICENSE

.include <bsd.prog.mk>

