# $FreeBSD: stable/9/usr.bin/clang/llvm-prof/Makefile 245431 2013-01-14 19:51:26Z dim $

PROG_CXX=llvm-prof

SRCDIR=	tools/llvm-prof
SRCS=	llvm-prof.cpp

LIBDEPS=llvmanalysis \
	llvmtarget \
	llvmmc \
	llvmobject \
	llvmbitreader \
	llvmcore \
	llvmsupport

.include "../clang.prog.mk"
