# The FreeBSD Russian Documentation Project
#
# $FreeBSDru: frdp/release/doc/ru_RU.KOI8-R/Makefile,v 1.9 2004/09/20 09:53:02 den Exp $
# $FreeBSD: release/7.0.0/release/doc/ru_RU.KOI8-R/Makefile 143355 2005-03-10 11:44:05Z den $
# 
# Original revision: 1.7
#

RELN_ROOT?= ${.CURDIR}/..

SUBDIR = relnotes
SUBDIR+= hardware
SUBDIR+= readme
SUBDIR+= errata
SUBDIR+= installation

COMPAT_SYMLINK = ru

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
