# $FreeBSD: stable/11/sys/modules/sdhci/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/sdhci

KMOD=	sdhci
SRCS=	sdhci.c sdhci.h sdhci_if.c sdhci_if.h device_if.h bus_if.h mmcbr_if.h

.include <bsd.kmod.mk>
