# $FreeBSD: stable/9/sys/modules/sdhci/Makefile 184138 2008-10-21 20:33:40Z mav $

.PATH: ${.CURDIR}/../../dev/sdhci

KMOD=	sdhci
SRCS=	sdhci.c sdhci.h device_if.h bus_if.h pci_if.h mmcbr_if.h

.include <bsd.kmod.mk>
