#!/bin/sh
# $Id: calendar3-stdout,v 1.1.1.1 2011-12-18 03:01:46 laffer1 Exp $

. ./setup-vars

RESULT=`$DIALOG --extra-button --extra-label "Hold" --help-button --stdout --title "CALENDAR" "$@" --calendar "Please choose a date..." 0 0 7 7 1981`
retval=$?

. ./report-string
