#!/bin/sh
# $Id: fselect2,v 1.1.1.1 2011-12-18 03:01:46 laffer1 Exp $

. ./setup-vars

exec 3>&1
RESULT=`$DIALOG --title "Please choose a file" "$@" --fselect $HOME/ 0 0 2>&1 1>&3`
retval=$?
exec 3>&-

. ./report-string
