#! /bin/sh
# $Id: infobox,v 1.1.1.1 2011-12-18 03:01:46 laffer1 Exp $

. ./setup-vars

left=10
unit="seconds"
while test $left != 0
do

$DIALOG --sleep 1 \
	--title "INFO BOX" "$@" \
        --infobox "Hi, this is an information box. It is
different from a message box: it will
not pause waiting for input after displaying
the message. The pause here is only introduced
by the sleep command within dialog.
You have $left $unit to read this..." 10 52
left=`expr $left - 1`
test $left = 1 && unit="second"
done
