#!/bin/sh
# $Id: inputbox6-8bit,v 1.1.1.1 2011-12-18 03:01:46 laffer1 Exp $

. ./setup-vars

. ./setup-tempfile

. ./testdata-8bit

$DIALOG \
--title    `printf "$SAMPLE"` "$@" \
--inputbox `printf "$SAMPLE"` \
10 40 `printf "$SAMPLE"` 2>$tempfile

retval=$?

. ./report-tempfile
