#!/bin/sh
# $Id: inputbox6-utf8,v 1.1.1.1 2011-12-18 03:01:46 laffer1 Exp $

. ./setup-vars

. ./setup-tempfile

. ./setup-utf8

$DIALOG \
--title    `printf "\xe3\x81\x82\xe3\x81\x84\xe3\x81\x86\xe3\x81\x88\xe3\x81\x8a"` "$@" \
--inputbox `printf "\xe3\x81\x82\xe3\x81\x84\xe3\x81\x86\xe3\x81\x88\xe3\x81\x8a"` \
10 20 "Ｄ.Ｏ.Ｇ"	 2>$tempfile

retval=$?

. ./report-tempfile
