#!/bin/sh
# $Id: timebox2-stdout,v 1.1.1.1 2011-12-18 03:01:46 laffer1 Exp $

. ./setup-vars

RESULT=`$DIALOG --stdout --title "TIMEBOX" "$@" --timebox "Please set the time..." 0 0`

retval=$?

. ./report-string
