#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/10.0.0/usr.bin/basename/Makefile 90415 2002-02-08 22:31:43Z markm $

PROG=	basename
MLINKS=	basename.1 dirname.1

.include <bsd.prog.mk>
