# $FreeBSD: release/10.0.0/sys/modules/geom/geom_mbr/Makefile 117254 2003-07-05 08:11:43Z jmg $

.PATH: ${.CURDIR}/../../../geom

KMOD=	geom_mbr
SRCS=	geom_mbr.c geom_mbr_enc.c

.include <bsd.kmod.mk>
