# $FreeBSD: src/games/bs/Makefile,v 1.5.2.1 2001/04/25 09:28:49 ru Exp $
# $DragonFly: src/games/bs/Makefile,v 1.4 2006/10/08 16:22:35 pavalos Exp $
# $MidnightBSD: src/games/bs/Makefile,v 1.1 2009/04/12 01:32:14 laffer1 Exp $

PROG=   bs
MAN=   bs.6
DPADD=  ${LIBNCURSES} 
LDADD=  -lncurses 
HIDEGAME=hidegame

.include <bsd.prog.mk>
