# $FreeBSD: release/7.0.0/gnu/usr.bin/binutils/libbfd/Makefile.i386 131832 2004-07-08 17:05:34Z obrien $

DEFAULT_VECTOR=	bfd_elf32_i386_freebsd_vec

SRCS+=	cpu-i386.c \
	elf32-i386.c \
	elf32-target.h \
	elf32.c \
	elflink.c

VECS=	${DEFAULT_VECTOR} \
	bfd_elf32_i386_vec
