# $FreeBSD: release/7.0.0/gnu/usr.bin/binutils/libbfd/Makefile.alpha 131832 2004-07-08 17:05:34Z obrien $

DEFAULT_VECTOR=	bfd_elf64_alpha_freebsd_vec

SRCS+=	coff-alpha.c \
	cpu-alpha.c \
	ecoff.c \
	ecofflink.c \
	elf64.c \
	elf64-alpha.c \
	elf64-target.h \
	elflink.c

VECS=	${DEFAULT_VECTOR} \
	bfd_elf64_alpha_vec \
	ecoffalpha_little_vec
