# $FreeBSD: stable/9/sys/modules/amr/amr_linux/Makefile 154789 2006-01-24 21:13:50Z ambrisko $

.PATH: ${.CURDIR}/../../../dev/amr

KMOD=	amr_linux
SRCS=	amr_linux.c device_if.h bus_if.h

.include <bsd.kmod.mk>
