# $FreeBSD: stable/11/sys/modules/amr/amr_linux/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/amr

KMOD=	amr_linux
SRCS=	amr_linux.c device_if.h bus_if.h

.include <bsd.kmod.mk>
