# $MidnightBSD$
# $FreeBSD: stable/10/usr.sbin/uefisign/Makefile 279315 2015-02-26 09:15:24Z trasz $

PROG=	uefisign
SRCS=	uefisign.c child.c pe.c
MAN=	uefisign.8

LDFLAGS=	-lcrypto

WARNS=	6

.include <bsd.prog.mk>
