# $FreeBSD: release/10.0.0/sys/modules/sound/driver/sb16/Makefile 70711 2001-01-06 14:00:42Z obrien $

.PATH: ${.CURDIR}/../../../../dev/sound/isa

KMOD=	snd_sb16
SRCS=	device_if.h bus_if.h isa_if.h pci_if.h
SRCS+=	sb16.c

.include <bsd.kmod.mk>
