# $FreeBSD: stable/11/share/examples/kld/cdev/Makefile 299293 2016-05-10 00:51:50Z gjb $

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/kld/cdev
SUBDIR=	module test

load unload: _SUBDIR

.include <bsd.subdir.mk>
