# $FreeBSD: stable/11/stand/sparc64/Makefile 344399 2019-02-20 23:55:35Z kevans $

NO_OBJ=t

.include <bsd.init.mk>

SUBDIR.yes=	boot1 loader
SUBDIR.${MK_LOADER_ZFS}+=zfsboot

.include <bsd.subdir.mk>
