# $MidnightBSD$
#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/10/usr.bin/locate/code/Makefile 276486 2014-12-31 23:25:37Z ngie $

PROG=	locate.code
CFLAGS+=-I${.CURDIR}/../locate 
MAN=
BINDIR=	${LIBEXECDIR}

.include <bsd.prog.mk>
