#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/10.0.0/usr.bin/locate/code/Makefile 139103 2004-12-21 08:47:35Z ru $

PROG=	locate.code
CFLAGS+=-I${.CURDIR}/../locate 
NO_MAN=
BINDIR=	${LIBEXECDIR}

.include <bsd.prog.mk>
