# $FreeBSD: release/10.0.0/share/doc/llvm/Makefile 225880 2011-09-29 18:12:40Z dim $

SUBDIR=		clang

SRCDIR=		${.CURDIR}/../../../contrib/llvm

.PATH: ${SRCDIR} ${SRCDIR}/lib/Support

NO_OBJ=

FILESGROUPS=	TOP
TOP=		LICENSE.TXT COPYRIGHT.regex
TOPDIR=		${DOCDIR}/llvm

.include <bsd.prog.mk>
