# $FreeBSD: release/7.0.0/usr.sbin/cdcontrol/Makefile 113091 2003-04-04 17:49:21Z obrien $

PROG= cdcontrol

WARNS?= 2

DPADD=	${LIBEDIT} ${LIBTERMCAP}
LDADD=	-ledit -ltermcap

.include <bsd.prog.mk>
