# $FreeBSD: stable/11/usr.bin/clang/llvm-profdata/Makefile 310618 2016-12-26 20:36:37Z dim $

PROG_CXX=	llvm-profdata

SRCDIR=		tools/llvm-profdata
SRCS+=		llvm-profdata.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
