#	from: @(#)Makefile	5.8 (Berkeley) 7/28/90
# $FreeBSD: release/7.0.0/usr.sbin/ypbind/Makefile 80029 2001-07-20 06:20:32Z obrien $

PROG=	ypbind
MAN=	ypbind.8
SRCS=	ypbind.c yp_ping.c

CFLAGS+= -DDAEMON

.include <bsd.prog.mk>
