#	from: @(#)Makefile	5.8 (Berkeley) 7/28/90
# $FreeBSD: release/10.0.0/usr.sbin/ypbind/Makefile 201390 2010-01-02 11:07:44Z ed $

PROG=	ypbind
MAN=	ypbind.8
SRCS=	ypbind.c yp_ping.c

CFLAGS+= -DDAEMON

WARNS?=	2

.include <bsd.prog.mk>
