# $FreeBSD: stable/11/lib/librt/tests/Makefile 299094 2016-05-04 23:20:53Z ngie $

LIBADD=	rt

NETBSD_ATF_TESTS_C=	sched_test
NETBSD_ATF_TESTS_C+=	sem_test

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
