# $FreeBSD: stable/11/share/examples/find_interface/Makefile 299293 2016-05-10 00:51:50Z gjb $

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/${PROG}
PROG=	find_interface
MAN=

.include <bsd.prog.mk>
