# $FreeBSD: release/10.0.0/sys/modules/acl_nfs4/Makefile 232937 2012-03-13 20:28:42Z adrian $

.include <bsd.own.mk>

.PATH:  ${.CURDIR}/../../kern
KMOD=	acl_nfs4
SRCS=	vnode_if.h subr_acl_nfs4.c

.include <bsd.kmod.mk>
