# $FreeBSD: release/10.0.0/usr.sbin/bsnmpd/tools/Makefile 216295 2010-12-08 14:30:25Z syrinx $
# Author: Shteryana Shopova <syrinx@FreeBSD.org>

SUBDIR=	libbsnmptools \
	bsnmptools

.include <bsd.subdir.mk>
