# $FreeBSD: release/10.0.0/sys/modules/digi/digi_EPCX/Makefile 76195 2001-05-02 01:08:09Z brian $

.PATH:	${.CURDIR}/../../../dev/digi
KMOD=	digi_EPCX
SRCS=	EPCX.c EPCX.bios.h EPCX.fepos.h digi_mod.h

.include <bsd.kmod.mk>
