# $MidnightBSD$
# $FreeBSD: stable/10/lib/libiconv_modules/UTF7/Makefile 260497 2014-01-09 23:08:56Z dim $

SHLIB=	UTF7
SRCS+=	citrus_utf7.c
CFLAGS.gcc+= --param max-inline-insns-single=32

.include <bsd.lib.mk>
