# Master Makefile for man, manpath, apropos, and whatis
#
# You may distribute under the terms of the GNU General Public
# License as specified in the README file that comes with the man 1.0
# distribution.
#
# $FreeBSD: release/7.0.0/gnu/usr.bin/man/Makefile 107054 2002-11-18 10:25:27Z ru $
#

SUBDIR = lib man manpath apropos

.include <bsd.subdir.mk>
