#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/9/usr.bin/finger/Makefile 202191 2010-01-13 17:50:58Z ed $

PROG=	finger
SRCS=	finger.c lprint.c net.c sprint.c util.c
MAN=	finger.1 finger.conf.5

WARNS?=	2

.include <bsd.prog.mk>
