#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/7.0.0/usr.bin/finger/Makefile 90415 2002-02-08 22:31:43Z markm $

PROG=	finger
SRCS=	finger.c lprint.c net.c sprint.c util.c
MAN=	finger.1 finger.conf.5

.include <bsd.prog.mk>
