# $FreeBSD: release/7.0.0/usr.sbin/i4b/isdntel/Makefile 80029 2001-07-20 06:20:32Z obrien $

PROG=	isdntel
MAN=	isdntel.8
SRCS=	main.c display.c files.c alias.c

DPADD=	${LIBNCURSES}
LDADD=	-lncurses

.include <bsd.prog.mk>
