# Makefile for ntpd.
# $FreeBSD: release/7.0.0/usr.sbin/ntp/Makefile 156736 2006-03-15 11:17:31Z ru $

SUBDIR=	libntp libparse ntpd ntpdc ntpq ntpdate ntptrace \
	ntptime ntp-keygen sntp
SUBDIR+=	doc

.include <bsd.subdir.mk>
