# Makefile for ntpd.
# $FreeBSD: stable/9/usr.sbin/ntp/Makefile 200577 2009-12-15 14:59:58Z roberto $

SUBDIR=	libopts libntp libparse ntpd ntpdc ntpq ntpdate \
	ntptime ntp-keygen sntp
SUBDIR+=	doc

.include <bsd.subdir.mk>
