# $FreeBSD: stable/11/lib/libclang_rt/stats_client/Makefile 305364 2016-09-03 21:41:29Z dim $

.include <bsd.init.mk>

LIB=		clang_rt.stats_client-${CRTARCH}

SRCS+=		stats/stats_client.cc

.include <bsd.lib.mk>
