# $MidnightBSD: src/libexec/revnetgroup/Makefile,v 1.2 2012/04/11 00:46:55 laffer1 Exp $
# $FreeBSD: src/libexec/revnetgroup/Makefile,v 1.6 2001/03/26 14:22:06 ru Exp $

PROG=	revnetgroup
SRCS=	revnetgroup.c hash.c parse_netgroup.c

MAN= revnetgroup.8

WARNS?= 2
.include <bsd.prog.mk>
