# $MidnightBSD$
# $FreeBSD: stable/10/lib/libc/tests/inet/Makefile 313498 2017-02-10 01:13:12Z ngie $

.include <bsd.own.mk>

NETBSD_ATF_TESTS_C+=	inet_addr_test
NETBSD_ATF_TESTS_C+=	inet_network_test

.include "../Makefile.netbsd-tests"

.include <bsd.test.mk>
