# $FreeBSD: stable/11/lib/libc/tests/inet/Makefile 309466 2016-12-03 02:47:16Z ngie $

.include <bsd.own.mk>

NETBSD_ATF_TESTS_C+=	inet_addr_test
NETBSD_ATF_TESTS_C+=	inet_network_test

.include "../Makefile.netbsd-tests"

.include <bsd.test.mk>
