# $MidnightBSD$
# $FreeBSD: stable/10/sys/boot/Makefile.amd64 293353 2016-01-07 20:34:06Z emaste $

SUBDIR+=		efi
SUBDIR+=		libstand32
SUBDIR+=		zfs
SUBDIR+=		userboot

.if ${MK_FORTH} != "no"
SUBDIR+=		ficl32
.endif

SUBDIR+=		i386
