# $FreeBSD: stable/11/usr.bin/clang/llvm-extract/Makefile 310618 2016-12-26 20:36:37Z dim $

PROG_CXX=	llvm-extract

SRCDIR=		tools/llvm-extract
SRCS+=		llvm-extract.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
