# $FreeBSD: release/10.0.0/lib/clang/libllvmarminfo/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvmarminfo

SRCDIR=	lib/Target/ARM/TargetInfo
INCDIR=	lib/Target/ARM
SRCS=	ARMTargetInfo.cpp

TGHDRS=	ARMGenInstrInfo \
	ARMGenRegisterInfo \
	ARMGenSubtargetInfo

.include "../clang.lib.mk"
