# $FreeBSD: release/10.0.0/share/i18n/esdb/MISC/Makefile 219019 2011-02-25 00:04:39Z gabor $
# $NetBSD: Makefile.inc,v 1.2 2008/10/25 22:35:36 apb Exp $

CODE=	MISC
NO_PREPROC= yes
NO_EPREFIX= yes

.include "../Makefile.part"
