# $FreeBSD: release/10.0.0/sys/modules/geom/geom_pc98/Makefile 115479 2003-05-31 18:36:41Z phk $

.PATH: ${.CURDIR}/../../../geom

KMOD=	geom_pc98
SRCS=	geom_pc98.c geom_pc98_enc.c

.include <bsd.kmod.mk>
