# $FreeBSD: release/10.0.0/share/keys/pkg/trusted/Makefile 257344 2013-10-29 15:07:54Z bdrewery $

NO_OBJ=

FILES=	pkg.freebsd.org.2013102301

FILESDIR=	/usr/share/keys/pkg/trusted
FILESMODE=	644

.include <bsd.prog.mk>
