# $FreeBSD: release/7.0.0/sbin/quotacheck/Makefile 126178 2004-02-23 20:25:27Z johan $
#	@(#)Makefile	8.1 (Berkeley) 6/5/93

PROG=	quotacheck
SRCS=	quotacheck.c preen.c utilities.c
WARNS?=	2
MAN=	quotacheck.8

.PATH:	${.CURDIR}/../fsck_ffs

.include <bsd.prog.mk>
