# $FreeBSD: release/7.0.0/sys/modules/gem/Makefile 108965 2003-01-08 20:40:29Z tmm $

.PATH: ${.CURDIR}/../../dev/gem

KMOD=	if_gem
SRCS=	if_gem.c if_gem_pci.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
