# $FreeBSD: stable/11/sys/modules/geom/geom_sched/gsched_delay/Makefile 292425 2015-12-18 05:39:25Z imp $

KMOD=   gsched_delay
SRCS=   gs_delay.c

# ../Makefile.inc automatically included
.include <bsd.kmod.mk>
