# $FreeBSD: stable/11/usr.bin/iconv/Makefile 274135 2014-11-05 14:55:01Z bapt $
# $NetBSD: Makefile,v 1.6 2009/04/14 22:15:21 lukem Exp $

.include <bsd.own.mk>

PROG=	iconv
#SRCS=	iconv.c
MAN=	iconv.1

.include <bsd.prog.mk>
