# $FreeBSD: release/7.0.0/share/doc/psd/22.rpcgen/Makefile 136910 2004-10-24 15:33:08Z ru $

VOLUME=		psd/22.rpcgen
SRCS=		stubs rpcgen.ms
MACROS=		-ms
USE_TBL=
SRCDIR=		${.CURDIR}/../../../../lib/libc/rpc/PSD.doc

.include <bsd.doc.mk>
