# $FreeBSD: stable/11/sys/modules/i2c/isl/Makefile 332113 2018-04-06 16:48:07Z ian $

.PATH:		${SRCTOP}/sys/dev/isl
KMOD		= isl
SRCS		= isl.c device_if.h bus_if.h iicbus_if.h opt_platform.h

.include <bsd.kmod.mk>
