# $MidnightBSD$
# $FreeBSD: stable/10/include/xlocale/Makefile 267465 2014-06-14 02:57:40Z pfg $ 

NO_OBJ=
INCS=	_ctype.h _inttypes.h _langinfo.h _locale.h _monetary.h _stdio.h\
	_stdlib.h _string.h _strings.h _time.h _uchar.h _wchar.h
INCSDIR=${INCLUDEDIR}/xlocale

.include <bsd.prog.mk>
