# $FreeBSD: stable/11/sys/modules/amdsbwd/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:  ${SRCTOP}/sys/dev/amdsbwd
KMOD    = amdsbwd
SRCS    = amdsbwd.c
SRCS    += device_if.h bus_if.h pci_if.h isa_if.h

.include <bsd.kmod.mk>
