# $FreeBSD: release/7.0.0/libexec/rpc.rquotad/Makefile 74814 2001-03-26 14:22:12Z ru $

PROG =	rpc.rquotad
SRCS =	rquotad.c
MAN  =	rpc.rquotad.8

DPADD=	${LIBRPCSVC}
LDADD=	-lrpcsvc

.include <bsd.prog.mk>
