/*
 * Copyright (c) 2026 Albert Song <albb0920@gmail.com>
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef AQ_HW_AQ2_H
#define AQ_HW_AQ2_H

/* AQ2 boot and host request/status registers. */
#define AQ2_MIF_HOST_FINISHED_STATUS_WRITE_REG 0x0e00u
#define AQ2_MIF_HOST_FINISHED_STATUS_READ_REG 0x0e04u
#define AQ2_MIF_HOST_FINISHED_STATUS_ACK BIT(0)

#define AQ2_MCP_HOST_REQ_INT_REG 0x0f00u
#define AQ2_MCP_HOST_REQ_INT_READY BIT(0)
#define AQ2_MCP_HOST_REQ_INT_CLR_REG 0x0f08u

#define AQ2_MIF_BOOT_REG 0x3040u
#define AQ2_MIF_BOOT_REQ_REBOOT BIT(0)
#define AQ2_MIF_BOOT_REQ_HOST_BOOT BIT(8)
#define AQ2_MIF_BOOT_HOST_DATA_LOADED BIT(16)
#define AQ2_MIF_BOOT_BOOT_STARTED BIT(24)
#define AQ2_MIF_BOOT_CRASH_INIT BIT(27)
#define AQ2_MIF_BOOT_BOOT_CODE_FAILED BIT(28)
#define AQ2_MIF_BOOT_FW_INIT_FAILED BIT(29)
#define AQ2_MIF_BOOT_FW_INIT_COMP_SUCCESS BIT(31)

#define AQ2_MIF_BOOT_FW_FAIL_MASK                                  \
	(AQ2_MIF_BOOT_CRASH_INIT | AQ2_MIF_BOOT_BOOT_CODE_FAILED | \
	    AQ2_MIF_BOOT_FW_INIT_FAILED)
#define AQ2_MIF_BOOT_FW_DONE_MASK \
	(AQ2_MIF_BOOT_FW_FAIL_MASK | AQ2_MIF_BOOT_FW_INIT_COMP_SUCCESS)

/* AQ2 hostboot request registers and field masks. */
#define AQ2_HOSTBOOT_REQ_OFFSET_REG 0x0328u
#define AQ2_HOSTBOOT_REQ_LENGTH_REG 0x032cu
#define AQ2_HOSTBOOT_SHARED_IMAGE_BUF 0x10000u
#define AQ2_HOSTBOOT_DATA_OFFSET_REG 0x12a4cu
#define AQ2_HOSTBOOT_DATA_LENGTH_REG 0x12a50u

#define AQ2_HOSTBOOT_MAX_OFFSET 0x80000u
#define AQ2_HOSTBOOT_MAX_LENGTH 0x1000u
#define AQ2_HOSTBOOT_CMD_REQ_MASK 0x80000000u
#define AQ2_HOSTBOOT_ITI_REQ_MASK 0x00100000u
#define AQ2_HOSTBOOT_OFFSET_MASK 0x7ffffu
#define AQ2_HOSTBOOT_LENGTH_MASK 0x0fffu

/* AQ2 firmware interface input registers and field masks. */
#define AQ2_FW_INTERFACE_IN_MTU_REG 0x12000u
#define AQ2_FW_INTERFACE_IN_MAC_ADDRESS_REG 0x12008u

#define AQ2_FW_INTERFACE_IN_LINK_CONTROL_REG 0x12010u
#define AQ2_FW_INTERFACE_IN_LINK_CONTROL_MODE 0x0000000fu
#define AQ2_FW_INTERFACE_IN_LINK_CONTROL_MODE_ACTIVE 1u
#define AQ2_FW_INTERFACE_IN_LINK_CONTROL_MODE_SLEEP_PROXY 2u
#define AQ2_FW_INTERFACE_IN_LINK_CONTROL_MODE_SHUTDOWN 4u

#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_REG 0x12018u
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_PAUSE_TX BIT(25)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_PAUSE_RX BIT(24)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_DOWNSHIFT_EN BIT(27)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_DOWNSHIFT 0xf8000000u
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_DOWNSHIFT_RETRY 0xf0000000u
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_DOWNSHIFT_RETRY_S 28
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_EEE_10G BIT(20)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_EEE_5G BIT(19)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_EEE_2G5 BIT(18)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_EEE_1G BIT(17)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_EEE_100M BIT(16)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_EEE           \
	(AQ2_FW_INTERFACE_IN_LINK_OPTIONS_EEE_10G |    \
	    AQ2_FW_INTERFACE_IN_LINK_OPTIONS_EEE_5G |  \
	    AQ2_FW_INTERFACE_IN_LINK_OPTIONS_EEE_2G5 | \
	    AQ2_FW_INTERFACE_IN_LINK_OPTIONS_EEE_1G |  \
	    AQ2_FW_INTERFACE_IN_LINK_OPTIONS_EEE_100M)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_RATE_10G BIT(15)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_RATE_N5G BIT(14)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_RATE_5G BIT(13)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_RATE_N2G5 BIT(12)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_RATE_2G5 BIT(11)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_RATE_1G BIT(10)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_RATE_100M BIT(9)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_RATE_10M BIT(8)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_RATE_1G_HD BIT(7)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_RATE_100M_HD BIT(6)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_RATE_10M_HD BIT(5)
#define AQ2_FW_INTERFACE_IN_LINK_OPTIONS_LINK_UP BIT(0)

#define AQ2_FW_INTERFACE_IN_SLEEP_PROXY_REG 0x12028u

#define AQ2_FW_INTERFACE_IN_REQUEST_POLICY_REG 0x12a58u
#define AQ2_FW_INTERFACE_IN_REQUEST_POLICY_MCAST_QUEUE_OR_TC 0x00800000u
#define AQ2_FW_INTERFACE_IN_REQUEST_POLICY_MCAST_RX_QUEUE_TC_INDEX 0x007c0000u
#define AQ2_FW_INTERFACE_IN_REQUEST_POLICY_MCAST_ACCEPT 0x00010000u
#define AQ2_FW_INTERFACE_IN_REQUEST_POLICY_BCAST_QUEUE_OR_TC 0x00008000u
#define AQ2_FW_INTERFACE_IN_REQUEST_POLICY_BCAST_RX_QUEUE_TC_INDEX 0x00007c00u
#define AQ2_FW_INTERFACE_IN_REQUEST_POLICY_BCAST_ACCEPT 0x00000100u
#define AQ2_FW_INTERFACE_IN_REQUEST_POLICY_PROMISC_QUEUE_OR_TC 0x00000080u
#define AQ2_FW_INTERFACE_IN_REQUEST_POLICY_PROMISC_RX_QUEUE_TX_INDEX 0x0000007cu

/* AQ2 firmware interface output registers and field masks. */
#define AQ2_FW_INTERFACE_OUT_TRANSACTION_ID_REG 0x13000u
#define AQ2_FW_INTERFACE_OUT_TRANSACTION_ID_B 0xffff0000u
#define AQ2_FW_INTERFACE_OUT_TRANSACTION_ID_B_S 16
#define AQ2_FW_INTERFACE_OUT_TRANSACTION_ID_A 0x0000ffffu
#define AQ2_FW_INTERFACE_OUT_TRANSACTION_ID_A_S 0

#define AQ2_FW_INTERFACE_OUT_VERSION_BUNDLE_REG 0x13004u
#define AQ2_FW_INTERFACE_OUT_VERSION_IFACE_REG 0x13010u

#define AQ2_FW_INTERFACE_OUT_VERSION_BUILD 0xffff0000u
#define AQ2_FW_INTERFACE_OUT_VERSION_BUILD_S 16
#define AQ2_FW_INTERFACE_OUT_VERSION_MINOR 0x0000ff00u
#define AQ2_FW_INTERFACE_OUT_VERSION_MINOR_S 8
#define AQ2_FW_INTERFACE_OUT_VERSION_MAJOR 0x000000ffu
#define AQ2_FW_INTERFACE_OUT_VERSION_MAJOR_S 0

#define AQ2_FW_INTERFACE_OUT_VERSION_IFACE_VER 0x0000000fu

#define AQ2_FW_INTERFACE_OUT_LINK_STATUS_REG 0x13014u
#define AQ2_FW_INTERFACE_OUT_LINK_STATUS_PAUSE_RX BIT(9)
#define AQ2_FW_INTERFACE_OUT_LINK_STATUS_PAUSE_TX BIT(8)
#define AQ2_FW_INTERFACE_OUT_LINK_STATUS_RATE 0x000000f0u
#define AQ2_FW_INTERFACE_OUT_LINK_STATUS_RATE_S 4
#define AQ2_FW_INTERFACE_OUT_LINK_STATUS_RATE_10G 6
#define AQ2_FW_INTERFACE_OUT_LINK_STATUS_RATE_5G 5
#define AQ2_FW_INTERFACE_OUT_LINK_STATUS_RATE_2G5 4
#define AQ2_FW_INTERFACE_OUT_LINK_STATUS_RATE_1G 3
#define AQ2_FW_INTERFACE_OUT_LINK_STATUS_RATE_100M 2
#define AQ2_FW_INTERFACE_OUT_LINK_STATUS_RATE_10M 1

#define AQ2_FW_INTERFACE_OUT_STATS_REG 0x13700u
#define AQ2_FW_INTERFACE_OUT_FILTER_CAPS_REG 0x13774u
#define AQ2_FW_INTERFACE_OUT_FILTER_CAPS3_RESOLVER_BASE_INDEX 0x00ff0000u
#define AQ2_FW_INTERFACE_OUT_FILTER_CAPS3_RESOLVER_BASE_INDEX_SHIFT 16

#endif /* AQ_HW_AQ2_H */
