# $FreeBSD: stable/11/usr.bin/bmake/tests/syntax/funny-targets/Makefile.test 263346 2014-03-19 12:29:20Z jmmv $
#
# PR bin/6612 / GRN r102178
#

test1: colons::colons::target

colons::colons::target:
	@echo '${.TARGET}'

test2: exclamation!target

exclamation!target:
	@echo '${.TARGET}
