#! /bin/sh
#
# Common setup.
#
# $FreeBSD: release/10.0.0/tools/tools/net80211/scripts/mesh/common 195618 2009-07-11 15:02:45Z rpaulo $
#
PATH=../:.:$PATH
. config
. config.mesh

WLAN=`ifconfig wlan create wlanmode mesh wlandev $WIRELESS`
ifconfig $WLAN meshid $MESHID channel $CHANNEL mtu 1500
wlandebug -i $WLAN mesh+hwmp+state+scan+assoc
