# $FreeBSD: release/7.0.0/lib/libipx/Makefile 119071 2003-08-18 15:25:39Z obrien $

LIB=	ipx
SHLIBDIR?= /lib
SRCS=	ipx_addr.c ipx_ntoa.c
MAN=	ipx.3
MLINKS+=ipx.3 ipx_addr.3 ipx.3 ipx_ntoa.3

.include <bsd.lib.mk>
