# $FreeBSD: release/10.0.0/cddl/usr.sbin/dtruss/Makefile 211841 2010-08-26 11:45:39Z rpaulo $

.PATH: ${.CURDIR}/../../../cddl/contrib/dtracetoolkit

SCRIPTS=dtruss
MAN=dtruss.1

.include <bsd.prog.mk>
