#	From: @(#)Makefile	8.2 (Berkeley) 4/20/94
# $FreeBSD: release/7.0.0/share/doc/usd/Makefile 124750 2004-01-20 13:09:29Z ru $

# The following modules are not provided:
# 14.jove

SUBDIR=	title \
	contents \
	04.csh \
	07.mail \
	10.exref \
	11.vitut \
	12.vi \
	13.viref \
	18.msdiffs \
	19.memacros \
	20.meref \
	21.troff \
	22.trofftut

.include <bsd.subdir.mk>
