#	From: @(#)Makefile	8.2 (Berkeley) 4/20/94
# $FreeBSD: stable/11/share/doc/usd/Makefile 289393 2015-10-15 22:55:08Z bdrewery $

# The following modules are not provided:
# 14.jove

SUBDIR=	title \
	contents \
	04.csh \
	05.dc \
	06.bc \
	07.mail \
	10.exref \
	11.vitut \
	12.vi \
	13.viref \
	18.msdiffs \
	19.memacros \
	20.meref \
	21.troff \
	22.trofftut
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
