#	From: @(#)Makefile	8.2 (Berkeley) 4/20/94
# $FreeBSD: src/share/doc/usd/Makefile,v 1.16 2004/01/20 13:08:33 ru Exp $

# The following modules are not provided:
# 14.jove 13.viref

SUBDIR=	title \
	contents \
	04.csh \
	07.mail \
	10.exref \
	11.vitut \
	12.vi \
	18.msdiffs \
	19.memacros \
	20.meref \
	21.troff \
	22.trofftut

.include <bsd.subdir.mk>
