# $FreeBSD: release/7.0.0/sys/modules/sound/driver/au88x0/Makefile 115618 2003-06-01 11:58:46Z des $

.PATH: ${.CURDIR}/../../../../dev/sound/pci

KMOD=	snd_au88x0
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	au88x0.c

.include <bsd.kmod.mk>
