# $FreeBSD: stable/11/usr.bin/clang/llvm-rtdyld/Makefile 310618 2016-12-26 20:36:37Z dim $

PROG_CXX=	llvm-rtdyld
MAN=

SRCDIR=		tools/llvm-rtdyld
SRCS+=		llvm-rtdyld.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
