# $FreeBSD: stable/11/sys/modules/i2c/smb/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:		${SRCTOP}/sys/dev/smbus
KMOD		= smb
SRCS		= device_if.h bus_if.h smbus_if.h \
		  smb.c

.include <bsd.kmod.mk>
