# $FreeBSD: stable/11/sys/modules/sound/driver/ad1816/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/sound/isa

KMOD=	snd_ad1816
SRCS=	device_if.h bus_if.h isa_if.h pci_if.h
SRCS+=	ad1816.c

.include <bsd.kmod.mk>
