# $FreeBSD: release/10.0.0/sys/modules/sound/driver/ad1816/Makefile 70711 2001-01-06 14:00:42Z obrien $

.PATH: ${.CURDIR}/../../../../dev/sound/isa

KMOD=	snd_ad1816
SRCS=	device_if.h bus_if.h isa_if.h pci_if.h
SRCS+=	ad1816.c

.include <bsd.kmod.mk>
