# $FreeBSD: stable/11/usr.bin/bmake/tests/syntax/directive-t0/Makefile 299094 2016-05-04 23:20:53Z ngie $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/syntax/directive-t0

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=	Makefile.test
${PACKAGE}FILES+=	expected.status.1
${PACKAGE}FILES+=	expected.stderr.1
${PACKAGE}FILES+=	expected.stdout.1

.include <bsd.test.mk>
