# $MidnightBSD$
# $FreeBSD: stable/10/kerberos5/usr.bin/string2key/Makefile 287428 2015-09-03 11:33:33Z ume $

PROG=	string2key
MAN=	string2key.8
CFLAGS+=	-I${KRB5DIR}/kdc \
		-I${KRB5DIR}/lib/asn1 \
		-I${KRB5DIR}/lib/krb5 \
		-I${KRB5DIR}/lib/roken \
		-I${KRB5DIR}/lib/windc
DPADD=	${LIBKRB5} ${LIBROKEN} ${LIBASN1} ${LIBCRYPTO} \
	${LIBCRYPT} ${LIBVERS}
LDADD=	-lkrb5 -lroken -lasn1 -lcrypto -lcrypt ${LIBVERS}

.include <bsd.prog.mk>

.PATH: ${KRB5DIR}/kdc
