# $FreeBSD: release/7.0.0/sys/modules/wlan_scan_sta/Makefile 170530 2007-06-11 03:36:55Z sam $

.PATH: ${.CURDIR}/../../net80211

KMOD=	wlan_scan_sta
SRCS=	ieee80211_scan_sta.c

.include <bsd.kmod.mk>
