# $FreeBSD: stable/9/sys/modules/ti/Makefile 153280 2005-12-10 00:38:33Z scottl $

.PATH: ${.CURDIR}/../../dev/ti

KMOD=	if_ti
SRCS=	if_ti.c device_if.h bus_if.h pci_if.h opt_ti.h opt_zero.h

.include <bsd.kmod.mk>
