# $FreeBSD: release/10.0.0/sys/modules/ti/Makefile 255608 2013-09-16 06:25:54Z kib $

.PATH: ${.CURDIR}/../../dev/ti

KMOD=	if_ti
SRCS=	if_ti.c device_if.h bus_if.h pci_if.h opt_ti.h

.include <bsd.kmod.mk>
