# $FreeBSD: stable/11/sys/modules/ti/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/ti

KMOD=	if_ti
SRCS=	if_ti.c device_if.h bus_if.h pci_if.h opt_ti.h

.include <bsd.kmod.mk>
