# $FreeBSD: stable/11/sys/modules/mxge/mxge_rss_eth_z8e/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/mxge
KMOD=	mxge_rss_eth_z8e
SRCS=	mxge_rss_eth_z8e.c

.include <bsd.kmod.mk>
