# $FreeBSD: release/10.0.0/sys/modules/mxge/mxge_rss_eth_z8e/Makefile 175365 2008-01-15 20:34:49Z gallatin $

.PATH: ${.CURDIR}/../../../dev/mxge
KMOD=	mxge_rss_eth_z8e
SRCS=	mxge_rss_eth_z8e.c

.include <bsd.kmod.mk>
