# $MidnightBSD$
# $FreeBSD: stable/10/usr.sbin/cxgbetool/Makefile 314579 2017-03-03 03:11:58Z np $

PROG=	cxgbetool
MAN=	cxgbetool.8
CFLAGS+= -I${SRCTOP}/sys/dev/cxgbe -I${SRCTOP}/sys -I.
WARNS?= 2

.include <bsd.prog.mk>
