# $FreeBSD: stable/11/sys/modules/geom/geom_part/geom_part_pc98/Makefile 285068 2015-07-03 01:50:26Z imp $

.PATH: ${.CURDIR}/../../../../geom/part

KMOD=	geom_part_pc98
SRCS=	g_part_pc98.c

SRCS+=	bus_if.h device_if.h g_part_if.h

.include <bsd.kmod.mk>
