# $FreeBSD: release/7.0.0/usr.sbin/newsyslog/Makefile 126878 2004-03-12 16:03:26Z trhodes $

PROG=	newsyslog
MAN=	newsyslog.8 newsyslog.conf.5
SRCS=	newsyslog.c ptimes.c

WARNS?=	2

.include <bsd.prog.mk>
