# $FreeBSD: stable/11/share/i18n/Makefile 289393 2015-10-15 22:55:08Z bdrewery $
# $NetBSD: Makefile,v 1.1 2003/06/27 08:39:59 tshiozak Exp $

.include <bsd.own.mk>

SUBDIR=	csmapper esdb
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
