# $FreeBSD: release/10.0.0/share/i18n/Makefile 219019 2011-02-25 00:04:39Z gabor $
# $NetBSD: Makefile,v 1.1 2003/06/27 08:39:59 tshiozak Exp $

.include <bsd.own.mk>

SUBDIR=	csmapper esdb

.include <bsd.subdir.mk>
