#	From: @(#)Makefile	1.5 (Berkeley) 6/8/93
# $FreeBSD: release/7.0.0/share/doc/papers/kerntune/Makefile 172506 2007-10-10 16:59:15Z cvs2svn $

VOLUME=		papers
DOC=		kerntune
SRCS=		0.t 1.t 2.t 3.t 4.t
EXTRA=		fig2.pic
MACROS=		-ms
USE_EQN=
USE_PIC=
USE_SOELIM=
USE_TBL=

.include <bsd.doc.mk>
