#	From: @(#)Makefile	1.5 (Berkeley) 6/8/93
# $FreeBSD: release/10.0.0/share/doc/papers/kerntune/Makefile 136910 2004-10-24 15:33:08Z ru $

VOLUME=		papers
DOC=		kerntune
SRCS=		0.t 1.t 2.t 3.t 4.t
EXTRA=		fig2.pic
MACROS=		-ms
USE_EQN=
USE_PIC=
USE_SOELIM=
USE_TBL=

.include <bsd.doc.mk>
