#
# $RISS: if_arl/arlconfig/Makefile,v 1.5 2003/01/13 08:05:29 frol Exp $
# $FreeBSD: release/7.0.0/usr.sbin/arlcontrol/Makefile 141565 2005-02-09 10:35:28Z stefanf $
#

PROG=	arlcontrol
CFLAGS+=	-I${.CURDIR}/../../sys -DARLCACHE
MAN=	arlcontrol.8

.include <bsd.prog.mk>
