# $FreeBSD: release/10.0.0/sys/modules/mxge/mxge_ethp_z8e/Makefile 171500 2007-07-19 16:16:00Z gallatin $

.PATH: ${.CURDIR}/../../../dev/mxge
KMOD=	mxge_ethp_z8e
SRCS=	mxge_ethp_z8e.c

.include <bsd.kmod.mk>
