# $FreeBSD: stable/11/sys/modules/i2c/jedec_dimm/Makefile 329843 2018-02-22 23:18:46Z rpokala $

.PATH:		${.CURDIR}/../../../dev/jedec_dimm
KMOD		= jedec_dimm
SRCS		= jedec_dimm.c jedec_dimm.h bus_if.h device_if.h smbus_if.h

.include <bsd.kmod.mk>
