name: perl
version: 5.014000
abstract: The Perl 5 language interpreter
author: perl5-porters@perl.org
license: perl
resources:
  homepage: http://www.perl.org/
  bugtracker: http://rt.perl.org/perlbug/
  license: http://dev.perl.org/licenses/
  repository: http://perl5.git.perl.org/
distribution_type: core
generated_by: Porting/makemeta
no_index:
  directory:
    - cpan
    - dist/Attribute-Handlers
    - dist/autouse
    - dist/B-Lint
    - dist/base
    - dist/bignum
    - dist/constant
    - dist/Cwd
    - dist/Data-Dumper
    - dist/Devel-SelfStubber
    - dist/Dumpvalue
    - dist/Env
    - dist/ExtUtils-CBuilder
    - dist/ExtUtils-Command
    - dist/ExtUtils-Install
    - dist/ExtUtils-Manifest
    - dist/ExtUtils-ParseXS
    - dist/File-CheckTree
    - dist/Filter-Simple
    - dist/I18N-Collate
    - dist/I18N-LangTags
    - dist/if
    - dist/IO/
    - dist/lib/
    - dist/Locale-Maketext
    - dist/Math-BigInt
    - dist/Math-BigInt-FastCalc
    - dist/Math-BigRat
    - dist/Module-CoreList
    - dist/Net-Ping
    - dist/Pod-Perldoc
    - dist/Safe
    - dist/SelfLoader
    - dist/Storable
    - dist/Thread-Queue
    - dist/Thread-Semaphore
    - dist/threads
    - dist/threads-shared
    - dist/XSLoader
    - lib/version
    - win32
  file:
    - dist/IO/ChangeLog
    - dist/IO/hints/sco.pl
    - dist/IO/IO.pm
    - dist/IO/IO.xs
    - dist/IO/lib/IO/Dir.pm
    - dist/IO/lib/IO/File.pm
    - dist/IO/lib/IO/Handle.pm
    - dist/IO/lib/IO/Pipe.pm
    - dist/IO/lib/IO/Poll.pm
    - dist/IO/lib/IO/Seekable.pm
    - dist/IO/lib/IO/Select.pm
    - dist/IO/lib/IO/Socket.pm
    - dist/IO/lib/IO/Socket/INET.pm
    - dist/IO/lib/IO/Socket/UNIX.pm
    - dist/IO/Makefile.PL
    - dist/IO/poll.c
    - dist/IO/poll.h
    - dist/IO/README
    - dist/IO/t/IO.t
    - dist/IO/t/io_const.t
    - dist/IO/t/io_dir.t
    - dist/IO/t/io_dup.t
    - dist/IO/t/io_file.t
    - dist/IO/t/io_file_export.t
    - dist/IO/t/io_linenum.t
    - dist/IO/t/io_multihomed.t
    - dist/IO/t/io_pipe.t
    - dist/IO/t/io_poll.t
    - dist/IO/t/io_sel.t
    - dist/IO/t/io_sock.t
    - dist/IO/t/io_taint.t
    - dist/IO/t/io_tell.t
    - dist/IO/t/io_udp.t
    - dist/IO/t/io_unix.t
    - dist/IO/t/io_utf8.t
    - dist/IO/t/io_xs.t
    - dist/lib/lib_pm.PL
    - dist/lib/Makefile.PL
    - dist/lib/t/01lib.t
    - lib/Exporter.pm
    - lib/Exporter.t
    - lib/Exporter/Heavy.pm
    - lib/newgetopt.pl
    - lib/unicore/mktables
    - lib/version.pm
    - lib/version.pod
    - lib/version.t
    - pod/perlfilter.pod
    - Porting/Maintainers.pm
    - Porting/perldelta_template.pod
    - TestInit.pm
