# $FreeBSD: stable/11/gnu/usr.bin/groff/src/utils/lkbib/Makefile 291738 2015-12-04 03:17:47Z bdrewery $

PROG_CXX=	lkbib
SRCS=		lkbib.cpp
DPADD=		${LIBBIB} ${LIBGROFF}
LDADD=		${LIBBIB} ${LIBGROFF}
LIBADD=		m
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
