# $FreeBSD: release/10.0.0/usr.sbin/bsdconfig/examples/Makefile 255818 2013-09-23 16:47:52Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/examples/bsdconfig
FILES=		browse_packages_ftp.sh browse_packages_http.sh bsdconfigrc

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
