# $MidnightBSD$
# $FreeBSD: stable/10/lib/libiconv_modules/BIG5/Makefile 260497 2014-01-09 23:08:56Z dim $

SHLIB=	BIG5
SRCS+=	citrus_big5.c
CFLAGS.gcc+= --param max-inline-insns-single=32

.include <bsd.lib.mk>
