#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: release/10.0.0/share/doc/usd/18.msdiffs/Makefile 50476 1999-08-28 00:22:10Z peter $

VOLUME=	usd/18.msdiffs
SRCS=	ms.diffs
MACROS=	-ms

.include <bsd.doc.mk>
