# $FreeBSD: stable/11/sys/modules/siis/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/siis

KMOD=	siis
SRCS=	siis.c siis.h device_if.h bus_if.h pci_if.h opt_cam.h

.include <bsd.kmod.mk>
