# $FreeBSD: release/10.0.0/sys/modules/siis/Makefile 195801 2009-07-21 12:32:46Z mav $

.PATH: ${.CURDIR}/../../dev/siis

KMOD=	siis
SRCS=	siis.c siis.h device_if.h bus_if.h pci_if.h opt_cam.h

.include <bsd.kmod.mk>
