# $FreeBSD: stable/11/lib/libsbuf/tests/Makefile 316557 2017-04-06 05:29:28Z ngie $

ATF_TESTS_C+=	sbuf_core_test
ATF_TESTS_C+=	sbuf_stdio_test
ATF_TESTS_C+=	sbuf_string_test

LIBADD+=	sbuf util

WARNS?=		6

.include <bsd.test.mk>
