# $FreeBSD: stable/11/usr.bin/stat/Makefile 321086 2017-07-17 21:01:10Z ngie $

.include <src.opts.mk>

PROG=	stat

LINKS=	${BINDIR}/stat ${BINDIR}/readlink
MLINKS=	stat.1 readlink.1

SUBDIR.${MK_TESTS}+=	tests

.include <bsd.prog.mk>
