# $FreeBSD: stable/9/sys/modules/mmcsd/Makefile 236089 2012-05-26 09:31:23Z marius $

.PATH: ${.CURDIR}/../../dev/mmc

KMOD=	mmcsd
SRCS=	bus_if.h device_if.h mmcbr_if.h mmcbus_if.h mmcsd.c

.include <bsd.kmod.mk>
