# $FreeBSD: release/10.0.0/sys/modules/mmcsd/Makefile 234524 2012-04-21 01:51:16Z marius $

.PATH: ${.CURDIR}/../../dev/mmc

KMOD=	mmcsd
SRCS=	bus_if.h device_if.h mmcbr_if.h mmcbus_if.h mmcsd.c

.include <bsd.kmod.mk>
