# $FreeBSD: release/7.0.0/sys/modules/mmcsd/Makefile 163519 2006-10-20 06:52:59Z imp $

.PATH: ${.CURDIR}/../../dev/mmc

KMOD=	mmcsd
SRCS=	mmcsd.c mmcbus_if.h device_if.h bus_if.h

.include <bsd.kmod.mk>
