# $FreeBSD: stable/11/include/arpa/Makefile 284345 2015-06-13 19:20:56Z sjg $

.include <src.opts.mk>

INCS=	ftp.h inet.h nameser.h nameser_compat.h tftp.h
INCS+=	telnet.h
INCSDIR=${INCLUDEDIR}/arpa

.include <bsd.prog.mk>
