# $FreeBSD: release/10.0.0/sys/modules/syscons/star/Makefile 106497 2002-11-06 13:47:00Z nyan $

.PATH:	${.CURDIR}/../../../dev/syscons/star

KMOD=	star_saver
SRCS=	star_saver.c

.include <bsd.kmod.mk>
