
# $FreeBSD: release/10.0.0/kerberos5/lib/Makefile 233294 2012-03-22 08:48:42Z stas $

SUBDIR=	libasn1 libgssapi_krb5 libgssapi_ntlm libgssapi_spnego libhdb \
	libheimntlm libhx509 libkadm5clnt libkadm5srv libkafs5 libkrb5 \
	libroken libsl libvers libkdc libwind libheimsqlite libheimbase libheimipcc libheimipcs

.include <bsd.subdir.mk>
