
# $FreeBSD: stable/9/kerberos5/lib/Makefile 178828 2008-05-07 13:53:12Z dfr $

SUBDIR=	libasn1 libgssapi_krb5 libgssapi_ntlm libgssapi_spnego libhdb \
	libheimntlm libhx509 libkadm5clnt libkadm5srv libkafs5 libkrb5 \
	libroken libsl libvers

.include <bsd.subdir.mk>
