# $MidnightBSD$
# $FreeBSD: stable/10/sys/modules/i2c/Makefile 330109 2018-02-28 10:00:02Z rpokala $

SUBDIR =
SUBDIR += controllers if_ic smbus iicbus iicbb iicsmb iic smb jedec_ts
SUBDIR += jedec_dimm

.include <bsd.subdir.mk>
