# $FreeBSD: stable/11/sys/modules/i2c/Makefile 331503 2018-03-24 23:01:10Z ian $

SUBDIR = \
	controllers \
	cyapa \
	ds1307 \
	ds13rtc \
	ds1672 \
	ds3231 \
	icee \
	if_ic \
	iic \
	iicbb \
	iicbus \
	iicsmb \
	isl \
	isl12xx \
	jedec_dimm \
	jedec_ts \
	nxprtc \
	rtc8583 \
	s35390a \
	smb \
	smbus \

.include <bsd.subdir.mk>
