# $FreeBSD: release/7.0.0/usr.sbin/i4b/isdntest/Makefile 113438 2003-04-13 14:21:56Z bde $

PROG=	isdntest
MAN=	isdntest.8
SRCS=	main.c

install:
	@${ECHO} "isdntest is not installed automatically"

.include <bsd.prog.mk>
