# $FreeBSD: stable/11/sys/modules/amdsmn/Makefile 323184 2017-09-05 15:13:41Z cem $

.PATH:	${SRCTOP}/sys/dev/amdsmn

KMOD=	amdsmn
SRCS=	amdsmn.c bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
