# $FreeBSD: stable/11/sys/modules/epic/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/sparc64/ebus

KMOD=	epic
SRCS=	device_if.h epic.c bus_if.h ofw_bus_if.h

.include <bsd.kmod.mk>
