# $FreeBSD: stable/11/gnu/usr.bin/groff/src/preproc/grn/Makefile 291738 2015-12-04 03:17:47Z bdrewery $

PROG_CXX=	grn
SRCS=		hdb.cpp hpoint.cpp hgraph.cpp main.cpp
DPADD=	 	${LIBGROFF}
LDADD=	 	${LIBGROFF}
LIBADD=		m
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
