# $FreeBSD: stable/11/sys/modules/dtb/imx6/Makefile 323399 2017-09-10 23:04:55Z ian $
# All the dts files for imx6 systems we support.
DTS=	\
	imx6dl-cubox-i.dts \
	imx6q-cubox-i.dts \
	imx6dl-hummingboard.dts \
	imx6q-hummingboard.dts \
	imx6dl-nitrogen6x.dts \
	imx6q-nitrogen6_max.dts \
	imx6q-nitrogen6x.dts \
	imx6dl-riotboard.dts \
	imx6dl-wandboard.dts \
	imx6dl-wandboard-revb1.dts \
	imx6q-wandboard.dts \
	imx6q-wandboard-revb1.dts \

.include <bsd.dtb.mk>
