# $MidnightBSD$
# $FreeBSD: stable/10/sys/modules/dtb/imx6/Makefile 284094 2015-06-06 18:49:02Z ian $
# All the dts files for imx6 systems we support.
DTS=	\
	imx6dl-cubox-i.dts \
	imx6q-cubox-i.dts \
	imx6dl-hummingboard.dts \
	imx6q-hummingboard.dts \
	imx6dl-wandboard.dts \
	imx6q-wandboard.dts

.include <bsd.dtb.mk>
