# $FreeBSD: release/7.0.0/sys/modules/rum/Makefile 169306 2007-05-06 10:07:21Z kevlo $

.PATH: ${.CURDIR}/../../dev/usb

KMOD    = if_rum
SRCS    = if_rum.c opt_usb.h device_if.h bus_if.h usbdevs.h

.include <bsd.kmod.mk>
