# $FreeBSD: release/10.0.0/tools/regression/pthread/mutex_isowned_np/Makefile 204311 2010-02-25 14:42:26Z ru $

PROG=	mutex_isowned_np
NO_MAN=
DPADD=	${LIBPTHREAD}
LDADD=	-lpthread

.include <bsd.prog.mk>
