#	@(#)Makefile.inc	8.1 (Berkeley) 6/4/93
# $FreeBSD: release/7.0.0/lib/libc/i386/string/Makefile.inc 113103 2003-04-05 04:17:05Z tjr $

MDSRCS+=bcmp.S bcopy.S bzero.S ffs.S index.S memchr.S memcmp.S memcpy.S \
	memmove.S memset.S rindex.S strcat.S strchr.S strcmp.S strcpy.S \
	strlen.S strncmp.S strrchr.S swab.S wcschr.S wcscmp.S wcslen.S \
	wmemchr.S
