# $FreeBSD: stable/11/lib/libc/i386/string/Makefile.inc 315044 2017-03-11 02:51:29Z brooks $

MDSRCS+= \
	bcmp.S \
	bcopy.S \
	bzero.S \
	ffs.S \
	memchr.S \
	memcmp.S \
	memcpy.S \
	memmove.S \
	memset.S \
	strcat.S \
	strchr.S \
	strcmp.S \
	strcpy.S \
	strncmp.S \
	strrchr.S \
	swab.S \
	wcschr.S \
	wcscmp.S \
	wcslen.S \
	wmemchr.S
