#	@(#)Makefile.inc	8.1 (Berkeley) 6/4/93
# $FreeBSD: release/10.0.0/lib/libc/i386/string/Makefile.inc 229368 2012-01-03 07:14:01Z ed $

MDSRCS+=bcmp.S bcopy.S bzero.S ffs.S memchr.S memcmp.S memcpy.S memmove.S \
	memset.S strcat.S strchr.S strcmp.S strcpy.S strncmp.S strrchr.S \
	swab.S wcschr.S wcscmp.S wcslen.S wmemchr.S
