# $FreeBSD: stable/11/gnu/usr.bin/rcs/Makefile 289393 2015-10-15 22:55:08Z bdrewery $

SUBDIR= lib .WAIT \
	ci co merge rcs rcsclean rcsdiff rcsmerge rlog rcsfreeze
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
