# $FreeBSD: release/10.0.0/sys/modules/geom/geom_sched/Makefile.inc 206497 2010-04-12 16:37:45Z luigi $
# included by geom_sched children

.PATH: ${.CURDIR}/../../../../geom/sched

# 6.x needs this path
#CFLAGS += -I${.CURDIR}/../../../../geom/sched

# .include <bsd.kmod.mk>
