# $FreeBSD: stable/11/sys/modules/geom/geom_sched/Makefile.inc 319182 2017-05-30 04:11:12Z ngie $
# included by geom_sched children

.PATH: ${SRCTOP}/sys/geom/sched

# 6.x needs this path
#CFLAGS += -I${SRCTOP}/sys/geom/sched

# .include <bsd.kmod.mk>
