# $FreeBSD: release/7.0.0/sys/modules/netgraph/atm/atmpif/Makefile 118774 2003-08-11 08:40:02Z harti $
#
# Author: Harti Brandt <harti@freebsd.org>
#
.PATH: ${.CURDIR}/../../../../netgraph/atm/atmpif

KMOD=	ng_atmpif
SRCS=	ng_atmpif.c ng_atmpif_harp.c

.include <bsd.kmod.mk>
