# $FreeBSD: release/7.0.0/gnu/usr.bin/dialog/TESTS/Makefile 139103 2004-12-21 08:47:35Z ru $

NO_OBJ=
FILES=		README checklist ftreebox infobox inputbox menubox msgbox \
		prgbox radiolist textbox treebox yesno
FILESDIR=	${SHAREDIR}/examples/dialog

.include <bsd.prog.mk>
