# $FreeBSD: stable/11/usr.sbin/pc-sysinstall/examples/Makefile 284255 2015-06-11 04:22:17Z sjg $

FILES=	README pc-autoinstall.conf pcinstall.cfg.fbsd-netinstall \
	pcinstall.cfg.geli pcinstall.cfg.gmirror pcinstall.cfg.netinstall \
	pcinstall.cfg.restore pcinstall.cfg.rsync pcinstall.cfg.upgrade \
	pcinstall.cfg.zfs

FILESDIR=${SHAREDIR}/examples/pc-sysinstall

.include <bsd.prog.mk>
