# $FreeBSD: stable/11/sys/modules/ffec/Makefile 323416 2017-09-11 02:14:28Z ian $

.PATH: ${SRCTOP}/sys/dev/ffec

KMOD=	if_ffec
SRCS=	if_ffec.c miibus_if.h device_if.h bus_if.h pci_if.h ofw_bus_if.h opt_global.h

.include <bsd.kmod.mk>
