# $FreeBSD: release/10.0.0/sys/modules/sdhci_pci/Makefile 241600 2012-10-16 01:10:43Z gonzo $

.PATH: ${.CURDIR}/../../dev/sdhci

KMOD=	sdhci_pci
SRCS=	sdhci_pci.c sdhci.h sdhci_if.h device_if.h bus_if.h pci_if.h mmcbr_if.h

.include <bsd.kmod.mk>
