# $FreeBSD: stable/11/sys/modules/sdhci_pci/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/sdhci

KMOD=	sdhci_pci
SRCS=	sdhci_pci.c sdhci.h sdhci_if.h device_if.h bus_if.h pci_if.h mmcbr_if.h

.include <bsd.kmod.mk>
