# $FreeBSD: release/10.0.0/sys/modules/acpi/acpi_ibm/Makefile 193530 2009-06-05 18:44:36Z jkim $

.PATH:		${.CURDIR}/../../../dev/acpi_support
KMOD=		acpi_ibm
SRCS=		acpi_ibm.c opt_acpi.h device_if.h bus_if.h acpi_if.h
SRCS+=		opt_ddb.h

.include <bsd.kmod.mk>
