# $FreeBSD: release/10.0.0/lib/clang/liblldbUtility/Makefile 255722 2013-09-20 01:52:02Z emaste $

.include <bsd.own.mk>

LIB=	lldbUtility

SRCDIR=	tools/lldb/source/Utility
SRCS=	ARM_DWARF_Registers.cpp \
	KQueue.cpp \
	PseudoTerminal.cpp \
	Range.cpp \
	RefCounter.cpp \
	SharingPtr.cpp \
	StringExtractor.cpp \
	StringExtractorGDBRemote.cpp \
	TimeSpecTimeout.cpp

.include "../lldb.lib.mk"
