# $MidnightBSD$
# $FreeBSD: stable/10/lib/clang/liblldbUtility/Makefile 263363 2014-03-19 13:11:35Z emaste $

.include <bsd.own.mk>

LIB=	lldbUtility

SRCDIR=	tools/lldb/source/Utility
SRCS=	ARM_DWARF_Registers.cpp \
	KQueue.cpp \
	PseudoTerminal.cpp \
	Range.cpp \
	SharingPtr.cpp \
	StringExtractor.cpp \
	StringExtractorGDBRemote.cpp \
	TimeSpecTimeout.cpp

.include "../lldb.lib.mk"
