# $FreeBSD: release/10.0.0/sys/modules/syscons/warp/Makefile 106762 2002-11-11 10:11:59Z mux $

.PATH:	${.CURDIR}/../../../dev/syscons/warp

KMOD=	warp_saver
SRCS=	warp_saver.c

.include <bsd.kmod.mk>
