# Makefile copyright Andreas Klemm <andreas@FreeBSD.ORG> 1998
#
# $FreeBSD: release/7.0.0/gnu/usr.bin/dc/doc/Makefile 50472 1999-08-27 23:37:10Z peter $

.PATH:	${.CURDIR}/../../../../contrib/bc/doc

INFO = dc
INFOSECTION= "System Utilities"
INFOENTRY_dc= "* DC: (dc).			The GNU Desktop Calculator."

.include <bsd.info.mk>
