# $FreeBSD: release/10.0.0/sys/modules/amdtemp/Makefile 189768 2009-03-13 16:08:08Z rpaulo $

.PATH:	${.CURDIR}/../../dev/amdtemp

KMOD=	amdtemp
SRCS=	amdtemp.c bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
