# $FreeBSD: stable/11/sys/modules/amdtemp/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:	${SRCTOP}/sys/dev/amdtemp

KMOD=	amdtemp
SRCS=	amdtemp.c bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
