# $FreeBSD: src/sys/modules/amdtemp/Makefile,v 1.1.2.1 2009/05/21 17:09:23 rpaulo Exp $

.PATH:	${.CURDIR}/../../dev/amdtemp

KMOD=	amdtemp
SRCS=	amdtemp.c bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
