#
# $FreeBSD: release/10.0.0/tools/regression/netipx/spxloopback/Makefile 204311 2010-02-25 14:42:26Z ru $
#

PROG=	spxloopback
NO_MAN=

DPADD=	${LIBIPX}
LDADD=	-lipx
WARNS?=	3

.include <bsd.prog.mk>
