# $FreeBSD: stable/11/lib/libcasper/services/cap_pwd/tests/Makefile 305626 2016-09-08 20:01:26Z oshogbo $

TAP_TESTS_C=	pwd_test

LIBADD+=	casper
LIBADD+=	cap_pwd
LIBADD+=	nv

WARNS?=		3

.include <bsd.test.mk>
