#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/10.0.0/usr.sbin/edquota/Makefile 207736 2010-05-07 00:41:12Z mckusick $

PROG=	edquota
MAN=	edquota.8

CSTD=	gnu99
WARNS?=	4

DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
