#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/11/usr.sbin/edquota/Makefile 275054 2014-11-25 16:57:27Z bapt $

PROG=	edquota
MAN=	edquota.8

CSTD=	gnu99
WARNS?=	4

LIBADD=	util

.include <bsd.prog.mk>
