# $FreeBSD: stable/10/usr.bin/bmake/tests/shell/Makefile 266074 2014-05-14 18:43:13Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/shell

TESTS_SUBDIRS=	builtin meta path path_select replace select

.include <bsd.test.mk>
