# $FreeBSD: stable/11/usr.bin/bmake/tests/shell/Makefile 299094 2016-05-04 23:20:53Z ngie $

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/shell

TESTS_SUBDIRS=	builtin meta path path_select replace select

.include <bsd.test.mk>
