# $FreeBSD: release/7.0.0/gnu/usr.bin/binutils/gdb/Makefile.arm 99015 2002-06-29 03:18:28Z obrien $

XSRCS+=	armnbsd-nat.c armnbsd-tdep.c arm-tdep.c \
	core-regset.c
CFLAGS+= -DDEFAULT_BFD_VEC=bfd_elf32_arm_vec
