# $FreeBSD: release/7.0.0/gnu/usr.bin/binutils/gdb/Makefile.ia64 99015 2002-06-29 03:18:28Z obrien $

XSRCS+=	ia64-tdep.c ia64-fbsd-nat.c \
	core-regset.c
CFLAGS+= -DDEFAULT_BFD_VEC=bfd_elf64_ia64_vec
