# $FreeBSD: stable/11/usr.bin/ident/tests/Makefile 316256 2017-03-30 06:20:24Z ngie $

PACKAGE=	tests

ATF_TESTS_SH=	ident_test
${PACKAGE}FILES+=	\
		test.in \
		test.out \
		testnoid

.include <bsd.test.mk>
