#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/11/usr.bin/uniq/Makefile 314818 2017-03-07 01:52:56Z ngie $

.include <src.opts.mk>

PROG=	uniq

.if ${MK_TESTS} != "no"
SUBDIR+=	tests
.endif

.include <bsd.prog.mk>
