# $MidnightBSD$
#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/10/usr.bin/uniq/Makefile 314817 2017-03-07 01:52:50Z ngie $

.include <bsd.own.mk>

PROG=	uniq

.if ${MK_TESTS} != "no"
SUBDIR+=	tests
.endif

.include <bsd.prog.mk>
