#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/env/Makefile,v 1.6 2005/06/20 03:43:25 gad Exp $
# $MidnightBSD: src/usr.bin/env/Makefile,v 1.2 2008/12/29 17:50:21 laffer1 Exp $

PROG=	env
SRCS=	env.c envopts.c

.include <bsd.prog.mk>
