# $FreeBSD: release/10.0.0/secure/lib/Makefile.inc 114283 2003-04-30 07:54:39Z ru $

.include "../Makefile.inc"
.if exists(${.CURDIR}/../../../lib/Makefile.inc)
.include "${.CURDIR}/../../../lib/Makefile.inc"
.endif
