# $FreeBSD: stable/11/usr.bin/clang/llvm-bcanalyzer/Makefile 331838 2018-03-31 11:38:16Z dim $

PROG_CXX=	llvm-bcanalyzer

SRCDIR=		tools/llvm-bcanalyzer
SRCS+=		llvm-bcanalyzer.cpp

.include "../llvm.prog.mk"
