# $FreeBSD: release/10.0.0/lib/clang/liblldbPluginABISysV_x86_64/Makefile 255722 2013-09-20 01:52:02Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginABISysV_x86_64

SRCDIR=	tools/lldb/source/Plugins/ABI/SysV-x86_64
SRCS=	ABISysV_x86_64.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
