# $FreeBSD: stable/11/usr.sbin/mlxcontrol/Makefile 319119 2017-05-29 10:15:41Z ngie $

PROG=	mlxcontrol
MAN=	mlxcontrol.8
SRCS=	command.c config.c interface.c util.c

CFLAGS+= -I${SRCTOP}/sys

WARNS?=	2

.include <bsd.prog.mk>
