# $FreeBSD: release/7.0.0/usr.sbin/mlxcontrol/Makefile 80029 2001-07-20 06:20:32Z obrien $

PROG=	mlxcontrol
MAN=	mlxcontrol.8
SRCS=	command.c config.c interface.c util.c

CFLAGS+= -I${.CURDIR}/../../sys

.include <bsd.prog.mk>
