# $FreeBSD: release/10.0.0/usr.sbin/mlxcontrol/Makefile 201390 2010-01-02 11:07:44Z ed $

PROG=	mlxcontrol
MAN=	mlxcontrol.8
SRCS=	command.c config.c interface.c util.c

CFLAGS+= -I${.CURDIR}/../../sys

WARNS?=	2

.include <bsd.prog.mk>
