.\" Copyright (c) 2010, 2011, 2015, 2021, 2022, 2025, 2026 Lucas Holt
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd April 19, 2026
.Dt MPORT 1
.Os
.Sh NAME
.Nm mport
.Nd package manager for MidnightBSD
.Sh SYNOPSIS
.Nm
.Op Fl b
.Op Fl c Ar chroot-path
.Op Fl f
.Op Fl o Ar output-path
.Op Fl q
.Op Fl U
.Op Fl V
.Op Fl v
.Ar command Op Ar args ...
.Pp
.Nm
.Cm add
.Op Fl A
.Ar package-file ...
.Pp
.Nm
.Cm annotate
.Op Fl a
.Op Fl q
.Fl S
.Ar package
.Ar tag
.Pp
.Nm
.Cm annotate
.Op Fl a
.Op Fl q
.Fl A
.Ar package
.Ar tag
.Ar value
.Pp
.Nm
.Cm annotate
.Fl D
.Ar package
.Ar tag
.Pp
.Nm
.Cm audit
.Op Fl r
.Op Ar package
.Pp
.Nm
.Cm autoremove
.Pp
.Nm
.Cm clean
.Pp
.Nm
.Cm config
.Cm list
.Pp
.Nm
.Cm config
.Cm get
.Ar setting
.Pp
.Nm
.Cm config
.Cm set
.Ar setting
.Ar value
.Pp
.Nm
.Cm cpe
.Op Ar package ...
.Pp
.Nm
.Cm delete
.Ar package ...
.Pp
.Nm
.Cm deleteall
.Pp
.Nm
.Cm download
.Op Fl a
.Op Fl d
.Op Ar package ...
.Pp
.Nm
.Cm export
.Ar file
.Pp
.Nm
.Cm import
.Ar file
.Pp
.Nm
.Cm index
.Pp
.Nm
.Cm info
.Ar package
.Pp
.Nm
.Cm install
.Op Fl A
.Op Fl M
.Op Fl y
.Ar package ...
.Pp
.Nm
.Cm list
.Op Cm updates | Cm up | Cm prime
.Pp
.Nm
.Cm lock
.Ar package
.Pp
.Nm
.Cm locks
.Pp
.Nm
.Cm mirror
.Cm list
.Pp
.Nm
.Cm mirror
.Cm select
.Pp
.Nm
.Cm purl
.Op Ar package ...
.Pp
.Nm
.Cm search
.Ar query ...
.Pp
.Nm
.Cm shell
.Pp
.Nm
.Cm stats
.Pp
.Nm
.Cm unlock
.Ar package
.Pp
.Nm
.Cm update
.Ar package ...
.Pp
.Nm
.Cm upgrade
.Pp
.Nm
.Cm verify
.Op Fl r
.Op Ar package ...
.Pp
.Nm
.Cm version
.Fl t
.Ar version1
.Ar version2
.Pp
.Nm
.Cm which
.Op Fl q
.Op Fl o
.Ar path
.Sh DESCRIPTION
.Nm
installs, upgrades, removes, and inspects
.Xr mport 5
packages.
It can work with repository packages, local package files, and the local
package database.
.Sh OPTIONS
The following global options are supported by
.Nm :
.Bl -tag -width ".Fl o Ar output-path"
.It Fl b, Cm --brief
Use brief output when supported by the command.
.It Fl c Ar chroot-path , Cm --chroot Ar chroot-path
Run inside the specified chroot.
.It Fl f, Cm --force
Force the operation when supported.
This currently applies to commands such as
.Cm install
and
.Cm delete .
.It Fl o Ar output-path , Cm --output Ar output-path
Write downloaded package files to
.Ar output-path .
.It Fl q, Cm --quiet
Reduce output verbosity and suppress download progress.
.It Fl U, Cm --no-index
Skip automatic index updates for this invocation.
.It Fl V, Cm --verbose
Increase output verbosity.
.It Fl v, Cm --version
Display the current version of
.Nm
and exit.
.El
.Sh COMMANDS
The following commands are supported by
.Nm :
.Bl -tag -width ".Cm annotate Fl A Ar package Ar tag Ar value"
.It Cm add Op Fl A Ar package-file ...
Install one or more local
.Pa .mport
package files.
If
.Fl A
is specified, mark the installed package as automatic.
For repository installs, use
.Cm install .
.It Cm annotate Op Fl a Op Fl q Fl S Ar package Ar tag
Show the value of an annotation tag for a package.
With
.Fl a ,
show the tag for all installed packages.
With
.Fl q ,
use abbreviated output suitable for scripts.
.It Cm annotate Op Fl a Op Fl q Fl A Ar package Ar tag Ar value
Add an annotation tag to a package.
.It Cm annotate Fl D Ar package Ar tag
Delete an annotation tag from a package.
.It Cm audit Op Fl r Op Ar package
Display vulnerable installed packages using CPE data matched against the
MidnightBSD security feed.
With
.Fl r ,
also include packages that depend on a vulnerable package.
If
.Ar package
is specified, audit only that package.
.It Cm autoremove
Remove packages that were installed automatically and are no longer required
by any explicitly installed package.
.It Cm clean
Remove package files no longer present in the index and perform maintenance on
the local package database.
.It Cm config list
List all available configuration settings.
.It Cm config get Ar setting
Display the value of
.Ar setting .
.It Cm config set Ar setting Ar value
Set
.Ar setting
to
.Ar value .
.It Cm cpe Op Ar package ...
List Common Platform Enumeration identifiers for installed packages.
If one or more package names are specified, restrict output to those packages.
.It Cm delete Ar package ...
Remove one or more installed packages.
.It Cm deleteall
Remove all installed packages.
This is primarily useful for testing or major operating system upgrades.
.It Cm download Op Fl a Op Fl d Op Ar package ...
Download package files without installing them.
With
.Fl a ,
download all available packages.
With
.Fl d ,
also download dependencies.
.It Cm export Ar file
Export package metadata or a package list to
.Ar file .
.It Cm import Ar file
Import package metadata or a package list from
.Ar file .
.It Cm index
Refresh the package index immediately instead of waiting for the automatic
update interval.
.It Cm info Ar package
Display detailed information about an installed package or an indexed package.
.It Cm install Op Fl A Op Fl M Op Fl y Ar package ...
Fetch and install one or more packages from the configured repository.
With
.Fl A ,
mark the installed packages as automatic.
With
.Fl M ,
ignore missing dependencies and attempt the installation anyway.
With
.Fl y ,
assume yes for confirmation prompts.
.It Cm list Op Cm updates | Cm up | Cm prime
Without arguments, list installed packages.
The
.Cm updates
or
.Cm up
subcommand lists installed packages with updates available.
The
.Cm prime
subcommand lists packages installed explicitly rather than as dependencies.
.It Cm lock Ar package
Prevent a package from being modified by upgrade or delete operations.
.It Cm locks
List all locked packages.
.It Cm mirror list
List available package mirrors.
.It Cm mirror select
Ping known mirrors, select the closest responding mirror, and save it as the
default.
.It Cm purl Op Ar package ...
List Package URL values for installed packages.
If one or more package names are specified, restrict output to those packages.
.It Cm search Ar query ...
Search package names and descriptions.
Glob patterns such as
.Dq *php*
are supported.
.It Cm shell
Start a
.Xr sqlite3 1
session connected to the
.Nm
master package database.
.It Cm stats
Display statistics about available and installed packages.
.It Cm unlock Ar package
Remove a package lock.
.It Cm update Ar package ...
Update one or more installed packages.
Wildcard arguments are supported.
.It Cm upgrade
Upgrade all installed packages to the newest available versions.
.It Cm verify Op Fl r Op Ar package ...
Verify that installed package files have not been deleted or modified.
If package names are provided, verify only those packages.
With
.Fl r ,
recompute and store checksums for the named packages.
This is useful after intentional local modifications.
.It Cm version Fl t Ar version1 Ar version2
Compare two version strings and print
.Ql <
if
.Ar version1
is older,
.Ql =
if they are equal, or
.Ql >
if
.Ar version1
is newer.
.It Cm which Op Fl q Op Fl o Ar path
Show which installed package owns
.Ar path .
With
.Fl q ,
print only the package name and version.
With
.Fl o ,
print the package origin instead.
.El
.Sh SETTINGS
The following configuration settings commonly affect
.Nm
behavior:
.Bl -tag -width ".Cm index_autoupdate"
.It Cm mirror_region
Select the mirror region used for downloads.
Valid values currently include
.Dq us ,
.Dq us2 ,
.Dq us3 ,
.Dq uk ,
and
.Dq jp .
The current list is stored in the
.Pa mirrors
table of
.Pa /var/db/mport/index.db .
.It Cm target_os
Override the operating system version used when fetching and installing
packages.
If unset,
.Nm
checks
.Pa /bin/midnightbsd-version
first and falls back to the running kernel version.
.It Cm index_last_check
Timestamp of the last index update check.
.It Cm index_autoupdate
Enable or disable automatic index refresh.
If set to
.Dq NO
or
.Dq FALSE ,
automatic updates are skipped unless the index is missing.
This is the persistent equivalent of the global
.Fl U
flag.
.It Cm handle_rc_scripts
If set to
.Dq yes
or
.Dq true ,
run rc.d start and stop scripts shipped by packages.
If set to
.Dq no
or
.Dq false ,
do not run them.
.El
.Pp
Use
.Cm mport config list
to see additional settings supported by the local installation.
.Sh ENVIRONMENT
.Bl -tag -width ".Ev FETCH_BIND_ADDRESS"
.It Ev ASSUME_ALWAYS_YES
If set to a non-empty value, answer yes to confirmation prompts.
.It Ev FETCH_BIND_ADDRESS
Bind outgoing network connections to the specified hostname or IP address.
.It Ev FTP_LOGIN
Default FTP login if none was provided in the URL.
.It Ev FTP_PASSIVE_MODE
If set to
.Ql no ,
forces the FTP code to use active mode.
If set to any other value, forces passive mode even if the application
requested active mode.
.It Ev FTP_PASSWORD
Default FTP password if the remote server requests one and none was
provided in the URL.
.It Ev FTP_PROXY
URL of the proxy to use for FTP requests.
If no scheme is specified,
.Dq ftp
is assumed.
.It Ev MPORT_FORCE_HTTP
If set to a non-empty value, fetch package indexes and package bundles over
HTTP by rewriting HTTPS download URLs to HTTP.
.It Ev HANDLE_RC_SCRIPTS
If set to a non-empty value, start or stop rc.d scripts included with the
package.
.El
.Sh EXAMPLES
Search for a package:
.Dl $ mport search curl
.Pp
Install a package from the repository:
.Dl # mport install curl
.Pp
Install a package without refreshing the index:
.Dl # mport -U install curl
.Pp
Install a local package file:
.Dl # mport add /home/myuser/mypkg.mport
.Pp
List installed packages:
.Dl $ mport list
.Pp
List packages needing upgrades:
.Dl $ mport list updates
.Pp
Show detailed package information:
.Dl $ mport info gmake
.Pp
Determine which package installed a file:
.Dl $ mport which /usr/local/bin/curl
.Pp
Lock a package before a system upgrade:
.Dl # mport lock curl
.Pp
Upgrade all installed packages:
.Dl # mport upgrade
.Pp
Upgrade a single package:
.Dl # mport update gmake
.Pp
Remove unneeded dependencies:
.Dl # mport autoremove
.Pp
Check installed packages for checksum mismatches:
.Dl # mport verify
.Pp
Search for all XFCE-related packages:
.Dl $ mport search xfce*
.Sh SEE ALSO
.Xr sqlite3 1
.Sh HISTORY
The
.Nm
command first appeared in
.Mx 0.3 .
.Sh AUTHORS
The
.Nm
utility and manual page were written by
.An Lucas Holt Aq Mt luke@MidnightBSD.org .
