.\" Copyright (c) 2010, 2011, 2015, 2021 Lucas Holt
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd July 3, 2022
.Dt MPORT 1
.Os
.Sh NAME
.Nm mport
.Nd "mport utility"
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl c Ao chroot path Ac
.Ao command Ac
.Pp
.Nm
.Cm autoremove
.Nm
.Cm clean
.Nm
.Cm config get
.Op Ar setting name
.Nm
.Cm config set
.Op Ar setting name
.Op Ar setting value
.Nm
.Cm cpe
.Nm
.Cm list
.Nm
.Cm list updates
.Nm
.Cm list prime
.Nm
.Cm info
.Op Ar name
.Nm
.Cm delete
.Op Ar name
.Nm
.Cm deleteall
.Nm
.Cm download
.Op Ar name
.Nm
.Cm index
.Nm
.Cm install
.Op Ar name
.Nm
.Cm mirror list
.Nm
.Cm search
.Op Ar name ...
.Nm
.Cm stats
.Nm
.Cm update
.Op Ar name
.Nm
.Cm upgrade
.Nm
.Cm verify
.Sh DESCRIPTION
The
.Nm
command installs or removes mport packages, and displays information on
installed packages.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width indent
.It Fl v, Cm --version
Display the current version of 
.Nm .
.It Fl c Ao chroot path Ac , Cm --chroot Ao chroot path Ac
.Nm
will chroot in the
.Ao chroot path Ac
environment.
.Sh COMMANDS
The following commands are supported by
.Nm :
.Bl -tag -width ".Cm install"
.It Cm autoremove
Experimental! Removes all packages installed as dependencies that are no longer needed
as the original package depending on them has been removed.
.It Cm clean
Clean up old packages not found in the index and perform maintenence on the
database.
.It Cm config get Ao name Ac
Displays the value of a configuration setting
.It Cm config set Ao name Ac Ao value Ac
Sets the value of the configuration setting. 
.It Cm cpe
List all CPE information for each installed package
.It Cm list
List all currently installed packages
.It Cm list updates
List currently installed packages with updates available
.It Cm list prime
List all packages explicitly installed rather than as a dependency
.It Cm info
Print detailed information about a package
.It Cm delete
Delete or uninstall a package
.It Cm deleteall
Delete or uninstall all packages on the system.  Useful for major OS upgrades,
or testing.
.It Cm download
Download a package, but do not install it. Useful for later offline installations.
.It Cm index
Force a download of the index to refresh it without waiting for the timeout interval. This
allows the user to get the latest list of packages.
.It Cm install
Fetch and install a package
.It Cm mirror list
Lists all available package mirrors.
.It Cm search
Search package names and descriptions.  Supports globbing queries such as 
"*php*".
.It Cm stats
List statistics about available and installed packages.
.It Cm update
Fetch and update a specific package
.It Cm upgrade
Upgrade all currently installed packages with the latest version
.It Cm verify
Verify currently installed packages have not had files deleted or modified from the original
installation.
.Sh SETTINGS
The
.Nm
command has the following settings that modify it's behavior:
.It Cm mirror_region
Determines which mirror region to use to fetch packages.  Valid values are currently us, us2, us3, uk, jp
The current list is always available in the mport index file in /var/db/mport/index.db in the mirrors table
.It Cm target_os
Override the OS version used to fetch packages and install them. If undefined, we try /bin/midnightbsd-version first and
fall back to the running kernel version.
.It Cm index_last_check
This is the last time the index file was checked for an update.
.Sh HISTORY
The
.Nm
command first appeared in
.Mx 0.3 .
.Sh AUTHORS
The
.Nm
utility and 
manual page were written by
.An Lucas Holt Aq luke@MidnightBSD.org .
