.\" Copyright (c) 2010, 2011, 2015, 2021, 2022 Lucas Holt
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd Januar 25, 2024
.Dt MPORT 1
.Os
.Sh NAME
.Nm mport
.Nd "mport package manager"
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl c Ao chroot path Ac
.Op Fl f
.Op Fl o Ao output path Ac
.Op Fl q
.Op Fl V
.Ao command Ac
.Pp
.Nm
.Cm add
.Op Fl A
.Op Ar name
.Nm
.Cm autoremove
.Nm
.Cm clean
.Nm
.Cm config get
.Op Ar setting name
.Nm
.Cm config set
.Op Ar setting name
.Op Ar setting value
.Nm
.Cm audit
.Nm
.Cm cpe
.Nm
.Cm list
.Nm
.Cm list updates
.Nm
.Cm list prime
.Nm
.Cm info
.Op Ar name
.Nm
.Cm delete
.Op Ar name
.Nm
.Cm deleteall
.Nm
.Cm download
.Op Fl d
.Op Ar name
.Nm
.Cm index
.Nm
.Cm install
.Op Fl A
.Op Ar name
.Nm
.Cm mirror list
.Nm
.Cm mirror select
.Nm
.Cm purl
.Nm
.Cm search
.Op Ar name ...
.Nm
.Cm shell
.Nm
.Cm stats
.Nm
.Cm update
.Op Ar name
.Nm
.Cm upgrade
.Nm
.Cm verify
.Sh DESCRIPTION
The
.Nm
command installs or removes mport packages, and displays information on
installed packages.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width indent
.It Fl v, Cm --version
Display the current version of 
.Nm .
.It Fl c Ao chroot path Ac , Cm --chroot Ao chroot path Ac
.Nm
will chroot in the
.Ao chroot path Ac
.It Fl q, Cm --quiet
Make output less verbose and hide download progress.
.It Fl V, Cm --verbose
Make output more verbose.
.It Fl f, Cm --force
Force the operation.  Supported for install and delete currently.
.It Fl o Ao output path Ac , Cm --output Ao output path Ac
.Nm
will download packages into the 
.Ao output path Ac
.Sh COMMANDS
The following commands are supported by
.Nm :
.Bl -tag -width ".Cm install"
.It Cm add Ao name Ac
Installs a local package file and also attempts to install any missing dependencies in the path specified.
For online installs, use mport install instead.
.It Cm audit
Displays vulnerable packages installed on the system. Uses CPE data to match against
a NVD feed provided by the MidnightBSD project.
.It Cm autoremove
Experimental! Removes all packages installed as dependencies that are no longer needed
as the original package depending on them has been removed.
.It Cm clean
Clean up old packages not found in the index and perform maintenence on the
database.
.It Cm config get Ao name Ac
Displays the value of a configuration setting
.It Cm config set Ao name Ac Ao value Ac
Sets the value of the configuration setting. 
.It Cm cpe
List all CPE information for each installed package
.It Cm list
List all currently installed packages
.It Cm list updates
List currently installed packages with updates available
.It Cm list prime
List all packages explicitly installed rather than as a dependency
.It Cm info Ao name Ac
Print detailed information about a package
.It Cm delete Ao name Ac
Delete or uninstall a package
.It Cm deleteall
Delete or uninstall all packages on the system.  Useful for major OS upgrades,
or testing.
.It Cm download Ao name Ac
Download a package, but do not install it. Useful for later offline installations.
The d flag will allow it to download dependencies as well.
.It Cm index
Force a download of the index to refresh it without waiting for the timeout interval. This
allows the user to get the latest list of packages.
.It Cm install Fl A Ao name Ac
Fetch and install a package.  
With the A flag set, marks the installed packages as automatic.  Will be automatically
removed	if no other packages depend on them.
.It Cm mirror list
Lists all available package mirrors.
.It Cm mirror select
Pings various mirrors to attempt to select the closest and sets it as default.
.It Cm purl
Lists PURL for each installed package
.It Cm search
Search package names and descriptions.  Supports globbing queries such as 
"*php*".
.It Cm shell
Starts a sqlite3 client connected to the mport master database.
.It Cm stats
List statistics about available and installed packages.
.It Cm update Ao name Ac
Fetch and update a specific package
.It Cm upgrade
Upgrade all currently installed packages with the latest version
.It Cm verify
Verify currently installed packages have not had files deleted or modified from the original
installation.
.Sh SETTINGS
The
.Nm
command has the following settings that modify it's behavior:
.Dl mirror_region
Determines which mirror region to use to fetch packages.  Valid values are currently us, us2, us3, uk, jp
The current list is always available in the mport index file in /var/db/mport/index.db in the mirrors table
.Pp
.Dl target_os
Override the OS version used to fetch packages and install them. If undefined, we try /bin/midnightbsd-version first and
fall back to the running kernel version.
.Pp
.Dl index_last_check
This is the last time the index file was checked for an update.
.Pp
.Dl index_autoupdate
Determines if the index file will be updated automatically. If set to NO or FALSE, it will be skipped unless
it is missing entirely. A persistent version of the mport -U flag. 
.Pp
.Dl handle_rc_scripts
When set to yes or true, will start and stop rc.d services included with the package. If set to no or false, will not run rc.d scripts.
.Sh ENVIRONMENT
.Bl -tag -width ".Ev FETCH_BIND_ADDRESS"
.It Ev FETCH_BIND_ADDRESS
Specifies a hostname or IP address to which sockets used for outgoing
connections will be bound.
.It Ev FTP_LOGIN
Default FTP login if none was provided in the URL.
.It Ev FTP_PASSIVE_MODE
If set to
.Ql no ,
forces the FTP code to use active mode.
If set to any other value, forces passive mode even if the application
requested active mode.
.It Ev FTP_PASSWORD
Default FTP password if the remote server requests one and none was
provided in the URL.
.It Ev FTP_PROXY
URL of the proxy to use for FTP requests.
The document part is ignored.
FTP and HTTP proxies are supported; if no scheme is specified, FTP is
assumed.
If the proxy is an FTP proxy,
.It Ev ASSUME_ALWAYS_YES
If set to a non empty value, will assume any question should be answered
with a yes.
.It Ev HANDLE_RC_SCRIPTS
If set to a non empty value, will start/stop rc.d scripts included in the package.
.Sh EXAMPLES
Search for a package:
.Dl $ mport search curl
.Pp
Install a package:
.Dl Installing must specify a unique origin
.Pp
.Dl % mport install curl
.Pp
List installed packages:
.Dl $ mport list
.Pp
Upgrade all installed packages:
.Dl % mport upgrade
.Pp
Upgrade a single package:
.Dl % mport update gmake
.Pp
List packages needing upgrades:
.Dl $ mport list updates
.Pp
List non-automatic packages:
.Dl $ mport list prime
.Pp
Delete an installed package:
.Dl % mport delete curl
.Pp
Remove unneeded dependencies:
.Dl % mport autoremove
.Pp
Determine which package installed a file:
.Dl $ mport which /usr/local/bin/curl
.Pp
Check installed packages for checksum mismatches:
.Dl # mport verify
.Pp 
Install a local package file:
.Dl $ mport add /home/myuser/mypkg.mport 
.Sh HISTORY
The
.Nm
command first appeared in
.Mx 0.3 .
.Sh AUTHORS
The
.Nm
utility and 
manual page were written by
.An Lucas Holt Aq luke@MidnightBSD.org .
