# $FreeBSD: release/10.0.0/sys/modules/cc/cc_cdg/Makefile 252504 2013-07-02 08:44:56Z lstewart $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/../../../netinet/cc
KMOD=	cc_cdg
SRCS=	cc_cdg.c

.include <bsd.kmod.mk>
