# $FreeBSD: release/10.0.0/sys/modules/netgraph/cisco/Makefile 89260 2002-01-11 15:49:02Z ru $
# $Whistle: Makefile,v 1.2 1999/01/19 19:39:20 archie Exp $

KMOD=	ng_cisco
SRCS= 	ng_cisco.c

.include <bsd.kmod.mk>
