# $FreeBSD: release/10.0.0/sys/modules/wbwd/Makefile 232614 2012-03-06 18:44:52Z bz $

.PATH: ${.CURDIR}/../../dev/wbwd

KMOD=	wbwd
SRCS=	wbwd.c
SRCS+=	bus_if.h device_if.h isa_if.h

.include <bsd.kmod.mk>
