# $FreeBSD: release/7.0.0/usr.sbin/setfmac/Makefile 140909 2005-01-27 14:52:47Z delphij $

PROG=   setfmac
LINKS=	${BINDIR}/setfmac ${BINDIR}/setfsmac
MAN=	setfmac.8 setfsmac.8

WARNS?=	6

.include <bsd.prog.mk>
