# $MidnightBSD$
# $FreeBSD: stable/10/lib/libc/tests/termios/Makefile 313488 2017-02-09 22:49:48Z ngie $

.include <bsd.own.mk>

NETBSD_ATF_TESTS_C=	tcsetpgrp_test

.include "../Makefile.netbsd-tests"

.include <bsd.test.mk>
