$ $FreeBSD: stable/11/usr.bin/grep/nls/es_ES.ISO8859-1.msg 322584 2017-08-16 17:46:45Z kevans $
$
$set 1
$quote "
1 "(entrada estándar)"
2 "no se puede leer el fichero comprimido bzip2"
3 "opción desconocida de %s"
4 "uso: %s [-abcDEFGHhIiJLlmnOoPqRSsUVvwxZz] [-A no] [-B no] [-C[no]]\n"
5 "\t[-e pauta] [-f fichero] [--binary-files=valor] [--color=cuando]\n"
6 "\t[--context[=no]] [--directories=acción] [--label] [--line-buffered]\n"
7 "\t[--null] [pauta] [fichero ...]\n"
8 "fichero binario %s se ajusta\n"
9 "%s (BSD grep) %s\n"
10 "%s (BSD grep, GNU compatible) %s\n"
