$ $FreeBSD: src/usr.bin/grep/nls/pt_BR.ISO8859-1.msg,v 1.2 2010/07/29 18:02:57 gabor Exp $
$
$set 1
$quote "
1 "(entrada padrão)"
2 "não se posso ler o fichero comprimido bzip2"
3 "opcão não conhecida de %s"
4 "uso: %s [-abcDEFGHhIiJLlmnOoPqRSsUVvwxZ] [-A num] [-B num] [-C[num]]\n"
5 "\t[-e padrão] [-f arquivo] [--binary-files=valor] [--color=quando]\n"
6 "\t[--context[=num]] [--directories=ação] [--label] [--line-buffered]\n"
7 "\t[--null] [padrão] [arquivo ...]\n"
8 "arquivo binário %s casa com o padrão\n"
9 "%s (BSD grep) %s\n"
