#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: release/7.0.0/sbin/dumpfs/Makefile 122670 2003-11-14 13:13:23Z johan $

PROG=	dumpfs
DPADD=	${LIBUFS}
LDADD=	-lufs
MAN=	dumpfs.8

.include <bsd.prog.mk>
