#	$FreeBSD: release/10.0.0/sys/modules/acpi/acpi_video/Makefile 193530 2009-06-05 18:44:36Z jkim $

.PATH:	${.CURDIR}/../../../dev/acpica

KMOD=	acpi_video
SRCS=	acpi_video.c
SRCS+=	opt_acpi.h acpi_if.h bus_if.h device_if.h

.include <bsd.kmod.mk>
