# $FreeBSD: release/10.0.0/sys/modules/netgraph/hole/Makefile 89260 2002-01-11 15:49:02Z ru $
# $Whistle: Makefile,v 1.2 1999/01/19 19:39:21 archie Exp $

KMOD=	ng_hole
SRCS= 	ng_hole.c

.include <bsd.kmod.mk>
