#	@(#)Makefile	8.1 (Berkeley) 3/31/94
# $FreeBSD: release/7.0.0/games/random/Makefile 110928 2003-02-15 10:26:10Z seanc $

PROG=	random
MAN=	random.6
SRCS=	random.c randomize_fd.c
WARNS?=	5

.include <bsd.prog.mk>
