#
# $FreeBSD: stable/11/sys/modules/tests/callout_test/Makefile 319182 2017-05-30 04:11:12Z ngie $
#

.PATH: ${SRCTOP}/sys/tests/callout_test

KMOD=	callout_test
SRCS=	callout_test.c

#
# Enable full debugging
#
#CFLAGS += -g

.include <bsd.kmod.mk>
