# $FreeBSD: release/10.0.0/sys/modules/i2c/iicsmb/Makefile 93023 2002-03-23 15:49:15Z nsouch $

.PATH:		${.CURDIR}/../../../dev/iicbus
KMOD		= iicsmb
SRCS		= device_if.h bus_if.h iicbus_if.h \
		  smbus_if.h iicsmb.c

.include <bsd.kmod.mk>
