# $MidnightBSD$
# $FreeBSD: stable/10/tools/tools/netrate/juggle/Makefile 276486 2014-12-31 23:25:37Z ngie $

PROG=	juggle
MAN=
WARNS?=	3
DPADD=	${LIBPTHREAD}
LDADD=	-lpthread

.include <bsd.prog.mk>
