# $FreeBSD: release/10.0.0/gnu/usr.bin/groff/src/utils/pfbtops/Makefile 75592 2001-04-17 12:37:18Z ru $

PROG=		pfbtops
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
