# $FreeBSD: release/10.0.0/sys/modules/my/Makefile 167453 2007-03-11 15:20:04Z brueffer $

.PATH: ${.CURDIR}/../../dev/my

KMOD=	if_my
SRCS=	if_my.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
