
# $FreeBSD: stable/11/sys/modules/lpt/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:	${SRCTOP}/sys/dev/ppbus
KMOD=	lpt
SRCS=	bus_if.h device_if.h ppbus_if.h \
	opt_lpt.h \
	lpt.c

.include <bsd.kmod.mk>
