
# $FreeBSD: release/10.0.0/sys/modules/lpt/Makefile 89260 2002-01-11 15:49:02Z ru $

.PATH:	${.CURDIR}/../../dev/ppbus
KMOD=	lpt
SRCS=	bus_if.h device_if.h ppbus_if.h \
	opt_lpt.h \
	lpt.c

.include <bsd.kmod.mk>
