#	@(#)Makefile	8.1 (Berkeley) 6/4/93
# $FreeBSD: release/7.0.0/libexec/makekey/Makefile 125503 2004-02-05 22:44:25Z ru $

PROG=	makekey
MAN=	makekey.8

DPADD=	${LIBCRYPT}
LDADD=	-lcrypt

.include <bsd.prog.mk>
