# $FreeBSD: stable/11/usr.bin/alias/Makefile 284255 2015-06-11 04:22:17Z sjg $

SCRIPTS=generic.sh
SCRIPTSNAME=alias

LINKS=	${BINDIR}/alias ${BINDIR}/bg \
	${BINDIR}/alias ${BINDIR}/cd \
	${BINDIR}/alias ${BINDIR}/command \
	${BINDIR}/alias ${BINDIR}/fc \
	${BINDIR}/alias ${BINDIR}/fg \
	${BINDIR}/alias ${BINDIR}/getopts \
	${BINDIR}/alias ${BINDIR}/hash \
	${BINDIR}/alias ${BINDIR}/jobs \
	${BINDIR}/alias ${BINDIR}/read \
	${BINDIR}/alias ${BINDIR}/type \
	${BINDIR}/alias ${BINDIR}/ulimit \
	${BINDIR}/alias ${BINDIR}/umask \
	${BINDIR}/alias ${BINDIR}/unalias \
	${BINDIR}/alias ${BINDIR}/wait

.include <bsd.prog.mk>
