# $FreeBSD: release/9.2.0/usr.bin/clang/llvm-ranlib/Makefile 252723 2013-07-04 20:17:04Z dim $

.include <bsd.own.mk>

PROG_CXX=llvm-ranlib

SRCDIR=	tools/llvm-ranlib
SRCS=	llvm-ranlib.cpp

LIBDEPS=llvmarchive \
	llvmbitreader \
	llvmcore \
	llvmsupport

.include "../clang.prog.mk"
