# $FreeBSD: release/10.0.0/sys/modules/i2c/if_ic/Makefile 93023 2002-03-23 15:49:15Z nsouch $

.PATH:		${.CURDIR}/../../../dev/iicbus
KMOD		= if_ic
SRCS		= device_if.h bus_if.h iicbus_if.h \
		  if_ic.c

.include <bsd.kmod.mk>
