# $FreeBSD: stable/11/sys/modules/i2c/if_ic/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:		${SRCTOP}/sys/dev/iicbus
KMOD		= if_ic
SRCS		= device_if.h bus_if.h iicbus_if.h \
		  if_ic.c

.include <bsd.kmod.mk>
