# $FreeBSD: stable/11/lib/libc/tests/ttyio/Makefile 299094 2016-05-04 23:20:53Z ngie $

.include <bsd.own.mk>

# TODO: ptm_test
NETBSD_ATF_TESTS_C=	ttyio_test

LIBADD.ttyio_test+=	util

.include "../Makefile.netbsd-tests"

.include <bsd.test.mk>
