# $FreeBSD: stable/11/libexec/rpc.rstatd/Makefile 275077 2014-11-25 21:18:18Z bapt $

PROG =	rpc.rstatd
SRCS =	rstatd.c rstat_proc.c
MAN =	rpc.rstatd.8

LIBADD=	rpcsvc devstat

WARNS?=	1

.include <bsd.prog.mk>
