# $MidnightBSD$
# $FreeBSD: stable/10/cddl/lib/libumem/Makefile 321270 2017-07-20 01:01:16Z ngie $

.PATH: ${SRCTOP}/cddl/compat/opensolaris/lib/libumem

LIB=	umem
SRCS=	umem.c
WARNS?=	3
CFLAGS+= -I${SRCTOP}/cddl/compat/opensolaris/lib/libumem

.include <bsd.lib.mk>
