# $FreeBSD: stable/11/cddl/lib/libumem/Makefile 321268 2017-07-20 00:53:50Z ngie $

.PATH: ${SRCTOP}/cddl/compat/opensolaris/lib/libumem

LIB=	umem
SRCS=	umem.c
WARNS?=	3
CFLAGS+= -I${SRCTOP}/cddl/compat/opensolaris/lib/libumem

.include <bsd.lib.mk>
