# $MidnightBSD: src/cddl/lib/libumem/Makefile,v 1.2 2008/10/15 19:10:19 laffer1 Exp $
# $FreeBSD: src/cddl/lib/libumem/Makefile,v 1.2 2007/04/16 21:20:25 ru Exp $

.PATH: ${.CURDIR}/../../../cddl/compat/opensolaris/lib/libumem

LIB=	umem
SRCS=	umem.c
WARNS?=	0
CFLAGS+= -I${.CURDIR}/../../../cddl/compat/opensolaris/lib/libumem

.include <bsd.lib.mk>
