# $FreeBSD: release/10.0.0/usr.bin/rpcgen/Makefile 201386 2010-01-02 10:27:05Z ed $

PROG=	rpcgen
SRCS=	rpc_main.c  rpc_clntout.c rpc_cout.c rpc_hout.c rpc_parse.c \
	rpc_sample.c rpc_scan.c rpc_svcout.c rpc_tblout.c rpc_util.c

.include <bsd.prog.mk>
