# $FreeBSD: release/7.0.0/usr.bin/rpcgen/Makefile 149680 2005-08-31 19:44:40Z stefanf $

PROG=	rpcgen
SRCS=	rpc_main.c  rpc_clntout.c rpc_cout.c rpc_hout.c rpc_parse.c \
	rpc_sample.c rpc_scan.c rpc_svcout.c rpc_tblout.c rpc_util.c

WARNS?=	2

.include <bsd.prog.mk>
