# $FreeBSD: release/10.0.0/gnu/usr.bin/texinfo/infokey/Makefile 146522 2005-05-23 10:52:07Z ru $

PROG=	infokey
SRCS=	infokey.c key.c

DPADD=	${LIBTXI}
LDADD=	${LIBTXI}

.include <bsd.prog.mk>

.PATH:	${TXIDIR}/info ${TXIDIR}/doc
