# $MidnightBSD: src/sys/modules/dtrace/lockstat/Makefile,v 1.1 2012/03/28 21:16:38 laffer1 Exp $
# $FreeBSD: src/sys/modules/dtrace/lockstat/Makefile,v 1.1.2.1.2.1 2008/11/25 02:59:29 kensmith Exp $

.PATH: ${.CURDIR}/../../../cddl/dev/lockstat

KMOD=		lockstat
SRCS=		lockstat.c 

SRCS+=		vnode_if.h opt_kdtrace.h

CFLAGS+=	-I${.CURDIR}/../../../cddl/compat/opensolaris \
		-I${.CURDIR}/../../../cddl/contrib/opensolaris/uts/common \
		-I${.CURDIR}/../../..

.include <bsd.kmod.mk>
