# $FreeBSD: stable/11/sys/modules/netgraph/iface/Makefile 269540 2014-08-04 22:37:02Z imp $
# $Whistle: Makefile,v 1.2 1999/01/19 19:39:21 archie Exp $

KMOD=	ng_iface
SRCS= 	ng_iface.c opt_inet.h opt_inet6.h

.include <bsd.kmod.mk>
