# $MidnightBSD$
# $FreeBSD: stable/10/usr.bin/pr/tests/Makefile 320706 2017-07-06 05:20:30Z ngie $

ATF_TESTS_SH+=    	basic2_test
NETBSD_ATF_TESTS_SH=    basic

FILES+=	across.out
FILES+=	d_basic.in
FILES+=	d_basic.out
FILES+=	merge.out
FILES+=	other.in
FILES+=	threecol.out

BINDIR=	${TESTSDIR}

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
