# $FreeBSD: stable/11/usr.bin/pr/tests/Makefile 316501 2017-04-04 20:03:57Z asomers $

PACKAGE=	tests

ATF_TESTS_SH+=    	basic2_test
NETBSD_ATF_TESTS_SH=    basic

${PACKAGE}FILES+=	across.out
${PACKAGE}FILES+=	d_basic.in
${PACKAGE}FILES+=	d_basic.out
${PACKAGE}FILES+=	merge.out
${PACKAGE}FILES+=	other.in
${PACKAGE}FILES+=	threecol.out

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
