# $FreeBSD: stable/11/usr.bin/bmake/tests/basic/t0/Makefile 299094 2016-05-04 23:20:53Z ngie $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/basic/t0

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=	expected.status.1
${PACKAGE}FILES+=	expected.stderr.1
${PACKAGE}FILES+=	expected.stdout.1

.include <bsd.test.mk>
