#
#      The FreeBSD Documentation Project
#      The FreeBSD French Documentation Project
#
#      $Id: Makefile,v 1.1.1.2 2006-02-25 02:35:16 laffer1 Exp $
#      $FreeBSD: src/release/doc/fr_FR.ISO8859-1/installation/Makefile,v 1.3 2002/10/19 21:49:09 gioria Exp $
#      Original revision: 1.4

RELN_ROOT?= ${.CURDIR}/../..

SUBDIR = alpha
SUBDIR+= i386
SUBDIR+= pc98
SUBDIR+= sparc64

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
