#	@(#)Makefile	8.1 (Berkeley) 7/19/93
# $FreeBSD: release/10.0.0/usr.bin/rlogin/Makefile 221123 2011-04-27 17:36:37Z jhb $

PROG=	rlogin

BINOWN=	root
BINMODE=4555
PRECIOUSPROG=

.include <bsd.prog.mk>
