# $MidnightBSD$
# $FreeBSD: stable/10/usr.bin/atf/tests/Makefile 257853 2013-11-08 14:33:41Z jmmv $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/usr.bin/atf

.PATH:		${.CURDIR:H:H:H}/tests
KYUAFILE=	yes

.include <bsd.test.mk>
