# $FreeBSD: release/10.0.0/tools/tools/mwl/mwlstats/Makefile 193242 2009-06-01 18:27:16Z sam $

PROG=	mwlstats
BINDIR=	/usr/local/bin
NO_MAN=

SRCS=	main.c statfoo.c mwlstats.c

.include <bsd.prog.mk>

CFLAGS+= -I.
