#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: src/share/misc/Makefile,v 1.23 2004/12/21 08:46:53 ru Exp $
# $MidnightBSD$

FILES=	acronyms airport ascii birthtoken bsd-family-tree eqnchar flowers init.ee \
	inter.phone iso3166 iso639 latin1 man.template mdoc.template na.phone \
	operator pci_vendors scsi_modes usb_hid_usages zipcodes
NO_OBJ=
FILESDIR=	${BINDIR}/misc

.include <bsd.prog.mk>
