#!/bin/sh

# $Id: reconf,v 1.1.1.1 2010-01-16 16:03:11 laffer1 Exp $

autoreconf
# We do not use automake but we need its install-sh file. We do not 
# care about the exit code.
automake --add-missing || true
