# $FreeBSD: stable/11/sys/modules/nctgpio/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:	${SRCTOP}/sys/dev/nctgpio
KMOD=	nctgpio
SRCS=	nctgpio.c
SRCS+=	device_if.h bus_if.h isa_if.h gpio_if.h opt_platform.h

.include <bsd.kmod.mk>
