# $Id: Makefile,v 1.2 2012-04-08 14:24:04 laffer1 Exp $
# $FreeBSD: src/lib/libautofs/Makefile,v 1.5 2007/05/21 02:49:02 deischen Exp $
# $MidnightBSD$

LIB=	autofs
SHLIB_MAJOR= 2
WARNS?=	4

SRCS=	libautofs.c
INCS=	libautofs.h
MAN=	libautofs.3

.include <bsd.lib.mk>
