# $Id: Makefile,v 1.1.1.3 2008-10-30 20:39:05 laffer1 Exp $
# $FreeBSD: src/lib/libautofs/Makefile,v 1.5 2007/05/21 02:49:02 deischen Exp $

LIB=	autofs
SHLIB_MAJOR= 2
WARNS?=	4

SRCS=	libautofs.c
INCS=	libautofs.h
MAN=	libautofs.3

.include <bsd.lib.mk>
