# $Id: Makefile,v 1.5 2004/09/08 08:12:21 bright Exp $
# $FreeBSD: release/7.0.0/lib/libautofs/Makefile 169807 2007-05-21 02:49:08Z deischen $

LIB=	autofs
SHLIB_MAJOR= 2
WARNS?=	4

SRCS=	libautofs.c
INCS=	libautofs.h
MAN=	libautofs.3

.include <bsd.lib.mk>
