# $FreeBSD: release/7.0.0/usr.sbin/named.reload/Makefile 135549 2004-09-21 19:01:48Z des $

SCRIPTS=	named.reload.sh
MAN=		named.reload.8

LINKS=		${BINDIR}/named.reload ${BINDIR}/named.reconfig
MLINKS=		named.reload.8 named.reconfig.8

.include <bsd.prog.mk>
