# $FreeBSD: stable/9/sys/boot/userboot/test/Makefile 223695 2011-06-30 16:08:56Z dfr $


NO_MAN=
WITHOUT_SSP=

.include <bsd.own.mk>

PROG=		test
INTERNALPROG=

CFLAGS+=	-I${.CURDIR}/..
CFLAGS+=	-I${.CURDIR}/../../..

.include <bsd.prog.mk>
