# $FreeBSD: release/10.0.0/sys/boot/userboot/test/Makefile 255944 2013-09-29 20:20:17Z bdrewery $


NO_MAN=

.include <bsd.own.mk>
MK_SSP=		no

PROG=		test
INTERNALPROG=

CFLAGS+=	-I${.CURDIR}/..
CFLAGS+=	-I${.CURDIR}/../../..

.include <bsd.prog.mk>
