# $MidnightBSD$
# $FreeBSD: stable/10/sys/boot/userboot/test/Makefile 276486 2014-12-31 23:25:37Z ngie $


MAN=

.include <bsd.own.mk>
MK_SSP=		no

PROG=		test
INTERNALPROG=

CFLAGS+=	-I${.CURDIR}/..
CFLAGS+=	-I${.CURDIR}/../../..

.include <bsd.prog.mk>
