# $FreeBSD: release/7.0.0/sys/modules/ugen/Makefile 146957 2005-06-04 10:58:39Z schweikh $

.PATH: ${.CURDIR}/../../dev/usb

KMOD=	ugen
SRCS=	bus_if.h device_if.h opt_usb.h ugen.c usbdevs.h

.include <bsd.kmod.mk>
