# ex:ts=8
#
# Makefile for amd
# 	This file is under a "BSD" copyright (c) by David O'Brien 1998
#
# $FreeBSD: release/10.0.0/usr.sbin/amd/Makefile 80029 2001-07-20 06:20:32Z obrien $

SUBDIR= include libamu amd amq doc fixmount fsinfo hlfsd mk-amd-map pawd \
	scripts wire-test

.include <bsd.subdir.mk>
