# ex:ts=8
#
# Makefile for amd
# 	This file is under a "BSD" copyright (c) by David O'Brien 1998
#
# $FreeBSD: stable/11/usr.sbin/amd/Makefile 288266 2015-09-26 14:13:51Z bdrewery $

SUBDIR= include libamu .WAIT \
	amd amq fixmount fsinfo hlfsd mk-amd-map pawd \
	scripts wire-test
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
