# $FreeBSD: release/10.0.0/sys/modules/netgraph/frame_relay/Makefile 89260 2002-01-11 15:49:02Z ru $
# $Whistle: Makefile,v 1.1 1999/01/19 19:39:21 archie Exp $

KMOD=	ng_frame_relay
SRCS= 	ng_frame_relay.c

.include <bsd.kmod.mk>
