#$FreeBSD: stable/11/sys/modules/chromebook_platform/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/chromebook_platform
KMOD= chromebook_platform
SRCS= chromebook_platform.c bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
