# $FreeBSD: stable/11/usr.sbin/lpr/Makefile 288266 2015-09-26 14:13:51Z bdrewery $

SUBDIR=	common_source .WAIT \
	chkprintcap lp lpc lpd lpq lpr lprm lptest pac \
	filters filters.ru
SUBDIR_PARALLEL=

# Questions/ideas for lpr & friends could also be sent to:
#	freebsd-print@bostonradio.org

.include <bsd.subdir.mk>
