# $FreeBSD: release/10.0.0/usr.sbin/lpr/Makefile 216178 2010-12-04 10:11:20Z uqs $

SUBDIR=	common_source chkprintcap lp lpc lpd lpq lpr lprm lptest pac \
	filters filters.ru

# Questions/ideas for lpr & friends could also be sent to:
#	freebsd-print@bostonradio.org

.include <bsd.subdir.mk>
