# $FreeBSD: release/7.0.0/usr.sbin/lpr/Makefile 116231 2003-06-12 03:32:21Z gad $

SUBDIR=	common_source chkprintcap lp lpc lpd lpq lpr lprm lptest pac \
	filters filters.ru SMM.doc

# Questions/ideas for lpr & friends could also be sent to:
#	freebsd-print@bostonradio.org

.include <bsd.subdir.mk>
