# $FreeBSD: release/7.0.0/sys/modules/sysvipc/sysvsem/Makefile 141562 2005-02-09 08:35:24Z obrien $

.PATH: ${.CURDIR}/../../../kern

KMOD=	sysvsem
SRCS=	sysv_sem.c opt_mac.h opt_sysvipc.h

.include <bsd.kmod.mk>
