# $FreeBSD: release/10.0.0/sys/modules/sysvipc/sysvsem/Makefile 213781 2010-10-13 14:44:38Z rpaulo $

.PATH: ${.CURDIR}/../../../kern

KMOD=	sysvsem
SRCS=	sysv_sem.c opt_sysvipc.h opt_compat.h

.include <bsd.kmod.mk>
