# $FreeBSD: stable/11/sys/modules/sysvipc/sysvsem/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/kern

KMOD=	sysvsem
SRCS=	sysv_sem.c opt_sysvipc.h opt_compat.h

.include <bsd.kmod.mk>
