# $FreeBSD: release/10.0.0/usr.bin/clang/macho-dump/Makefile 246705 2013-02-12 05:56:00Z andrew $

NO_MAN=
.include <bsd.own.mk>

PROG_CXX=macho-dump

SRCDIR=	tools/macho-dump
SRCS=	macho-dump.cpp

LIBDEPS=llvmobject \
	llvmsupport

.include "../clang.prog.mk"
