# $FreeBSD: release/9.2.0/usr.bin/clang/macho-dump/Makefile 252723 2013-07-04 20:17:04Z dim $

NO_MAN=
.include <bsd.own.mk>

PROG_CXX=macho-dump

SRCDIR=	tools/macho-dump
SRCS=	macho-dump.cpp

LIBDEPS=llvmobject \
	llvmsupport

.include "../clang.prog.mk"
