# $MidnightBSD$
# $FreeBSD: stable/10/cddl/usr.sbin/dtrace/tests/Makefile 313488 2017-02-09 22:49:48Z ngie $

.include <bsd.own.mk>

TESTS_SUBDIRS+=	common

.PATH:		${SRCTOP}/tests
KYUAFILE=	YES

.PATH:		${.CURDIR}/tools
SCRIPTSDIR=	${TESTSDIR}
SCRIPTS=	dtest.sh

.include <bsd.test.mk>
