# $FreeBSD: stable/11/cddl/usr.sbin/dtrace/tests/Makefile 299094 2016-05-04 23:20:53Z ngie $

.include <bsd.own.mk>

TESTS_SUBDIRS+=	common

.PATH:		${SRCTOP}/tests
KYUAFILE=	yes

.PATH:		${.CURDIR}/tools
SCRIPTSDIR=	${TESTSDIR}
SCRIPTS=	dtest.sh

.include <bsd.test.mk>
