# $MidnightBSD$
# $FreeBSD: stable/10/lib/libc/tests/iconv/Makefile 319252 2017-05-30 21:03:44Z asomers $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/lib/libc/iconv

ATF_TESTS_C+=	iconvctl_test
WARNS?=		2

.include <bsd.test.mk>
