# $FreeBSD: release/10.0.0/sys/modules/syscons/green/Makefile 89260 2002-01-11 15:49:02Z ru $

.PATH:	${.CURDIR}/../../../dev/syscons/green

KMOD=	green_saver
SRCS=	green_saver.c

.include <bsd.kmod.mk>
