# $FreeBSD: release/10.0.0/sys/modules/drm/tdfx/Makefile 124472 2004-01-13 11:28:51Z ru $

.PATH:	${.CURDIR}/../../../dev/drm
KMOD	= tdfx
SRCS	= tdfx_drv.c
SRCS	+=device_if.h bus_if.h pci_if.h opt_drm.h

.include <bsd.kmod.mk>
