# $FreeBSD: release/10.0.0/lib/libvmmapi/Makefile 245678 2013-01-20 03:42:49Z neel $

LIB=	vmmapi
SRCS=	vmmapi.c vmmapi_freebsd.c
INCS=	vmmapi.h

WARNS?=	2

CFLAGS+= -I${.CURDIR}

.include <bsd.lib.mk>
