#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: release/7.0.0/usr.sbin/route6d/Makefile 160755 2006-07-27 15:31:13Z yar $

PROG=	route6d
MAN=	route6d.8

CFLAGS+= -DHAVE_POLL_H

.include <bsd.prog.mk>
