#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: release/10.0.0/usr.sbin/route6d/Makefile 201390 2010-01-02 11:07:44Z ed $

PROG=	route6d
MAN=	route6d.8

CFLAGS+= -DHAVE_POLL_H

WARNS?=	1

.include <bsd.prog.mk>
