#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/7.0.0/usr.sbin/rwhod/Makefile 113091 2003-04-04 17:49:21Z obrien $

PROG=	rwhod
MAN=	rwhod.8

# XXX breaks on Alpha due to alignment constraints
#WARNS?=	4

.include <bsd.prog.mk>
