# $FreeBSD: src/usr.bin/unzip/Makefile,v 1.1.2.1 2009/08/03 08:13:06 kensmith Exp $
# $MidnightBSD$

PROG = unzip
WARNS ?= 6
CSTD = c99
DPADD = ${LIBARCHIVE}
LDADD = -larchive

.include <bsd.prog.mk>
