# $FreeBSD: release/7.0.0/sys/modules/sound/driver/ich/Makefile 110498 2003-02-07 13:56:33Z nyan $

.PATH:		${.CURDIR}/../../../../dev/sound/pci
KMOD		= snd_ich
SRCS		= device_if.h bus_if.h pci_if.h
SRCS		+= ich.c

.include <bsd.kmod.mk>
