# $FreeBSD: stable/10/usr.bin/bmake/tests/archives/Makefile 266074 2014-05-14 18:43:13Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/archives

TESTS_SUBDIRS=	fmt_44bsd fmt_44bsd_mod fmt_oldbsd

.include <bsd.test.mk>
