# $FreeBSD: stable/11/usr.bin/bmake/tests/archives/Makefile 299094 2016-05-04 23:20:53Z ngie $

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/archives

TESTS_SUBDIRS=	fmt_44bsd fmt_44bsd_mod fmt_oldbsd

.include <bsd.test.mk>
