# $FreeBSD: release/10.0.0/release/picobsd/tinyware/view/Makefile 139103 2004-12-21 08:47:35Z ru $

PROG=view
SRCS=view.c
CFLAGS+=-I/usr/local/include
LDADD+=-L/usr/local/lib -lpng -lvgl -lz -lm
NO_MAN=

.include <bsd.prog.mk>
