# $MidnightBSD$
# $FreeBSD: stable/10/release/picobsd/tinyware/view/Makefile 276486 2014-12-31 23:25:37Z ngie $

PROG=view
SRCS=view.c
CFLAGS+=-I/usr/local/include
LDADD+=-L/usr/local/lib -lpng -lvgl -lz -lm
MAN=

.include <bsd.prog.mk>
