# $FreeBSD: stable/11/sys/modules/ata/ataisa/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/ata

KMOD=	ataisa
SRCS=	ata-isa.c
SRCS+=	ata_if.h bus_if.h device_if.h isa_if.h

.include <bsd.kmod.mk>
