# $FreeBSD: release/10.0.0/sys/modules/ata/ataisa/Makefile 249213 2013-04-06 19:12:49Z marius $

.PATH: ${.CURDIR}/../../../dev/ata

KMOD=	ataisa
SRCS=	ata-isa.c
SRCS+=	ata_if.h bus_if.h device_if.h isa_if.h

.include <bsd.kmod.mk>
