# $MidnightBSD$
# $FreeBSD: stable/10/sys/modules/geom/geom_shsec/Makefile 140074 2005-01-11 18:06:44Z pjd $

.PATH: ${.CURDIR}/../../../geom/shsec

KMOD=	geom_shsec
SRCS=	g_shsec.c

.include <bsd.kmod.mk>
