# $FreeBSD: release/7.0.0/sys/modules/ufm/Makefile 131186 2004-06-27 12:33:20Z imp $

.PATH:	${.CURDIR}/../../dev/usb
KMOD=	ufm
SRCS=	bus_if.h device_if.h vnode_if.h opt_usb.h ufm.c dsbr100io.h usbdevs.h

.include <bsd.kmod.mk>
