#	$NetBSD: Makefile,v 1.2 1998/07/12 20:40:45 augustss Exp $
#	FreeBSD $FreeBSD: release/7.0.0/usr.sbin/usbdevs/Makefile 80029 2001-07-20 06:20:32Z obrien $

PROG=	usbdevs
MAN=	usbdevs.8

WARNS?=	2

.include <bsd.prog.mk>
