# $MidnightBSD$
# $FreeBSD: stable/10/lib/libiconv_modules/UES/Makefile 260497 2014-01-09 23:08:56Z dim $

SHLIB=	UES
SRCS+=	citrus_ues.c
CFLAGS.gcc+= --param max-inline-insns-single=64

.include <bsd.lib.mk>
