# $MidnightBSD$
# $FreeBSD: stable/10/usr.bin/mkulzma/Makefile 292588 2015-12-22 08:03:23Z delphij $

PROG=	mkulzma
MAN=	mkulzma.8
DPADD=	${LIBLZMA} ${LIBPTHREAD}
LDADD=	-llzma -lpthread

.include <bsd.prog.mk>
