# $FreeBSD: stable/11/gnu/usr.bin/groff/src/roff/groff/Makefile 291738 2015-12-04 03:17:47Z bdrewery $

PROG_CXX=	groff
SRCS=		groff.cpp pipeline.c
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
LIBADD=		m
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
