# $FreeBSD: release/7.0.0/sbin/newfs_msdos/Makefile 140691 2005-01-24 01:56:06Z cognet $

PROG=	newfs_msdos
MAN=	newfs_msdos.8

.if ${MACHINE_ARCH} == "arm"
WARNS?= 3
.else
WARNS?=	6
.endif

.include <bsd.prog.mk>
