#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: release/10.0.0/games/fortune/strfile/Makefile 203923 2010-02-15 14:32:00Z uqs $

PROG=	strfile
MAN=	strfile.8
MLINKS= strfile.8 unstr.8

.include <bsd.prog.mk>
