#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: release/7.0.0/games/fortune/strfile/Makefile 142327 2005-02-23 20:42:47Z ru $

PROG=	strfile
MAN=	strfile.8
MLINKS= strfile.8 unstr.8
WARNS?=	6

.include <bsd.prog.mk>
