# $FreeBSD: release/10.0.0/include/protocols/Makefile 139103 2004-12-21 08:47:35Z ru $

NO_OBJ=
INCS=	dumprestore.h routed.h rwhod.h talkd.h timed.h
INCSDIR=${INCLUDEDIR}/protocols

.include <bsd.prog.mk>
