# $FreeBSD: stable/11/sys/modules/i2c/cyapa/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:		${SRCTOP}/sys/dev/cyapa
KMOD		= cyapa
SRCS		= cyapa.c device_if.h bus_if.h iicbus_if.h vnode_if.h

.include <bsd.kmod.mk>
