# $MidnightBSD: src/usr.sbin/mport/Makefile,v 1.4 2011/03/07 20:02:23 laffer1 Exp $

PROG= mport

CFLAGS= -I${.CURDIR}/../../lib/libmport/

DPADD=  ${LIBMPORT}
LDADD=  -lmport

.include <bsd.prog.mk>
