.\" Copyright (c) 2010, 2011, 2015 Lucas Holt
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $MidnightBSD$
.\"
.Dd November 29, 2015
.Dt MPORT 1
.Os
.Sh NAME
.Nm mport
.Nd "mport utility"
.Sh SYNOPSIS
.Nm
.Cm clean
.Nm
.Cm cpe
.Nm
.Cm list
.Ar updates
.Nm
.Cm info
.Op Ar name
.Nm
.Cm delete
.Op Ar name
.Nm
.Cm deleteall
.Nm
.Cm download
.Op Ar name
.Nm
.Cm index
.Nm
.Cm install
.Op Ar name
.Nm
.Cm search
.Op Ar name ...
.Nm
.Cm stats
.Nm
.Cm update
.Op Ar name
.Nm
.Cm upgrade
.Nm
.Cm verify
.Sh DESCRIPTION
The
.Nm
command installs or removes mport packages, and displays information on
installed packages.
.Pp
Here is the list of standard commands:
.Bl -tag -width ".Cm install"
.It Cm clean
Clean up old packages not found in the index and perform maintenence on the
database.
.It Cm cpe
List all CPE information for each installed package
.It Cm list
List all currently installed packages
.It Cm info
Print detailed information about a package
.It Cm delete
Delete or uninstall a package
.It Cm deleteall
Delete or uninstall all packages on the system.  Useful for major OS upgrades,
or testing.
.It Cm download
Download a package, but do not install it. Useful for later offline installations.
.It Cm index
Force a download of the index to refresh it without waiting for the timeout interval. This
allows the user to get the latest list of packages.
.It Cm install
Fetch and install a package
.It Cm search
Search package names and descriptions.  Supports globbing queries such as 
"*php*".
.It Cm stats
List statistcs about available and installed packages.
.It Cm update
Fetch and update a specific package
.It Cm upgrade
Upgrade all currently installed packages with the latest version
.It Cm verify
Verify currently installed packages have not had files deleted or modified from the original
installation.
.Sh HISTORY
The
.Nm
command first appeared in
.Mx 0.3 .
.Sh AUTHORS
The
.Nm
utility and 
manual page were written by
.An Lucas Holt Aq luke@MidnightBSD.org .
