# $FreeBSD: stable/11/sys/modules/bios/smbios/Makefile 319182 2017-05-30 04:11:12Z ngie $
#

.PATH:  ${SRCTOP}/sys/x86/bios

KMOD=	smbios
SRCS=	smbios.c \
	bus_if.h device_if.h

.include <bsd.kmod.mk>
