# $FreeBSD: release/7.0.0/sys/modules/bios/smbios/Makefile 112798 2003-03-29 15:20:45Z mdodd $
#

.PATH:  ${.CURDIR}/../../../i386/bios

KMOD=	smbios
SRCS=	smbios.c \
	bus_if.h device_if.h

.include <bsd.kmod.mk>
