# $FreeBSD: release/10.0.0/usr.bin/svn/Makefile 251886 2013-06-18 02:53:45Z peter $

SUBDIR = lib svn svnadmin svndumpfilter svnlook svnserve svnsync svnversion svnmucc svnrdump

.include <bsd.subdir.mk>
