# $FreeBSD: stable/11/usr.bin/svn/Makefile 289180 2015-10-12 09:53:55Z peter $

SUBDIR=	lib .WAIT \
	svn svnadmin svnbench svndumpfilter svnfsfs svnlook svnserve \
	svnsync svnversion svnmucc svnrdump
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
