# $FreeBSD: stable/9/secure/lib/libcrypto/engines/Makefile 160819 2006-07-29 19:41:41Z simon $

SUBDIR=	lib4758cca libaep libatalla libcswift libchil libnuron \
	libsureware libubsec

.include <bsd.subdir.mk>
