# $FreeBSD: stable/11/secure/lib/libcrypto/engines/Makefile 292287 2015-12-15 19:57:56Z bdrewery $

SUBDIR=	lib4758cca libaep libatalla libcapi libchil libcswift libgost \
	libnuron libsureware libubsec
SUBDIR_PARALLEL=
.include <bsd.subdir.mk>
