# $FreeBSD: release/10.0.0/secure/lib/libcrypto/engines/Makefile 238405 2012-07-12 19:30:53Z jkim $

SUBDIR=	lib4758cca libaep libatalla libchil libcswift libgost libnuron \
	libsureware libubsec

.include <bsd.subdir.mk>
