# $FreeBSD: release/10.0.0/usr.sbin/bsdconfig/password/share/Makefile 240684 2012-09-18 22:28:42Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/bsdconfig/password
FILES=		password.subr

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
