#	@(#)Makefile	8.1 (Berkeley) 7/19/93
# $FreeBSD: release/7.0.0/usr.bin/rsh/Makefile 140909 2005-01-27 14:52:47Z delphij $

PROG=	rsh
CFLAGS+=-I${.CURDIR}/../../libexec/rlogind

BINOWN=	root
BINMODE=4555
PRECIOUSPROG=

.include <bsd.prog.mk>
