# $MidnightBSD: src/etc/defaults/Makefile,v 1.2 2006/08/28 01:35:54 laffer1 Exp $

FILES=	bluetooth.device.conf devfs.rules periodic.conf rc.conf
NO_OBJ=
FILESDIR= /etc/defaults

.include <bsd.prog.mk>
