# $FreeBSD: release/7.0.0/etc/defaults/Makefile 153272 2005-12-09 15:19:31Z ru $

FILES=	bluetooth.device.conf devfs.rules pccard.conf periodic.conf rc.conf
NO_OBJ=
FILESDIR= /etc/defaults

.include <bsd.prog.mk>
