# $FreeBSD: release/10.0.0/etc/defaults/Makefile 223543 2011-06-25 17:01:46Z hselasky $

FILES=	bluetooth.device.conf devfs.rules periodic.conf rc.conf
NO_OBJ=
FILESDIR= /etc/defaults

.include <bsd.prog.mk>
