# $FreeBSD: release/10.0.0/lib/libcom_err/doc/Makefile 50476 1999-08-28 00:22:10Z peter $

INFO=	com_err
INFOSECTION= "Programming & development tools."
INFOENTRY_com_err= "* libcom_err: (com_err).        A Common Error Description Library for UNIX."

.include <bsd.info.mk>
