# $MidnightBSD$
# $FreeBSD: stable/10/usr.bin/getconf/tests/Makefile 318436 2017-05-18 01:43:30Z ngie $

ATF_TESTS_SH+=	getconf_test

PROGS+=		arch_type

BINDIR=		${TESTSDIR}

WARNS?=		6

.include <bsd.test.mk>
