# $FreeBSD: release/10.0.0/sys/modules/acpi/acpi_sony/Makefile 193530 2009-06-05 18:44:36Z jkim $

.PATH:		${.CURDIR}/../../../dev/acpi_support

KMOD=		acpi_sony
SRCS=		acpi_sony.c opt_acpi.h device_if.h bus_if.h acpi_if.h

.include <bsd.kmod.mk>
