# $Id: Makefile,v 1.1.1.2 2006-02-25 02:38:23 laffer1 Exp $
# $FreeBSD: src/usr.sbin/acpi/acpiconf/Makefile,v 1.5 2004/11/13 01:54:22 philip Exp $

PROG=	acpiconf
MAN=	acpiconf.8
WARNS?=	6

.include <bsd.prog.mk>
