# $Id: Makefile,v 1.2 2000/07/14 18:16:25 iwasaki Exp $
# $FreeBSD: release/7.0.0/usr.sbin/acpi/acpiconf/Makefile 137638 2004-11-13 01:54:22Z philip $

PROG=	acpiconf
MAN=	acpiconf.8
WARNS?=	6

.include <bsd.prog.mk>
