# $Id: Makefile,v 1.2 2012-06-25 02:46:25 laffer1 Exp $
# $FreeBSD: src/usr.sbin/acpi/acpiconf/Makefile,v 1.5 2004/11/13 01:54:22 philip Exp $

PROG=	acpiconf
MAN=	acpiconf.8
WARNS?=	6

CFLAGS+=-fno-strict-aliasing

.include <bsd.prog.mk>
