# $FreeBSD: stable/11/stand/lua/Makefile 355345 2019-12-03 18:25:16Z kevans $

.include <bsd.init.mk>

MAN=	cli.lua.8 \
	color.lua.8 \
	config.lua.8 \
	core.lua.8 \
	drawer.lua.8 \
	hook.lua.8 \
	menu.lua.8 \
	password.lua.8 \
	screen.lua.8

FILESDIR=	${LUAPATH}
FILES=	cli.lua \
	color.lua \
	config.lua \
	core.lua \
	drawer.lua \
	hook.lua \
	loader.lua \
	logo-beastie.lua \
	logo-beastiebw.lua \
	logo-fbsdbw.lua \
	logo-orb.lua \
	logo-orbbw.lua \
	menu.lua \
	password.lua \
	screen.lua

.include <bsd.prog.mk>
