# $FreeBSD: stable/11/lib/libc/mips/string/Makefile.inc 315044 2017-03-11 02:51:29Z brooks $

MDSRCS+= \
	bcmp.S \
	bcopy.S \
	bzero.S \
	ffs.S \
	memcpy.S \
	memmove.S \
	strchr.S \
	strcmp.S \
	strlen.S \
	strrchr.S
