# $FreeBSD: stable/11/sys/modules/dtb/allwinner/Makefile 308272 2016-11-04 00:34:12Z manu $
# All the dts files for allwinner systems we support.
DTS=	\
	bananapi.dts \
	bananapim2.dts \
	cubieboard.dts \
	cubieboard2.dts \
	olimex-a20-som-evb.dts \
	olinuxino-lime.dts \
	pcduino3.dts \
	sinovoip-bpi-m3.dts \
	sun5i-a13-olinuxino.dts

.include <bsd.dtb.mk>
