# $FreeBSD: release/10.0.0/share/i18n/esdb/CP/Makefile 219019 2011-02-25 00:04:39Z gabor $
# $NetBSD: Makefile.inc,v 1.4 2008/10/25 22:27:35 apb Exp $

CODE=	CP
SED_EXP= "s/CPx/CP%%PART%%/"
NO_SEP=	 yes

.include "../Makefile.part"
