# $FreeBSD: release/7.0.0/sys/modules/uark/Makefile 164295 2006-11-15 09:13:25Z maxim $

.PATH: ${.CURDIR}/../../dev/usb

KMOD=	uark
SRCS=	uark.c opt_usb.h bus_if.h device_if.h usbdevs.h

.include <bsd.kmod.mk>
