# $FreeBSD: stable/9/lib/clang/libllvmruntimedyld/Makefile 246637 2013-02-10 21:24:47Z dim $

.include <bsd.own.mk>

LIB=	llvmruntimedyld

SRCDIR=	lib/ExecutionEngine/RuntimeDyld
SRCS=	GDBRegistrar.cpp \
	RuntimeDyld.cpp \
	RuntimeDyldELF.cpp \
	RuntimeDyldMachO.cpp

.include "../clang.lib.mk"
