# $FreeBSD: release/10.0.0/sys/modules/i2c/controllers/nfsmb/Makefile 153618 2005-12-21 15:49:51Z ru $

.PATH: ${.CURDIR}/../../../../pci

KMOD=	nfsmb
SRCS=	nfsmb.c
SRCS+=	device_if.h smbus_if.h pci_if.h bus_if.h

.include <bsd.kmod.mk>
