# $FreeBSD: release/10.0.0/sys/modules/alc/Makefile 193880 2009-06-10 02:07:58Z yongari $

.PATH: ${.CURDIR}/../../dev/alc

KMOD=	if_alc
SRCS=	if_alc.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
