# $FreeBSD: release/10.0.0/lib/clang/libllvmx86utils/Makefile 246259 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvmx86utils

SRCDIR=	lib/Target/X86/Utils
INCDIR=	lib/Target/X86
SRCS=	X86ShuffleDecode.cpp

.include "../clang.lib.mk"
