# $FreeBSD: stable/9/lib/clang/libllvmx86utils/Makefile 246637 2013-02-10 21:24:47Z dim $

.include <bsd.own.mk>

LIB=	llvmx86utils

SRCDIR=	lib/Target/X86/Utils
INCDIR=	lib/Target/X86
SRCS=	X86ShuffleDecode.cpp

.include "../clang.lib.mk"
