# $FreeBSD: src/gnu/usr.bin/cvs/Makefile,v 1.16 2005/06/03 15:08:29 imp Exp $
# $MidnightBSD: src/gnu/usr.bin/cvs/Makefile,v 1.2 2007/04/06 17:59:29 laffer1 Exp $

SUBDIR = lib libdiff cvs contrib doc

.include <bsd.subdir.mk>
