# $FreeBSD: release/10.0.0/share/security/Makefile 139103 2004-12-21 08:47:35Z ru $

FILES=	lomac-policy.contexts
NO_OBJ=
FILESDIR=	${BINDIR}/security

.include "${.CURDIR}/../Makefile.inc"
.include <bsd.prog.mk>
