# $FreeBSD: stable/11/share/security/Makefile 291347 2015-11-26 01:14:27Z bdrewery $

FILES=	lomac-policy.contexts
FILESDIR=	${BINDIR}/security

.include "${.CURDIR}/../Makefile.inc"
.include <bsd.prog.mk>
