# $MidnightBSD$
# $FreeBSD: src/usr.bin/make/Makefile.dist,v 1.6 2008/03/04 05:35:27 imp Exp $
# a simple makefile to help builds on !FreeBSD systems
pmake:
	@echo 'make started.'
	cc -D__dead2="" -D__unused="" -Darc4random=random -D__FBSDID="static const char *id=" -DDEFSHELLNAME=\"sh\" -I. -c *.c
	cc *.o -o pmake
	@echo 'make completed.'

clean:
	@rm -f *.o pmake
