# $FreeBSD: release/7.0.0/usr.bin/make/Makefile.dist 146571 2005-05-24 13:19:40Z harti $
# a very simple makefile...
pmake:
	@echo 'make started.'
	cc -DDEFSHELLNAME=\"sh\" -I. -c *.c
	cc *.o -o pmake
	@echo 'make completed.'
