# $FreeBSD: release/10.0.0/share/i18n/esdb/EUC/Makefile 219019 2011-02-25 00:04:39Z gabor $
# $NetBSD: Makefile.inc,v 1.1 2003/06/27 08:40:55 tshiozak Exp $

CODE=	EUC
NO_PREPROC= yes

.include "../Makefile.part"
