# $MidnightBSD$
# $FreeBSD: stable/10/tests/sys/geom/class/nop/Makefile 312828 2017-01-26 20:10:31Z asomers $

TESTSDIR=	${TESTSBASE}/sys/geom/class/${.CURDIR:T}

ATF_TESTS_SH+=	nop_test

.include <bsd.test.mk>
