# $FreeBSD: stable/11/tests/sys/geom/class/nop/Makefile 312829 2017-01-26 20:15:14Z asomers $

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/sys/geom/class/${.CURDIR:T}

ATF_TESTS_SH+=	nop_test

.include <bsd.test.mk>
