# $FreeBSD: stable/11/usr.sbin/pc-sysinstall/doc/Makefile 284321 2015-06-12 14:30:27Z sjg $

FILES=	help-disk-list help-disk-size help-index help-start-autoinstall

FILESDIR=${SHAREDIR}/pc-sysinstall/doc

.include <bsd.prog.mk>
