# $FreeBSD: release/10.0.0/usr.sbin/services_mkdb/Makefile 241777 2012-10-20 10:33:15Z ed $

PROG=	services_mkdb
MAN=	services_mkdb.8
SRCS=	services_mkdb.c uniq.c extern.h

DPADD+=	${LIBUTIL}
LDADD+=	-lutil

.include <bsd.prog.mk>
