# $FreeBSD: stable/9/usr.sbin/services_mkdb/Makefile 206156 2010-04-04 08:38:14Z ume $

PROG=	services_mkdb
MAN=	services_mkdb.8
SRCS=	services_mkdb.c uniq.c

DPADD+=	${LIBUTIL}
LDADD+=	-lutil

.include <bsd.prog.mk>
