# $MidnightBSD$
# $FreeBSD: stable/10/usr.bin/uniq/tests/Makefile 314817 2017-03-07 01:52:50Z ngie $

NETBSD_ATF_TESTS_SH=	uniq_test

FILES+=	d_basic.in
FILES+=	d_basic.out
FILES+=	d_counts.out
FILES+=	d_input.in
FILES+=	d_show_duplicates.out
FILES+=	d_show_uniques.out

BINDIR=	${TESTSDIR}

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
