# $FreeBSD: stable/11/usr.bin/uniq/tests/Makefile 312127 2017-01-14 06:51:31Z ngie $

PACKAGE=		tests

NETBSD_ATF_TESTS_SH=	uniq_test

${PACKAGE}FILES+=	d_basic.in
${PACKAGE}FILES+=	d_basic.out
${PACKAGE}FILES+=	d_counts.out
${PACKAGE}FILES+=	d_input.in
${PACKAGE}FILES+=	d_show_duplicates.out
${PACKAGE}FILES+=	d_show_uniques.out

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
