# $FreeBSD: release/7.0.0/sys/modules/cryptodev/Makefile 168190 2007-03-31 23:15:11Z sam $

.PATH:	${.CURDIR}/../../opencrypto
KMOD	= cryptodev
SRCS	= cryptodev.c
SRCS	+= bus_if.h device_if.h

.include <bsd.kmod.mk>
