# $FreeBSD: release/7.0.0/sys/modules/ural/Makefile 150636 2005-09-27 18:10:43Z mlaier $

.PATH: ${.CURDIR}/../../dev/usb

KMOD    = if_ural
SRCS    = if_ural.c opt_usb.h device_if.h bus_if.h usbdevs.h

.include <bsd.kmod.mk>
