# $FreeBSD: stable/11/sys/modules/ntb/ntb_transport/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:  ${SRCTOP}/sys/dev/ntb

KMOD    = ntb_transport
SRCS    = ntb_transport.c
SRCS += device_if.h bus_if.h ntb_if.h

.include <bsd.kmod.mk>
