# $FreeBSD: release/7.0.0/usr.sbin/i4b/isdnphone/Makefile 80029 2001-07-20 06:20:32Z obrien $

PROG=	isdnphone
MAN=	isdnphone.8
SRCS=	main.c display.c audio.c isdn.c

DPADD=	${LIBCURSES}
LDADD=	-lcurses

.include <bsd.prog.mk>
