#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: release/7.0.0/sbin/badsect/Makefile 111265 2003-02-22 21:33:42Z johan $

PROG=	badsect
DPADD=	${LIBUFS}
LDADD=	-lufs
MAN=	badsect.8

.include <bsd.prog.mk>
