#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: release/10.0.0/sbin/badsect/Makefile 198236 2009-10-19 16:00:24Z ru $

PROG=	badsect
DPADD=	${LIBUFS}
LDADD=	-lufs
MAN=	badsect.8
WARNS?=	2

.include <bsd.prog.mk>
