# $FreeBSD: release/10.0.0/sys/modules/ahci/Makefile 238805 2012-07-26 13:44:48Z mav $

.PATH: ${.CURDIR}/../../dev/ahci

KMOD=	ahci
SRCS=	ahci.c ahciem.c ahci.h device_if.h bus_if.h pci_if.h opt_cam.h

.include <bsd.kmod.mk>
