# $FreeBSD: stable/9/sys/modules/ahci/Makefile 195534 2009-07-10 08:18:08Z scottl $

.PATH: ${.CURDIR}/../../dev/ahci

KMOD=	ahci
SRCS=	ahci.c ahci.h device_if.h bus_if.h pci_if.h opt_cam.h

.include <bsd.kmod.mk>
