# $FreeBSD: stable/11/sys/modules/geom/geom_sched/gsched_rr/Makefile 275948 2014-12-20 00:07:53Z imp $

KMOD=   gsched_rr
SRCS=   gs_rr.c

# ../Makefile.inc automatically included
.include <bsd.kmod.mk>
