# $FreeBSD: release/10.0.0/sys/modules/geom/geom_sched/gsched_rr/Makefile 206497 2010-04-12 16:37:45Z luigi $

KMOD=   gsched_rr
SRCS=   gs_rr.c
# hash.h on 6.x has a (char *) cast on a const pointer
#CWARNFLAGS=

# ../Makefile.inc automatically included
.include <bsd.kmod.mk>
