# $MidnightBSD$
# $FreeBSD: stable/10/tools/tools/netrate/tcpp/Makefile 276486 2014-12-31 23:25:37Z ngie $

PROG=	tcpp
INCS=	tcpp.h
MAN=
SRCS=	tcpp.c tcpp_client.c tcpp_server.c tcpp_util.c
WARNS?=	3

.include <bsd.prog.mk>
