# $FreeBSD: release/10.0.0/sys/modules/mac_test/Makefile 105725 2002-10-22 17:10:15Z rwatson $

.PATH: ${.CURDIR}/../../security/mac_test

KMOD=	mac_test
SRCS=	vnode_if.h \
	mac_test.c

.include <bsd.kmod.mk>
