#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: release/7.0.0/share/doc/smm/04.quotas/Makefile 172506 2007-10-10 16:59:15Z cvs2svn $

VOLUME=	smm/04.quotas
SRCS=	quotas.ms
MACROS=	-ms

.include <bsd.doc.mk>
