#	@(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: stable/10/share/skel/Makefile 291794 2015-12-04 18:21:05Z bdrewery $
# $MidnightBSD$

FILESGROUPS=	FILES1 FILES2
FILES1=		dot.cshrc dot.login dot.login_conf dot.mailrc dot.mkshrc dot.profile \
		dot.shrc
FILES2=		dot.mail_aliases dot.rhosts 
FILES1DIR=	${SHAREDIR}/skel
FILES2DIR=	${SHAREDIR}/skel
FILES1MODE=	0644
FILES2MODE=	0600
NO_OBJ=

.include <bsd.prog.mk>
