# $MidnightBSD$
# $FreeBSD: stable/10/tests/sys/geom/class/gate/Makefile 313754 2017-02-15 00:16:52Z asomers $

TESTSDIR=	${TESTSBASE}/sys/geom/class/${.CURDIR:T}

ATF_TESTS_SH+=	ggate_test

.include <bsd.test.mk>
