# $FreeBSD: stable/11/sys/modules/am335x_dmtpps/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/arm/ti/am335x

KMOD=	am335x_dmtpps
SRCS=	am335x_dmtpps.c

SRCS+= bus_if.h device_if.h ofw_bus_if.h

.include <bsd.kmod.mk>
