# $OpenBSD: Makefile,v 1.5 2012/07/09 17:52:09 schwarze Exp $

REGRESS_TARGETS = simple font
LINT_TARGETS =	  simple

# it's unclear what font changes in link destinations should do

SKIP_MARKDOWN ?= font

.include <bsd.regress.mk>
