# $FreeBSD: release/7.0.0/sys/modules/uipaq/Makefile 166306 2007-01-28 11:56:14Z takawata $

S=	${.CURDIR}/../..
.PATH: $S/dev/usb

KMOD=	uipaq
SRCS=	uipaq.c opt_usb.h device_if.h bus_if.h usbdevs.h

.include <bsd.kmod.mk>
