# $FreeBSD: stable/11/sys/modules/i2c/jedec_ts/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:		${SRCTOP}/sys/dev/jedec_ts
KMOD		= jedec_ts
SRCS		= jedec_ts.c bus_if.h device_if.h smbus_if.h

.include <bsd.kmod.mk>
