# $MidnightBSD$
# $FreeBSD: stable/10/sys/modules/i2c/jedec_ts/Makefile 307768 2016-10-22 08:00:46Z avg $

.PATH:		${.CURDIR}/../../../dev/jedec_ts
KMOD		= jedec_ts
SRCS		= jedec_ts.c bus_if.h device_if.h smbus_if.h

.include <bsd.kmod.mk>
