# $FreeBSD: stable/11/sys/modules/sound/driver/vibes/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/sound/pci

KMOD=	snd_vibes
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	vibes.c

.include <bsd.kmod.mk>
