#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/10.0.0/usr.bin/wall/Makefile 202200 2010-01-13 18:09:54Z ed $

PROG=	wall
SRCS=	ttymsg.c wall.c
BINGRP=	tty
BINMODE=2555

.include <bsd.prog.mk>
