#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/7.0.0/usr.bin/unifdef/Makefile 115823 2003-06-04 10:01:10Z fanf $

PROG=	unifdef
SCRIPTS=unifdefall.sh
MLINKS=	unifdef.1 unifdefall.1
WARNS?=	5

.include <bsd.prog.mk>
