# $FreeBSD: stable/11/gnu/usr.bin/groff/src/preproc/html/Makefile 270168 2014-08-19 15:04:32Z bdrewery $

PROG_CXX=	pre-grohtml
SRCS=		pre-html.cpp pushback.cpp
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
MAN=

.include <bsd.prog.mk>
