# $FreeBSD: release/10.0.0/gnu/usr.bin/groff/src/preproc/html/Makefile 139103 2004-12-21 08:47:35Z ru $

PROG_CXX=	pre-grohtml
SRCS=		pre-html.cpp pushback.cpp
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
NO_MAN=

.include <bsd.prog.mk>
