# $FreeBSD: stable/11/share/man/man4/man4.powerpc/Makefile 298107 2016-04-16 07:45:30Z gjb $

PACKAGE=runtime-manuals

MAN=	adb.4 \
	akbd.4 \
	abtn.4 \
	ams.4 \
	bm.4 \
	cuda.4 \
	llan.4 \
	pmu.4 \
	powermac_nvram.4 \
	smu.4 \
	snd_ai2s.4 \
	snd_davbus.4 \
	tsec.4

MANSUBDIR=/powerpc

.include <bsd.prog.mk>
