# $FreeBSD: release/7.0.0/sys/modules/mqueue/Makefile 152853 2005-11-27 08:30:12Z davidxu $

.PATH: ${.CURDIR}/../../kern

KMOD=	mqueuefs
SRCS=	uipc_mqueue.c \
	vnode_if.h \
	opt_posix.h

.include <bsd.kmod.mk>
