#	$FreeBSD: stable/11/sbin/ipf/ipfstat/Makefile 298107 2016-04-16 07:45:30Z gjb $

NOGCCERROR=	# defined

PACKAGE=	ipf
PROG=		ipfstat
SRCS=		ipfstat.c
MAN=		ipfstat.8
LIBADD+=	ncursesw

.include <bsd.prog.mk>
