 # $FreeBSD: stable/11/sys/modules/exca/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/exca

KMOD=	exca
SRCS=	exca.c device_if.h bus_if.h power_if.h card_if.h pccarddevs.h

.include <bsd.kmod.mk>
