 # $FreeBSD: release/10.0.0/sys/modules/exca/Makefile 129740 2004-05-26 00:53:10Z imp $

.PATH: ${.CURDIR}/../../dev/exca

KMOD=	exca
SRCS=	exca.c device_if.h bus_if.h power_if.h card_if.h pccarddevs.h

.include <bsd.kmod.mk>
