# $FreeBSD: release/10.0.0/lib/libpam/modules/pam_opieaccess/Makefile 112044 2003-03-09 20:06:38Z obrien $

LIB=	pam_opieaccess
SRCS=	${LIB}.c
MAN=	pam_opieaccess.8

DPADD=	${LIBOPIE}
LDADD=	-lopie

.include <bsd.lib.mk>
