# $MidnightBSD$
# $FreeBSD: stable/10/lib/clang/libllvmoption/Makefile 261991 2014-02-16 19:44:07Z dim $

.include <bsd.own.mk>

LIB=	llvmoption

SRCDIR=	lib/Option
SRCS=	Arg.cpp \
	ArgList.cpp \
	OptTable.cpp \
	Option.cpp

.include "../clang.lib.mk"
