#	@(#)Makefile	8.1 (Berkeley) 8/14/93
# $FreeBSD: release/10.0.0/share/doc/usd/21.troff/Makefile 136910 2004-10-24 15:33:08Z ru $

VOLUME=		usd/21.troff
SRCS=		m.mac m0 m0a m1 m2 m3 m4 m5 table1 table2
USE_TBL=

.include <bsd.doc.mk>
