# $FreeBSD: stable/11/usr.bin/enigma/Makefile 275042 2014-11-25 14:29:10Z bapt $

PROG=	enigma

LINKS=	${BINDIR}/enigma ${BINDIR}/crypt
MLINKS=	enigma.1 crypt.1

LIBADD=	crypt

.include <bsd.prog.mk>
