#	From: @(#)Makefile	5.2 (Berkeley) 6/8/93
# $FreeBSD: stable/11/share/doc/papers/beyond4.3/Makefile 106146 2002-10-29 15:01:59Z ru $

VOLUME=	papers
DOC=	beyond43
SRCS=	beyond43.ms
MACROS=	-ms

.include <bsd.doc.mk>
