# $FreeBSD: release/10.0.0/sys/modules/i2c/controllers/alpm/Makefile 171020 2007-06-24 20:35:59Z njl $

.PATH:		${.CURDIR}/../../../../pci
KMOD		= alpm
SRCS		= device_if.h bus_if.h iicbus_if.h smbus_if.h pci_if.h \
		  alpm.c

.include <bsd.kmod.mk>
