# $FreeBSD: release/10.0.0/sys/modules/cpsw/Makefile 239281 2012-08-15 06:31:32Z gonzo $

.PATH: ${.CURDIR}/../../arm/ti/cpsw

KMOD=   if_cpsw
SRCS=   if_cpsw.c device_if.h bus_if.h ofw_bus_if.h miibus_if.h

.include <bsd.kmod.mk>
