# $FreeBSD: stable/11/sys/modules/cpsw/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/arm/ti/cpsw

KMOD=   if_cpsw
SRCS=   if_cpsw.c device_if.h bus_if.h ofw_bus_if.h miibus_if.h

.include <bsd.kmod.mk>
