# $FreeBSD: release/10.0.0/gnu/usr.bin/groff/font/devhtml/Makefile 151504 2005-10-20 10:57:53Z ru $

DEV=		html
FONTS=		R I B BI CR CI CB CBI S
GHOSTSCRIPT=	/usr/local/bin/gs
DESC_EXT=	echo "image_generator ${GHOSTSCRIPT}"

.include "../Makefile.tty"
.include "../Makefile.dev"
