#	@(#)Makefile	8.2 (Berkeley) 3/27/94
#
# $FreeBSD: release/7.0.0/sbin/idmapd/Makefile 163376 2006-10-15 13:51:49Z ceri $

PROG=	idmapd
MAN=	idmapd.8

CFLAGS+= -DNFS -I${.CURDIR}/../../sys
WARNS?=	2

.include <bsd.prog.mk>
