# $FreeBSD: release/10.0.0/sys/modules/sysvipc/sysvmsg/Makefile 213781 2010-10-13 14:44:38Z rpaulo $

.PATH: ${.CURDIR}/../../../kern

KMOD=	sysvmsg
SRCS=	sysv_msg.c opt_sysvipc.h opt_compat.h

.include <bsd.kmod.mk>
