# $FreeBSD: release/7.0.0/sys/modules/sysvipc/sysvmsg/Makefile 141562 2005-02-09 08:35:24Z obrien $

.PATH: ${.CURDIR}/../../../kern

KMOD=	sysvmsg
SRCS=	sysv_msg.c opt_mac.h opt_sysvipc.h

.include <bsd.kmod.mk>
