# $FreeBSD: stable/11/sys/modules/sysvipc/sysvmsg/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/kern

KMOD=	sysvmsg
SRCS=	sysv_msg.c opt_sysvipc.h opt_compat.h

.include <bsd.kmod.mk>
