# $FreeBSD: stable/11/sys/modules/netgraph/atm/atm/Makefile 319182 2017-05-30 04:11:12Z ngie $
#
# Author: Harti Brandt <harti@freebsd.org>
#
.PATH: ${SRCTOP}/sys/netgraph/atm

KMOD=	ng_atm
SRCS=	ng_atm.c
# CFLAGS+= -DNGATM_DEBUG

.include <bsd.kmod.mk>
