# $FreeBSD: release/7.0.0/sys/modules/netgraph/atm/atm/Makefile 116808 2003-06-25 13:20:19Z harti $
#
# Author: Harti Brandt <harti@freebsd.org>
#
.PATH: ${.CURDIR}/../../../../netgraph/atm

KMOD=	ng_atm
SRCS=	ng_atm.c
# CFLAGS+= -DNGATM_DEBUG

.include <bsd.kmod.mk>
