# $MidnightBSD$
# $FreeBSD: stable/10/libexec/atf/atf-check/tests/Makefile 313488 2017-02-09 22:49:48Z ngie $

.include <bsd.init.mk>

ATF=		${SRCTOP}/contrib/atf
.PATH:		${ATF}/atf-sh

ATF_TESTS_SH=	atf-check_test

.include <bsd.test.mk>
