# $FreeBSD: stable/9/usr.sbin/cpucontrol/Makefile 229471 2012-01-04 08:14:05Z fabient $

PROG=	cpucontrol
MAN=	cpucontrol.8
SRCS=	cpucontrol.c intel.c amd.c via.c

NO_WCAST_ALIGN=

.include <bsd.prog.mk>
