#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/11/usr.bin/quota/Makefile 275042 2014-11-25 14:29:10Z bapt $

PROG=	quota
BINOWN=	root
BINMODE=4555

LIBADD=	rpcsvc util

.include <bsd.prog.mk>
