# $FreeBSD: release/10.0.0/usr.sbin/bsdconfig/startup/include/Makefile 240684 2012-09-18 22:28:42Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/140.startup/include
FILES=		messages.subr

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
