# $FreeBSD: stable/11/sys/modules/ipfw_nptv6/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/netpfil/ipfw/nptv6

KMOD=	ipfw_nptv6
SRCS=	ip_fw_nptv6.c nptv6.c opt_ipfw.h

.include <bsd.kmod.mk>
