# $FreeBSD: release/10.0.0/lib/clang/liblldbPluginDynamicLoaderStatic/Makefile 255722 2013-09-20 01:52:02Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginDynamicLoaderStatic

SRCDIR=	tools/lldb/source/Plugins/DynamicLoader/Static
SRCS=	DynamicLoaderStatic.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
