# $FreeBSD: release/10.0.0/gnu/usr.bin/diff/doc/Makefile 170758 2007-06-15 07:09:34Z delphij $

INFO = diff

INFOENTRY_diff= "* DIFF: (diff).                 DIFF/PATCH Reference Manual."

SRCDIR=${.CURDIR}/../../../../contrib/diff/doc

.include <bsd.info.mk>
