# $FreeBSD: stable/9/sys/modules/iwn/Makefile 179215 2008-05-22 21:53:15Z sam $

.PATH:  ${.CURDIR}/../../dev/iwn

KMOD    = if_iwn
SRCS    = if_iwn.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
