# $FreeBSD: release/10.0.0/sys/modules/iwn/Makefile 253911 2013-08-03 08:21:35Z uqs $

.PATH:  ${.CURDIR}/../../dev/iwn

KMOD    = if_iwn
SRCS    = if_iwn.c device_if.h bus_if.h pci_if.h opt_iwn.h opt_wlan.h

.include <bsd.kmod.mk>
