#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/10.0.0/usr.bin/tput/Makefile 75286 2001-04-07 11:21:35Z ru $

PROG=	tput
DPADD=	${LIBTERMCAP}
LDADD=	-ltermcap
SCRIPTS=clear.sh
MLINKS=	tput.1 clear.1

.include <bsd.prog.mk>
