# $FreeBSD: src/gnu/Makefile.inc,v 1.6 2004/12/21 09:33:44 ru Exp $
# $MidnightBSD: src/gnu/Makefile.inc,v 1.2 2007/03/14 23:44:42 laffer1 Exp $

# Do not lint the GNU stuff. It is all externally maintained and
# lint output is wasteful noise here.

NO_LINT=
