#	@(#)Makefile	5.33.1.1 (Berkeley) 5/6/91
# $FreeBSD: src/gnu/Makefile,v 1.36 2002/06/05 17:02:37 obrien Exp $
# $MidnightBSD: src/gnu/Makefile,v 1.2 2007/03/14 23:44:42 laffer1 Exp $

SUBDIR= lib usr.bin

.include <bsd.subdir.mk>
