# $MidnightBSD$
# $FreeBSD: stable/10/usr.bin/join/tests/Makefile 313488 2017-02-09 22:49:48Z ngie $

TAP_TESTS_SH=	legacy_test

FILESDIR=	${TESTSDIR}
FILES=		regress.1.in
FILES+=		regress.2.in
FILES+=		regress.out
FILES+=		regress.sh

.include <bsd.test.mk>
