# $FreeBSD: stable/11/usr.bin/join/tests/Makefile 299094 2016-05-04 23:20:53Z ngie $

PACKAGE=	tests

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		regress.1.in
${PACKAGE}FILES+=		regress.2.in
${PACKAGE}FILES+=		regress.out
${PACKAGE}FILES+=		regress.sh

.include <bsd.test.mk>
