
# $FreeBSD: release/10.0.0/sys/modules/plip/Makefile 89260 2002-01-11 15:49:02Z ru $

.PATH:	${.CURDIR}/../../dev/ppbus
KMOD=	plip
SRCS=	bus_if.h device_if.h ppbus_if.h \
	opt_plip.h \
	if_plip.c

.include <bsd.kmod.mk>
