# $MidnightBSD$
# $FreeBSD: stable/10/lib/libiconv_modules/EUCTW/Makefile 260497 2014-01-09 23:08:56Z dim $

SHLIB=	EUCTW
SRCS+=	citrus_euctw.c
CFLAGS.gcc+= --param max-inline-insns-single=32

.include <bsd.lib.mk>
