# $FreeBSD$

NO_OBJ=
INCS=	hash_info.h \
	ipc_info.h \
	lockgroup_info.h \
	mach_debug_types.defs \
	mach_debug_types.h \
	page_info.h \
	vm_info.h \
	zone_info.h
INCSDIR=${INCLUDEDIR}/mach_debug

.include <bsd.prog.mk>
