# $FreeBSD: release/7.0.0/etc/periodic/security/Makefile 161602 2006-08-25 07:34:36Z trhodes $

FILES=	100.chksetuid \
	200.chkmounts \
	300.chkuid0 \
	400.passwdless \
	410.logincheck \
	500.ipfwdenied \
	510.ipfdenied \
	520.pfdenied \
	550.ipfwlimit \
	700.kernelmsg \
	800.loginfail \
	900.tcpwrap \
	security.functions

.include <bsd.prog.mk>
