# $FreeBSD: release/10.0.0/sys/modules/netgraph/sppp/Makefile 127376 2004-03-24 17:24:01Z rik $
# Cronyx Id: ng_sppp.Makefile,v 1.1.2.1 2002/12/25 08:37:25 rik Exp $

KMOD=	ng_sppp
SRCS= 	ng_sppp.c

.include <bsd.kmod.mk>
