#	@(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: release/10.0.0/share/doc/psd/06.Clang/Makefile 136910 2004-10-24 15:33:08Z ru $

VOLUME=		psd/06.Clang
SRCS=		Clang.ms
MACROS=		-ms
USE_TBL=

.include <bsd.doc.mk>
