# $FreeBSD: release/10.0.0/sys/modules/mac_biba/Makefile 105725 2002-10-22 17:10:15Z rwatson $

.PATH: ${.CURDIR}/../../security/mac_biba

KMOD=	mac_biba
SRCS=	vnode_if.h \
	mac_biba.c

.include <bsd.kmod.mk>
