# $Id: Makefile,v 1.7 2003/08/14 20:07:14 max Exp $
# $FreeBSD: stable/11/usr.bin/bluetooth/btsockstat/Makefile 275042 2014-11-25 14:29:10Z bapt $

PROG=		btsockstat
WARNS?=		2
BINGRP=		kmem
BINMODE=	2555

LIBADD=		bluetooth kvm

.include <bsd.prog.mk>
