# $FreeBSD: stable/11/usr.bin/apply/tests/Makefile 299094 2016-05-04 23:20:53Z ngie $

PACKAGE=	tests

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		regress.00.in
${PACKAGE}FILES+=		regress.00.out
${PACKAGE}FILES+=		regress.01.out
${PACKAGE}FILES+=		regress.01.sh
${PACKAGE}FILES+=		regress.sh

.include <bsd.test.mk>
