# $MidnightBSD$
# $FreeBSD: stable/10/usr.bin/apply/tests/Makefile 313488 2017-02-09 22:49:48Z ngie $

TAP_TESTS_SH=	legacy_test

FILESDIR=	${TESTSDIR}
FILES=		regress.00.in
FILES+=		regress.00.out
FILES+=		regress.01.out
FILES+=		regress.01.sh
FILES+=		regress.sh

.include <bsd.test.mk>
