#	from: @(#)Makefile	5.5 (Berkeley) 5/11/90
# $FreeBSD: release/7.0.0/usr.sbin/rtprio/Makefile 74816 2001-03-26 14:42:20Z ru $

PROG=	rtprio
LINKS=  ${BINDIR}/rtprio ${BINDIR}/idprio
MLINKS= rtprio.1 idprio.1

.include <bsd.prog.mk>
