#	from: @(#)Makefile	5.5 (Berkeley) 5/11/90
# $FreeBSD: release/10.0.0/usr.sbin/rtprio/Makefile 201390 2010-01-02 11:07:44Z ed $

PROG=	rtprio
LINKS=  ${BINDIR}/rtprio ${BINDIR}/idprio
MLINKS= rtprio.1 idprio.1

WARNS?=	2

.include <bsd.prog.mk>
