# $FreeBSD: release/10.0.0/tools/tools/net80211/stumbler/Makefile 204311 2010-02-25 14:42:26Z ru $

PROG=	stumbler
BINDIR=	/usr/local/bin
DPADD=	${LIBPCAP} ${LIBNCURSES}
LDADD=	-lpcap -lncurses
CFLAGS=-g
NO_MAN=

.include <bsd.prog.mk>
