# $FreeBSD: release/7.0.0/tools/tools/net80211/stumbler/Makefile 160994 2006-08-05 05:12:03Z sam $

PROG=	stumbler
BINDIR=	/usr/local/bin
DPADD=	${LIBPCAP}
LDADD=	-lpcap -lncurses
CFLAGS=-g
NO_MAN=

.include <bsd.prog.mk>
