# $MidnightBSD$
# $FreeBSD: stable/10/tools/tools/wtap/wtap/Makefile 276486 2014-12-31 23:25:37Z ngie $

BINDIR?=	/usr/local/bin
PROG=	wtap
SRC=	wtap.c
MAN=

CFLAGS+=	-I${.CURDIR}/../../../../sys/dev/wtap/

.include <bsd.prog.mk>
