# Makefile to build LCD control software for ppi(4) interface.
#
# $FreeBSD: stable/11/share/examples/ppi/Makefile 299293 2016-05-10 00:51:50Z gjb $

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/ppi
PROG=	ppilcd
MAN=

.include <bsd.prog.mk>
