# $MidnightBSD$
# Makefile to build LCD control software for ppi(4) interface.
#
# $FreeBSD: stable/10/share/examples/ppi/Makefile 276486 2014-12-31 23:25:37Z ngie $

PROG=	ppilcd
MAN=

.include <bsd.prog.mk>
