# $FreeBSD: stable/11/gnu/usr.bin/groff/src/utils/tfmtodit/Makefile 291738 2015-12-04 03:17:47Z bdrewery $

PROG_CXX=	tfmtodit
SRCS=		tfmtodit.cpp
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
LIBADD=		m
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
