# $FreeBSD: release/10.0.0/sys/modules/mlx/Makefile 70711 2001-01-06 14:00:42Z obrien $

.PATH: ${.CURDIR}/../../dev/mlx

KMOD=	mlx
SRCS=	mlx.c mlx_pci.c mlx_disk.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
