# $MidnightBSD$
# $FreeBSD: stable/10/usr.bin/dirname/tests/Makefile 313488 2017-02-09 22:49:48Z ngie $

.include <bsd.own.mk>

NETBSD_ATF_TESTS_SH=	dirname_test

.include <netbsd-tests.test.mk>

.include <bsd.test.mk>
