# $FreeBSD: stable/11/sys/modules/geom/geom_mirror/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/geom/mirror

KMOD=	geom_mirror
SRCS=	g_mirror.c
SRCS+=	g_mirror_ctl.c

.include <bsd.kmod.mk>
