# $FreeBSD: stable/9/sys/modules/geom/geom_mirror/Makefile 132904 2004-07-30 23:13:45Z pjd $

.PATH: ${.CURDIR}/../../../geom/mirror

KMOD=	geom_mirror
SRCS=	g_mirror.c
SRCS+=	g_mirror_ctl.c

.include <bsd.kmod.mk>
