# $FreeBSD: stable/11/sys/modules/sound/driver/via8233/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH: ${SRCTOP}/sys/dev/sound/pci

KMOD=	snd_via8233
SRCS=	device_if.h bus_if.h pci_if.h
SRCS+=	via8233.c

.include <bsd.kmod.mk>
