# $MidnightBSD$
# $FreeBSD: stable/10/sys/modules/imgact_binmisc/Makefile 264269 2014-04-08 20:10:22Z sbruno $

.PATH: ${.CURDIR}/../../kern

KMOD=	imgact_binmisc
SRCS=	imgact_binmisc.c

.include <bsd.kmod.mk>
