# $FreeBSD: stable/11/stand/powerpc/Makefile 332148 2018-04-06 19:54:10Z kevans $

NO_OBJ=t

.include <bsd.init.mk>

SUBDIR.yes=		boot1.chrp ofw uboot
SUBDIR.${MK_FDT}+=	kboot

.include <bsd.subdir.mk>
