#	from: @(#)Makefile	8.1 (Berkeley) 6/4/93
# $FreeBSD: release/7.0.0/libexec/rbootd/Makefile 90164 2002-02-04 02:33:51Z kris $

PROG=	rbootd
SRCS=	bpf.c conf.c parseconf.c rbootd.c rmpproto.c utils.c
MAN=	rbootd.8

WFORMAT=0

.include <bsd.prog.mk>
