#	@(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: release/10.0.0/share/doc/psd/04.uprog/Makefile 96964 2002-05-20 00:47:03Z grog $

VOLUME=	psd/04.uprog
SRCS=	p.mac p0 p1 p2 p3 p4 p5 p6 p8 p9
MACROS=	-ms

.include <bsd.doc.mk>
