# $FreeBSD: release/7.0.0/usr.sbin/ctm/ctm_smail/Makefile 139103 2004-12-21 08:47:35Z ru $

.PATH: ${.CURDIR}/../ctm_rmail

PROG=	ctm_smail
NO_MAN=
SRCS=	ctm_smail.c error.c

CFLAGS+= -I${.CURDIR}/../ctm_rmail

.include <bsd.prog.mk>
