# $MidnightBSD$
# $FreeBSD: stable/10/usr.sbin/ctm/ctm_smail/Makefile 276486 2014-12-31 23:25:37Z ngie $

.PATH: ${.CURDIR}/../ctm_rmail

PROG=	ctm_smail
MAN=
SRCS=	ctm_smail.c error.c

CFLAGS+= -I${.CURDIR}/../ctm_rmail

WARNS?=	2

.include <bsd.prog.mk>
