# $FreeBSD: stable/11/usr.sbin/ctm/ctm_smail/Makefile 319119 2017-05-29 10:15:41Z ngie $

.PATH: ${.CURDIR:H}/ctm_rmail

PROG=	ctm_smail
MAN=
SRCS=	ctm_smail.c error.c

CFLAGS+= -I${.CURDIR:H}/ctm_rmail

WARNS?=	2

.include <bsd.prog.mk>
