# $FreeBSD: release/10.0.0/share/i18n/esdb/KOI/Makefile 219019 2011-02-25 00:04:39Z gabor $
# $NetBSD: Makefile.inc,v 1.2 2008/10/25 22:27:36 apb Exp $

CODE=	KOI
SED_EXP= 's/KOIx/KOI%%PART%%/'
NO_SEP=	yes

.include "../Makefile.part"
