#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/share/dict/Makefile,v 1.14 2004/12/21 08:46:52 ru Exp $

.include "../../Makefile.inc"

# XXX MISSING:	connectives words
FILES=		math
FILESDIR=	${BINDIR}/dict/special/

.include <bsd.prog.mk>
