# $FreeBSD: stable/11/sys/modules/i2c/s35390a/Makefile 323929 2017-09-22 15:40:56Z ian $

.PATH:		${SRCTOP}/sys/dev/iicbus
KMOD		= s35390a
SRCS		= s35390a.c bus_if.h clock_if.h device_if.h iicbus_if.h ofw_bus_if.h opt_platform.h

.include <bsd.kmod.mk>
