#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: release/7.0.0/games/pom/Makefile 145782 2005-05-01 19:34:22Z stefanf $

PROG=	pom
MAN=	pom.6
DPADD=	${LIBM}
LDADD=	-lm

WARNS?=	6

.include <bsd.prog.mk>
