# $FreeBSD: stable/11/libexec/makewhatis.local/Makefile 295733 2016-02-18 00:26:21Z bdrewery $

SCRIPTS=	makewhatis.local.sh
MAN=		makewhatis.local.8
SCRIPTSDIR=	${LIBEXECDIR}
LINKS=		${SCRIPTSDIR}/makewhatis.local ${SCRIPTSDIR}/catman.local
MLINKS=		makewhatis.local.8 catman.local.8

.include <bsd.prog.mk>
