# $FreeBSD: stable/11/usr.bin/ofed/infiniband-diags/iblinkinfo/Makefile 335253 2018-06-16 15:05:05Z kib $

PROG=	iblinkinfo
SRCS=	iblinkinfo.c
LIBADD= ibnetdisc
MAN=	iblinkinfo.8

.include <bsd.prog.mk>
