#	@(#)Makefile	8.1 (Berkeley) 6/29/93
#	$FreeBSD: release/7.0.0/usr.bin/gprof/Makefile 130776 2004-06-20 11:05:25Z stefanf $

PROG=	gprof
SRCS=	gprof.c aout.c arcs.c dfn.c elf.c lookup.c hertz.c \
	printgprof.c printlist.c kernel.c
FILES=	gprof.flat gprof.callg
FILESDIR=	${SHAREDIR}/misc

.include <bsd.prog.mk>
