#	$OpenBSD: Makefile,v 1.1 1997/01/26 02:23:20 millert Exp $
# $FreeBSD: release/7.0.0/sbin/fsirand/Makefile 126178 2004-02-23 20:25:27Z johan $

PROG=	fsirand
WARNS?=	0
MAN=	fsirand.8
DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
