#	$OpenBSD: Makefile,v 1.1 1997/01/26 02:23:20 millert Exp $
# $FreeBSD: stable/11/sbin/fsirand/Makefile 298107 2016-04-16 07:45:30Z gjb $

PACKAGE=runtime
PROG=	fsirand
MAN=	fsirand.8
WARNS?=	3

.include <bsd.prog.mk>
