# $FreeBSD: release/7.0.0/lib/libgpib/Makefile 169807 2007-05-21 02:49:08Z deischen $

LIB=		gpib
SHLIB_MAJOR=	2
INCS=		gpib.h
INCSDIR=	${INCLUDEDIR}/gpib
SRCS=		ibfoo.c
WARNS?=		6

.include <bsd.lib.mk>
