# $FreeBSD: release/7.0.0/sys/modules/hfa/pci/Makefile 94898 2002-04-17 00:26:09Z mdodd $

.PATH:	${.CURDIR}/../../../dev/hfa
  
KMOD=	hfa_pci
SRCS=	hfa_pci.c pci_if.h device_if.h bus_if.h

.include <bsd.kmod.mk>
