#	$ANA: Makefile,v 1.1.1.1 1996/09/25 21:12:57 wollman Exp $
# $FreeBSD: release/7.0.0/usr.sbin/pciconf/Makefile 166435 2007-02-02 19:54:17Z jhb $

PROG=	pciconf
SRCS=	pciconf.c cap.c
MAN=	pciconf.8

CFLAGS+= -I${.CURDIR}/../../sys

.include <bsd.prog.mk>
