#	$ANA: Makefile,v 1.1.1.1 1996/09/25 21:12:57 wollman Exp $
# $FreeBSD: stable/9/usr.sbin/pciconf/Makefile 247566 2013-03-01 19:39:54Z jhb $

PROG=	pciconf
SRCS=	pciconf.c cap.c err.c
MAN=	pciconf.8

WARNS?=	3

.include <bsd.prog.mk>
