#	$ANA: Makefile,v 1.1.1.1 1996/09/25 21:12:57 wollman Exp $
# $FreeBSD: release/10.0.0/usr.sbin/pciconf/Makefile 246367 2013-02-05 18:55:09Z jhb $

PROG=	pciconf
SRCS=	pciconf.c cap.c err.c
MAN=	pciconf.8

WARNS?=	3

.include <bsd.prog.mk>
