# $MidnightBSD: src/etc/periodic/weekly/Makefile,v 1.3 2006/12/29 22:55:20 laffer1 Exp $
# $FreeBSD: src/etc/periodic/weekly/Makefile,v 1.8 2002/07/18 12:33:01 ru Exp $

FILES=	310.locate \
	320.whatis \
	330.catman \
	340.noid \
	350.msearch \
	400.status-pkg \
	999.local

.include <bsd.prog.mk>
