# $FreeBSD: release/7.0.0/etc/periodic/weekly/Makefile 161708 2006-08-29 08:49:58Z ru $

FILES=	310.locate \
	320.whatis \
	330.catman \
	340.noid \
	400.status-pkg \
	999.local

.include <bsd.prog.mk>
