# $FreeBSD: stable/11/usr.bin/bmake/tests/variables/Makefile 299094 2016-05-04 23:20:53Z ngie $

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/variables

TESTS_SUBDIRS=	modifier_M modifier_t opt_V t0

.include <bsd.test.mk>
