# $FreeBSD: stable/10/usr.bin/bmake/tests/variables/Makefile 266074 2014-05-14 18:43:13Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/bmake/variables

TESTS_SUBDIRS=	modifier_M modifier_t opt_V t0

.include <bsd.test.mk>
