# $MidnightBSD$
# $FreeBSD: src/usr.sbin/bsdinstall/distfetch/Makefile,v 1.1 2011/02/18 14:54:34 nwhitehorn Exp $

BINDIR= /usr/libexec/bsdinstall
PROG=	distfetch
LDADD=	-lfetch -lncursesw -ldialog -lm

WARNS?=	6
NO_MAN=	true

.include <bsd.prog.mk>
