# $FreeBSD: release/10.0.0/gnu/lib/libstdc++/doc/Makefile 97517 2002-05-29 21:14:48Z obrien $

SRCDIR= ${.CURDIR}/../../../../contrib/libstdc++

.PATH: ${SRCDIR}/../libio

INFO = iostream

INFOENTRY_iostream= "* iostream: (iostream).	The GNU C++ I/O library."

MAKEINFOFLAGS+= -I ${SRCDIR}/../libio 

.include <bsd.info.mk>
