# $FreeBSD: release/10.0.0/lib/libiconv_modules/UTF1632/Makefile 219019 2011-02-25 00:04:39Z gabor $

SHLIB=	UTF1632
SRCS+=	citrus_utf1632.c
CFLAGS+= --param max-inline-insns-single=32

.include <bsd.lib.mk>
