# $MidnightBSD$
# $FreeBSD: stable/10/lib/libiconv_modules/UTF1632/Makefile 260497 2014-01-09 23:08:56Z dim $

SHLIB=	UTF1632
SRCS+=	citrus_utf1632.c
CFLAGS.gcc+= --param max-inline-insns-single=32

.include <bsd.lib.mk>
