# $FreeBSD: stable/11/lib/libiconv_modules/UTF1632/Makefile 285884 2015-07-26 00:11:04Z pfg $

SHLIB=	UTF1632
SRCS+=	citrus_utf1632.c
CFLAGS.gcc+= --param max-inline-insns-single=64

.include <bsd.lib.mk>
