#!/bin/sh
# $FreeBSD: release/10.0.0/usr.sbin/ntp/scripts/ntpver 54552 1999-12-13 14:09:56Z roberto $
# print version string of NTP daemon
# Copyright (c) 1997 by Ulrich Windl
# Modified 970318: Harlan Stenn: rewritten...
# usage: ntpver hostname

ntpq -c "rv 0 daemon_version" $* | awk '/daemon_version/ { print $2 }'
