# $FreeBSD: release/10.0.0/lib/clang/liblldbPluginObjectContainerBSDArchive/Makefile 255722 2013-09-20 01:52:02Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginObjectContainerBSDArchive

SRCDIR=	tools/lldb/source/Plugins/ObjectContainer/BSD-Archive
SRCS=	ObjectContainerBSDArchive.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
