# $MidnightBSD$
# $FreeBSD: stable/10/lib/libiconv_modules/GBK2K/Makefile 260497 2014-01-09 23:08:56Z dim $

SHLIB=	GBK2K
SRCS+=	citrus_gbk2k.c
CFLAGS.gcc+= --param max-inline-insns-single=16

.include <bsd.lib.mk>
