#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: release/7.0.0/sbin/swapon/Makefile 108375 2002-12-28 23:39:47Z dillon $

PROG=	swapon
MAN=	swapon.8
LINKS=	${BINDIR}/swapon ${BINDIR}/swapoff
LINKS+=	${BINDIR}/swapon ${BINDIR}/swapctl
MLINKS=	swapon.8 swapoff.8
MLINKS+=swapon.8 swapctl.8

.include <bsd.prog.mk>
