# ex:ts=8
#
# Makefile for amd
# 	This file is under a "BSD" copyright (c) by David O'Brien 1998
#
# $FreeBSD: stable/11/usr.sbin/amd/mk-amd-map/Makefile 275054 2014-11-25 16:57:27Z bapt $

.PATH: ${.CURDIR}/../../../contrib/amd/mk-amd-map

PROG=	mk-amd-map
MAN=	mk-amd-map.8

LIBADD=	amu

.include <bsd.prog.mk>
