# ex:ts=8
#
# Makefile for amd
# 	This file is under a "BSD" copyright (c) by David O'Brien 1998
#
# $FreeBSD: release/10.0.0/usr.sbin/amd/mk-amd-map/Makefile 174305 2007-12-05 16:25:43Z obrien $

.PATH: ${.CURDIR}/../../../contrib/amd/mk-amd-map

PROG=	mk-amd-map
MAN=	mk-amd-map.8

DPADD=	${LIBAMU}
LDADD=	${LIBAMU}

.include <bsd.prog.mk>
