# ex:ts=8
#
# Makefile for amd
# 	This file is under a "BSD" copyright (c) by David O'Brien 1998
#
# $FreeBSD: release/7.0.0/usr.sbin/amd/mk-amd-map/Makefile 80029 2001-07-20 06:20:32Z obrien $

.PATH: ${.CURDIR}/../../../contrib/amd/mk-amd-map

PROG=	mk-amd-map
MAN=	mk-amd-map.8

.include <bsd.prog.mk>
