# $FreeBSD: release/10.0.0/sys/modules/mac_portacl/Makefile 139435 2004-12-30 13:49:01Z rwatson $

.PATH: ${.CURDIR}/../../security/mac_portacl

KMOD=	mac_portacl
SRCS=	mac_portacl.c

.include <bsd.kmod.mk>
