#!/bin/sh
#
#

# PROVIDE: ntpd
# REQUIRE: DAEMON rdate FILESYSTEMS devfs
# BEFORE:  LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name=ntpd
rcvar="ntpd_enable"
command="/usr/sbin/${name}"
start_precmd="ntpd_precmd"
required_files="/etc/ntpd.conf"

ntpd_precmd()
{
	if checkyesno ntpd_sync_on_start; then
		rc_flags="-s ${ntpd_flags}"
	fi
}

load_rc_config $name
run_rc_command "$1"
