#
# $FreeBSD: release/7.0.0/tools/regression/environ/Makefile.envctl 171195 2007-07-04 00:00:41Z scf $
#
SRCS=	envctl.c
PROG=	envctl

CFLAGS+=-Wall -I../../../include

CLEANFILES=	${PROG}.core

NO_MAN=	yes

.include <bsd.prog.mk>

test: ${PROG}
	@sh envtest.t
