#
# $FreeBSD: stable/11/tools/regression/environ/Makefile.envctl 264400 2014-04-13 05:21:56Z imp $
#
SRCS=	envctl.c
PROG=	envctl

CFLAGS+=-Wall -I../../../include

CLEANFILES=	${PROG}.core

MAN=

.include <bsd.prog.mk>

test: ${PROG}
	@env -i sh envtest.t
