#
# $FreeBSD: stable/11/tools/regression/environ/Makefile.timings 264400 2014-04-13 05:21:56Z imp $
#
SRCS=	timings.c
PROG=	timings

CFLAGS+=-Wall -I../../../include

CLEANFILES=	${PROG}.core

MAN=

.include <bsd.prog.mk>

test: ${PROG}
	@./timings
