#	$FreeBSD: release/10.0.0/sbin/ipf/Makefile 145524 2005-04-25 18:55:52Z darrenr $

#.WAIT
SUBDIR=		libipf
SUBDIR+=	ipf ipfs ipfstat ipftest ipmon ipnat ippool ipresend
#SUBDIR+=	ipsend iptest rules

.include <bsd.subdir.mk>
