#	$FreeBSD: stable/11/sbin/ipf/Makefile 355131 2019-11-27 13:46:28Z cy $

SUBDIR=		libipf .WAIT
SUBDIR+=	ipf ipfs ipfstat ipmon ipnat ippool
# XXX Temporarily disconnected.
# SUBDIR+=	ipftest ipresend
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
