# $MidnightBSD$
#	$FreeBSD: stable/10/sbin/ipf/Makefile 289247 2015-10-13 18:43:49Z bdrewery $

SUBDIR=		libipf .WAIT
SUBDIR+=	ipf ipfs ipfstat ipftest ipmon ipnat ippool ipresend
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
