# $FreeBSD: release/10.0.0/share/i18n/csmapper/Makefile.inc 219019 2011-02-25 00:04:39Z gabor $

CSMAPPERDIR?= /usr/share/i18n/csmapper
MKCSMAPPER?= ${.OBJDIR}/../../../usr.bin/mkcsmapper_static/mkcsmapper_static
