# $FreeBSD: stable/11/lib/libcasper/services/cap_grp/tests/Makefile 305626 2016-09-08 20:01:26Z oshogbo $

TAP_TESTS_C=	grp_test

LIBADD+=	casper
LIBADD+=	cap_grp
LIBADD+=	nv

WARNS?=		3

.include <bsd.test.mk>
