# $FreeBSD: release/7.0.0/usr.sbin/i4b/isdndecode/Makefile 80029 2001-07-20 06:20:32Z obrien $

PROG=	isdndecode
MAN=	isdndecode.8
SRCS=	main.c layer1.c layer2.c layer3.c layer3_subr.c facility.c pcause.c 

.include <bsd.prog.mk>

