#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: release/7.0.0/usr.sbin/lpr/SMM.doc/Makefile 172506 2007-10-10 16:59:15Z cvs2svn $

BINDIR=	/usr/share/doc
VOLUME=	smm/07.lpd
SRCS=	0.t 1.t 2.t 3.t 4.t 5.t 6.t 7.t
MACROS=	-ms

USE_TBL=
SRCDIR=	${.CURDIR}

.include <bsd.doc.mk>
