# $FreeBSD: release/10.0.0/share/i18n/esdb/GB/Makefile 219019 2011-02-25 00:04:39Z gabor $
# $NetBSD: Makefile.inc,v 1.1 2006/11/23 03:25:25 tnozaki Exp $

CODE=	GB
NO_PREPROC= yes
NO_SEP=	yes

.include "../Makefile.part"
