# $FreeBSD: release/10.0.0/tools/regression/netinet6/inet6_rth/Makefile 168925 2007-04-21 11:23:33Z mtm $
#
PROG=   inet6_rth-segments
SRCS=	test_subr.c inet6_rth-segments.c
NO_MAN=

CFLAGS+=	-Wall
DEBUG_FLAGS=	-g

.include <bsd.prog.mk>
