# $FreeBSD: stable/11/tools/regression/netinet6/inet6_rth/Makefile 264400 2014-04-13 05:21:56Z imp $
#
PROG=   inet6_rth-segments
SRCS=	test_subr.c inet6_rth-segments.c
MAN=

CFLAGS+=	-Wall
DEBUG_FLAGS=	-g

.include <bsd.prog.mk>
