# $FreeBSD: release/10.0.0/lib/clang/libllvmtablegen/Makefile 249423 2013-04-12 17:57:40Z dim $

.include <bsd.own.mk>

LIB=	llvmtablegen

SRCDIR=	lib/TableGen
SRCS=	Error.cpp \
	Main.cpp \
	Record.cpp \
	StringMatcher.cpp \
	TableGenBackend.cpp \
	TGLexer.cpp \
	TGParser.cpp

.include "../clang.lib.mk"
