# $FreeBSD: stable/9/lib/clang/libllvmtablegen/Makefile 246637 2013-02-10 21:24:47Z dim $

.include <bsd.own.mk>

LIB=	llvmtablegen

SRCDIR=	lib/TableGen
SRCS=	Error.cpp \
	Main.cpp \
	Record.cpp \
	StringMatcher.cpp \
	TableGenBackend.cpp \
	TGLexer.cpp \
	TGParser.cpp
LLVM_REQUIRES_EH=

.include "../clang.lib.mk"
