# $FreeBSD: release/9.2.0/lib/clang/libllvmtablegen/Makefile 252723 2013-07-04 20:17:04Z dim $

.include <bsd.own.mk>

LIB=	llvmtablegen

SRCDIR=	lib/TableGen
SRCS=	Error.cpp \
	Main.cpp \
	Record.cpp \
	StringMatcher.cpp \
	TableGenBackend.cpp \
	TGLexer.cpp \
	TGParser.cpp

.include "../clang.lib.mk"
