#	@(#)Makefile	8.1 (Berkeley) 7/19/93
# $FreeBSD: release/7.0.0/usr.sbin/sliplogin/Makefile 137164 2004-11-03 18:01:21Z ru $

PROG=	sliplogin
MAN=	sliplogin.8
BINOWN=	root
BINGRP=	network
BINMODE=4550
PRECIOUSPROG=

.include <bsd.prog.mk>
