#!/bin/sh
# $Id: calendar3,v 1.1.1.1 2011-12-18 03:01:46 laffer1 Exp $

. ./setup-vars

exec 3>&1
RESULT=`$DIALOG --extra-button --extra-label "Hold" --help-button --title "CALENDAR" "$@" --calendar "Please choose a date..." 0 0 7 7 1981 2>&1 1>&3`
retval=$?
exec 3>&-

. ./report-string
