#! /bin/sh
# $Id: checklist9,v 1.1.1.1 2011-12-18 03:01:46 laffer1 Exp $
# "checklist8" using --file

. ./setup-vars

. ./setup-tempfile

$DIALOG "$@" --file checklist9.txt 2>$tempfile

retval=$?

. ./report-tempfile
