#!/bin/sh
# $Id: editbox3,v 1.1.1.1 2011-12-18 03:01:46 laffer1 Exp $
# example with extra- and help-buttons

. ./setup-vars

. ./setup-edit

cat << EOF > $input
EOF

$DIALOG --title "EDIT BOX" \
	--extra-button \
	--help-button \
	--fixed-font "$@" --editbox $input 0 0 2>$output
retval=$?

. ./report-edit
