#!/bin/sh
# $Id: fselect-stdout,v 1.1.1.1 2011-12-18 03:01:46 laffer1 Exp $

. ./setup-vars

RESULT=`$DIALOG --stdout --title "Please choose a file" "$@" --fselect $HOME/ 14 48`
retval=$?

. ./report-string
