#!/bin/sh
# $Id: msgbox-help,v 1.1.1.1 2011-12-18 03:01:46 laffer1 Exp $

. ./setup-vars

$DIALOG --title "MESSAGE BOX" --clear \
	--help-button "$@" \
        --msgbox "Hi, this is a simple message box. You can use this to \
                  display any message you like. The box will remain until \
                  you press the ENTER key." 10 41

retval=$?

. ./report-button
