#!/bin/sh
# $Id: msgbox-utf8,v 1.1.1.1 2011-12-18 03:01:46 laffer1 Exp $
# from Debian #570634

. ./setup-vars

. ./setup-utf8

${DIALOG-dialog} "$@" \
	--title "ทดสอบวรรณยุกต์" \
	--msgbox "วรรณยุกต์อยู่ท้ายบรรทัดได้หรือไม่" 8 23
retval=$?

. ./report-button
