#!/bin/sh
# $Id: shortlist,v 1.1.1.1 2011-12-18 03:01:46 laffer1 Exp $
# make a short listing, which writes to both stdout and stderr.

if test $# != 0
then
	count=$1
else
	count=10
fi

while test $count != 0
do
	echo "** $count -- `date`"
	w >&2
	sleep 1
	count=`expr $count - 1 2>/dev/null`
	test -z "$count" && count=0
done
