#! /bin/sh
# $Id: yesno-utf8,v 1.1.1.1 2011-12-18 03:01:46 laffer1 Exp $

. ./setup-vars

. ./setup-utf8

DIALOG_ERROR=254
export DIALOG_ERROR

$DIALOG "$@" --yesno "Are you a ＤＯＧ?" 0 0
retval=$?

. ./report-yesno
