# $MidnightBSD$
# $FreeBSD: stable/10/usr.bin/ctlstat/Makefile 229997 2012-01-12 00:34:33Z ken $

PROG=		ctlstat
MAN=		ctlstat.8
SDIR=		${.CURDIR}/../../sys
CFLAGS+=	-I${SDIR}

.include <bsd.prog.mk>
