#	$FreeBSD: release/10.0.0/sbin/ipf/iptest/Makefile 145524 2005-04-25 18:55:52Z darrenr $

.include <bsd.own.mk>

PROG=		iptest
SRCS=		iptest.c iptests.c ip.c sbpf.c sock.c 44arp.c
MAN=		iptest.1

.PATH:		${NETBSDSRCDIR}/dist/ipf/ipsend

.include <bsd.prog.mk>
