# $FreeBSD: stable/9/sys/modules/syscons/snake/Makefile 106497 2002-11-06 13:47:00Z nyan $

.PATH:	${.CURDIR}/../../../dev/syscons/snake

KMOD=	snake_saver
SRCS=	snake_saver.c

.include <bsd.kmod.mk>
