# $FreeBSD: release/7.0.0/sys/boot/i386/Makefile 170101 2007-05-29 14:35:57Z simokawa $

SUBDIR=		mbr boot0 boot0sio btx boot2 cdboot kgzldr libi386 libfirewire \
		loader

# special boot programs, 'self-extracting boot2+loader'
SUBDIR+=	pxeldr

.include <bsd.subdir.mk>
