# $FreeBSD: stable/11/sys/modules/acpi/Makefile 298716 2016-04-27 19:38:24Z jkim $

SUBDIR=		acpi_asus acpi_asus_wmi acpi_dock acpi_fujitsu acpi_hp	\
		acpi_ibm acpi_panasonic acpi_sony acpi_toshiba		\
		acpi_video acpi_wmi aibs

.include <bsd.subdir.mk>
