# $FreeBSD: stable/9/sys/modules/acpi/Makefile 215007 2010-11-08 20:30:59Z jhb $

SUBDIR=		acpi_asus acpi_fujitsu acpi_hp acpi_ibm	\
		acpi_panasonic acpi_sony acpi_toshiba acpi_video	\
		acpi_dock acpi_wmi aibs

.include <bsd.subdir.mk>
