# $FreeBSD: release/10.0.0/lib/clang/liblldbHostCommon/Makefile 255722 2013-09-20 01:52:02Z emaste $

.include <bsd.own.mk>

LIB=	lldbHostCommon

SRCDIR=	tools/lldb/source/Host/common
SRCS=	Condition.cpp \
	DynamicLibrary.cpp \
	File.cpp \
	FileSpec.cpp \
	Host.cpp \
	Mutex.cpp \
	SocketAddress.cpp \
	Symbols.cpp \
	Terminal.cpp \
	TimeValue.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
