# $FreeBSD: release/10.0.0/sys/modules/syscons/fire/Makefile 106762 2002-11-11 10:11:59Z mux $

.PATH:	${.CURDIR}/../../../dev/syscons/fire

KMOD=	fire_saver
SRCS=	fire_saver.c

.include <bsd.kmod.mk>
