#!/bin/sh

# $Id: reconf,v 1.1.1.1 2013-08-22 22:51:56 laffer1 Exp $

autoreconf
# We do not use automake but we need its install-sh file. We do not 
# care about the exit code.
automake --add-missing || true
