# $FreeBSD: release/7.0.0/sys/modules/powermac_nvram/Makefile 163771 2006-10-29 17:23:54Z marius $

.PATH: ${.CURDIR}/../../dev/powermac_nvram

KMOD=	powermac_nvram
SRCS=	powermac_nvram.c powermac_nvramvar.h
SRCS+=	bus_if.h device_if.h

.include <bsd.kmod.mk>
