# $FreeBSD: stable/11/share/doc/papers/Makefile 289393 2015-10-15 22:55:08Z bdrewery $

SUBDIR=	beyond4.3 \
	bufbio \
	contents \
	devfs \
	diskperf \
	fsinterface \
	jail \
	kernmalloc \
	kerntune \
	malloc \
	newvm \
	relengr \
	sysperf \
	timecounter

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
