# $FreeBSD: release/10.0.0/share/doc/papers/Makefile 163030 2006-10-05 13:42:30Z ru $

SUBDIR=	beyond4.3 \
	bufbio \
	contents \
	devfs \
	diskperf \
	fsinterface \
	hwpmc \
	jail \
	kernmalloc \
	kerntune \
	malloc \
	newvm \
	relengr \
	sysperf \
	timecounter

.include <bsd.subdir.mk>
