# $FreeBSD: stable/11/share/doc/legal/realtek/Makefile 289399 2015-10-16 00:38:05Z bdrewery $

FILES=		${.CURDIR}/../../../../sys/contrib/dev/urtwn/LICENSE
FILESDIR=	${SHAREDIR}/doc/legal
FILESNAME=	realtek.LICENSE

.include <bsd.prog.mk>
