# $FreeBSD: stable/11/usr.bin/clang/llvm-lto2/Makefile 311310 2017-01-04 21:47:39Z dim $

PROG_CXX=	llvm-lto2
MAN=

SRCDIR=		tools/llvm-lto2
SRCS=		llvm-lto2.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
