#	From: @(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/7.0.0/usr.bin/msgs/Makefile 140389 2005-01-17 17:45:38Z delphij $

PROG=	msgs
WARNS?=	6
DPADD=	${LIBTERMCAP}
LDADD=	-ltermcap

.include <bsd.prog.mk>
