# $MidnightBSD: src/libexec/pppoed/Makefile,v 1.2 2012/04/11 00:46:55 laffer1 Exp $
# $FreeBSD: src/libexec/pppoed/Makefile,v 1.5.18.1 2008/11/25 02:59:29 kensmith Exp $

PROG=	pppoed
DPADD=	${LIBNETGRAPH}
LDADD=	-lnetgraph
MAN=	pppoed.8

WARNS?=	1
WFORMAT=0

.include <bsd.prog.mk>
