# $MidnightBSD$
# $FreeBSD: stable/10/lib/clang/libllvmbitreader/Makefile 249423 2013-04-12 17:57:40Z dim $

.include <bsd.own.mk>

LIB=	llvmbitreader

SRCDIR=	lib/Bitcode/Reader
SRCS=	BitReader.cpp \
	BitcodeReader.cpp \
	BitstreamReader.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
