# $FreeBSD: release/9.2.0/lib/clang/libllvmbitreader/Makefile 252723 2013-07-04 20:17:04Z dim $

.include <bsd.own.mk>

LIB=	llvmbitreader

SRCDIR=	lib/Bitcode/Reader
SRCS=	BitReader.cpp \
	BitcodeReader.cpp \
	BitstreamReader.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
