# $FreeBSD$

.include <bsd.own.mk>

NO_OBJ=
INCS=	_posix_availability.h \
	_symbol_aliasing.h \
	appleapiopts.h \
	fileport.h \
	kdebug.h \
	kern_control.h \
	kern_event.h \
	kern_memorystatus.h \
	proc_info.h \
	process_policy.h \
	resource.h \
	spawn.h \
	spawn_internal.h \
	sys_domain.h \

INCSDIR=${INCLUDEDIR}/apple/sys
SUBDIR=	_pthread _types

.include <bsd.prog.mk>
