# $FreeBSD: release/9.2.0/lib/clang/libclangedit/Makefile 252723 2013-07-04 20:17:04Z dim $

.include <bsd.own.mk>

LIB=	clangedit

SRCDIR=	tools/clang/lib/Edit
SRCS=	Commit.cpp \
	EditedSource.cpp \
	RewriteObjCFoundationAPI.cpp

TGHDRS=	AttrList \
	Attrs \
	CommentCommandList \
	CommentNodes \
	DeclNodes \
	StmtNodes \
	DiagnosticCommonKinds

.include "../clang.lib.mk"
