# $FreeBSD: release/10.0.0/lib/clang/libclangedit/Makefile 249423 2013-04-12 17:57:40Z dim $

.include <bsd.own.mk>

LIB=	clangedit

SRCDIR=	tools/clang/lib/Edit
SRCS=	Commit.cpp \
	EditedSource.cpp \
	RewriteObjCFoundationAPI.cpp

TGHDRS=	AttrList \
	Attrs \
	CommentCommandList \
	CommentNodes \
	DeclNodes \
	StmtNodes \
	DiagnosticCommonKinds

.include "../clang.lib.mk"
