# $FreeBSD: stable/11/lib/libc/arm/string/Makefile.inc 315044 2017-03-11 02:51:29Z brooks $

MDSRCS+= \
	bcopy.S \
	bzero.S \
	ffs.S \
	memcmp.S \
	memcpy.S \
	memmove.S \
	memset.S \
	strcmp.S \
	strlen.S \
	strncmp.S
