# $FreeBSD: stable/11/etc/casper/Makefile 258838 2013-12-02 08:21:28Z pjd $

FILES=	system.dns
FILES+=	system.grp
FILES+=	system.pwd
FILES+=	system.random
FILES+=	system.sysctl

NO_OBJ=
FILESDIR= /etc/casper

.include <bsd.prog.mk>
