# $FreeBSD: stable/11/sys/modules/acpi/acpi_rapidstart/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:		${SRCTOP}/sys/dev/acpi_support

KMOD=		acpi_rapidstart
SRCS=		acpi_rapidstart.c opt_acpi.h device_if.h bus_if.h acpi_if.h

.include <bsd.kmod.mk>
