#	$FreeBSD: stable/11/share/examples/kld/firmware/Makefile 299293 2016-05-10 00:51:50Z gjb $

PACKAGE=examples
FILESDIR=${SHAREDIR}/examples/kld/firmware
SUBDIR= fwimage fwconsumer

.include <bsd.subdir.mk>
